### PR TITLE
Remove obsolete methodes, properties and classes

### PR DESCRIPTION
**Pull request by 304NotModified**
fixes https://github.com/NLog/NLog/issues/2529, fixes https://github.com/NLog/NLog/issues/531

### CODE REVIEW

**Comment by snakefoot** [comment]
If the Logger-interface is no longer sacred. Then I think LoggerV1-interface should be removed

**Comment by 304NotModified** [comment]
Good one, please create a new issue for that, we could check that later (for v5)

**Comment by snakefoot** [comment]
Created  #3432

**Comment by snakefoot** [comment]
Searched the Wiki for the deprecated properties that no longer exists in NLog 5.0, but found no traces in the Wiki.

**Pull request merged**
