### PR TITLE
#5478 Implementation in AsyncTargetWrapper of timer type selection. Implementation of timer with dedicated thread.

### PR DESCRIPTION
**Pull request by A6blpka**
Reason for implementations in issue #5478

### CODE REVIEW

**Comment by A6blpka** [comment]
> Does your example code where 500 parallel-threads are logging in parallel, and a single dedicated background-thread ?

img
Not a problem

**Comment by snakefoot** [comment]
I have now run you code-example, and I think that I need some help to understand the issue:
```c#
using System.Collections.Concurrent;
using NLog;
using NLog.Targets;

var logFactory = NLog.LogManager.Setup().LoadConfiguration(cfg => cfg.ForLogger().WriteToMethodCall((evt, args) => Thread.Sleep(1)).WithAsync()).LogFactory;

var logger = logFactory.GetLogger("test");
var tasks = new List<Task>(101);
var tmp = new ConcurrentDictionary<int, int>();

new Thread(() =>
{
    while (true)
    {
        Console.WriteLine(DateTime.Now.ToString("T") + " Threads worked: " + tmp.Count + " Thread pool thread count: " + ThreadPool.ThreadCount + " LogCount:" + tmp.Sum(x => x.Value));
        tmp.Clear();
        Thread.Sleep(1000);
    }

}).Start();

ThreadPool.SetMinThreads(520, 520);
ThreadPool.SetMaxThreads(520, 520);

for (var i = 0; i < 500; i++)
    tasks.Add(Task.Run(() =>
    {
        while (true)
        {
            logger.Info("Test");
            tmp.AddOrUpdate(Thread.CurrentThread.ManagedThreadId, 1, (_, value) => ++value);
        }
    }));

await Task.WhenAll(tasks);
```
So right now dotnet have I have 500 threads running on 4 cpu-cores, and they are logging at full throttle:
```
19.34.05 Threads worked: 474 Thread pool thread count: 505 LogCount:17580726
19.34.15 Threads worked: 500 Thread pool thread count: 505 LogCount:7205461
19.34.17 Threads worked: 500 Thread pool thread count: 505 LogCount:19621638
19.34.24 Threads worked: 500 Thread pool thread count: 502 LogCount:18196968
19.34.31 Threads worked: 496 Thread pool thread count: 502 LogCount:3496854
19.34.32 Threads worked: 445 Thread pool thread count: 502 LogCount:25805227
19.34.42 Threads worked: 500 Thread pool thread count: 502 LogCount:9143153
19.34.46 Threads worked: 302 Thread pool thread count: 502 LogCount:6778661
19.34.48 Threads worked: 499 Thread pool thread count: 502 LogCount:6861520
```
What is it that this PullRequest-changes ?

**Comment by A6blpka** [comment]
Set AsyncTargetWrapperOverflowAction.Block

**Comment by snakefoot** [comment]
Ahh yes thank you, now it looks funny.

**Comment by A6blpka** [comment]
And if you change the maximum number of threads in the thread pool to 20, for example, you'll get a full lockout pretty quickly. The fewer threads in the pool at the moment when starvation starts, the faster it will happen.

**Comment by snakefoot** [comment]
Applied your code-changes, and seeing the same behavior as the before, that all 500 threads are stuck here:
```
>	NLog.dll!NLog.Targets.Wrappers.ConcurrentRequestQueue.WaitForBelowRequestLimit() Line 148	C#
 	NLog.dll!NLog.Targets.Wrappers.ConcurrentRequestQueue.Enqueue(NLog.Common.AsyncLogEventInfo logEventInfo) Line 94	C#
 	NLog.dll!NLog.Targets.Wrappers.AsyncTargetWrapper.Write(NLog.Common.AsyncLogEventInfo logEvent) Line 470	C#
 	NLog.dll!NLog.Targets.Wrappers.AsyncTargetWrapper.WriteAsyncThreadSafe(NLog.Common.AsyncLogEventInfo logEvent) Line 488	C#
 	NLog.dll!NLog.Targets.Target.WriteAsyncLogEvent(NLog.Common.AsyncLogEventInfo logEvent) Line 321	C#
 	NLog.dll!NLog.LoggerImpl.WriteToTargetWithFilterChain(NLog.Targets.Target target, NLog.Filters.FilterResult result, NLog.LogEventInfo logEvent, NLog.Common.AsyncContinuation onException) Line 158	C#
 	NLog.dll!NLog.LoggerImpl.Write(System.Type loggerType, NLog.Internal.TargetWithFilterChain targetsForLevel, NLog.LogEventInfo logEvent, NLog.LogFactory logFactory) Line 99	C#
 	NLog.dll!NLog.Logger.WriteToTargets(NLog.LogEventInfo logEvent, NLog.Internal.TargetWithFilterChain targetsForLevel) Line 736	C#
```
And the logging dedicated-timer-thread is here:
```
>	System.Private.CoreLib.dll!System.Threading.Thread.Sleep(int millisecondsTimeout) Line 665	C#
 	NLog.dll!NLog.Targets.MethodCallTarget.ExecuteLogMethod(object[] parameters, NLog.LogEventInfo logEvent) Line 254	C#
 	NLog.dll!NLog.Targets.MethodCallTarget.DoInvoke(object[] parameters, NLog.Common.AsyncLogEventInfo logEvent) Line 221	C#
 	NLog.dll!NLog.Targets.MethodCallTargetBase.Write(NLog.Common.AsyncLogEventInfo logEvent) Line 88	C#
 	NLog.dll!NLog.Targets.Target.Write(System.Collections.Generic.IList<NLog.Common.AsyncLogEventInfo> logEvents) Line 611	C#
 	NLog.dll!NLog.Targets.Target.WriteAsyncThreadSafe(System.Collections.Generic.IList<NLog.Common.AsyncLogEventInfo> logEvents) Line 640	C#
 	NLog.dll!NLog.Targets.Target.WriteAsyncLogEvents(System.Collections.Generic.IList<NLog.Common.AsyncLogEventInfo> logEvents) Line 386	C#
 	NLog.dll!NLog.Targets.Wrappers.AsyncTargetWrapper.WriteLogEventsToTarget(System.Collections.Generic.IList<NLog.Common.AsyncLogEventInfo> logEvents, string reason) Line 641	C#
 	NLog.dll!NLog.Targets.Wrappers.AsyncTargetWrapper.WriteLogEventsInQueue(int batchSize, string reason) Line 619	C#
 	NLog.dll!NLog.Targets.Wrappers.AsyncTargetWrapper.ProcessPendingEvents() Line 553	C#
 	NLog.dll!NLog.Internal.Timers.DedicatedThreadTimer.DoWork() Line 230	C#
```
And the console-output is the same, that not much is happening:
```
20.10.37 Threads worked: 0 Thread pool thread count: 500 LogCount:0
20.10.38 Threads worked: 4 Thread pool thread count: 500 LogCount:200
20.10.39 Threads worked: 0 Thread pool thread count: 500 LogCount:0
20.10.40 Threads worked: 0 Thread pool thread count: 500 LogCount:0
20.10.41 Threads worked: 0 Thread pool thread count: 500 LogCount:0
20.10.42 Threads worked: 3 Thread pool thread count: 500 LogCount:200
20.10.43 Threads worked: 0 Thread pool thread count: 500 LogCount:0
20.10.44 Threads worked: 0 Thread pool thread count: 500 LogCount:0
20.10.45 Threads worked: 4 Thread pool thread count: 500 LogCount:200
```

**Comment by A6blpka** [comment]
But it works :)
Try it on a smaller thread pool size (for example 20), it will be more obvious.
This is an example with a standard timer:
```
22:14:30 Threads worked: 0 Thread pool thread count: 18 LogCount: 0
22:14:31 Threads worked: 16 Thread pool thread count: 19 LogCount: 7947
22:14:32 Threads worked: 6 Thread pool thread count: 20 LogCount: 200
22:14:33 Threads worked: 0 Thread pool thread count: 21 LogCount: 0
22:14:34 Threads worked: 0 Thread pool thread count: 22 LogCount: 0
22:14:35 Threads worked: 0 Thread pool thread count: 22 LogCount: 0
22:14:36 Threads worked: 7 Thread pool thread count: 22 LogCount: 200
22:14:37 Threads worked: 0 Thread pool thread count: 22 LogCount: 0
22:14:38 Threads worked: 0 Thread pool thread count: 22 LogCount: 0
22:14:39 Threads worked: 8 Thread pool thread count: 22 LogCount: 200
22:14:40 Threads worked: 0 Thread pool thread count: 22 LogCount: 0
22:14:41 Threads worked: 0 Thread pool thread count: 22 LogCount: 0
22:14:42 Threads worked: 7 Thread pool thread count: 22 LogCount: 200
22:14:43 Threads worked: 0 Thread pool thread count: 22 LogCount: 0
22:14:44 Threads worked: 0 Thread pool thread count: 22 LogCount: 0
22:14:45 Threads worked: 9 Thread pool thread count: 21 LogCount: 200
22:14:46 Threads worked: 0 Thread pool thread count: 21 LogCount: 0
22:14:47 Threads worked: 0 Thread pool thread count: 21 LogCount: 0
22:14:48 Threads worked: 0 Thread pool thread count: 21 LogCount: 0
22:14:49 Threads worked: 0 Thread pool thread count: 21 LogCount: 0
22:14:51 Threads worked: 0 Thread pool thread count: 21 LogCount: 0
22:14:52 Threads worked: 0 Thread pool thread count: 21 LogCount: 0
22:14:53 Threads worked: 0 Thread pool thread count: 21 LogCount: 0
22:14:54 Threads worked: 0 Thread pool thread count: 21 LogCount: 0
22:14:55 Threads worked: 0 Thread pool thread count: 21 LogCount: 0
22:14:56 Threads worked: 0 Thread pool thread count: 21 LogCount: 0
22:14:57 Threads worked: 0 Thread pool thread count: 21 LogCount: 0
22:14:58 Threads worked: 0 Thread pool thread count: 21 LogCount: 0
22:14:59 Threads worked: 0 Thread pool thread count: 21 LogCount: 0
22:15:00 Threads worked: 0 Thread pool thread count: 21 LogCount: 0
22:15:01 Threads worked: 0 Thread pool thread count: 21 LogCount: 0
22:15:02 Threads worked: 0 Thread pool thread count: 21 LogCount: 0
22:15:03 Threads worked: 0 Thread pool thread count: 21 LogCount: 0
22:15:04 Threads worked: 0 Thread pool thread count: 21 LogCount: 0
```

**Comment by snakefoot** [comment]
Yes I can see the pattern that with a dedicated thread, then it actually makes a little bit of progress instead of never firing the background-writer. Also tried the `ThreadPool.QueueUserWorkItem` and it also never fired. 

So because dotnet-runtime exhaust it ability to start new threads to handle any background-task / timer / threadpool-work, then it is unable to schedule the async-write-task. And your solution is reserving the thread upfront, so it will always be available to do work.

Can you change the DedicatedThreadTimer to just be this:
```
            while (!_stopSignalled)
            {
                if (_lazyWriterSignal.WaitOne(1000))
                    _lazyWriterSignal.Reset();
                ProcessPendingEvents(state);
            }
```
And just let `NextTrigger` be like this:
```
public void NextTrigger(int dueTime)
{
    _lazyWriterSignal.Set();
}
```
Maybe rename DedicatedThreadTimer to BackgroundWorkerThread, since all that Timer logic with `ConcurrentQueue` etc. is

**Comment by A6blpka** [comment]
I simplified the DedicatedThreadTimer.

> Can you change the DedicatedThreadTimer to just be this:
> 
> ```
>             while (!_disposed)
>             {
>                 if (_lazyWriterSignal.WaitOne(1000))
>                     _lazyWriterSignal.Reset();
>                 ProcessPendingEvents(state);
>             }
> ```

I replicated the external behavior of the default System.Threading.Timer (in the current way it is used), who doesn't do anything on his own at any intervals. I want the way the timers behave to be the same, so that at some point the external code doesn't have to adjust to implement them.


> Maybe rename DedicatedThreadTimer to BackgroundWorkerThread, since all that Timer logic with `ConcurrentQueue` etc. is

This can get confusing with [BackgroundWorker](https://learn.microsoft.com/en-us/dotnet/api/system.componentmodel.backgroundworker?view=net-8.0)

**Comment by A6blpka** [comment]
I don't understand yet what the current implementation does not suit you, if you can make it simpler without damage - please do, pull request is open for editing.

But what I want to point out, try this.
```c#
var format = "mm:ss.ffffff";
void Print(string text) => Console.WriteLine(DateTime.Now.ToString(format) + ": " + text);
var timer = new Timer(_ => Print("Default timer triggered"));
timer.Change(5000, Timeout.Infinite);
Print("Default timer changed");
Thread.Sleep(100);
timer.Change(0, Timeout.Infinite);
Print("Default timer changed");
timer.Change(1000, Timeout.Infinite);
Print("Default timer changed");
Console.ReadLine();
```
and you will see only one timer triggered, even though an instant run has been performed:
```
59:47.743340: Default timer changed
59:47.860054: Default timer changed
59:47.860237: Default timer changed
59:48.872261: Default timer triggered
```
Sometimes you can see instant triggering, but in my practice it happens very rarely.

But if you change the example to this:
```c#
var format = "mm:ss.ffffff";
void Print(string text) => Console.WriteLine(DateTime.Now.ToString(format) + ": " + text);
var timer = new Timer(_ => Print("Default timer triggered"));
timer.Change(0, Timeout.Infinite);
Print("Default timer changed");
timer.Change(5000, Timeout.Infinite);
Print("Default timer changed");
Thread.Sleep(100);
timer.Change(0, Timeout.Infinite);
Print("Default timer changed");
timer.Change(1000, Timeout.Infinite);
Print("Default timer changed");
Console.ReadLine();
```
You will receive three timer triggers.

So I decided not to play the race condition lottery when it comes to calling instant triggering and keep it a priority.

**Comment by snakefoot** [comment]
> if you can make it simpler without damage - please do, pull request is open for editing.

The goal is to reserve one (or more) threads upfront to ensure the AsyncTargetWrapper still functions after dotnet-threadpool-starvation.

Maybe the AsyncTargetWrapper should get a ITaskScheduler-option, where one can override the TaskScheduler. Then build a default TimeScheduler that wraps a standard Timer (just like now, and it handles all timer-throttle logic internally). People can then decide whether to assign a dedicated-TaskScheduler (with 1 thread) or a shared-TaskScheduler (with 1 or more threads that can be shared by all AsyncTargetWrapper-instances). Or a completely custom-TaskScheduler-logic.

Anyway if I have to built it then you just have to wait (The problem with free opensource and sparetime). Alternative you can make a pull-request that adds extension-points so it is easy for your to built own custom AsyncTargetWrapper.

**Comment by A6blpka** [comment]
I'd prefer to wait for a change from you.
I think this pull request is not needed, so I'm closing it.

**Pull request closed without merging**
