### PR TITLE
FileTarget: Fix archive does not work when date in file name.

### LINKED ISSUE #1271: archiving would not work if we have a date in the filename
With this configuration, it never archives/compresses the old log files. Normal log files are working as expected with this config. Tried different config options like archiveEvery, archiveNumbering, archiveEvery, archiveFileName. still no luck

- Bug?

**NLog version**:  4.2.3

**Platform**:  .Net 4.5.1 and .Net 4.5

**Current NLog config

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <!-- 
  See https://github.com/nlog/nlog/wiki/Configuration-file 
  for information on customizing logging rules and outputs.
   -->
  <targets async="true">
    <target xsi:type="File"
            name="file"
            fileName="${basedir}/logs/${logger}_${shortdate}.log"
            archiveFileName="${basedir}/archives/log.{#}.txt"
            archiveEvery="Day"
            archiveNumbering="Rolling"
            maxArchiveFiles="7"
            enableArchiveFileCompression="true"
            layout="${longdate} ${logger} ${message}"  />
    <target xsi:type="ColoredConsole"
          name="console"
          layout="${longdate} ${logger} ${message}"  />
  </targets>
  <rules>
    <logger name="*" minlevel="Trace" writeTo="file,console" />
  </rules>
</nlog>
```

### PR DESCRIPTION
**Pull request by bhaeussermann**
Fixes #1271

### CODE REVIEW

**Comment by 304NotModified** [comment]
I broke the unit tests :( 

See #1251

**Comment by 304NotModified** [comment]
Please rebase with master :)

**Comment by 304NotModified** [comment]
mmm there is an "update branch" button?

**Comment by bhaeussermann** [comment]
> hmmm there is an "update branch" button? 

Is that bad? Oo

**Comment by 304NotModified** [comment]
Well it does an merge I see. Rebase is of course much nicer :)

**Comment by bhaeussermann** [comment]
> Well it does an merge I see. Rebase is of course much nicer :)

That's odd. My local repository is up-to-date with master.

**Comment by 304NotModified** [comment]
yes it's now OK. You didn't rebased?

**Comment by bhaeussermann** [comment]
> yes it's now OK. You didn't rebased?

I did ;)

**Comment by 304NotModified** [comment]
:D great fix just before the release.

**Pull request merged**
