### PR TITLE
MessageTemplateParameter(s)  ctors to internal

### PR DESCRIPTION
**Pull request by 304NotModified**
fixes https://github.com/NLog/NLog/issues/2552

+ small c#7  change

### CODE REVIEW

**Comment by 304NotModified** [comment]
@snakefoot decline this and wontfix for #2552?

**Comment by snakefoot** [comment]
I was thinking to allow use of MessageTemplateParameters constructor to access the internal parser. The MessageTemplateParameter struct is used by NLog.Extensions to capture Microsoft Extension Logging Message Properties. But we don't need two constructors, only the one with CaptureType



Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment]
So for both classes we need public ctors?

**Comment by 304NotModified** [comment]
> I was thinking to allow use of MessageTemplateParameters constructor to access the internal parser.

No really a fan of this magic. 

updated it: MessageTemplateParameter full ctor is still public

MessageTemplateParameters is internal ctor. IMO the ctor of MessageTemplateParameters do maybe to much parsing and so it's a good candidate to keep it internal. 

Let me know if you agree 

We can always open the ctor if we need it in the future.

**Comment by 304NotModified** [comment]
PS I will try to create rc6 tonight/tomorrow. I hope that the latest RC before the RTM

@snakefoot if your still on holiday, have a good holiday :)

**Comment by snakefoot** [comment]
Yes. I think so


Sent from my Samsung device


-------- Original message --------

**Comment by snakefoot** [comment]
Will also work for me


Sent from my Samsung device


-------- Original message --------

**Pull request merged**
