### PR TITLE
moving FileTarget archival methods to their own namespace.

### PR DESCRIPTION
**Pull request by nathan-schubkegel**
This change is 0% functional, just code shuffled around to new smaller files.

I found a corner case defect in FileTarget with ConcurrentWrites and Rolling archival at my day job. I want to fix it, but I'm having sincere trouble reasoning about FileTarget's archival code because it feels like a spahgetti monster. Trying to refactor / extract it down to a mere ravioli monster so future work on defects in this class can be clearer.

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks, but I'm afraid this is in a bad timing with #1040

**Comment by 304NotModified** [comment]
>The type or namespace name 'Compression' does not exist in the namespace 'System.IO' (are you missing an assembly reference?) [C:\projects\nlog\src\NLog\NLog.sl4.csproj]
Command exited with code 1

Your are missing some `#if`  


Did you used a refactoring tool? (eg resharper)

**Comment by nathan-schubkegel** [comment]
I'm patient, will be glad to wait until #1040 is complete. (So far it looks like I'll just need to carefully merge a few !WINDOWS_PHONE directives when it comes out).

No, I did not use Resharper this time (my goal was to keep the code identical to original, at least for this pull request. Resharper tends to encourage code massage which is good for code but hard on reviewers)

No good excuse for `#if` mistakes... I will thoroughly correct them.

**Comment by 304NotModified** [comment]
#1040 has been merged and this PR has now a conflict as expected ;)

Can you fix the conflict and the also Travis error (it does work on master)

**Comment by nathan-schubkegel** [comment]
AppVeyor failed, looks like a configuration blooper. Drop me a line when it's a good time to push a whitespace-change commit to make it build again. =)

**Comment by 304NotModified** [comment]
it fails due to the `appveyor RegisterXamarinLicense`
See: https://github.com/NLog/NLog/blob/master/appveyor.yml#L11

not sure how to make that conditional...

**Pull request closed without merging**
