### PR TITLE
Database target: dropped UseRawValue option on parameters, introduced ${myRenderer:noRawValue=true}

### PR DESCRIPTION
**Pull request by snakefoot**
NoRawValueLayoutRendererWrapper can be used by "many".

After seeing the trouble in making IRawValue work with wrappers. Then why not make a wrapper where the purpose is to disable the IRawValue-interface.

Another unreleased breaking change.

### CODE REVIEW

**Comment by snakefoot** [comment]
Guess I should modify the DatabaseTargetTests so the logger includes assignment of DbType and escapes string-value with string-quotes.

**Comment by 304NotModified** [comment]
> See the difference between "2" and ""2""

I'm a bit confused by the `""2""` 👼 

Good idea! Now we "lose" useRawValue=true with `string`, but I guess that's a good thing.

**Comment by snakefoot** [comment]
> I'm a bit confused by the ""2""

Could also say see the difference between `2` (non-string) and `"2"` (string) in the MockDb-Log-Verification.

**Comment by 304NotModified** [comment]
> Could also say see the difference between `2` (non-string) and `"2"` (string) in the MockDb-Log-Verification.

I missed it was a verbatim string ;)

**Comment by 304NotModified** [comment]
could you please help me with the docs? I will release RC3 then

**Comment by snakefoot** [comment]
Created https://github.com/NLog/NLog/wiki/NoRawValue-layout-renderer

**Comment by 304NotModified** [comment]
thanks!

**Pull request merged**
