### PR TITLE
${AppSetting} for .NET standard 2 (NLog.Extended)

### PR DESCRIPTION
**Pull request by 304NotModified**
In NLog.Extended

using https://www.nuget.org/packages/System.Configuration.ConfigurationManager/

- [ ] adapt current unit tests (if there are)
- [ ] move `IConfigurationManager` and `ConfigurationManager` from NLog to NLog.Extended

### CODE REVIEW

**Comment by snakefoot** [comment]
Why not move it out of NLog.Extended and create a NLog.AppSettings-nuget-package ?

**Comment by 304NotModified** [comment]
yeah doubting about that. Thanks for the input

**Comment by 304NotModified** [comment]
superseded by #2919

**Comment by snakefoot** [comment]
And #2919 has been superseded by #3053

**Pull request closed without merging**
