### PR TITLE
Added Fluent configuration API

### PR DESCRIPTION
**Pull request by snakefoot**
Alternative solution for #1429 (See also #2998)

It attempts to guide the user to configure the NLog configuration the right way.

Ex.

```C#
var factory = LogManager.LogFactory.BuildConfig(c =>
   c.FilterMinLevel(LogLevel.Debug,
      w => w.WriteToWithAsync(async =>
              async.WriteToFile(fileName: "file.txt")));
   c.FilterMinLevel(LogLevel.Info
      w => w.WriteToWithAsync(async =>
              async.WriteToConsole()));
);
var logger = factory.GetCurrentClassLogger();
```

### CODE REVIEW

**Comment by 304NotModified** [comment]
cool!

I'm not sure if this is the same as #2998. The goal of #2998 is that another config (e.g. xml) will be enhanced from C#. That's not always needed/preferred. 

Of course we could also tackle that with

```
var factory = LogManager.Configure(c =>
    c.LoadFromFile("nlog.config")
```


Some ideas:
---

 ```
var factory = LogManager.LogFactory.BuildConfig(c =>
```

I think I would prefer 
```
var factory = LogManager.Configure(c =>
```

---

```
 w => w.WriteToWithAsync(async =>
```
what about:
```
 w => w.WriteAsync(async =>
```
or would this also possible?

```
var factory = LogManager.LogFactory.BuildConfig(c =>
   c.FilterMinLevel(LogLevel.Debug,
      w => w.Async().WriteToFile(fileName: "file.txt")));
   c.FilterMinLevel(LogLevel.Info
      w => w.Async().WriteToConsole()));
);
```

**Comment by snakefoot** [comment]
Yes adding a static `BuildConfig`-method to `LogManager` should not be difficult.

I like `WriteToWithAsync` because it matches the other `WriteTo` methods, that indicates that one is doing target-configuration. But I also don't like it because it is rather "wordy".

It would also be possible to use `w.async().WriteToFile`. Should be a simple change

**Comment by 304NotModified** [comment]
> But then it would be different from compound-targets in their API.

I don't think most users will think async as an compound thing

**Comment by snakefoot** [comment]
> I don't think most users will think async as an compound thing. So OK to me :)

I was talking about compound-wrappers like the FallbackGroup. Like when interfaces act similar.

**Comment by 304NotModified** [comment]
> I was talking about compound-wrappers like the FallbackGroup. Like when interfaces act similar.

Yes, and I think this is OK: 

> But then it would be different from compound-targets in their API.

**Comment by snakefoot** [comment]
> Yes, and I think this is OK:

So how should the WriteToWithFallback work then?

`WriteToWithFallback(f => f.WriteToConsole().WriteToDebug());`

`WriteToWithAsync(f => f.WriteToConsole());`

Also remember one can chain them together in any order, as NLog supports.

**Comment by 304NotModified** [comment]
> So how should the WriteToWithFallback work then?

Do you mean the API design, or how it should work technically?

**Comment by snakefoot** [comment]
Everything in this PR is about API-design. Making a nice API is the hardest part.

But maybe it should cook a little longer, and not hold NLog 4.6 back ?

**Comment by 304NotModified** [comment]
> But maybe it should cook a little longer, and not hold NLog 4.6 back ? It was just something I thought could be nice and made an attempt.

I think that also wise. Only https://github.com/NLog/NLog/pull/2899 is really blocking 4.6, but unfortunately it should have more unit tests before merge.

**Comment by 304NotModified** [comment]
but what about https://github.com/NLog/NLog/pull/2998, that one will hurt this one in the future?

**Comment by snakefoot** [comment]
> but what about #2998, that one will hurt this one in the future?

Yes it will be a little confusing with many different fluent-config-approaches. Else it should be a minimal builder-object that has LoggingConfiguration as property ? (Then it can grow from there).

**Comment by 304NotModified** [comment]
@snakefoot thanks for this PR, but gonna close this one for now as it isn't active and I try to focus the stuff of 4.6

**Comment by snakefoot** [comment]
Created  #4128 that now extends the `LogFactory.Setup()`-logic

**Pull request closed without merging**
