### PR TITLE
adding <repository> to nuspec NLog.Config and NLog.Schema

### PR DESCRIPTION
**Pull request by 304NotModified**
closes https://github.com/NLog/NLog/issues/2852

### CODE REVIEW

**Comment by snakefoot** [comment]
Why update the nuspec-files ? They should just be deleted. Using dotnet pack and VS2017 csproj.

**Comment by 304NotModified** [comment]
because we need then more csproj AFAIK

**Comment by snakefoot** [comment]
> because we need then more csproj files AFAIK (for nlog.schema and nlog.config).

Well then delete  all but those two

**Comment by 304NotModified** [comment]
you're right, done!

**Pull request merged**
