### PR TITLE
FileTarget - Faster archive check by caching the static file-create-time (60-70% improvement)

### PR DESCRIPTION
**Pull request by snakefoot**
FileTarget - FileAppenderCache now caches the conversion of File-Time-Utc to File-Time-TimeSource thus avoiding the expensive DateTime.ToLocalTime(). Also the ArchiveEvery-check now performs truncate of DateTime.Ticks instead of performing DateTime.ToString() allocation.

This PR also contains the following changes:
- MutexMultiProcessFileAppender now uses the cached File-Creation-Time, instead of doing lookup using file-handle
- WindowsMultiProcessFileAppender now uses the cached File-Creation-Time, instead of doing lookup using file-handle
- UnixMultiProcessFileAppender now updates the cached File-Creation-Time as expected by the FileTarget / FileAppenderCache.
- Changed some FileTargetTests to use ShiftedTimeSource instead of using File.SetCreationTime. This allows FileAppenders that caches the static File-Creation-Time to be tested (Now also testing SingleProcessFileAppender).

Have done performance tests with the following config:

`<target name="SyncFilePerfArchive" type="File" fileName="C:\Temp\Log\NLogPerformanceArchivePerf.txt" autoFlush="false" keepFileOpen="true" concurrentWrites="false" layout="${message}" ArchiveAboveSize="10000000000" MaxArchiveFiles="1000" ArchiveEvery="Year" ArchiveNumbering="Date" />`

| Logger Name      | Messages   | Size | Threads | Loggers |
|------------------|------------|------|---------|---------|
| PerfArchiveLogger | 10.000.000 |  128 |       1 |       1 |

| This PR | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Mem (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|----------|
| concurrentWrites = false   |    18.694 |   534.917 |   0 |   0 | 1243 |   19.000 |   36,551 |
| concurrentWrites = true    |    90.754 |   110.187 |   0 |   0 | 1275 |   90.843 |   36,320 |

| Master | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Mem (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|----------|
| concurrentWrites = false   |    32.902 |   303.924 |   0 |   1 | 1459 |   33.046 |   36,746 |
| concurrentWrites = true    |    144.539 |    69.185 |   0 |   1 | 1520 |  143.015 |   36,648 |

Merry Kerstmis :)

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1876)

### CODE REVIEW

**Comment by 304NotModified** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/NLog/Internal/FileAppenders/BaseFileAppender.cs, line 79 at r1](https://reviewable.io:443/reviews/nlog/nlog/1876#-K_aLtP_ufvVSnCMswR0:-K_aLtP_ufvVSnCMswR1:bk5kusc) ([raw file](https://github.com/nlog/nlog/blob/5c8cbe2ff6818f490e49179ac82351512a067b32/src/NLog/Internal/FileAppenders/BaseFileAppender.cs#L79)):*
> ```Smalltalk
>         /// </summary>
>         /// <returns>The creation time of the file.</returns>
>         public DateTime CreationTimeUtc { get { return _creationTimeUtc; } internal set { _creationTimeUtc = value; CreationTimeSouce = Time.TimeSource.Current.FromSystemTime(value); } }
> ```

smart one. Please add a comment that we are doining this for performance reasons.

---

*[src/NLog/Internal/FileAppenders/BaseFileAppender.cs, line 82 at r1](https://reviewable.io:443/reviews/nlog/nlog/1876#-K_aLy7nJ6vyPFmOEoWG:-K_aLy7nJ6vyPFmOEoWH:b-7prn9v) ([raw file](https://github.com/nlog/nlog/blob/5c8cbe2ff6818f490e49179ac82351512a067b32/src/NLog/Internal/FileAppenders/BaseFileAppender.cs#L82)):*
> ```Smalltalk
>         DateTime _creationTimeUtc;
> 
>         public DateTime CreationTimeSouce { get; private set; }
> ```

Please add some XML docs and refer to CreationTimeUtc (<see tag)

It's also SouRce? (or is it my limited English vocabulary..)

---

*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 177 at r1](https://reviewable.io:443/reviews/nlog/nlog/1876#-K_aLm89klMqJntk6ZYH:-K_aLm89klMqJntk6ZYI:b-i9qdya) ([raw file](https://github.com/nlog/nlog/blob/5c8cbe2ff6818f490e49179ac82351512a067b32/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L177)):*
> ```Smalltalk
>                 }
> 
>                 if (string.CompareOrdinal(appenders[i].FileName, fileName) == 0)
> ```

What about .Compare (...Ordinal)? 

---

*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 182 at r1](https://reviewable.io:443/reviews/nlog/nlog/1876#-K_aMUE8RGEVj-woHq_q:-K_aMUE8RGEVj-woHq_r:bgaoe8t) ([raw file](https://github.com/nlog/nlog/blob/5c8cbe2ff6818f490e49179ac82351512a067b32/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L182)):*
> ```Smalltalk
>                     // (MRU)
>                     BaseFileAppender app = appenders[i];
>                     if (i != 0)
> ```

if (i > 0)? 

---

*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 332 at r1](https://reviewable.io:443/reviews/nlog/nlog/1876#-K_aMp_Rp7RAp5x3VfqN:-K_aMp_Rp7RAp5x3VfqO:b9sfubg) ([raw file](https://github.com/nlog/nlog/blob/5c8cbe2ff6818f490e49179ac82351512a067b32/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L332)):*
> ```Smalltalk
>                     if (result.HasValue)
>                     {
>                         if (result.Value != appender.CreationTimeUtc)
> ```

we're checking the cached version here right? Please add it as comment, thanks!

---

*[src/NLog/Internal/FileAppenders/MutexMultiProcessFileAppender.cs, line 196 at r1](https://reviewable.io:443/reviews/nlog/nlog/1876#-K_aMxkbLvpLoYcW6p4P:-K_aMxkbLvpLoYcW6p4Q:b-tf1cn7) ([raw file](https://github.com/nlog/nlog/blob/5c8cbe2ff6818f490e49179ac82351512a067b32/src/NLog/Internal/FileAppenders/MutexMultiProcessFileAppender.cs#L196)):*
> ```Smalltalk
>         public override DateTime? GetFileCreationTimeUtc()
>         {
>             return CreationTimeUtc; // File is kept open, so creation time is static
> ```

smart one :)

Thanks for the comment. Needed it

---

*[src/NLog/Internal/FileAppenders/UnixMultiProcessFileAppender.cs, line 101 at r1](https://reviewable.io:443/reviews/nlog/nlog/1876#-K_aNEvbdlv6Lf2eX2Us:-K_aNEvbdlv6Lf2eX2Ut:b-zh1gu5) ([raw file](https://github.com/nlog/nlog/blob/5c8cbe2ff6818f490e49179ac82351512a067b32/src/NLog/Internal/FileAppenders/UnixMultiProcessFileAppender.cs#L101)):*
> ```Smalltalk
> 
>                 long filePosition = this.file.Position;
>                 if (fileExists || filePosition > 0)
> ```

isn't fileExists always true when filePosition > 0 ?

---

*[src/NLog/Internal/FileAppenders/WindowsMultiProcessFileAppender.cs, line 203 at r1](https://reviewable.io:443/reviews/nlog/nlog/1876#-K_aNXBfxYakFafM0Bhv:-K_aNXBfxYakFafM0Bhw:b-qgnq3p) ([raw file](https://github.com/nlog/nlog/blob/5c8cbe2ff6818f490e49179ac82351512a067b32/src/NLog/Internal/FileAppenders/WindowsMultiProcessFileAppender.cs#L203)):*
> ```Smalltalk
>         public override DateTime? GetFileCreationTimeUtc()
>         {
>             return CreationTimeUtc; // File is kept open, so creation time is static
> ```

are you sure this is the case here?

---

*[src/NLog/Targets/FileTarget.cs, line 2065 at r1](https://reviewable.io:443/reviews/nlog/nlog/1876#-K_aNfRVLKq0AyUAtLWP:-K_aNfRVLKq0AyUAtLWQ:b-xtpyir) ([raw file](https://github.com/nlog/nlog/blob/5c8cbe2ff6818f490e49179ac82351512a067b32/src/NLog/Targets/FileTarget.cs#L2065)):*
> ```Smalltalk
>         }
> 
>         private static DateTime TruncateArchiveTime(DateTime input, FileArchivePeriod resolution)
> ```

what are we trying to do here? (xmldoc please)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1876)*

**Comment by snakefoot** [comment]
*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 182 at r1](https://reviewable.io:443/reviews/nlog/nlog/1876#-K_aMUE8RGEVj-woHq_q:-K_aWruUTwmGvQoibT3Z:b63mq4u) ([raw file](https://github.com/nlog/nlog/blob/5c8cbe2ff6818f490e49179ac82351512a067b32/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L182)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

if (i > 0)? 
</blockquote></details>

Also works

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1876)*

**Comment by snakefoot** [comment]
*[src/NLog/Internal/FileAppenders/WindowsMultiProcessFileAppender.cs, line 203 at r1](https://reviewable.io:443/reviews/nlog/nlog/1876#-K_aNXBfxYakFafM0Bhv:-K_aY-dXeSXTn6567Xc6:bm5sq27) ([raw file](https://github.com/nlog/nlog/blob/5c8cbe2ff6818f490e49179ac82351512a067b32/src/NLog/Internal/FileAppenders/WindowsMultiProcessFileAppender.cs#L203)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

are you sure this is the case here?
</blockquote></details>

FileCreation-time should not be updated by having multiple writers to the same file. They will just update FileModified-time. Ofcourse it will not longer react to random application that for fun modifies the file-creation-time of log-files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1876)*

**Comment by snakefoot** [comment]
*[src/NLog/Internal/FileAppenders/UnixMultiProcessFileAppender.cs, line 101 at r1](https://reviewable.io:443/reviews/nlog/nlog/1876#-K_aNEvbdlv6Lf2eX2Us:-K_aZrDSN_1dUDCoSzrs:bo31sib) ([raw file](https://github.com/nlog/nlog/blob/5c8cbe2ff6818f490e49179ac82351512a067b32/src/NLog/Internal/FileAppenders/UnixMultiProcessFileAppender.cs#L101)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

isn't fileExists always true when filePosition > 0 ?
</blockquote></details>

Well there can be a race-condition between the fileExists-check and the filePosition > 0. If someone was able to create the file and append to it between doing the fileExists-check and the filePosition-check.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1876)*

**Comment by snakefoot** [comment]
*[src/NLog/Targets/FileTarget.cs, line 2065 at r1](https://reviewable.io:443/reviews/nlog/nlog/1876#-K_aNfRVLKq0AyUAtLWP:-K_a_FAWJzV8fzce3edh:bb6un1j) ([raw file](https://github.com/nlog/nlog/blob/5c8cbe2ff6818f490e49179ac82351512a067b32/src/NLog/Targets/FileTarget.cs#L2065)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

what are we trying to do here? (xmldoc please)
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1876)*

**Comment by snakefoot** [comment]
*[src/NLog/Internal/FileAppenders/BaseFileAppender.cs, line 79 at r1](https://reviewable.io:443/reviews/nlog/nlog/1876#-K_aLtP_ufvVSnCMswR0:-K_a_IN6Aey9MQlxt1YJ:bb6un1j) ([raw file](https://github.com/nlog/nlog/blob/5c8cbe2ff6818f490e49179ac82351512a067b32/src/NLog/Internal/FileAppenders/BaseFileAppender.cs#L79)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

smart one. Please add a comment that we are doining this for performance reasons.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1876)*

**Comment by snakefoot** [comment]
*[src/NLog/Internal/FileAppenders/BaseFileAppender.cs, line 82 at r1](https://reviewable.io:443/reviews/nlog/nlog/1876#-K_aLy7nJ6vyPFmOEoWG:-K_a_KJsDMSFfqWgaVpC:bb6un1j) ([raw file](https://github.com/nlog/nlog/blob/5c8cbe2ff6818f490e49179ac82351512a067b32/src/NLog/Internal/FileAppenders/BaseFileAppender.cs#L82)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

Please add some XML docs and refer to CreationTimeUtc (<see tag)

It's also SouRce? (or is it my limited English vocabulary..)
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1876)*

**Comment by snakefoot** [comment]
*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 177 at r1](https://reviewable.io:443/reviews/nlog/nlog/1876#-K_aLm89klMqJntk6ZYH:-K_a_MBgJL7AN4zqjZbQ:b-886gsx) ([raw file](https://github.com/nlog/nlog/blob/5c8cbe2ff6818f490e49179ac82351512a067b32/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L177)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

What about .Compare (...Ordinal)? 
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1876)*

**Comment by snakefoot** [comment]
*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 332 at r1](https://reviewable.io:443/reviews/nlog/nlog/1876#-K_aMp_Rp7RAp5x3VfqN:-K_a_OqTbOe0RLhnhjYm:bb6un1j) ([raw file](https://github.com/nlog/nlog/blob/5c8cbe2ff6818f490e49179ac82351512a067b32/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L332)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

we're checking the cached version here right? Please add it as comment, thanks!
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1876)*

**Comment by snakefoot** [comment]
*[src/NLog/Internal/FileAppenders/MutexMultiProcessFileAppender.cs, line 196 at r1](https://reviewable.io:443/reviews/nlog/nlog/1876#-K_aMxkbLvpLoYcW6p4P:-K_a_SEANfgDFlpjk2Of:b32vhw) ([raw file](https://github.com/nlog/nlog/blob/5c8cbe2ff6818f490e49179ac82351512a067b32/src/NLog/Internal/FileAppenders/MutexMultiProcessFileAppender.cs#L196)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

smart one :)

Thanks for the comment. Needed it
</blockquote></details>

:)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1876)*

**Comment by 304NotModified** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1876)*

**Comment by 304NotModified** [comment]
Close/reopen for triggering appveyor

**Comment by 304NotModified** [comment]
Ow conflict :/

**Comment by snakefoot** [comment]
@304NotModified Fixed merge conflicts

**Comment by 304NotModified** [comment]
Merci!

---

Reviewed 7 of 7 files at r3, 9 of 9 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1876#-:-KaNa2NroS9oNpfFrrpw:bwbw24m)*

**Comment by 304NotModified** [comment]
Reviewed all.

**Pull request merged**
