### PR TITLE
IRawvalue support in ${when}

### PR DESCRIPTION
**Pull request by 304NotModified**
fixes https://github.com/NLog/NLog/issues/3139

todo 
- other conditional layouts

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/3140)

### CODE REVIEW

**Comment by 304NotModified** [comment]
@snakefoot could you please explain to me:

> NLog.UnitTests.ApiTests.TryGetRawValue_ThreadAgnostic_Attribute_Required [FAIL]
>      NLog.LayoutRenderers.Wrappers.WrapperLayoutRendererBase cannot implement IRawValue

**Comment by snakefoot** [comment]
Erhh you have just added `IRawValue` to the base class, and suddenly changed the meaning of the interface.

Before it was not conditional. Now it is. Before it was not on base-classses. Now it is.

**Comment by 304NotModified** [comment]
> Erhh you have just added IRawValue to the base class, and suddenly changed the meaning of the interface

Not really, as the interface was about retrieving raw values. But ok, the implementation was (unfortunately?) more limited

> Before it was not conditional. Now it is. Before it was not on base-classses. Now it is.

> The unit-test verifies the old interface meaning. When changing the meaning, then the unit-test will probably also need to be changed.

Any ideas with this change? Change the unit test? Is this change a bad idea? Do you expect unwanted side effects of this change?

**Comment by snakefoot** [comment]
> Any ideas with this change? Change the unit test? Is this change a bad idea? Do you expect unwanted side effects of this change?

I see both IRawValue and IStringValue as hacks to improve performance. As the Layout and LayoutRenderers have been born to output strings. They have to be implemented carefully as they can break the safety net need when doing async-logging.

If we want to open up for people setting up their own logic for returning actual objects, then I think we should consider looking at the Serilog-enrichers. Maybe getting inspiration from there?

**Comment by 304NotModified** [comment]
Clear, but that's more about go to public with the irawvalue 

What about implementing it like this for ${when}?
 I could merge the refactor (to try pattern) an do the  ${when} impl in a later version.

**Comment by snakefoot** [comment]
I would probably just settle for `WhenEmptyLayoutRendererWrapper` since it is the standard coalesce-method in NLog. 

But it sounds like you are actually using the DatabaseTarget, so I guess you have a better idea of common use-cases. Prefer not to sprinkle performance hacks everywhere unless they are part of main-code-path.

**Comment by 304NotModified** [comment]
after #3144 this isn't a breaking change

**Comment by snakefoot** [comment]
@304NotModified Could also make a special layoutrenderer-wrapper that support IRawValue and if the inner-Layout supports IRawValue-interface and it returns null/empty-string. Then it can coalesce to DbNull-value as raw-value.

**Comment by snakefoot** [comment]
But after doing performance testing in #3150, then IRawValue-optimization of DateTime is dwarfed by the overhead in DatabaseTarget of building DbCommands.

So right now the IRawValue goal is to allow one to return dbnull, because one cannot render a magic-string value that can be converted by to dbnull.

**Comment by 304NotModified** [comment]
> But after doing performance testing in #3150, then IRawValue-optimization of DateTime is dwarfed by the overhead in DatabaseTarget of building DbCommands

Please elaborate, can't follow this unfortunately

**Comment by snakefoot** [comment]
> Please elaborate, can't follow this unfortunately

Just saying that IRawValue is a very special hammer, and one have to look hard for nails where the hammer really shines.

**Comment by 304NotModified** [comment]
Lol I'm more lost now. Another day I think ;)

**Comment by 304NotModified** [comment]
TIME

**Comment by 304NotModified** [comment]
superseded by https://github.com/NLog/NLog/pull/3373

**Pull request closed without merging**
