### PR TITLE
Replaced question.md issue-template with contact_links to StackOverflow

### PR DESCRIPTION
**Pull request by snakefoot**
Also disables use of blank-issue-template:
image

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks!

**Comment by snakefoot** [comment]
Seems I config.yaml should be renamed to config.yml #4920

**Comment by 304NotModified** [comment]
Not sure if its now working?

**Comment by 304NotModified** [comment]
@snakefoot maybe we should also update the support link on nlog-project.org? (Or perhaps split it)

**Pull request merged**
