### PR TITLE
Introduced ILog to replace ILogger. Introduced LogEventBuilder to replace LogBuilder

### LINKED ISSUE #532: Callsite Layout Renderer and Caller Attributes
The current `CallSiteLayoutRenderer` uses the stacktrace for the method name, line number and file name.

This could be done with the [Caller attributes](https://msdn.microsoft.com/en-us/library/hh534540.aspx). In theory this would be a performance improvement. 

This should be tested in a prototype.

Keep in mind that the current classname isn's supported with the 'Caller Attributes'.

From a quick scan, this should be done:
- Extend **all** the methods in the `Logger` with the following parameters:

```
 [CallerMemberName] string memberName = "",   [CallerFilePath] string sourceFilePath = "",
        [CallerLineNumber] int sourceLineNumber = 0
```

Extend the `LogEventInfo` with the three properties so that the `CallSiteLayoutRenderer` could use this information. 

Inspired by #509

### PR DESCRIPTION
**Pull request by snakefoot**
Right now `ILogger` has over 300 interface-members (Most are from NLog 1.0 before generics was invented). The new `ILog` has 25 interface-members. I guess one could reduce the number even further, but like that one can easily be notified on error-events when mocking.

It would be a major breaking change to make any changes to `ILogger`. Even adding a new interface-method like `WithProperty` and `PushScopeContext`.

Now marked `ILogger` as obsolete, and instead redirected people to `ILog`. The interfaces has same features, except that `ILog` has reduced the number of methods that takes `IFormatProvider`-input-parameter and removed all non-generic-overrides. The methods with `IFormatProvider`-input-parameter has been moved into LoggerExtensions-methods.

Have at the same time added several extension-methods to `ILog` so it has similar capabilities like actual `Logger`:
- Supports LogMessageGenerator
- Supports Swallow
- Supports SwallowAsync
- Supports ConditionalDebug
- Supports ConditionalTrace

One could consider in NLog 6.0 to remove `ILogger`-interface (and `ILoggerBase`) and then reintroduce it again where inheriting from `ILog`.

Have at the same time obsoleted the old fluent `LogBuilder` and introduced `LogEventBuilder` that is available without needing to write `using NLog.Fluent`. The interfaces are very similar, but the start method is a little different:

- **LogBuilder:** `logger.Info().Message("Hello").Write();`
- **LogEventBuilder:** `logger.ForInfoEvent().Message("Hello").Write();`

I guess one could change `LogEventBuilder` to be activated from using `Info()` but it would generate more noise about ambiguous extensions-methods. But actually I like `ForInfoEvent()` since it signals that one is starting to define a LogEvent.

Also unsure if I like the `Write()`-method. Think I prefer `.Log()` but then the transformation would not be that easy:

- **LogEventBuilder:** `logger.ForInfoEvent().Message("Hello").Log();`

The major improvement in `LogEventBuilder` is there is no allocation if the LogLevel is not enabled. And when the LogLevel is enabled, then it no longer allocates an additional `LogBuilder`-object (Because `LogEventBuilder` is a struct on the stack). Resolves #532

### CODE REVIEW

**Comment by snakefoot** [comment]
Need to improve on the test-coverage with all the new LoggerExtensions-methods.

Also has some TODOs regarding improving single-parameter-logging, where the parameter is an Exception-object (Enable ExceptionMessageFormatProvider)

**Comment by snakefoot** [comment]
Might consider adding caller-member-attributes-parameters to these ILog-extension-methods:

```c#
public static void Trace([NotNull] this ILog logger, [NotNull] LogMessageGenerator messageFunc)
public static void Trace([NotNull] this ILog logger, Exception exception, [NotNull] LogMessageGenerator messageFunc)
```

So it becomes:

```c#
public static void Trace([NotNull] this ILog logger, [NotNull] LogMessageGenerator messageFunc, 
                        [CallerMemberName]string callerMemberName = null,
                        [CallerFilePath]string callerFilePath = null,
                        [CallerLineNumber]int callerLineNumber = 0)
public static void Trace([NotNull] this ILog logger, Exception exception, [NotNull] LogMessageGenerator messageFunc
                        [CallerMemberName]string callerMemberName = null,
                        [CallerFilePath]string callerFilePath = null,
                        [CallerLineNumber]int callerLineNumber = 0)
```

Then it will also get the benefit of faster callsite-logic.

**Comment by 304NotModified** [comment]
I'm doubting if we should not wait for default interface implementations.

**Comment by 304NotModified** [comment]
I like the change, but I am very reluctant to change the logging API. There should be a big benefit. Sure, 25 interface is much better than 300, but I think #3656 , #1148  , #3675  and #1234 are far more important

**Comment by snakefoot** [comment]
Yes this interface change is a preparation for doing default implementation with netstandard21


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


I'm doubting if we should not wait for default interface implementations.

**Comment by snakefoot** [comment]
All of those PullRequests are important, but any heavy refactoring to split NLog into multiple targets should wait for the `Layout<T>` to be committed. 

Also quite happy with the current state of DependencyInjection-support. There is a huge task with refactoring the NLog-UnitTests to stop using the global NLog.LogManager and instead use isolated LogFactory. Making it clear that isolated LogFactory is fully working.

I just saw that `ILog` was an isolated area that didn't overlap with those important PullRequests (Little change of merge conflicts). Besides putting a strain of the critical time-resource.

**Comment by 304NotModified** [comment]
> There is a huge task with refactoring the NLog-UnitTests to stop using the global NLog.LogManager and instead use isolated LogFactory. Making it clear that isolated LogFactory is fully working.

Yes this would be great. Also for performance and parallel testing. It started with this once, but replaced to much (so broke things). I think we should a few test classes per pr. Maybe we should mark then somehow that they're done

**Comment by snakefoot** [comment]
Alternative interface than ILog could be `INLog` or `INLogger`, but maybe the name-collission with other Logger-interface is wanted.

**Comment by snakefoot** [comment]
Given up on replacing `ILogger` and instead created #432

**Pull request closed without merging**
