### PR TITLE
Added ${HostName} Layout Renderer

### PR DESCRIPTION
**Pull request by amitsaha**
This implements a new `hostname` layout renderer. This is slightly tangential to the original issue (#3024), but I think this makes more sense than "fixing" `machinename` since it's a Windows behavior that the machine name property is truncated to 15 characters.

PS: I wasn't sure what to do about the copyright header. so have left them as it is.

### CODE REVIEW

**Comment by snakefoot** [comment]
What are the outputs of the 3 methods? 
All correctly contains more than 15 chars?
Do they contains domain-name? If so should it be stripped?

**Comment by amitsaha** [comment]
@snakefoot i will have to verify on my real system. But considering i have seen HOSTNAME being set correctly on a Windows system, I don’t see any issue there.

For the question regarding the domain mame, I am not sure. Do we need to?

**Comment by 304NotModified** [comment]
> What are the outputs of the 3 lookup-methods for your machine?
> All correctly contains more than 15 chars?
> Do they contains domain-name? If so should it be stripped?

Good questions!

**Comment by amitsaha** [comment]
@snakefoot some tests

Program.cs:

```
using System;

namespace test
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("HOSTNAME env variable: " + Environment.GetEnvironmentVariable("HOSTNAME"));
            Console.WriteLine("DNS Get Hostname: " + System.Net.Dns.GetHostName());
            Console.WriteLine("COMPUTERNAME env variable: " + Environment.GetEnvironmentVariable("COMPUTERNAME"));
        }
    }
}
```

`Dockerfile`:

```
FROM microsoft/dotnet:2.2-sdk

RUN mkdir C:\app
ADD . C:/app/

WORKDIR C:/app
CMD ["dotnet", "run"]
```

Build the image and run:

```
C:\> docker run -e HOSTNAME="averylong-hostname.com" -h "averylong-hostname.com"  amitsaha/test

HOSTNAME env variable: averylong-hostname.com
DNS Get Hostname: averylong-hostname.com
COMPUTERNAME env variable: AVERYLONG-HOSTN
```

So, as expected both HOSTNAME (via env variable) and DNS get hostname call returns the complete hostname where as the COMPUTERNAME is limited to 15 characters.

I am not sure how you feel about the domain name being present in the hostname. But, I think it's fine to leave it as it is?

**Comment by snakefoot** [comment]
Then I think you should replace the COMPUTERNAME fallback-lookup with `NLog.Internal.EnvironmentHelper.GetMachineName()`.

**Comment by amitsaha** [comment]
@snakefoot done.

**Comment by 304NotModified** [comment]
Thanks!

**Comment by amitsaha** [comment]
Thanks @304NotModified - i saw that the [wiki](https://github.com/NLog/NLog/wiki/HostName-Layout-Renderer) is updated as well.

**Comment by 304NotModified** [comment]
please also add it here :) (https://github.com/NLog/NLog.github.io/blob/master/config/layout-renderers.json) - for https://nlog-project.org/config/?tab=targets&search=hostname 

thanks!

**Comment by amitsaha** [comment]
Sure, done, https://github.com/NLog/NLog.github.io/pull/89

**Comment by 304NotModified** [comment]
Thanks!

**Comment by 304NotModified** [comment]
FYI, NLog 4.6 RC is online including this change!

**Pull request merged**
