### PR TITLE
Release 4.5.5

### PR DESCRIPTION
**Pull request by 304NotModified**
- [x] merge #2736 and in changelog
- [x] merge #2739  and changelog
- [x] merge #2740  and rebase

### CODE REVIEW

**Comment by 304NotModified** [comment]
not sure why it's now broken...

**Comment by 304NotModified** [comment]
@snakefoot any idea why the build fails with this change?

> Attempting to gather dependency information for package 'OpenCover.4.6.519' with respect to project 'C:\projects\nlog', targeting 'Any,Version=v0.0'
Gathering dependency information took 172.63 ms
Attempting to resolve dependencies for package 'OpenCover.4.6.519' with DependencyBehavior 'Lowest'
Unable to find package 'NLog'. Existing packages must be restored before performing an install or update.
Command exited with code 1


I works locally without problems for me

**Comment by snakefoot** [comment]
Nope no idea. Looks like "nuget install opencover" tries to resolve project dependencies when doing install of opencover. Which is unwanted.

Sent from my Samsung device


-------- Original message --------

**Comment by snakefoot** [comment]
Looks like your update worked. Build successful


Sent from my Samsung device


-------- Original message --------

**Pull request merged**
