### PR TITLE
fix for async test using xunit2 async support

### PR DESCRIPTION
**Pull request by petemounce**

### CODE REVIEW

**Comment by 304NotModified** [comment]
Cool, does it also work with xunit 1.9?

I tried xunit2, but failed with xamarin /win phone and other. Any experience with that?

**Comment by petemounce** [comment]
Oh, excuse me; I've got passing local tests using ncrunch v2.17 running tests in parallel inside Visual Studio 2015. I haven't tried this with modifying any nuget references, and I see xunit 1.9.1 is what's used. I see that doesn't pass in CI :(

**Comment by petemounce** [comment]
No, no direct experience with xamarin / windows phone.

**Comment by 304NotModified** [comment]
Did you have used xUnit 1 and 2? Any experience you like to share?

**Comment by petemounce** [comment]
Yes, I've used xunit. Mostly 1, some 2. It was a more pleasant experience
than nunit. What sort of experience are you looking for?

--

**Comment by 304NotModified** [comment]
Wll with xUNit 2 the runner is printing all the console writes, while with xUnit 1 that wasn't the case. Do you know how to fix that? It pollutes the build log 


image


See https://ci.appveyor.com/project/nlog/nlog/build/1.0.1099

**Comment by 304NotModified** [comment]
Don't close this one, we will move to xUnit2 and then will merge this one.

**Comment by 304NotModified** [comment]
fixes https://github.com/NLog/NLog/issues/1237

**Comment by 304NotModified** [comment]
Superseded by #1239

**Pull request closed without merging**
