### PR TITLE
Stacktrace broken fix

### LINKED ISSUE #541: UserStackFrame wrong when logger wrapped
Commit https://github.com/NLog/NLog/commit/abfd394e1119d1eee49738d5027f99b119693a7e
has reintroduced the behaviour logged in BUG 6737 "UserStackFrame wrong when logger wrapped" that was fixed in commit https://github.com/NLog/NLog/commit/08183add1cc7dbded0d84fa673358ad19e8824e5

### PR DESCRIPTION
**Pull request by 304NotModified**
Fixes  #541 and #579 (duplicate)

### CODE REVIEW

**Comment by 304NotModified** [comment]
Maybe I was smart to first create a 3.2.1 branch and then create the PR?

**Comment by Xharze** [comment]
That would be great. Then I'll fix the issue with variables too, and create
a new patch release

**Comment by 304NotModified** [comment]
Wont work. THe `SkipAssembly(Assembly assembly)` conflicts with new unit test `When_Wrapped_Ignore_Wrapper_Methods_In_Callstack`

**Comment by ilya-g** [comment]
@304NotModified since you're near `SkipAssembly` method, could you take a look on this issue:
`SkipAssembly` checks whether the `LogManager.HiddenAssemblies` contains an assembly, but accessing that property incurs copying its internal list storage to an array.

Since this occurs on every stack frame being analyzed on every log record being made, this can create a serious memory pressure.

**Comment by 304NotModified** [comment]
@ilya-g good idea. Any idea how to prevent this? 'static caching'?

**Comment by 304NotModified** [comment]
@ilya-g is there a issue ticket for the possible memory issue?

**Comment by 304NotModified** [comment]
@Xharze can you explain the method `FindCallingMethodOnStackTrace`?

I think it needs to be reimplemented

**Comment by ilya-g** [comment]
@304NotModified no there was no ticket, just an observation.
Proposed PR https://github.com/304NotModified/NLog/pull/4 for your branch.

**Comment by ilya-g** [comment]
The only way I see to have all the requirements, set out in tests, met is to extend the frame skipping condition to the `loggerType` and any of its subtypes.
Proposed this in PR https://github.com/304NotModified/NLog/pull/5 for this branch.

**Comment by 304NotModified** [comment]
@ilya-g excellent! 

Can you add some comments to the code? I have to admit it unclear what exactly is happening. Also it will prevent new bugs if it's more clear for everyone: )

**Comment by Xharze** [comment]
Is this PR ready to be merged?

**Comment by 304NotModified** [comment]
Almost. I will remove WIP and inform you when it's ready

**Comment by Xharze** [comment]
No problem

**Comment by ilya-g** [comment]
I've been trying to document the `FindCallingMethodOnStackTrace` method, and have stumbled across a question: what is the legal use case when it's `loggerType` parameter is null?

Technically it can come from `Logger.Log(Type wrapperType, LogEventInfo logEvent)`, but what are the real use cases when it would be required to pass `null` as `wrapperType` and thus disable frame skipping, based on logger type, leaving only assembly-skipping?

**Comment by 304NotModified** [comment]
Isn't just defensive programming?

**Comment by Xharze** [comment]
I believe so too, just defensive.

**Comment by ilya-g** [comment]
Ok, I've moved this defense to another level: when `null` is passed as `wrapperType` to the `WriteToTargets` method, it's substituted with the value of the `loggerType` field, which is constantly `typeof(Logger)`
PR https://github.com/304NotModified/NLog/pull/8 is ready to merge.

**Comment by 304NotModified** [comment]
If the merge errors are fixed, This PR is ready

**Comment by ilya-g** [comment]
@304NotModified, could you merge current NLog/master to this branch? It would require manual merge in Logger.cs.
After merging master into this branch, this branch can be seamlessly merged back into master.

**Comment by 304NotModified** [comment]
This is ready. Credits to @ilya-g

**Comment by Xharze** [comment]
I was currently looking into merging this for the v3.2.1 release, but this pull request is based of the master branch not the v3.2.1 branch. Could you create a new pull request for this? Otherwise it cannot be included in the patch release

**Comment by Xharze** [comment]
Ahh sorry we already talked about this. I'll remove the v3.2.1 milestone and change it to v4.0

**Comment by 304NotModified** [comment]
Well i'm favor of including in 3.2.1. I will try a new PR this weekend

**Pull request merged**
