### PR TITLE
Fix VerificationException Operation could destabilize the runtime

### PR DESCRIPTION
**Pull request by snakefoot**
That was triggered by copying readonly structs in medium trust AppDomain. Not sure why it would destabilize, but lets not get into details.

See also #3142 and #3138

### CODE REVIEW

**Comment by 304NotModified** [comment]
Looks good. Is it a good idea to add some comments that the `readonly` should not be readded to these places. E.g. R#/SonarQube will suggest to add these again

**Comment by snakefoot** [comment]
Sure. Added some comments

**Review by 304NotModified — APPROVED** [review]

**Comment by 304NotModified** [comment]
Thanks!

**Comment by snakefoot** [comment]
See also: https://minidump.net/verificationexception-in-net-framework-when-using-structs-6269eb3df448

**Pull request merged**
