### PR TITLE
JSON serializer: support objects, improvements and formatting, add memoryCache

### PR DESCRIPTION
**Pull request by 304NotModified**
Extends the default Json Serializer

- number formating with formatting string
- support serializing objects (with reflection)
- support timespan and guid
- serializer options object
- some method renames (only internals)
- performance tweaks
- more unit tests

Needed for #1376 and #2127 

todo:
- [x]  make backwardscomp
- [x] remove inner class
- [x] remove json5 support for now
- [x] quote key
- [x] option to disable quote key  -> for structured logging, so don't enable by default
- [x] is formatting really needed? -> for structured logging, so don't enable by default
- [x] props as real caching instead of static?
- [x] escape quotes
- [x] update commit text
- [x] check enum

### CODE REVIEW

**Comment by snakefoot** [comment]
PropCache should support multithreaded access. If using Dictionary then make a clone and throw the old dictionary away instead of modifying the existing dictionary.

**Comment by 304NotModified** [comment]
> PropCache should support multithreaded access. If using Dictionary then make a clone and throw the old dictionary away instead of modifying the existing dictionary.

Well in the worst case the props are lost? (lost update), That isn't a problem as it as "cache" imo. 

> Maybe have a parameter to control whether it should call ToString() on custom-object or if it should enumerate the customer-object-properties.

Yes, will add it. Was thinking to add a serializationProperties objects, so we could easily extend it in the future. 

ALso thinking to make a new interface ISerializer (in the correct namespace) and obsolete the current one. 

> Maybe also recognize IEnumerable<KeyValuePair> so they are translated more optimal.

Checking generic interfaces is AFAIK expensive. So doubting about this.

**Comment by snakefoot** [comment]
> Well in the worst case the props are lost? (lost update), That isn't a problem as it as "cache" imo.

In the worst case you will get an exception during TryGetValue because another thread modifying the Dictionary-object. But not if using the clone-update-method.

**Comment by 304NotModified** [comment]
could also add a try catch ;)

cloning and locking is expensive :|

**Comment by snakefoot** [comment]
> could also add a try catch ;)

Yes that is also a solution, if we are certain Dictionary never comes into a bad state after the exception (Two threads inserting at the same time).

> cloning and locking is expensive :|

Locking is expensive, but cloning is only expensive in the beginning where object-types are being discovered.

**Comment by 304NotModified** [comment]
AFAIK the concurrent dictionary is even slower.   ;)

**Comment by 304NotModified** [comment]
Related info: https://www.codeproject.com/Articles/548406/Dictionary-plus-Locking-versus-ConcurrentDictionar

**Comment by snakefoot** [comment]
> AFAIK the concurrent dictionary is even slower. ;)

Yes the ConcurrentDictionary is slower than Dictionary without locks. But if it is faster than Dictionary with lock, when doing lots of reads. Just like the article says:

> It is optimized to allow lock-free reading

> if you do much more reads than writes you will see that the ConcurrentDictionary is still faster

**Comment by 304NotModified** [comment]
FYI, when tracing NLog before I found that the cache in the layout renderer (dictionary) was one of time consuming the parts.

On topic. I'm not sure if I need locks. Just try catch.

**Comment by 304NotModified** [comment]
Also I didn't finished reading the article ;)

**Comment by snakefoot** [comment]
Maybe also add `DateTimeOffset` to this line:

`if (value is Guid || value is TimeSpan)`

Maybe consider to use this method instead of just calling ToString():

`Convert.ToString(value, System.Globalization.CultureInfo.InvariantCulture);`

**Comment by 304NotModified** [comment]
Thanks!

**Comment by snakefoot** [comment]
Could you not change the _propsCache into a _typeSerializerCache, where the serializer for a type is saved. Then you could also put the serializers for TimeSpan, Guid and DateTimeOffset into this cache at startup. 

The same cache can then also be used for saving the KeyValuePair-types that you might meet. Then there will only be an overhead the first time you meet a Type not seen before.

**Comment by 304NotModified** [comment]
Do you mean to cache the whole `Type` instead of the `PropertyInfo[]` ?

Ps. Improving the cache is still on the list. Gonna check the `MenoryCache` (and some replacement for net35)

**Comment by snakefoot** [comment]
> Do you mean to cache the whole Type instead of the PropertyInfo[] ?

Right it is declared like this:

`private static Dictionary<Type, PropertyInfo[]> _propsCache = new Dictionary<Type, PropertyInfo[]>(); `

Instead of mapping to `PropertyInfo[]`, then you could map to a function that can serialize the type. This delegate could then have captured PropertyInfo[] for its usage. Then you can register custom functions for custom Types like TimeSpan, Guid and DateTimeOffset (And maybe also KeyValuePair)

**Comment by 304NotModified** [comment]
Ah yes cache at a higher level. :) will check that. Thx!

**Comment by snakefoot** [comment]
> Improving the cache is still on the list. Gonna check the MenoryCache (and some replacement for net35)

"Advanced" caches like the MemoryCache usually introduces the ability to evict items that have not been used for a long time (Using timers and other exciting stuff). When an object-serializer has been born, do you plan to remove it from the cache again when not used for some time?

Think Dictionary and ConcurrentDictionary are excellent for doing caching.

**Comment by 304NotModified** [comment]
> "Advanced" caches like the MemoryCache usually introduces the ability to evict items that have not been used for a long time (Using timers and other exciting stuff). When an object-serializer has been born, do you plan to remove it from the cache again when not used for some time?

Yes, but then I should no use a dictionary in a memoryCache I guess (which is maybe even better)

**Comment by 304NotModified** [comment]
@snakefoot the MemoryCache is using [string as key](https://msdn.microsoft.com/en-us/library/dd988741(v=vs.110).aspx). I don't think It correct to use `Type.FullName` as key? What do you think?

**Comment by snakefoot** [comment]
I think MemoryCache is overkill. Dictionary is excellent for caching on its own. I would consider having a factory and give each layout their own instance of the serialiser. This will remove the multi threaded issue and also allow one to have a reusable string builder. It should be possible to register custom object serialiser in the factory so new instances born knows them. Nlog configuration reload should release and acquire new serialiser instances



Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment]
> I think MemoryCache is overkill.

not afraid that memory is never released? 

> I would consider having a factory and give each layout their own instance of the serialiser.

So also their own cache?

> This will remove the multi threaded issue and also allow one to have a reusable string builder.

I don't see that, but I think you're right ;)

**Comment by snakefoot** [comment]
Unless the application is planning to log an infinite amount of different types, then I am not afraid of the cache size

Yes an instance for each, also means a cache for each.


Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment]
@snakefoot I like to merge this one, would you like to review it?

Some things I will add in the future:

- [ ] readable date format
- [ ] better stringbuilder usage, lazyStringBuilder type?
- [ ] force stringify

I have added a caching class and a simple one for .NET 3.5, otherwise I don't feel comfortable to release it.

**Comment by snakefoot** [comment]
Still not sure why you are using MemoryCache. Is there a need for cache expiry? Have you tested performance between Dictionary and MemoryCache?

Remember a try-catch for the unprotected dictionary-lookup without lock, as it can throw exceptions.

**Comment by 304NotModified** [comment]
> Still not sure why you are using MemoryCache. Is there a need for cache expiry?

Static variable as cache could lead to memory leaks, as it's never removed from memory. The current max of 1000 is really arbitrary  - systems with more memory usage could how more and systems with less, less. 

Also MemoryCache is specially built for this, so I think it's the best choice.

**Comment by snakefoot** [comment]
> Also MemoryCache is specially built for this, so I think it's the best choice.

Think it is a strange to have a cache that generates garbage (MemoryCacheKey) for every item-lookup :)

**Comment by 304NotModified** [comment]
it's shortliving garbage, isn't it/

**Comment by snakefoot** [comment]
Any reason why you need a static-global-cache? Why not have a serializer-factory (that can be exchanged) that can create serializer-instance where needed. Then have multiple json-serializers. Each serializer can then have a lock-object that allows them to have a reusable-string-builder, and their own local type-cache. The serializer-instance can then be created on initialize of target or layout, and discarded on dispose of target or layout.

**Comment by snakefoot** [comment]
Looks like there are issues with the MemoryCache, when using the "new" concurrent garbage-collection:

https://stackoverflow.com/questions/5655439/net-4-memorycache-leaks-with-concurrent-garbage-collection

**Comment by 304NotModified** [comment]
> Any reason why you need a static-global-cache?

Well the cache will be less effective when it's not global.

**Comment by snakefoot** [comment]
> Well the cache will be less effective when it's not global.

Not sure I understand. How big are these objects in the cache? Are you worried about the initial prime of the cache?

**Comment by 304NotModified** [comment]
> Looks like there are issues with the MemoryCache, when using the "new" concurrent garbage-collection:
> 
> https://stackoverflow.com/questions/5655439/net-4-memorycache-leaks-with-concurrent-garbage-collection

mmm that's bad indeed

**Comment by snakefoot** [comment]
Instead of doing cache-clear when it reaches a 1000 items, then you could maintain a Most-Recently-Used-Cache:

https://stackoverflow.com/questions/22002814/is-this-algorithm-implementation-lru-or-mru

Would probably make the following modifications:
- Change MruItem into a struct (instead of class) that has the members Value + LinkedListNode<TKey> (Avoid unnecessary cache-line-misses after dictionary lookup).
- Change LinkedList into just holding the TKey (instead of MruItem)
- TryGetValue should check if the found item is already located first in the LinkedList, before doing Remove / AddFirst.
- Now instead of clearing the entire cache, then you can just remove the least recently used items.

Also the JsonSerializer should not perform constant lookups into the cache when serializing a list or dictionary of objects. Instead it should perform cache-lookup once, and reuse that for all items in the collection (ofcourse with fallback to cache-lookup if the collection have many different types of objects).

**Comment by 304NotModified** [comment]
if you have time, please go ahead.

Unfortunately less time these weeks, busy on a new house, planning, painting, moving etc. Not sure if I have time tomorrow. 

I could also remove the cache, and then we could create a new PR

**Comment by 304NotModified** [comment]
superseded by https://github.com/NLog/NLog/pull/2179

**Pull request closed without merging**
