### PR TITLE
ConfigSetting - Preregister so it can be accessed without extension registration

### PR DESCRIPTION
**Pull request by snakefoot**
Improved user experience for #3097

### CODE REVIEW

**Comment by 304NotModified** [comment]
>   NLog.UnitTests.LogManagerTests.GlobalThresholdTest [SKIP]
      Side effects to other unit tests.
    NLog.UnitTests.ConfigFileLocatorTests.NLogDotDllDotNLogInDirectoryWithSpaces [FAIL]
      System.IO.IOException : The process cannot access the file 'NLog.dll' because it is being used by another process.
      Stack Trace:

not sure what is going on (on appveyor)

**Comment by snakefoot** [comment]
> not sure what is going on (on appveyor)

Yes it is weird. Only happens when doing code-coverage testing.

**Comment by snakefoot** [comment]
Working build:

> Successfully installed 'OpenCover 4.6.519' to C:\projects\nlog

Non-working build:

> Successfully installed 'OpenCover 4.7.922' to C:\projects\nlog

Guess we should use the old version until NLog 4.6 is done to avoid more noise.

**Comment by snakefoot** [comment]
Could this become NLog 4.6 since it is not a critical change?

**Comment by snakefoot** [comment]
Wheee a successful build

**Comment by 304NotModified** [comment]
> Could this become NLog 4.6 since it is not a major change? And really critical for usability.

FYI I really prefer code freeze after a RC.  But this change is indeed kinda bugfix. Thanks!

**Pull request merged**
