### PR TITLE
Update NLog.Config for DNX

### PR DESCRIPTION
**Pull request by 304NotModified**
Fixes partly https://github.com/NLog/NLog/issues/1080. Needs confirm that it's working.

### CODE REVIEW

**Comment by 304NotModified** [comment]
not working yet

**Comment by Page-Not-Found** [comment]
We might have to think about exposing a extension method like `UseNLog` or `AddNlog` which can be attached to the pipeline in ASP.Net 5 or added as a injected service. Instead of doing all this.

The methods can have the filenames which you want to search for. :)

**Comment by 304NotModified** [comment]
@Page-Not-Found like [this](https://github.com/NLog/NLog.Framework.logging/blob/init/src/NLog.Framework.logging/AspNetExtensions.cs)?

**Comment by Page-Not-Found** [comment]
Yes. Correct.

**Comment by 304NotModified** [comment]
So you have experience with asp.net 5 /dnx @Page-Not-Found?

**Comment by Page-Not-Found** [comment]
@304NotModified I started learning now. :) We are working on a new project in my company for migration, so thinking about using ASP.net 5

**Comment by 304NotModified** [comment]
I have to test https://github.com/NLog/NLog.Framework.logging/tree/init

Can you do that?

**Comment by Page-Not-Found** [comment]
Sure. I will take this up may be next week.

**Comment by Page-Not-Found** [comment]
Let us Discuss in Gitter.

**Comment by 304NotModified** [comment]
Won't work. Docs nuget unclear and not supported?

**Pull request closed without merging**
