### PR TITLE
.NET Core support (NLog 5)

### PR DESCRIPTION
**Pull request by 304NotModified**
CoreCLR support PR for more visibility / build status / merge status.

This is work in progress, mostly by @phenixdotnet (thanks!!)

See for discussion: https://github.com/NLog/NLog/issues/641

todo:
- [x] run net45 test on AppVeyor
- [x] run coreCLR tests on AppVeyor
- [x] rename UWP10 cond compilation symbol.
- [x] include net40 build
- [x] include xamarin builds
- [x] To netplatform (when CoreCLR RC2 has been released)
- [ ] fix assembly FILE version.
- [x] fix UWP build (nuget dependencies packages weren't working yet)
- [x] fix Travis (build.sh)
- [x] all tests are failing for dotnet5.4?
- [x] add SL4 + SL5
- [x] add wp8
- [x] Fix XML docs
- [ ] fix failing unit tests, among others:
  - [ ] basedir (appContext?)
  - [ ] callsite
- [ ] Enable unit tests
  - [ ] Callsite
  - [ ] RelativeSequentialArchiveTest_MaxArchiveFiles_0

NETSTANDARD2 needed for
- [ ] TryTypeConverterConversion, TypeDescriptor
- [ ] getCurrentClassLogger() - StackFrame 

# build
- build.ps1

---

This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1160)

### CODE REVIEW

**Comment by 304NotModified** [comment]
build from dnu:

```
dnu restore --quiet
dnu build src/NLog --quiet
```

and nuget 

```
dnu pack src/NLog --quiet
```

**Comment by 304NotModified** [comment]
@phenixdotnet I fixed the .cake and DNU version. There was a mistake with the version and target for the unit tests in the .Cake file. 

TODO
- [ ] fix .cake for Travis (build.sh)

**Comment by 304NotModified** [comment]
> An error occured when executing task 'sl5'.
>  
> ======================================== 
> pack 
> ========================================

@phenixdotnet any idea what this error is about?

Is this related? (maybe we can disabled nlog.unittests.web)

> Running unit tests in project .\tests\NLog.UnitTests.Web 
> Error: Unable to load application or execute command 'test'.
> An error occured when executing task 'net35'.

**Comment by phenixdotnet** [comment]
Any error logs ?
No I don't thinks it's related.

I don't know if the tests\NLog.UnitTests.Web is really under dev in the coreclr ;)

**Comment by 304NotModified** [comment]
Do you know if It the Travis problem is a cake or unit test problem?   [NLog.Extensions.Logging](https://github.com/NLog/NLog.Extensions.Logging) does [run on Travis](https://travis-ci.org/NLog/NLog.Extensions.Logging)

**Comment by phenixdotnet** [comment]
The Travis build fail because travis use an unsupported version of linux. We can try to force travis to build on mac os x ?

**Comment by phenixdotnet** [comment]
I update the .travis file to use osx.
The project build but unit tests failed (as expected ^^)

**Comment by 304NotModified** [comment]
Thanks! 

I did not expected errors. Unit tests should succeed in dotnet5.4 and net451

**Comment by Page-Not-Found** [comment]
> fix net45 test

What is the failure here? I can help with this.

**Comment by 304NotModified** [comment]
Wel try to run on appveyor. See branch coreCLR+test.  Help would be appreciated! Please test in a separate branch

**Comment by jasonwilliams200OK** [comment]
> fix Travis (build.sh)

@304NotModified, should it be considered fixed by 086ff66?

> fix assembly FILE version.

Can you elaborate on this one? If this is about AssemblyInfo and still an issue, I can give it a try.. :)

---

Since #1592 was merged as "Squash and merge", this PR is still showing conflicts with master (as the original merge commit and yet commits from master are squashed); coreCLR branch would require another merge with master.

**Comment by 304NotModified** [comment]
> @304NotModified, should it be considered fixed by 086ff66?

I think it does :)



> Can you elaborate on this one? If this is about AssemblyInfo and still an issue, I can give it a try.. :)

Sure, two things:

1. The assembly file version is now fixed (it should be from AppVeyor)

image

2. We are missing info in netstandard1.5 (but maybe it's a NPE bug)
image

netstandard1.3 is correct:
image



> Since #1592 was merged as "Squash and merge", this PR is still showing conflicts with master (as the original merge commit and yet commits from master are squashed); coreCLR branch would require another merge with master.

Oops, sorry about that. If you have time for this, please, otherwise I will fix it probable this week

**Comment by jasonwilliams200OK** [comment]
I cloned [NuGetPackageExplorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) and debug the netstandard1.5 issue and it doesn't seems like the bug in NPE, but with Assembly.GetCustomAttributesData throwing at [CodeExecutor/AppDomainWorker.cs#L64](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/0df06e7/CodeExecutor/AppDomainWorker.cs#L64):

>+		{"Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.":"System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"}	System.Exception {System.IO.FileNotFoundException}


 So far, steps to reproduce are:

```cmd
mkdir \temp
cd \temp
git clone https://github.com/NLog/NLog --single-branch -b coreCLR --recursive
cd NLog
dotnet restore
dotnet build src/NLog -f netstandard1.3 -c Release
dotnet build src/NLog -f netstandard1.5 -c Release
```

Then create an additional application to test assembly loading:

```cmd
mkdir \temp\test-asm
cd \temp\test-asm
dotnet new 
```

Replace Program.cs with:

```c#
using System.Reflection;

public class Program
{
  public static void Main(string[] args)
  {
    Assembly.Load
    (
    	AssemblyName.GetAssemblyName(@"\temp\NLog\src\NLog\bin\Debug\netstandard1.5\NLog.dll")
        // change 1.5 to 1.3 and won't have any exception thrown
    )
    .GetCustomAttributesData();
  }
}
```

and project.json with:

```json
{
  "buildOptions": { "emitEntryPoint": true },
  "frameworks": { "net45": { } }
}
```

Would be nice if we could narrow the issue down and make a self-contained example for coreclr issue tracker. I can't reproduce, for example, with assembly produced by new lib project: `dotnet new -t lib && notepad project.json && dotnet restore && dotnet run` and having netstandard1.3 and netstandard1.5 simultaneously in the project.json.

**Comment by 304NotModified** [comment]
cool! thanks, looks like something is wrong with the nuspec maybe

**Comment by snakefoot** [comment]
@304NotModified Maybe we should create a new branch from master (ex coreclr2), and then fix that to support NetStandard13 + NetStandard15 + NetStandard20.

But maybe wait until we have a NLog 4.5 BETA ready.

**Comment by 304NotModified** [comment]
> @304NotModified Maybe we should create a new branch from master (ex coreclr2), and then fix that to support NetStandard13 + NetStandard15 + NetStandard20.

Well I'm thinking of dropping NetStandard13+NetStandard15 support. Too much legacy.

> But maybe wait until we have a NLog 4.5 BETA ready.

Yes, I prefer that at least.

**Comment by 304NotModified** [comment]
4.5 will have .NET standard 2 support. These changes won't be merged to master

**Pull request closed without merging**
