### PR TITLE
Merge NLog 4.7.7 to dev* 

### PR DESCRIPTION
**Pull request by 304NotModified**
supersedes the revered #4258. It has the same commits as #4258

### CODE REVIEW

**Review by snakefoot — APPROVED** [review]
Thank you for reverting my mistake, and making it right.

**Comment by 304NotModified** [comment]
No problem. I hope this won't get into confusing with PR in the future, but otherwise I will rebase them with pleasure :)

**Comment by snakefoot** [comment]
Git (or maybe GitHub) really sucks at showing merges (maybe caused by file being moved):

https://github.com/NLog/NLog/commits/dev/src/NLog/Layouts/JSON/JsonLayout.cs

But this files looks ok:

https://github.com/NLog/NLog/commits/dev/src/NLog/Internal/SingleCallContinuation.cs

Not sure what the best direction is for getting a proper commit-history when NLog 5.0 is released.

**Comment by 304NotModified** [comment]
> Git (or maybe GitHub) really sucks at showing merges (maybe caused by file being moved):
> 
> https://github.com/NLog/NLog/commits/dev/src/NLog/Layouts/JSON/JsonLayout.cs

What is the expected result for you?

**Comment by snakefoot** [comment]
To see these 3 commits:

- JsonLayout - Unwind after invalid property value to avoid invalid Json
- Added ExcludeEmptyProperties to JsonLayout. along with unit tests.
-  fix: generate legal json for keys that contain quote (#4202) 

https://github.com/NLog/NLog/commits/master/src/NLog/Layouts/JsonLayout.cs

**Comment by 304NotModified** [comment]
I see maybe commits on https://github.com/NLog/NLog/commits/master/src/NLog/Layouts/JsonLayout.cs?

image

**Comment by snakefoot** [comment]
Yes those commits are not visibile here on dev-branch:

https://github.com/NLog/NLog/commits/dev/src/NLog/Layouts/JSON/JsonLayout.cs

But I see them here, and they have just been merged from master to dev-branch:

https://github.com/NLog/NLog/commits/master/src/NLog/Layouts/JsonLayout.cs

**Comment by 304NotModified** [comment]
I see locally that cb8d8fc213e4ac47fda198955265cd4d50c8fc1b in in both dev and master. So I guess the rename indeed.

**Comment by snakefoot** [comment]
The problem can also be seen here with last commit on master-branch:

https://github.com/NLog/NLog/commits/master/src/NLog/LoggerImpl.cs

But because of file changes (not because of rename), then it just becomes this:

https://github.com/NLog/NLog/commits/dev/src/NLog/LoggerImpl.cs

**Pull request merged**
