### PR TITLE
WebServiceTarget - Enable OptimizeBufferReuse by default & Ability to add HTTP request headers

### PR DESCRIPTION
**Pull request by snakefoot**
Waiting for NLog ver. 4.5

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1912)

### CODE REVIEW

**Comment by snakefoot** [comment]
Added support for HttpWebRequest Headers. Not sure if it should be pushed to NLog 5.0, as it is a breaking change.

**Comment by 304NotModified** [comment]
Where is the breaking change?

**Comment by snakefoot** [comment]
> Where is the breaking change?

This method is now throwing an exception:

```
protected override void DoInvoke(object[] parameters, AsyncContinuation continuation)
{
   // method is not used, instead asynchronous overload will be used
   throw new NotImplementedException();
}
```

As it has been replaced by this override method:

`protected override void DoInvoke(object[] parameters, AsyncLogEventInfo logEvent)`

**Comment by snakefoot** [comment]
@304NotModified Now modified the code, so it is no longer a breaking change.

**Comment by 304NotModified** [comment]
\0/ thanks!

**Comment by snakefoot** [comment]
Updated documentation:

https://github.com/NLog/NLog/wiki/WebService-target

**Pull request merged**
