### PR TITLE
Release 4.6.4 (WIP)

### PR DESCRIPTION
**Pull request by 304NotModified**
Merge commit

### CODE REVIEW

**Comment by snakefoot** [comment]
Have PR for improving the reflection on JObject from JSON.NET that I would like to include. Just need a little more time.

**Comment by 304NotModified** [comment]
Ok! I will try to release this week.

**Comment by 304NotModified** [comment]
will reopen when all prs are merged

**Comment by 304NotModified** [comment]
superseded by https://github.com/NLog/NLog/pull/3437

**Pull request closed without merging**
