### PR TITLE
Reduce code complexity in different locations

### PR DESCRIPTION
**Pull request by snakefoot**

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks!

Did you use a refactoring tool for this? (e.g. VS2017, R#). Does it need a review?

**Comment by snakefoot** [comment]
Tried using VS2017 method extractor, but it failed at all locations. So I moved the code manually.

Split into individual commits, so they should be easy to review.

**Comment by 304NotModified** [comment]
yes, R# is much better.

**Comment by 304NotModified** [comment]
Looks good, thanks! 👍

**Pull request merged**
