### PR TITLE
Fix use of single archive in file target

### LINKED ISSUE #470: using a single archive file may not continue to rollover properly
My file target looks like this:

 ```xml
<target name="LogFile" xsi:type="File" 
   FileName="${specialfolder:CommonApplicationData}\AppName\logfilename.log"
   Layout="${longdate} | ${threadid} | ${level:uppercase=true} | ${logger} | ${message}" 
   archiveAboveSize="5242880"
   maxArchiveFiles="1"
   archiveFileName="${specialfolder:CommonApplicationData}\AppName\logfilename.lg2"
/>
```

The `logfilename.log` fills up and rolls over to `logfilename.lg2` but then logging stops.

`FileTarget.DynamicArchiveFileHandlerClass.AddToArchive(string archiveFileName, string fileName, bool createDirectoryIfNotExists)` had an empty `archiveFileEntryQueue`.  And so `File.Delete` wasn't being called on the archive file which caused the `File.Move` to throw an exception.

I've modified `AddToArchive` to delete the archive file if only one file is to be kept, and can submit a PR if that solution is good.

Is there a different way to configure the logging that I need?

### PR DESCRIPTION
**Pull request by Xharze**
Manual fix of merge conflicts. Code taken from #471
closes #471
fixes #470

### CODE REVIEW

**Comment by 304NotModified** [comment]
Can we unit test this?

**Comment by Xharze** [comment]
It should be possible to unit test, I'll give it a shot

**Comment by 304NotModified** [comment]
@Xharze I think this can be merged?

**Comment by Xharze** [comment]
It has been merged

**Pull request merged**
