### PR TITLE
Added failing unit test for #1426

### PR DESCRIPTION
**Pull request by niemyjski**
See https://github.com/NLog/NLog/issues/1426

This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1660)

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks! Will look in depth of it

**Comment by 304NotModified** [comment]
Too bad AppVeyor is broken :(

**Comment by 304NotModified** [comment]
Related

- http://stackoverflow.com/questions/31346574/setting-thread-currentprincipal-with-async-await
- http://stackoverflow.com/questions/16552539/set-thread-currentprincipal-asynchronously

**Comment by niemyjski** [comment]
@304NotModified This unit test might not be the best to show it but what I'm seeing is that the layouts and writes happen on the same thread but the async calls to the target happen on a different thread. Thus the information is lost. If the information that was used to calculate the layouts was in a cache this wouldn't be an issue.

**Comment by 304NotModified** [comment]
@niemyjski I would be nice if the unit test works without `async`. The would be easier to debug. Is that possible?

**Comment by niemyjski** [comment]
You're trying to test async targets without any async? Granted this test doesn't really reproduce the environment I'm running in but does show off a symptom of the real issue.

**Comment by 304NotModified** [comment]
Yes with task.run on something like that? It's unclear to me if this is only an issue when using `async`

**Comment by 304NotModified** [comment]
> Yes with task.run on something like that? It's unclear to me if this is only an issue when using async

Bump @niemyjski

**Comment by niemyjski** [comment]
Well, the reason this fails is because the thread can change because doing any async operation can change the synchronization context (please correct me if I'm wrong). The core problem is that layouts run on the same calling thread but targets can happen on a completely different background thread due to async targets..

**Comment by 304NotModified** [comment]
Well this issue happens because the first possible to record the info (`logger.Debug("test write");`) is on the wrong thread. 

I don't know if this would be possible to fix. We need an additional call on the correct thread I guess.

**Comment by 304NotModified** [comment]
the unit test is wrong IMO. This is not testing NLog's functionality, but it tests that the `Thread.CurrentPrincipal ` has been changed.

I will update the test and prove `${identity}` **is** working and also in `async` contexts.

**Comment by 304NotModified** [comment]
See https://github.com/niemyjski/NLog/pull/1

**Comment by 304NotModified** [comment]
superseded by https://github.com/NLog/NLog/pull/1692

**Pull request closed without merging**
