### PR TITLE
LogFactory.Setup with fluent registration of condition methods

### LINKED ISSUE #1934: New syntax for registering ConditionMethods via code?
**NLog Version:** 4.4.1
**Platform:** .NET 4.5

Not really sure if this would be considered a bug or a feature or just a question, but it looks to me like there's no suitable manual registration method for ConditionMethods that matches the new syntax style found in the examples for other extensions [here](https://github.com/NLog/NLog/wiki/Register%20your%20custom%20component). I'm trying to prototype some stuff in LINQPad where configuring NLog using code for now and I'm finding it would be nice to be able to point NLog at my static class decorated with ConditionMethods, rather than use the extensions configuration element (probably using the `typeof` format, since static classes can't be used as Generic Type Arguments). It looks like in the meantime, I can probably use the older style like the following example (haven't tested this yet, but it looks like it will probably work), but I thought I'd point out the discrepancy since it looks like there's some movement to provide a different mechanism for registering extensions with code.

```c-sharp
    ConfigurationItemFactory.Default.ConditionMethods.RegisterDefinition("has-diag-category", typeof(NLogConditionMethods).GetMethod("HasDiagnosticCategory", BindingFlags.Static));

### PR DESCRIPTION
**Pull request by snakefoot**
Trying to resolve #1934
```c#
LogManager.Setup().SetupExtensions(s => 
   s.RegisterConditionMethod("hasParameters", evt => evt.Parameters?.Length > 0)
);
```

And ofcourse the usual suspect:
```c#
LogManager.Setup().SetupExtensions(s =>
   s.RegisterConditionMethod("has-diag-category", typeof(NLogConditionMethods).GetMethod("HasDiagnosticCategory", BindingFlags.Static))
);
```

Also optimized the MethodFactory to only scan classes and abstract-classes for static-methods. Skipping value-types and interfaces.

### CODE REVIEW

**Comment by 304NotModified** [comment]
proposal: rename to RegisterConditionMethod

**Comment by snakefoot** [comment]
Well `ConditionMethod` are used for filtering. That is why I suggest:

> RegisterFilter**ConditionMethod**

So it is easier for new users to recognize what `ConditionMethod` is used for.

**Comment by 304NotModified** [comment]
I understand that. But it's called ConditionMethod  and not FilterConditionMethod (unfortunately).  I prefer keeping one term for one thing and don't use other names in other APIs

**Comment by snakefoot** [comment]
> But it's called ConditionMethod and not FilterConditionMethod (unfortunately).

I'm confused. We are trying to make a new Setup-API and mark the old `ConfigurationItemFactory.Default` as obsolete. Why should the new API continue the errors from something that will be obsolete (And some point removed) ?

**Comment by 304NotModified** [comment]
It's not only ConfigurationItemFactory.Default, it also the base class and all the docs on the web .

Also I don't thing adding Filter makes it really that more clear. Filters use conditions and those are not the same.

**Comment by snakefoot** [comment]
Well a change has to start somewhere. But not today. `RegisterConditionMethod` it is.

**Comment by 304NotModified** [comment]
> Well a change has to start somewhere.

Yes this is difficult. When doubting I prefer to use the old terms and not adding obsoletes at all. If the name is a 6 out of 10, then if IMO still better dan 2 names.

**Comment by snakefoot** [comment]
Updated wiki: https://github.com/NLog/NLog/wiki/When-Filter#extensibility

**Pull request merged**
