### PR TITLE
FileTarget - KeepFileOpen should watch for file deletion

### LINKED ISSUE #1826: Logging stops using archiving and async target
Hi,

I tried to use archiving (DateAndSequence) in combination with async target and keepFileOpen.
Testing this feature locally with our database log worked fine and the archive files where created like expected (Database 20161205.1.log, Database 20161205.2.log ....).

Putting same configuration under stress running multiple WCF-Requests causing the logging to stop. Leaving a valid log file like Database ${522or5ae}.0.log and no further activity.

First I thought it could be something like #1029 but updating from 3.2.0 to 4.3.11 did not help. It looks like the logger dies silently the very moment the current file is archived (see internal log). 

The WCF Service is running on Windows Server 2008 and .Net-Framework 4.5.1.

My current work around is using the archiving on daily base only. but files with size of 1.5 GB and more are not easy to handle.

[nlog.config.txt](https://github.com/NLog/NLog/files/631357/nlog.config.txt)

~nlog-internal.log.txt~

### LINKED ISSUE #1856: File target - keepFileOpen: file is not recreated if deleted manually.
**Type**: Bug
**NLog version**: 4.3.4
**Platform**: .Net 4.5

I have configured a file target:
`<target name="myFileTarget" xsi:type="File"
	fileName="${event-properties:item=myFileDir}\${event-properties:item=myFile}"
	layout="${message}"
	cleanupFileName="false"
	autoFlush="false"
	concurrentWrites="false"
	keepFileOpen="true">
</target>`

When I run my application the file gets created and logged into like expected. When my application is idle (no logs are created) and I delete the logfile and then the application starts to produce logs again, the file is not re-created, the logs go to nowhere and no exception or error occures.

I expect that the file is recreated when it does no longer exist. If I set keepFileOpen = "false" this is the case.

### LINKED ISSUE #1866: FileTarget Archiving gets stuck
**Type**:

- Bug

**NLog version**: 4.4.0

**Platform**: .Net 4.5

**Current NLog config** (xml or C#, if relevant)
```

	        var fileTarget = new FileTarget
	        {
	            FileName = Path.Combine(directoryPath, "${logger}_${date:format=yyyyMMdd}.txt"),
	            Layout = DefaultLayoutFormatter,
                NetworkWrites = false,
                KeepFileOpen = true,
                ConcurrentWrites = true,
	            Name = name,
                MaxArchiveFiles = 10,
                ArchiveAboveSize = 1024 * 20, //1024*1024*10 - we reduce the log size before archiving to 20KB to reach the problematic condition quicker, with log size of 10MB the problem reproduces as well
                ArchiveFileName = Path.Combine(directoryPath, "${logger}_{#}.txt"),
                ArchiveDateFormat = "yyyyMMdd.HHmmss",
                ArchiveNumbering = ArchiveNumberingMode.DateAndSequence
            };
            var fileWrapper = new BufferingTargetWrapper
            {
                WrappedTarget = fileTarget,
                Name = name,
                SlidingTimeout = true
            };

            LogManager.Configuration.AddTarget(name, fileWrapper);

            var logFileLoggingRule = new LoggingRule("*", minLevel, fileTarget);
	        LogManager.Configuration.LoggingRules.Add(logFileLoggingRule);

```

Bug description:
We have a "host" application that spins up multiple child "runner" applications.
The "host" application can write to it's own single "host" log.
Multiple "Runner" application can write to a single "runners" log as well as write some diagnostic information in "host" log.
Therefore, for both "runner" and "host" logs there are multiple writers.
The configuration above reflects that.

- What is the current result?

At some point during the runtime of the application when archiving of "host" log happens, it gets stuck on "host" application side (at least) with the following message:

```

2016-12-18 21:15:36.4364 Info Deleting old archive D:\Temp\Logs\HOST_20161218.211223.0.txt.
2016-12-18 21:15:36.4364 Warn Failed to archive file 'D:\Temp\Logs\HOST_20161218.txt'. Exception: System.UnauthorizedAccessException: Access to the path 'D:\Temp\Logs\HOST_20161218.211223.0.txt' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at NLog.Targets.FileTarget.EnsureArchiveCount(List`1 oldArchiveFileNames)
   at NLog.Targets.FileTarget.ArchiveByDateAndSequence(String fileName, String pattern, LogEventInfo logEvent)
   at NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventInfo)
   at NLog.Targets.FileTarget.TryArchiveFile(String fileName, LogEventInfo ev, Int32 upcomingWriteSize)

```
If we look at system handles, we see the following picture:

```

ServiceManager.Host.exe (29528), File, D:\Temp\Logs\HOST_20161218.txt, 0x104c
ServiceManager.Runner.exe (4824), File, D:\Temp\Logs\HOST_20161218.211240.0.txt, 0xb0c
ServiceManager.Runner.exe (7404), File, D:\Temp\Logs\HOST_20161218.211520.0.txt, 0x8c4
ServiceManager.Runner.exe (8404), File, D:\Temp\Logs\HOST_20161218.211223.0.txt, 0x8ac
ServiceManager.Runner.exe (17008), File, D:\Temp\Logs\HOST_20161218.211456.0.txt, 0x87c
ServiceManager.Runner.exe (17812), File, D:\Temp\Logs\HOST_20161218.211432.0.txt, 0xaec
ServiceManager.Runner.exe (23244), File, D:\Temp\Logs\HOST_20161218.211456.0.txt, 0x8dc
ServiceManager.Runner.exe (26364), File, D:\Temp\Logs\HOST_20161218.211536.0.txt, 0x860
ServiceManager.Runner.exe (27284), File, D:\Temp\Logs\HOST_20161218.211552.0.txt, 0x884
ServiceManager.Runner.exe (27892), File, D:\Temp\Logs\HOST_20161218.211536.0.txt, 0x6bc
ServiceManager.Runner.exe (28220), File, D:\Temp\Logs\HOST_20161218.211520.0.txt, 0x884
ServiceManager.Runner.exe (29672), File, D:\Temp\Logs\HOST_20161218.211520.0.txt, 0x8b8
ServiceManager.Runner.exe (37296), File, D:\Temp\Logs\HOST_20161218.211456.0.txt, 0x8ac
ServiceManager.Runner.exe (37856), File, D:\Temp\Logs\HOST_20161218.211601.0.txt, 0x4f4
ServiceManager.Runner.exe (38412), File, D:\Temp\Logs\HOST_20161218.211552.0.txt, 0x8d4
ServiceManager.Runner.exe (40516), File, D:\Temp\Logs\HOST_20161218.txt, 0x8c8
ServiceManager.Runner.x86.exe (26160), File, D:\Temp\Logs\HOST_20161218.211601.0.txt, 0x98c

```
Where (8404) is process id. We see that "Runner" process with process id of "8404" has got a hold of the "host" log file and none of the processes can now archive it, if we observe this for longer we see that this process never closes this handle, so I expect that it is stuck.

If we attach a debugger to 8404 PID "Runner" process we see the following messages being generated over and over:
```

NLog: 2016-12-18 20:56:16.0584 Error Error has been raised. Exception: System.ObjectDisposedException: Cannot access a closed file.
   at System.IO.__Error.FileNotOpen()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.FileStream.get_SafeFileHandle()
   at NLog.Internal.Win32FileCharacteristicsHelper.GetFileCharacteristics(String fileName, FileStream fileStream)
   at NLog.Internal.FileAppenders.WindowsMultiProcessFileAppender.GetFileLength()
   at NLog.Internal.FileAppenders.FileAppenderCache.GetFileLength(String filePath, Boolean fallback)
   at NLog.Targets.FileTarget.GetArchiveFileNameBasedOnFileSize(String fileName, Int32 upcomingWriteSize)
   at NLog.Targets.FileTarget.GetArchiveFileName(String fileName, LogEventInfo ev, Int32 upcomingWriteSize)
   at NLog.Targets.FileTarget.TryArchiveFile(String fileName, LogEventInfo ev, Int32 upcomingWriteSize)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
```

On some occasions when we attach to the Runner that has the problematic fild handle open - we see no exceptions as above.

- What is the expected result?

The archiving of files does not get stuck when there's multiple log writers.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?

Yes, it contains the exceptions reported.

- Please post full exception details (message, stacktrace, inner exceptions)

See above

- Are there any work arrounds? yes/no

Not to my knowledge

- Is there a version in which it did worked? 

Unknown

- Can you help us by writing an unit test?

At this point I have a repro case and can supply exception traces

### PR DESCRIPTION
**Pull request by snakefoot**
KeepFileOpen should watch for file deletes/renames and close active appenders. Deactivate background monitoring when no active appenders.

(Should) fixes #1826, fixes #1856, fixes #1866

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1878)

### CODE REVIEW

**Comment by 304NotModified** [comment]
I think this one also fixes https://github.com/NLog/NLog/issues/298 ?

**Comment by snakefoot** [comment]
> I think this one also fixes #298 ?

The MultiFileWatcher.NotifyFilters for the Reload-Timer is different from the MultiFileWatcher.NotifyFilters for the Archive-Folder. So I don't know.

**Comment by 304NotModified** [comment]
Reviewed 1 of 4 files at r1, 2 of 4 files at r2.
Review status: 3 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/NLog/Internal/MultiFileWatcher.cs, line 179 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aHH3EHgCuGaLPJCLD:-K_aHH3EHgCuGaLPJCLE:bm9p09k) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/src/NLog/Internal/MultiFileWatcher.cs#L179)):*
> ```Smalltalk
>             var exception = e.GetException();
>             if (exception != null)
>                 InternalLogger.Info(exception, "Error Watching Path {0}", watcherPath);
> ```

I think .Warn is better? (twice)

---

*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 122 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aHvgpvyCdxykZdvAU:-K_aHvgqpeXMRoiM8vsY:b-6wc2go) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L122)):*
> ```Smalltalk
>                     {
>                         string currentFolderPath = Path.GetDirectoryName(e.FullPath);
>                         if (StringComparer.OrdinalIgnoreCase.Compare(archiveFolderPath, currentFolderPath) != 0)
> ```

why not .Equals(..., .OrdinalIgnoreCase)? 

---

*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 124 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aI3CZmBbCxc6itQaN:-K_aI3CZmBbCxc6itQaO:b-4gtt8l) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L124)):*
> ```Smalltalk
>                         if (StringComparer.OrdinalIgnoreCase.Compare(archiveFolderPath, currentFolderPath) != 0)
>                         {
>                             if ((e.ChangeType & (WatcherChangeTypes.Deleted | WatcherChangeTypes.Renamed)) != 0)
> ```

Duplicate code (4 lines) 

---

*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 138 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aI9ZJdv9p9I2LBLog:-K_aI9ZJdv9p9I2LBLoh:b-vnapov) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L138)):*
> ```Smalltalk
>             if ((e.ChangeType & WatcherChangeTypes.Created) == WatcherChangeTypes.Created)
>             {
>                 logFileWasArchived = true;  // Something was created in the archive folder
> ```

partly duplicate code.

---

*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 160 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aINdbMT6is4-yF7VW:-K_aINdbMT6is4-yF7VX:bqzvagw) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L160)):*
> ```Smalltalk
>                             externalFileArchivingWatcher.StopWatching(directoryPath);
>                     }
> ```

no need to fall back to `externalFileArchivingWatcher.StopWatching();` ?

---

*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 176 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aI_N4l95BsHZAfEWE:-K_aI_N4l95BsHZAfEWF:b-ci9faj) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L176)):*
> ```Smalltalk
>             {
>                 logFileWasArchived = false;
>                 CloseAppenders("Cleanup Archive");
> ```

why the order change? Is this to prevent to preform the cleanup twice? Don't we need a lock in that case?

---

*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 269 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aJ6aS-bIfXWO8Rxvo:-K_aJ6aS-bIfXWO8Rxvp:bobfl9k) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L269)):*
> ```Smalltalk
>                     var oldAppender = appenders[freeSpot];
>                     appenders[freeSpot] = null;
>                     CloseAppender(oldAppender, "Stale");
> ```

is this change necessary?  Or an enhancement? 

---

*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 293 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aJI2O38TBn-XUXgiF:-K_aJI2O38TBn-XUXgiG:b-5ghp2m) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L293)):*
> ```Smalltalk
>                         externalFileArchivingWatcher.Watch(archiveFilePatternToWatch);
>                     }
>                     externalFileArchivingWatcher.Watch(appenderToWrite.FileName);
> ```

two watches is by design?

---

*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 319 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aJS9O16k0bM71GUyO:-K_aJS9O16k0bM71GUyP:b-vqgjc1) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L319)):*
> ```Smalltalk
>                     var oldAppender = appenders[i];
>                     appenders[i] = null;
>                     CloseAppender(oldAppender, reason);
> ```

idem, is this change necessary?  Or an enhancement? 

---

*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 339 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aJefrcODAZ-bLCSei:-K_aJefrcODAZ-bLCSej:b-w09h6x) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L339)):*
> ```Smalltalk
> #endif
>             {
>                 if (expireTime != DateTime.MinValue)
> ```

nice improvement :)

---

*[tests/NLog.UnitTests/Targets/FileTargetTests.cs, line 3300 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aKSu6CANp0CnzCpu2:-K_aKSu72pa-Yo0yLt6J:be5bvu2) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/tests/NLog.UnitTests/Targets/FileTargetTests.cs#L3300)):*
> ```Smalltalk
>                 logger.Info("log to force archiving");
> 
>                 LogManager.Configuration = null;    // Flush
> ```

why are we doing this if we like to flush? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1878)*

**Comment by 304NotModified** [comment]
Reviewed 2 of 4 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1878)*

**Comment by 304NotModified** [comment]
Thanks, reviewed it!

I'm a bit cautious with the changes in the fileAppenderCache, as I don't have worked a lot with it

**Comment by snakefoot** [comment]
> I'm a bit cautious with the changes in the fileAppenderCache, as I don't have worked a lot with it

I have just noticed the bug-reports about using archiving together with keepFileOpen, and gets into the locked-file-handle problems. Not high priority for me, so can easily wait for NLog 5 (or 6)

**Comment by 304NotModified** [comment]
> Not high priority for me, so can easily wait for NLog 5 (or 6)

Think that's not necessary, I'm just asking more questions in the review.  ;)

**Comment by snakefoot** [comment]
*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 122 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aHvgpvyCdxykZdvAU:-K_aTqlD7AwB_g1FSF9O:b-886gsx) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L122)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

why not .Equals(..., .OrdinalIgnoreCase)? 
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1878)*

**Comment by snakefoot** [comment]
*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 124 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aI3CZmBbCxc6itQaN:-K_aTtqmwvbK9mWC3F5Q:b-886gsx) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L124)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

Duplicate code (4 lines) 
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1878)*

**Comment by snakefoot** [comment]
*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 138 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aI9ZJdv9p9I2LBLog:-K_aTvLBBaJ43vM37VaJ:b-886gsx) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L138)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

partly duplicate code.
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1878)*

**Comment by snakefoot** [comment]
*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 160 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aINdbMT6is4-yF7VW:-K_aTx_fFCNT8rcxq4gd:bp7tyip) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L160)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

no need to fall back to `externalFileArchivingWatcher.StopWatching();` ?
</blockquote></details>

Not in case there are open file appenders. Not sure if these properties are often used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1878)*

**Comment by snakefoot** [comment]
*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 176 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aI_N4l95BsHZAfEWE:-K_aU9ea-C1YFScOLCpN:b-6vacec) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L176)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

why the order change? Is this to prevent to preform the cleanup twice? Don't we need a lock in that case?
</blockquote></details>

Have changed the logic for stopping the timer, when closing the last file appender

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1878)*

**Comment by snakefoot** [comment]
*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 269 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aJ6aS-bIfXWO8Rxvo:-K_aULXAuCtR2g0XFio_:b-6vacec) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L269)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

is this change necessary?  Or an enhancement? 
</blockquote></details>

Have changed the logic for stopping the timer, when closing the last file appender

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1878)*

**Comment by snakefoot** [comment]
*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 293 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aJI2O38TBn-XUXgiF:-K_aUNF-fi2cS4AaM4Wx:b-ae4zyz) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L293)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

two watches is by design?
</blockquote></details>

Have added comments. Not sure why we monitor the archive folder instead of just the active file-appenders. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1878)*

**Comment by snakefoot** [comment]
*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 319 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aJS9O16k0bM71GUyO:-K_aU_GpV_4y2k6DIVzr:b-6vacec) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L319)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

idem, is this change necessary?  Or an enhancement? 
</blockquote></details>

Have changed the logic for stopping the timer, when closing the last file appender

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1878)*

**Comment by snakefoot** [comment]
*[tests/NLog.UnitTests/Targets/FileTargetTests.cs, line 3300 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aKSu6CANp0CnzCpu2:-K_aUbo5gHoBM5uIkRWb:b4l7rnx) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/tests/NLog.UnitTests/Targets/FileTargetTests.cs#L3300)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

why are we doing this if we like to flush? 
</blockquote></details>

Because it also means we are completely done with logging, so target-timers and target-file-handles should be closed (Allowing cleanup).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1878)*

**Comment by snakefoot** [comment]
*[src/NLog/Internal/MultiFileWatcher.cs, line 179 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aHH3EHgCuGaLPJCLD:-K_aUviEGyyZCHs2FmKv:b-886gsx) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/src/NLog/Internal/MultiFileWatcher.cs#L179)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

I think .Warn is better? (twice)
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1878)*

**Comment by snakefoot** [comment]
*[src/NLog/Internal/FileAppenders/FileAppenderCache.cs, line 339 at r2](https://reviewable.io:443/reviews/nlog/nlog/1878#-K_aJefrcODAZ-bLCSei:-K_aUzACYNDW1Wz3UnSh:b32vhw) ([raw file](https://github.com/nlog/nlog/blob/a7295af4f136077c3eff7ac9445466969f396c60/src/NLog/Internal/FileAppenders/FileAppenderCache.cs#L339)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

nice improvement :)
</blockquote></details>

:)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1878)*

**Comment by snakefoot** [comment]
Reviewed 1 of 2 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1878)*

**Comment by 304NotModified** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1878)*

**Comment by 304NotModified** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1878#-:-KaEd37eqkeVrPb8SHly:bb6ywmx)*

**Comment by 304NotModified** [comment]
\0/ 3 closed issues \0/ \0/

**Pull request merged**
