### PR TITLE
Fix global editorconfig to create correct license header for new files (WIP)

### PR DESCRIPTION
**Pull request by snakefoot**
Looks like semi-colon is always recognized as comment, and can never be escaped. Also missing some newlines, and some missing spaces.

### CODE REVIEW

**Comment by snakefoot** [comment]
Close and reopen to rebuild

**Comment by 304NotModified** [comment]
I don't get this, this worked before when I created the initial config?

**Comment by 304NotModified** [comment]
This one worked? https://github.com/NLog/NLog/pull/3972 What am I missing?

**Comment by snakefoot** [comment]
No idea maybe because I'm using VS2019 16.8 preview


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


This one worked? #3972<https://github.com/NLog/NLog/pull/3972> What am I missing?

**Comment by 304NotModified** [comment]
I will test with that one otherwise, Currently on Version 16.7.4

**Comment by 304NotModified** [comment]
Tested this with Version 16.8.3:

image

**Comment by 304NotModified** [comment]
--> https://github.com/MicrosoftDocs/visualstudio-docs/issues/6386

**Comment by 304NotModified** [comment]
--> https://github.com/dotnet/roslyn/issues/44596

No fix expected for now

**Comment by 304NotModified** [comment]
We could two things:

1. Or change all headers (and .editorconfig) so we use comma's
2. Or close this one and reopen after fix from MS.

**Comment by snakefoot** [comment]
> Change all headers (and .editorconfig) so we use comma's

I like this one.

**Comment by 304NotModified** [comment]
Ok I will do that :)

**Comment by 304NotModified** [comment]
(but only for dev?)

**Comment by snakefoot** [comment]
Yes only for dev-branch is fine.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


(but only for dev?)

**Comment by 304NotModified** [comment]
I was thinking about this, of only the dev branch then you need always a (manual) change of you add a file in master. Maybe better to wait for NLog 5 when dev is merged into master?

Or just both is still an option, but will do a master to dev before it (of needed)

**Comment by snakefoot** [comment]
No idea what is the best. Just annnoying that when creating new files, then the header is wrong by default :)

**Comment by 304NotModified** [comment]
Closed for now until bug is fixed in VS

**Comment by snakefoot** [comment]
@304NotModified Then maybe delete the `file_header_template` from `.editorconfig` until the bug has been fixed? (Since it is currently broken)

**Comment by 304NotModified** [comment]
That's a good idea :)

**Pull request closed without merging**
