### PR TITLE
Move InternalLogger settings reading at initialization to a SetupBuilder extension

### PR DESCRIPTION
**Pull request by noamyogev84**
Trying to help with #4032 🌷 
@snakefoot please review and let me know if i'm anywhere near...
In case it's a good direction, i'll work on some tests if needed.
:beers:

### CODE REVIEW

**Comment by snakefoot** [comment]
Thank you for the pull-request. It is close to what I was thinking. But I would like some changes:

Instead of having one `SetupFromSettings` then it should be two different methods:

- SetupFromAppSettings (Not available for NetCore)
- SetupFromEnvironmentVariables

I can understand the beauty of having the abstraction `ISettingsReader`, but the lookup code is like this:

```c#
InternalLogger.LogToConsole = settingsReader.GetSetting("nlog.internalLogToConsole", "NLOG_INTERNAL_LOG_TO_CONSOLE", false);
```

The 2 setting-names makes the abstraction very leaky. I prefer that ISettingsReader and SettingsReader are removed, and the setting lookup are just simple like this:

**SetupFromEnvironmentVariables():**
```c#
// Injecting the original value `InternalLogger.LogToConsole` as default-value
InternalLogger.LogToConsole = LookupEnvironmentVariable("NLOG_INTERNAL_LOG_TO_CONSOLE", InternalLogger.LogToConsole);
```

**SetupFromAppSettings():** (`#if !NETSTANDARD`)
```c#
// Injecting the original value `InternalLogger.LogToConsole` as default-value
InternalLogger.LogToConsole = LookupAppSettings("nlog.internalLogToConsole", InternalLogger.LogToConsole);
```

**Comment by snakefoot** [comment]
To handle the type conversion, then maybe something like this might work:

```c#
T LookupEnvironmentVariable<T>(string environmentVariabel, T defaultValue)
{
      try
      {
         string stringValue = LookupStringValue(environmentVariabel)?.Trim();
         if (string.IsNullOrEmpty(stringValue))
             return defaultValue;

         var typeConverter = System.ComponentModel.TypeDescriptor.GetConverter(typeof(T));
         var environmentValue = (T)typeConverter.ConvertFrom(stringValue);
         return environmentValue;
      }
      catch
      {
         return defaultValue;
      }
}
```

**Comment by noamyogev84** [comment]
OK. I will take a look.
You want all this code to be implemented in the extension method?

**Comment by snakefoot** [comment]
> You want all this code to be implemented in the extension method?

You are welcome put the two extension methods in their own individual static-class-file if you feel they grow wildly.

The NLog project is also very keen on putting reusable-methods into NLog.Internal-namespace. Ex. `GetSafeEnvironmentVariable`

**Comment by snakefoot** [comment]
@noamyogev84 Should the pull-request be closed, or is it just a minor delay before completion?

**Comment by noamyogev84** [comment]
i misht return to that soon :)

**Comment by snakefoot** [comment]
Superseeded by #4184

**Pull request closed without merging**
