### PR TITLE
ScopeContext - Merged with NDC + MDC

### PR DESCRIPTION
**Pull request by snakefoot**
ScopeContext now merges MDLC + MDC and NDLC + NDC into a single context.

It will have the side-effect that NET35 + NET45 will start using CallContext for MDC (Can give side-effects for applications using deprecated remoting-methods, but the new ScopeContext gives less serialization issues than NDLC). But NET46 + NETCORE will use AsyncLocal that will not give side-effects together with remoting-methods.

Very happy that all unit-tests stayed green without being changed. Afterwards changed unit-tests that gave warnings about using deprecated methods (Without being directly related to testing MDC + NDC)

### CODE REVIEW

**Comment by snakefoot** [comment]
Closing and reopening to trigger Travis-rebuild.

**Comment by snakefoot** [comment]
Closing and reopening to trigger Travis-rebuild.

**Comment by 304NotModified** [comment]
restarted both failing builds

**Comment by snakefoot** [comment]
Updated wiki-pages:
- https://github.com/NLog/NLog/wiki/ScopeNested-Layout-Renderer
- https://github.com/NLog/NLog/wiki/ScopeProperty-Layout-Renderer

**Pull request merged**
