### PR TITLE
Layout class refactoring

### PR DESCRIPTION
**Pull request by ie-zero**
The refactorings of Layout class supplied in small commits in order to be easy to review the changes on each one of them. 

----
Extract IsThreadAgnostic() method
* Improve the code readability by extracting IsThreadAgnostic() method.

Refactor internal property ThreadAgnostic 
* Remove obsolete threadAgnostic private property.
* Rename the IsThreadAgnostic internal property to ThreadAgnostic to align with the expected naming for properties.

Reduce duplicate code in Layout class
* Extract method GetRenderBufferLength() to reduce code replication

Change code formatting
* Organise using statements
* Remove redundant this. qualifier from methods and properties

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/2020)

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks for the changes. Unfortunately NLog is currently not in a state for doing big refactors due to #1160 

So doubting to merge this one, as it will give probably many conflicts :(

> Remove redundant this. qualifier from methods and properties

In almost every class there is the `this.`. I also don't like it ;) But I like to replace it with the underscore style (for private fields), **after** the release of NLog 5.

**Comment by ie-zero** [comment]
Would it help @304NotModified if submit the same PR against the coreCLR branch?

**Comment by 304NotModified** [comment]
Yes certainty!

**Comment by ie-zero** [comment]
PR resubmitted against the coreCLR branch.

**Pull request closed without merging**
