### PR TITLE
Merge 4.7 rc1 into dev

### PR DESCRIPTION
**Pull request by 304NotModified**

### CODE REVIEW

**Comment by 304NotModified** [comment]
hmmm looks like these tests are broken. Dunno why:

1. IncludeAllJsonPropertiesMutableNestedXml
1. SetupExtensionsRegisterConditionMethodTest

**Comment by snakefoot** [comment]
Think `IncludeAllJsonPropertiesMutableNestedXml` fails because MaxRecursionLimit has the new default value = 1 in NLog 5 (Starts printing the properties of the StringBuilder).

Guess the test needs to have MaxRecursionLimit explicitly set to 0.

**Comment by 304NotModified** [comment]
Thanks @snakefoot. Good thinking :)

**Comment by 304NotModified** [comment]
merge commit!

**Pull request merged**
