### PR TITLE
Fix monodevelop build.

### LINKED ISSUE #648: Support Mono in NLog
Current Mono build is broken. The code won't build. 

Reported at #635

for Nlog 4.0 would be nice , but this has a low priority ("could have"). PR's are accepted.

### PR DESCRIPTION
**Pull request by txdv**
We move the .NET target version to 4.5 and add the references
to the xunit packages.

Open the sln file with monodevelop first so it can restore the
nuget packages before calling make.

fix #648

@akoeplinger do you have maybe some further suggestions?
This is just a quick fix to get what we can compile NLog with monodevelop.
I dropped 3.5, because that is under mono considered to be ancient and mostly never used.

### CODE REVIEW

**Comment by txdv** [comment]
Tell me please if you want me the two commits to squash.

First one just fixes the monodevelop build issue, the second one fixes the README entry for the mono issue.

**Comment by akoeplinger** [comment]
> do you have maybe some further suggestions?

The changes look good to me, though I wonder why a separate MonoDevelop solution is needed (we should try to avoid special casing Mono whenever possible).

**Comment by txdv** [comment]
I will look into this.

**Comment by 304NotModified** [comment]
Thanks l! Looks good :+1: :smiley:

**Comment by txdv** [comment]
Error: /home/bentkus/Projects/mono/NLog/src/NLog/NLog.netfx45.csproj: /home/bentkus/Projects/mono/NLog/src/NLog/NLog.netfx45.csproj could not import "$(SolutionDir)\.nuget\nuget.targets" (NLog.netfx45)

I have monodevelop 5.7 though, since I am using 12.04 and there is no newer release, I had some weird diffs when I tried clone the repo on 14.04 64bit, like line endings everywhere changed. I will keep investigating and turn back as soon as possible, because it looks like that problem has been solved in the newer monodevelop and when I pinged @directhex he said that he would gonna update the monodevelop for the 12.04 ubuntu.

Also, why is there are there mono2 solutions? What are they for?

**Comment by txdv** [comment]
Ok, the error is related to NuGet.targets being named nuget.targets in some project files, so the standard projects work fine (except the tests in those project files have an exclamation mark in monodevelop).

However, git is again changing the CRLF to LF

```
warning: CRLF will be replaced by LF in src/NLog/NLog.mono2.csproj.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in src/NLog/NLog.netfx40.csproj.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in src/NLog/NLog.netfx45.csproj.
The file will have its original line endings in your working directory.
diff --git a/src/NLog/NLog.mono2.csproj b/src/NLog/NLog.mono2.csproj
index a974558..22f43b4 100644
--- a/src/NLog/NLog.mono2.csproj
+++ b/src/NLog/NLog.mono2.csproj
@@ -1,415 +1,415 @@
-<U+FEFF><?xml version="1.0" encoding="utf-8"?>
-<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
-  <PropertyGroup>
-    <BaseOutputDirectory Condition=" '$(BaseOutputDirectory)' == '' ">$(MSBuildProjectDirectory)\..\..\build\</BaseOutputDirectory>
-    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
-    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
-    <ProductVersion>9.0.30729</ProductVersion>
-    <SchemaVersion>2.0</SchemaVersion>
-    <ProjectGuid>{E7AB20BF-6920-442A-B876-CC05BC5CEC79}</ProjectGuid>
-    <OutputType>Library</OutputType>
-    <AppDesignerFolder>Properties</AppDesignerFolder>
```

I don't know how to prevent git from doing this.

**Comment by txdv** [comment]
Really annoying, I'm going to investigate further tommorow.

**Comment by williamb1024** [comment]
Git is trying to do EOL normalization. One of the recent commits changed the .gitattributes and a number of the files need to be normalized.

**Comment by txdv** [comment]
@williamb1024 Yes, I realized that too, I did a

```bash
find . -not -type d -exec file "{}" ";" | grep CRLF
```

```
./examples/NLogWindowsPhoneApplication/Properties/WMAppManifest.xml: XML  document, UTF-8 Unicode (with BOM) text, with very long lines, with CRLF line terminators
./examples/NLogWindowsPhoneApplication/NLogWindowsPhoneApplication.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF, LF line terminators
./tests/NLog.UnitTests/LoggerTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/LayoutRenderers/EventContextTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/LayoutRenderers/Wrappers/ReplaceTests.cs: UTF-8 Unicode (with BOM) C++ program text, with CRLF, LF line terminators
./tests/NLog.UnitTests/LayoutRenderers/Log4JXmlTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/LayoutRenderers/SpecialFolderTests.cs: UTF-8 Unicode (with BOM) C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/LayoutRenderers/EventPropertiesTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/LayoutRenderers/BaseDirTests.cs: ASCII C++ program text, with CRLF, LF line terminators
./tests/NLog.UnitTests/LayoutRenderers/EnvironmentTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/LayoutRenderers/DateTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/NLog.UnitTests.netfx40.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./tests/NLog.UnitTests/GetLoggerTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/ConfigFileLocatorTests.cs: UTF-8 Unicode (with BOM) C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/LogManagerTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/LogFactoryTests.cs: UTF-8 Unicode (with BOM) C++ program text, with CRLF, LF line terminators
./tests/NLog.UnitTests/NLogTraceListenerTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/NLog.UnitTests.netfx45.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./tests/NLog.UnitTests/Targets/MailTargetTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/Targets/ConsoleTargetTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/Targets/Wrappers/FallbackGroupTargetTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/Targets/Wrappers/BufferingTargetWrapperTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/Targets/Wrappers/RetryingTargetWrapperTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/Targets/Wrappers/PostFilteringTargetWrapperTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/Targets/LogReceiverWebServiceTargetTests.cs: ASCII C++ program text, with CRLF, LF line terminators
./tests/NLog.UnitTests/Targets/FileTargetTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/Targets/NetworkTargetTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/Targets/MessageQueueTargetTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/Targets/TargetTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/NLog.UnitTests.sl5.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./tests/NLog.UnitTests/Config/TimeConfigurationTests.cs: UTF-8 Unicode (with BOM) C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/Internal/NetworkSenders/TcpNetworkSenderTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/Internal/NetworkSenders/UdpNetworkSenderTests.cs: UTF-8 Unicode (with BOM) C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/TimeSourceTests.cs: UTF-8 Unicode (with BOM) C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/NLog.UnitTests.netfx35.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./tests/NLog.UnitTests/Layouts/SimpleLayoutParserTests.cs: ASCII C++ program text, with CRLF, LF line terminators
./tests/NLog.UnitTests/Layouts/CsvLayoutTests.cs: ASCII C++ program text, with CRLF line terminators
./tests/NLog.UnitTests/NLog.UnitTests.mono2.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./tests/NLog.UnitTests/packages.config: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./tests/SampleExtensions/SampleExtensions.netfx45.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./tests/SampleExtensions/SampleExtensions.sl5.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./tests/SampleExtensions/SampleExtensions.netfx35.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./tests/SilverlightApp/SilverlightApp.sl5.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./src/NLog.monodevelop.sln: UTF-8 Unicode (with BOM) text, with CRLF line terminators
./src/NLog.netfx45.sln: ASCII text, with CRLF line terminators
./src/NLog.Extended/NLog.Extended.netfx45.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./src/NLog.Extended/Targets/MessageQueueTarget.cs: HTML document, ASCII text, with CRLF, LF line terminators
./src/.nuget/NuGet.Config: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./src/InstallNLogConfig/InstallNLogConfig.netfx45.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./src/NuGet/NLog.Snippets/tools/install.ps1: ASCII text, with CRLF line terminators
./src/NuGet/NLog.Snippets/content/empty.txt: ASCII text, with CRLF line terminators
./src/NLog.netfx35.sln: ASCII text, with CRLF line terminators
./src/NLog.netfx40.sln: ASCII text, with CRLF line terminators
./src/NLog/Common/InternalLogger.cs: ASCII C++ program text, with CRLF, LF line terminators
./src/NLog/LayoutRenderers/EventPropertiesLayoutRenderer.cs: ASCII C++ program text, with CRLF, LF line terminators
./src/NLog/LayoutRenderers/BaseDirLayoutRenderer.cs: ASCII C++ program text, with CRLF, LF line terminators
./src/NLog/LayoutRenderers/Wrappers/ReplaceLayoutRendererWrapper.cs: ASCII C++ program text, with CRLF, LF line terminators
./src/NLog/LayoutRenderers/AssemblyVersionLayoutRenderer.cs: UTF-8 Unicode (with BOM) C++ program text, with CRLF, LF line terminators
./src/NLog/LayoutRenderers/EventContextLayoutRenderer.cs: ASCII C++ program text, with CRLF, LF line terminators
./src/NLog/LayoutRenderers/EnvironmentLayoutRenderer.cs: ASCII C++ program text, with CRLF, LF line terminators
./src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs: ASCII C++ program text, with CRLF line terminators
./src/NLog/LogLevel.cs: ASCII C++ program text, with CRLF, LF line terminators
./src/NLog/NLog.doc.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./src/NLog/NLog.netfx40.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./src/NLog/Time/FastLocalTimeSource.cs: UTF-8 Unicode (with BOM) C++ program text, with CRLF line terminators
./src/NLog/Time/TimeSourceAttribute.cs: UTF-8 Unicode (with BOM) C++ program text, with CRLF line terminators
./src/NLog/Time/TimeSource.cs: UTF-8 Unicode (with BOM) C++ program text, with CRLF line terminators
./src/NLog/Time/AccurateUtcTimeSource.cs: UTF-8 Unicode (with BOM) C++ program text, with CRLF line terminators
./src/NLog/Time/AccurateLocalTimeSource.cs: UTF-8 Unicode (with BOM) C++ program text, with CRLF line terminators
./src/NLog/Time/CachedTimeSource.cs: UTF-8 Unicode (with BOM) C++ program text, with CRLF line terminators
./src/NLog/Time/FastUtcTimeSource.cs: UTF-8 Unicode (with BOM) C++ program text, with CRLF line terminators
./src/NLog/Targets/TraceTarget.cs: HTML document, ASCII text, with CRLF, LF line terminators
./src/NLog/Targets/MailTarget.cs: HTML document, ASCII text, with CRLF line terminators
./src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs: HTML document, ASCII text, with CRLF line terminators
./src/NLog/Targets/Wrappers/AsyncRequestQueue-T.cs: UTF-8 Unicode (with BOM) C++ program text, with CRLF line terminators
./src/NLog/Targets/Target.cs: ASCII C++ program text, with CRLF, LF line terminators
./src/NLog/Targets/NetworkTarget.cs: HTML document, ASCII text, with CRLF line terminators
./src/NLog/Targets/EventLogTarget.cs: HTML document, ASCII text, with CRLF line terminators
./src/NLog/Config/LoggingConfiguration.cs: ASCII C++ program text, with CRLF line terminators
./src/NLog/Config/XmlLoggingConfiguration.cs: ASCII C++ program text, with CRLF line terminators
./src/NLog/Config/ConfigSectionHandler.cs: ASCII C++ program text, with CRLF, LF line terminators
./src/NLog/Internal/FileAppenders/RetryingMultiProcessFileAppender.cs: ASCII C++ program text, with CRLF, LF line terminators
./src/NLog/Internal/FileAppenders/CountingSingleProcessFileAppender.cs: ASCII C++ program text, with CRLF, LF line terminators
./src/NLog/Internal/FileAppenders/SingleProcessFileAppender.cs: ASCII C++ program text, with CRLF line terminators
./src/NLog/Internal/NetworkSenders/TcpNetworkSender.cs: ASCII C++ program text, with CRLF line terminators
./src/NLog/Internal/NetworkSenders/UdpNetworkSender.cs: ASCII C++ program text, with CRLF, LF line terminators
./src/NLog/Internal/NetworkSenders/INetworkSenderFactory.cs: ASCII C++ program text, with CRLF, LF line terminators
./src/NLog/Internal/NetworkSenders/NetworkSenderFactory.cs: ASCII C++ program text, with CRLF, LF line terminators
./src/NLog/Internal/NetworkSenders/SocketProxy.cs: ASCII C++ program text, with CRLF, LF line terminators
./src/NLog/Internal/Fakeables/AppDomainWrapper.cs: ASCII C++ program text, with CRLF line terminators
./src/NLog/Internal/Fakeables/IAppDomain.cs: ASCII C++ program text, with CRLF line terminators
./src/NLog/Internal/NativeMethods.cs: ASCII C++ program text, with CRLF, LF line terminators
./src/NLog/LogFactory.cs: ASCII C++ program text, with CRLF line terminators
./src/NLog/NLog.netfx45.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./src/NLog/NLog.mono2.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./src/NLog/NLog.sl5.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./src/NLog/NLog.netfx35.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./src/NLog/Layouts/LayoutParser.cs: ASCII C++ program text, with CRLF, LF line terminators
./src/NLog/packages.config: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./src/NLog/LogEventInfo.cs: ASCII C++ program text, with CRLF line terminators
./tools/MakeNLogXSD/MakeNLogXSD.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
./tools/MergeApiXml/MergeApiXml.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF, LF line terminators
./tools/DumpApiXml/DocFileBuilder.cs: UTF-8 Unicode (with BOM) C++ program text, with CRLF, LF line terminators
./tools/DumpApiXml/DumpApiXml.csproj: XML  document, UTF-8 Unicode (with BOM) text, with CRLF line terminators
```

A lot of files with CRLF or even mixed files.

git reads .gitattributes and immediately changes these files.

**Comment by txdv** [comment]
I was able to create some commits in https://github.com/txdv/NLog/commits/attributes only by deleting .gitattributes first. Because the moment I touch one of those files it creates changes all the line endings in the files mentioned abouve.

I renamed nuget.targets in the project files to NuGet.targets and the second commit fixed a cref and an unused field usage which didn't let me compile, since warnings = errors.

I don't know how to approach this problem. Should I just change all line endings in the csproj files that I touched?

**Comment by 304NotModified** [comment]
EOL should be fixed (see #752)

**Comment by 304NotModified** [comment]
Is this still WIP?

**Comment by txdv** [comment]
Yes it is, i will rebase it if all end of lines have been fixed. I will report when I get to it!

**Comment by 304NotModified** [comment]
If someone has still the line endings issues, this solved it for me:

https://help.github.com/articles/dealing-with-line-endings/#refreshing-a-repository-after-changing-line-endings

**Comment by 304NotModified** [comment]
@txdv For who is the question?

**Comment by txdv** [comment]
The one who wrote that code?

The compiler complained that the variable is not used, I removed it to fix it.

**Comment by 304NotModified** [comment]
It's fine to remove unused vars, but be aware, due to a lot of #if pragma's (for all the different platforms) the compiler gives sometimes false positives.

So a string search is a good idea.

**Comment by 304NotModified** [comment]
Is there still a open question? It's not clear to me.

**Comment by txdv** [comment]
Good explanation, I'll just leave that variable then there.

**Comment by txdv** [comment]
Another question I have is what the difference between mono2 and monodevelop is.

**Comment by txdv** [comment]
It seems to me that the main difference is that monodevelop solution has WCF_SUPPORTED on and mono2 not...

**Comment by txdv** [comment]
Now, that I reversed the removal of the variable 'pattern' I remember why I removed it in the first place:

Now when I compile with xbuild the NLog.netfx45.sln I get:

```csharp
Errors:

/home/bentkus/Projects/mono/NLog/src/NLog.netfx45.sln (default targets) ->
(Build target) ->
/home/bentkus/Projects/mono/NLog/src/NLog/NLog.netfx45.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

	Targets/FileTarget.cs(1973,37): error CS0414: Warning as Error: The private field `NLog.Targets.FileTarget.FileNameTemplate.pattern' is assigned but its value is never used

	 3 Warning(s)
	 1 Error(s)

Time Elapsed 00:00:02.5564080
```

I wonder why this doesn't happen under windows, since 4.5 seems to be a popular target framework. Did you have any trouble with it?

**Comment by 304NotModified** [comment]
@Xharze 
Can you answer: 
>Another question I have is: what is the difference between mono2 and monodevelop?

Because I dunno. 

About the unused var. Please remove it if it's not used (and if you not sure), just build every solution. If it's used in a target, please use a pragma

**Comment by Xharze** [comment]
Actually I don't know what the difference between mono2 and monodevelop is, they were present when I took over the project. Which know do you recommend we keep? I think we should delete the other

**Comment by txdv** [comment]
the difference is that one of them has the WCF definition on, the other doesn't. My bet is that someone created a xamarin project solution for windows, I don't think we need it, since the net45 solution builds fine, I will start up windows, investigate and report ASAP.

**Comment by 304NotModified** [comment]
@txdv can you elaborate on the Xamarin point? We would like to support Xamarin, but the PR (https://github.com/NLog/NLog/pull/389) is never merged :(

**Comment by txdv** [comment]
Well, I was talking about using xamarin studio to compile it for windows, not for android and all the other platforms.

**Comment by 304NotModified** [comment]
OK thanks for the feedback.

**Comment by 304NotModified** [comment]
Is this still WIP? It would be nice if we could include this in the 4.1 release

**Comment by txdv** [comment]
Well, I'm waiting for some input. What I have currently makes the build process already better, so merging it will make it better.

However I would suggest to remove one of the builds, because we have mono and monodevelop and I don't think we need both.

**Comment by 304NotModified** [comment]
Yes one can be removed. I would keep the WCF version.

**Comment by 304NotModified** [comment]
Removal is nice to have. So merge it now.

**Comment by 304NotModified** [comment]
@txdv with the merge of this PR, it should be possible to build the project with xbuild?

- With NLog.monodevelop.sln: error : Illegal characters in path.
- With NLog.mono2.sln I get the error?: "Registry function"

Do I missing something? 

XBuild Engine Version 12.0
Mono, Version 4.0.2.0
Windows 8.1 X64

**Comment by txdv** [comment]
I actually built using the makefile for monodevelop, but now I see the error messages when using xbuild on the solution file:

```
bentkus@gracious:~/Projects/mono/NLog/src$ xbuild NLog.monodevelop.sln 
XBuild Engine Version 12.0
Mono, Version 4.0.2.0
Copyright (C) 2005-2013 Various Mono authors

Build started 7/21/2015 11:24:28 AM.
__________________________________________________
NLog.monodevelop.sln: error : Input string was not in a correct format.

Unhandled Exception:
System.FormatException: Input string was not in a correct format.
  at System.String.ParseFormatSpecifier (System.String str, System.Int32& ptr, System.Int32& n, System.Int32& width, System.Boolean& left_align, System.String& format) [0x00000] in <filename unknown>:0 
  at System.String.FormatHelper (System.Text.StringBuilder result, IFormatProvider provider, System.String format, System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.String.Format (IFormatProvider provider, System.String format, System.Object[] args) [0x00000] in <filename unknown>:0 
  at System.String.Format (System.String format, System.Object[] args) [0x00000] in <filename unknown>:0 
  at Microsoft.Build.BuildEngine.Project.LogWarning (System.String filename, System.String message, System.Object[] messageArgs) [0x00000] in <filename unknown>:0 
  at Microsoft.Build.BuildEngine.Project+<Load>c__AnonStorey3.<>m__0 (Int32 errorNumber, System.String message) [0x00000] in <filename unknown>:0 
  at Mono.XBuild.CommandLine.SolutionParser.ParseSolution (System.String file, Microsoft.Build.BuildEngine.Project p, Mono.XBuild.CommandLine.RaiseWarningHandler RaiseWarning) [0x00000] in <filename unknown>:0 
  at Microsoft.Build.BuildEngine.Project.Load (System.String projectFileName, ProjectLoadSettings settings) [0x00000] in <filename unknown>:0 
  at Microsoft.Build.BuildEngine.Project.Load (System.String projectFileName) [0x00000] in <filename unknown>:0 
  at Microsoft.Build.BuildEngine.Engine.BuildProjectFileInternal (System.String projectFile, System.String[] targetNames, Microsoft.Build.BuildEngine.BuildPropertyGroup globalProperties, IDictionary targetOutputs, BuildSettings buildFlags, System.String toolsVersion) [0x00000] in <filename unknown>:0 
  at Microsoft.Build.BuildEngine.Engine.BuildProjectFile (System.String projectFile, System.String[] targetNames, Microsoft.Build.BuildEngine.BuildPropertyGroup globalProperties, IDictionary targetOutputs, BuildSettings buildFlags, System.String toolsVersion) [0x00000] in <filename unknown>:0 
Build FAILED.
Errors:

NLog.monodevelop.sln: error : Input string was not in a correct format.

	 0 Warning(s)
	 1 Error(s)

Time Elapsed 00:00:00.1560450
```

however if I open the solution file with monodevelop and compile it then everything is ok ¯\_(ツ)_/¯

**Comment by 304NotModified** [comment]
I think that our teamcity build server can only compile mono with xbuild. If the build server can compile this solution,  we keep the mono build working . 

Any ideas how too fix this?

**Comment by 304NotModified** [comment]
@txdv 

If have found out that:

- the solution build with xbuild if the unit test project is excluded (otherwise the error: "Input string was not in a correct format.")
- building the csproj for the unit test also fails: "The type or namespace name `Xunit' could not be found. Are you missing an assembly reference?".  

Any idea's why this isn't working? See https://travis-ci.org/304NotModified/NLog/builds/

We should get this working, otherwise I think we should drop mono as it's impossible to validate if it's working...

**Comment by 304NotModified** [comment]
moved to #837

**Pull request merged**
