### PR TITLE
[WIP] Configuration Serialization

### PR DESCRIPTION
**Pull request by Pretasoc**
This pr provides a set of extension methods to the `LoggingConfiguration` class. Theese overload can create an xml configuration from a `LoggingConfiguration` as asked for in #57.

Todos:
- [ ] Write Unit Tests
- [ ] Add filter support
- [ ] Add Wrapper target support
- [ ] Add extension support
- [ ] Add Configuration Settings support
- [ ] Check supported platforms

### CODE REVIEW

**Comment by Pretasoc** [comment]
I am sorry for including e8e80d8 in this pr. It slipped accidental in, when i was cleaning up the commits. Shall i create a new pr and cherry pick only the commits intended to be here?

**Comment by 304NotModified** [comment]
> I am sorry for including e8e80d8 in this pr. It slipped accidental in, when i was cleaning up my commit history. Shall i create a new pr and cherry pick only the commits intended to be here?

I prefer changing the history and force push. 


e.g. git rebase head~2 -i

**Comment by 304NotModified** [comment]
> I prefer changing the history and force push.
> 
> e.g. git rebase head~2 -i. Remove commit line. Close file. git push -f

need some help on this?

**Comment by 304NotModified** [comment]
please create a new PR if you have time, thanks!

**Pull request closed without merging**
