### PR TITLE
Issue 730: Correct detection of an invalid file handle returned from …

### PR DESCRIPTION
**Pull request by nernst**
…Win32 CreateFile API to be compatible with 32 & 64 bit systems.

SafeFileHandle was already being used to manage the lifetime of the created file. It also has a IsInvalid property that handles detection of an invalid handle via an IntPtr for both 32 & 64-bit systems.

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks for the PR. 

We are doubting to include this in 4.0 (release, today). I dunno the possible impact on this issue.

**Comment by 304NotModified** [comment]
Related #730

**Comment by 304NotModified** [comment]
Again thanks for this PR, but it seems that #744 is a safer version (regarding leaks) of this fix.

**Comment by nernst** [comment]
No problem at all. Just happy it's being resolved. Thanks, everyone!

**Pull request closed without merging**
