### PR TITLE
Added ${environment-user}

### LINKED ISSUE #3381: Implement Environment.UserName layoutrenderer
Right now one can use these:

- [${windows-identity}](https://github.com/NLog/NLog/wiki/Windows-Identity-Layout-Renderer)
- [${environment:variable=UserName}](https://github.com/NLog/NLog/wiki/Environment-layout-renderer)

Both are extremely slow, and the second one doesn't support impersonations. But there are actually much faster calls:

- Environment.UserName
- Environment.UserDomainName

And these should support impersonation, and should also be available of NetCore:

- On Windows the UserName property wraps a call to the Windows GetUserName function. The domain account credentials for a user are formatted as the user's domain name, the '\' character, and user name. Use the UserDomainName property to obtain the user's domain name and the UserName property to obtain the user name.

- On Unix platforms the UserName property wraps a call to the getpwuid_r function.

- If an ASP.NET application runs in a development environment, the UserName property returns the name of the current user. In a published ASP.NET application, this property returns the name of the application pool account (such as Default AppPool).

See the output here:

https://richhewlett.com/2011/02/15/getting-a-users-username-in-asp-net/

### PR DESCRIPTION
**Pull request by snakefoot**
Resolves #3381

### CODE REVIEW

**Comment by 304NotModified** [comment]
This could be also on 4.6.4? Small chance on conflicts :)

**Comment by snakefoot** [comment]
@304NotModified Changed base to `master`

**Comment by 304NotModified** [comment]
Could you please help me with the docs? Thanks!

**Comment by snakefoot** [comment]
> Could you please help me with the docs? Thanks!

Created https://github.com/NLog/NLog/wiki/Environment-User-Layout-Renderer and made a link from https://github.com/NLog/NLog/wiki/Windows-Identity-Layout-Renderer

**Comment by 304NotModified** [comment]
thanks. I've added https://github.com/NLog/NLog.github.io/pull/116

**Pull request merged**
