### PR TITLE
Support for aliases for LayoutRenderer, targets, conditions etc. + Added some aliases

### PR DESCRIPTION
**Pull request by 304NotModified**
fixes https://github.com/NLog/NLog/issues/1948

todo

- [x] test multiple aliases
- [x] add test for target and layout

### CODE REVIEW

**Comment by snakefoot** [comment]
Think it is "Aliases" (Instead of Aliasses)

**Comment by 304NotModified** [comment]
Thanks!

**Comment by 304NotModified** [comment]
@snakefoot 

please your opinion, I was thinking, maybe this is better:

```c#
    [Target("Database")]
    [Target("DB")]
    public class DatabaseTarget : Target, IInstallable
```

now in this PR:

```c#
   [Target("Database", Aliases = "DB")]
```

**Comment by snakefoot** [comment]
Think I like this better:
```
    [Target("Database")]
    [Target("DB")]
```
But don't actually see a need for the "DB"-alias :)

But I can see this makes sense:
```
    [LayoutRenderer("event-properties")]
    [LayoutRenderer("event-property")]
```

**Comment by 304NotModified** [comment]
Yeah, it was primary for the layout renderers (also for ${document-uri})

**Comment by 304NotModified** [comment]
OK thanks for the feedback, done :)

**Comment by snakefoot** [comment]
@304NotModified Please update the Wiki with whatever details you find necessary (And when done then add tag with docs completed)

**Pull request merged**
