### PR TITLE
Internal Log - Include target type and target name in the log messages

### PR DESCRIPTION
**Pull request by snakefoot**
Minor improvement for NLog 4.6, while waiting for #2508

### CODE REVIEW

**Comment by 304NotModified** [comment]
Was thinking to add this more structural - e.g. adding a parameter to the internal logger methods, so it's consistent and clear which logs includes the target name

**Comment by snakefoot** [comment]
I'm guessing that #2508 will make it a lot easier to add a context-parameter.

**Comment by snakefoot** [comment]
@304NotModified Have resolved merge conflicts

**Comment by snakefoot** [comment]
@304NotModified  Maybe include for NLog 4.5.3, since InternalLogger is not breaking change, and we are out of hypercare.

**Comment by 304NotModified** [comment]
> @304NotModified Maybe include for NLog 4.5.3, since InternalLogger is not breaking change, and we are out of hypercare.

OK, i fixed the conflict and will merge it :)

**Comment by snakefoot** [comment]
> OK, i fixed the conflict and will merge it :)

But you reverted all my changes to FileTarget. Not a good merge

**Comment by 304NotModified** [comment]
> But you reverted all my changes to FileTarget. Not a good conflict fix

Oops, strange, will try again

**Comment by 304NotModified** [comment]
it should be OK now

Thanks for paying attention

**Comment by snakefoot** [comment]
This one looks weird:

`InternalLogger.Trace("FileTarget(Name={0}): "Calculating archive date. Last write time: {1}; Previous log event time: {2}", Name, lastWriteTimeSource, previousLogEventTimestamp);`

Think it should be:

`InternalLogger.Trace("FileTarget(Name={0}): Calculating archive date. Last write time: {1}; Previous log event time: {2}", Name, lastWriteTimeSource, previousLogEventTimestamp);`

**Comment by 304NotModified** [comment]
Thanks! Fixed :)

**Comment by 304NotModified** [comment]
Thanks! Fixed :)

**Pull request merged**
