### PR TITLE
Added LogMessageGenerator overloads for exceptions

### PR DESCRIPTION
**Pull request by c0shea**
Added support for deferred message generation on method overloads that also support Exceptions. See #2014

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks!

Unfortunately this isn't backwards-compatible. I think we should write a C# extensions. What do you think?

PS: changes ignoring whitespace changes: https://github.com/NLog/NLog/pull/2051/files?w=1

**Comment by c0shea** [comment]
Could you clarify what you mean by it being a breaking change so I know for next time?

I think extensions sound good, though. Do you mean something like [this](https://gist.github.com/c0shea/43e51c671681d6a1a3d85d9be0e93ea1)?

**Comment by 304NotModified** [comment]
Well extending a public interface is a breaking change as other uses who implement that interface have to implement those new methods. 

(Custom) Code written to NLog 4.x, should always work for every NLog 4.y (where `y>=x`) version (we are taking [semver](semver.org) very serious)

**Comment by 304NotModified** [comment]
A full list of what is breaking and what is not: https://github.com/dotnet/corefx/blob/c02d33b18398199f6acc17d375dab154e9a1df66/Documentation/coding-guidelines/breaking-change-rules.md

**Comment by c0shea** [comment]
Thanks for the link! That list makes a lot of sense. How should I back out these breaking changes in order to add the extension methods?

**Comment by 304NotModified** [comment]
Well you could add methods to the interface by using c# extensions. That won't break anything :)

**Comment by c0shea** [comment]
Thanks for the suggestion. I added a new class for the extension methods. Let me know what you think.

**Comment by 304NotModified** [comment]
Looks good, but the changes to `ILogger` needs to be reverted? 

What's the problem with the CLScompliant? We prefer CLScompliant code

**Comment by c0shea** [comment]
Whoops, I forgot to revert the changes to `ILogger` earlier. They're reverted now.

I couldn't have the extensions be CLS-compliant because the `ILogger` parameter isn't. Both `ILogger-V1.cs` and `ILoggerBase-V1.cs` are decorated with `[CLSCompliant(false)]` and caused the compile to fail.

**Comment by 304NotModified** [comment]
Thanks! Merged!  Will be in NLog 4.4.6

**Comment by 304NotModified** [comment]
FYI,

NLog 4.4.6 is live! 

https://www.nuget.org/packages/NLog/4.4.6

**Pull request merged**
