### PR TITLE
InternalLogger should only allocate params-array when needed

### PR DESCRIPTION
**Pull request by snakefoot**
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1702)

### CODE REVIEW

**Comment by 304NotModified** [comment]
Please also extend the unit tests.

**Comment by 304NotModified** [comment]
Thx in advance!

**Comment by 304NotModified** [comment]
Thanks!!

**Comment by 304NotModified** [comment]
This has been published, a lot of `@snakefoot` in 4.3.10!!! Thanks 💯 👍

**Comment by snakefoot** [comment]
Yes it has been some busy weeks ;). Learned a lot about the NLog-framework. Also excited about #1693 and #1694

**Pull request merged**
