### PR TITLE
Visual studio 2019 on AppVeyor

### PR DESCRIPTION
**Pull request by 304NotModified**
Needed for https://github.com/NLog/NLog/issues/4036

### CODE REVIEW

**Comment by 304NotModified** [comment]
Failfast should be enabled also on AppVeyor :)

**Comment by 304NotModified** [comment]
Fix first license url

**Comment by 304NotModified** [comment]
Azure pipeline is also vs2017

**Comment by 304NotModified** [comment]
working on the icon and lisence

**Comment by snakefoot** [comment]
Close / reopen to trigger rebuild

**Comment by snakefoot** [comment]
Guess #4036 is ready for up-for-graps again ?

**Comment by 304NotModified** [comment]
Yes. Maybe I should remove all comments so it won't scare others?

**Comment by snakefoot** [comment]
Sure no problem


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


Yes. Maybe I should remove all comments so it won't scare others?

**Pull request merged**
