### PR TITLE
LoggingConfiguration - Rollback static Reload-method

### PR DESCRIPTION
**Pull request by snakefoot**
Rollback of #3306 until a better solution comes around for https://github.com/NLog/NLog.Extensions.Logging/pull/283

### CODE REVIEW

**Comment by 304NotModified** [comment]
Hi, thanks for the PR,

but would it be more logical to have something like this:

```c#
LogManager.ReloadConfiguration();
// and/or
LogFactory.ReloadConfiguration();

```

I find the "active" a bit unusual

**Comment by snakefoot** [comment]
> I find the "active" a bit unusual

I need a method on LoggingConfiguraion (or method that takes LoggingConfiguration as parameter), that allows one to reload the config with respect to KeepVariablesOnReload.

But maybe I should just remove the new introduced method completely. Since I can probably implement this variable copy manually in NLog.Extension.Logging.

**Comment by snakefoot** [comment]
I need a method that I can call on an LoggingConfiguration object. That returns a reloaded config.


You are welcome to suggest a new name, but the method must be a member on LoggingConfiguration or take LoggingConfiguration as parameter


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


Hi, thanks for the PR,

but would it be more logical to have something like this:

LogManager.ReloadConfiguration();
// and/or
LogFactory.ReloadConfiguration();


I find the "active" a bit unusual

**Comment by 304NotModified** [comment]
> But maybe I should just remove the new introduced method completely. Since I can probably implement this variable copy manually in NLog.Extension.Logging.

I'm also doubting this addition makes things easier, so for now I think 

     NLog.LogManager.Configuration = NLog.LogManager.Configuration.Reload();

Is good enough

**Comment by snakefoot** [comment]
> Is good enough

But it will not support `KeepVariablesOnReload`

**Comment by 304NotModified** [comment]
> but would it be more logical to have something like this:
> 
> ```cs
> LogManager.ReloadConfiguration();
> // and/or
> LogFactory.ReloadConfiguration();
> ```

Can't be do `newConfig.CopyVariables(currentConfig.Variables);` in e.g. the LogManager to arrange this?

**Comment by snakefoot** [comment]
> in e.g. the LogManager to arrange this?

Sounds like something for NLog 5.0. Lets just rollback #3306

**Comment by 304NotModified** [comment]
I'm confused. You forced pushed different content? Won't it be more logical to close the old PR and create a new one?

**Comment by snakefoot** [comment]
Hate to waste a precious PulRequest-number :)

**Comment by 304NotModified** [comment]
This is still valid, isn't?

**Comment by snakefoot** [comment]
Yes it removes an unnecessary public method.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


This is still valid, isn't?

**Pull request merged**
