### PR TITLE
Remove old classic ASP stuff

### PR DESCRIPTION
**Pull request by 304NotModified**
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1647)

### CODE REVIEW

**Comment by UgurAldanmaz** [comment]
Good idea for old parts!

I have searched through codes and wikis and I have found somethings.

We also need to remove these files:
- [ASPTests.cs](https://github.com/NLog/NLog/blob/master/tests/NLog.UnitTests.Web/ASPTests.cs)
- Asp things in the [webtest](https://github.com/NLog/NLog/tree/master/tests/) folder

and wiki pages:
- [Platform-Support](https://github.com/NLog/NLog/wiki/Platform-Support)
- [AspResponse target](https://github.com/NLog/NLog/wiki/AspResponse-target)
- [AspApplication-Layout-Renderer](https://github.com/NLog/NLog/wiki/AspApplication-Layout-Renderer)
- [AspRequest-Layout-Renderer](https://github.com/NLog/NLog/wiki/AspRequest-Layout-Renderer)
- [AspSession-Layout-Renderer](https://github.com/NLog/NLog/wiki/AspSession-Layout-Renderer)

I can do wiki things after merging. Just let me know!

**Comment by 304NotModified** [comment]
thanks @UgurAldanmaz !



> and wiki pages:

We will remove the old pages from the index, but deletion is unneeded IMO

**Comment by UgurAldanmaz** [comment]
I agree, index removing is enough. :)

I am not sure if old ASP things are still using. Should we mark it as a breaking change?

**Comment by 304NotModified** [comment]
Well AFAIK you can't even use it.

**Pull request merged**
