### PR TITLE
Add example configuration for ToolStripItemTarget

### PR DESCRIPTION
**Pull request by Fr33dan**
After encountering the "bug" #147 . I implemented a target capable of logging to a ToolStripItem. That is in the NLog.Windows.Forms project under pull request [#87](https://github.com/NLog/NLog.Windows.Forms/pull/87). This pull incorporates the documentation for said target.

### CODE REVIEW

**Comment by snakefoot** [comment]
Thank you for the pull-request. Think there is a pending cleanup of the example projects, that no longer directly belongs to the NLog-core-project (Like `NLog.Windows.Forms`)

Think it would makes most sense to have the example-project in the `NLog.Windows.Forms`-repository. Maybe even part of the solution, so it is easy to see it in action.

One could consider moving the existing [FormControl](https://github.com/NLog/NLog/tree/dev/examples/targets/Configuration%20API/FormControl)-sample together into the `NLog.Windows.Forms`-repository aswell.

**Comment by Fr33dan** [comment]
That is fair, I mainly just copied what was already there for existing targets. Mainly I have never used inline XML documentation with linkage like FormControlTarget and figured if I copied from that it would work as intended. I can move example(s), but I have no idea what effect it will have wherever the XML documentation is used.

I figure its probably most important to have it documented in the wiki but it doesn't make sense to try to edit that until the new target is approved.

**Comment by snakefoot** [comment]
Yes also think wiki-page-documenation is most important. Think the API-docs should just pickup a wiki-link, instead of having these example projects referenced directly. Instead the wiki-page should do the nice introduction, and if very needed then it can decide to throw a repository-link to an example project.

**Comment by 304NotModified** [comment]
@Fr33danis this PR still needed? I will try to release NLog.Windows.Forms  4.6 soon

**Comment by Fr33dan** [comment]
As that I wrote the code for the ToolStripItem I should also write the documentation but where I should do so is a question for y'all as package maintainers. Based on this discussion I did write a page in the wiki. 

I think snakeroot is probably right in that it doesn't really belong here but I figure that is a call for you two. If you agree this PR can be closed.

**Comment by snakefoot** [comment]
Thank you for creating the wiki-page:

https://github.com/NLog/NLog/wiki/ToolstripmenuItem-target

I was thinking example-projects in the solution, like done here:

https://github.com/NLog/NLog.Web/tree/master/examples

I will close this pull-request, and then one can consider creating pull-request for the `NLog.Windows.Forms`-project.

**Pull request closed without merging**
