### PR TITLE
BugFix: <targets> after <rules> won't work

### LINKED ISSUE #2045: In the config file, order of targets and rules blocks may cause errors
I'm new to NLog and just went through a process of setting up NLog within a project of mine. I couldn't get NLog to properly load for awhile. I eventually got NLog to generate the internal log file and got an error saying that NLog could not locate a target of mine. I looked at my config and noticed that my `targets` block was below my `rules` block. So, I swapped it so that `targets` was now above `rules` and everything started working as intended. This remained the case regardless of whether or not I used a stand alone `NLog.config` file or the `app.config` file.

I'm unsure of how NLog loads the config file, but order of these blocks interfering with things seems odds to me. I think that this is either a bug or needs to be mentioned in the config file documentation, if it's not already.

### PR DESCRIPTION
**Pull request by 304NotModified**
Fixes #2045

### CODE REVIEW

**Comment by 304NotModified** [comment]
supersedes https://github.com/NLog/NLog/pull/2096

**Comment by snakefoot** [comment]
Maybe change the logic, so it always parses elements in this order (and not just targets first):

```
case "EXTENSIONS":
case "INCLUDE":
case "TIME":
case "VARIABLE":
case "APPENDERS":
case "TARGETS":
case "RULES":
```

**Comment by 304NotModified** [comment]
Indeed this was too Much quick fix

**Comment by snakefoot** [comment]
Easy fix would be to always parse "RULES" last :)

**Comment by 304NotModified** [comment]
Have to look into this. Where variables and include is defined, does matter.

**Comment by 304NotModified** [comment]
> Easy fix would be to always parse "RULES" last :)

That's indeed a much easier approach -  keep it simple :)

changed!

**Comment by 304NotModified** [comment]
Fixed in 4.4.10 and the release is queued. Will be online in a few hours!

**Pull request merged**
