### PR TITLE
Log4JXml - Removed redundant logging of exception, default IncludeNLogData to false

### PR DESCRIPTION
**Pull request by snakefoot**
Skip NLog-namespace handling when IncludeNLogData = false.

For NLog 5.0

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/2672)

### CODE REVIEW

**Comment by snakefoot** [comment]
Added `WriteThrowableCData` to support  #2791

**Comment by 304NotModified** [comment]
Please rebase this, and then I will merge it - thanks!

**Comment by snakefoot** [comment]
> @304NotModified Please rebase this, and then I will merge it - thanks!

Done

**Comment by 304NotModified** [comment]
Thanks!

**Comment by snakefoot** [comment]
Updated wiki: https://github.com/NLog/NLog/wiki/Log4JXMLEvent-Layout-Renderer (With new `includeNLogData` default value)

**Pull request merged**
