### PR TITLE
Added LogFactory.ConfigurationLoading for better reload event

### PR DESCRIPTION
**Pull request by snakefoot**
Allow #3929 to use `ConfigurationLoading` (Because `ConfigurationReloaded` only works for xml-config. And `ConfigurationReloaded` happens AFTER target initialization):

```c#
            if (applyOnReload)
            {
                setupBuilder.LogFactory.ConfigurationLoading += (sender, e) =>
                {
                    if (e.IsNewConfiguration)
                    {
                         setupBuilder.Configuration = e.ActivatedConfiguration;
                         setupBuilder.LoadConfiguration(false, configBuilder);
                    }
```

This will make it also work for MEL-NLogLoggingConfiguration.

Maybe mark `ConfigurationReloaded` as obsolete in NLog 5.0? (Since that event-handler only works for xml-config)

### CODE REVIEW

**Comment by 304NotModified** [comment]
Hey! I was reviewing, but don't fully get it. Why has a *change* something to do with *activated*. ?

Could it be `e.IsInitialConfiguration` instead of `e.InitialConfigActivation`?

**Comment by snakefoot** [comment]
> Could it be e.IsInitialConfiguration instead of e.InitialConfigActivation?

Lets say you do this:

```
var config = new LoggingConfiguration();
LogManager.Configuration = config;  // InitialConfigActivation = true
LogManager.Configuration = config;  // InitialConfigActivation = false
LogManager.Configuration = config;  // InitialConfigActivation = false

var config2 = new LoggingConfiguration();
LogManager.Configuration = config2;  // InitialConfigActivation = true
LogManager.Configuration = config2;  // InitialConfigActivation = false
LogManager.Configuration = config;    // InitialConfigActivation = false
```

Think `IsInitialConfiguration` sounds like it is the very first assignment, but you can assign the same configuration multiple times. But you can also assign different configs for every time.

**Comment by 304NotModified** [comment]
> Think `IsInitialConfiguration` sounds like it is the very first assignment

Well, InitialConfigActivation doesn't sound as a boolean to me ;)

**Comment by 304NotModified** [comment]
I sounds more like a "FirstApplyOfThisConfig" boolean, but it's hard to understand/use!

**Comment by snakefoot** [comment]
What about `IsInitialActivation` ?

**Comment by snakefoot** [comment]
Btw. created this PR mostly as an example of how to use `ConfigurationChanged` instead of `ConfigurationReloaded`. Because it would make it more generic and work with MEL-NLogLoggingConfiguration.

But happy you are approving and we are just arguing about a property-names :)

**Comment by 304NotModified** [comment]
out-of-the-box thinking...

What about a new event, and leave this one unchanged? As now you capture events but are only interested in a subset which is a bit strange. 

Maybe don't add the event on logmanager, but only on logfactory.

**Comment by snakefoot** [comment]
> What about a new event, and leave this one unchanged? As now you capture events but are only interested in a subset which is a bit strange.

I like the idea of using `ConfigurationChanged`. Hate where there are too many door-handles to the same door (Sickness that comes with some libraries where there is 3 standard ways to do the same thing).

**Comment by 304NotModified** [comment]
Well it sounds so unrelated to ConfigurationChanged to me. I find it hard to understand

btw, I think it should be onReloaded. Which is good, as I changed applyOnReload already to reloaded event (not merged yet of course)

**Comment by snakefoot** [comment]
> Well it sounds so unrelated to ConfigurationChanged to me. I find it hard to understand

Think you have to explain this some more. I'm not changing `ConfigurationChanged`. I'm just adding more context-detail to the EventArg.

> btw, I think it should be onReloaded. Which is good, as I changed applyOnReload already to reloaded event (not merged yet of course)

Again we are back to having too many events. Think we should get rid of `ConfigurationReloaded` and focus on only recommending `ConfigurationChanged`

**Comment by 304NotModified** [comment]
> Think you have to explain this some more. I'm not changing `ConfigurationChanged`. I'm just adding more context-detail to the EventArg (Whether it is a new config assigned for the first time, or whether it is same config being re-assigned)

Yes that's clear. But of course the properties should be understandable. 

> Again we are back to having too many events. Think we should get rid of ConfigurationReloaded and focus on only recommending (and improving) ConfigurationChanged (Easier for us, and easier for the NLog users)

That's another discussion on which on don't agree. Reload could lead to change, but also not. And Change could be triggered by reload but also another way.

**Comment by snakefoot** [comment]
> Yes that's clear. But of course the properties should be understandable.

Yes also want a clear and understandable name, that can signal that the change was done with a fresh/vanilla config, that has not yet been touched.

**Comment by snakefoot** [comment]
I now see that there is a vital knob missing in this PR. the `ConfigurationChanged`-event is triggered AFTER the config has been assigned. `applyOnReload` wants to trigger BEFORE assigning (and initializing) the config.

**Comment by snakefoot** [comment]
> @304NotModified  What about a new event, and leave this one unchanged?

Think you are right about this. Now introduced `ConfigurationChanging` (I know I have reused `LoggingConfigurationChangedEventArgs` as EventArgs and that will be changed, but right now working on the mental drawing board).

**Comment by snakefoot** [comment]
@304NotModified How do you feel about having both `ConfigurationChanging` and `ConfigurationChanged` ?

**Comment by 304NotModified** [comment]
> @304NotModified How do you feel about having both `ConfigurationChanging` and `ConfigurationChanged` ?

I have to think about this.

**Comment by 304NotModified** [comment]
> Maybe mark ConfigurationReloaded as obsolete in NLog 5.0? (Since that event-handler only works for xml-config)

This is difficult as I see a manual assignment as change, but not as reload. 

Maybe stupid question, but what goes wrong if we always do LoadConfiguration? E.g.:


> ```cs
>             if (applyOnReload)
>             {
>                 setupBuilder.LogFactory.ConfigurationChanging += (sender, e) =>
>                 {
>                          setupBuilder.LoadConfiguration(false, configBuilder);
> ```

**Comment by snakefoot** [comment]
Let's say the configBuilder method adds a new target to config and then re-assigns LogFactory.Configuration.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


Maybe mark ConfigurationReloaded as obsolete in NLog 5.0? (Since that event-handler only works for xml-config)

This is difficult as I see a manual assignment as change, but not as reload.

Maybe stupid question, but what goes wrong if we always do LoadConfiguration? E.g.:

            if (applyOnReload)
            {
                setupBuilder.LogFactory.ConfigurationChanging += (sender, e) =>
                {
                         setupBuilder.LoadConfiguration(false, configBuilder);

**Comment by snakefoot** [comment]
Can also see that `ConfigurationReloaded` is not optimal for hooking `configBuilder`. Because the config-method will be called AFTER having loaded and initialized the configuration.

The idea with `LoadConfiguration` is that you adjust the LoggingConfiguration before assigning it as the new active LogFactory.Configuration. When using `ConfigurationReloaded`-event then it will be too late for adjusting Target-properties that must be configured before Target-initialization.

**Comment by snakefoot** [comment]
Added unit-test that will only succeed when using `ConfigurationChanging`.

**Comment by snakefoot** [comment]
Could also rename it from `ConfigurationChanging` to `ConfigurationLoading` and ensure it is only called when `if (!e.IsConfigAmend && e.ActivatedConfiguration != null)`. Like this:
```c#
            if (applyOnReload)
            {
                setupBuilder.LogFactory.ConfigurationLoading += (sender, e) =>
                {
                     setupBuilder.Configuration = e.NewConfiguration;
                     setupBuilder.LoadConfiguration(false, configBuilder);
```

**Comment by 304NotModified** [comment]
>  Could also rename it from `ConfigurationChanging` to `ConfigurationLoading`

If we gonna drop ConfigurationLoaded soon, then that's a bit strange? 

Anyway, I really like another name for amend, but don't have a proposal. (I tried thinking of a new name by asking questions, but unfortunately I don't have one)

**Comment by snakefoot** [comment]
> If we gonna drop ConfigurationLoaded soon, then that's a bit strange?

Dropping `ConfigurationReloaded` for `ConfigurationLoading` doesn't sound strange to me. 

Also `ConfigurationReloaded` only works for xml-config, and the event is merely a left-over from when LogFactory was doing all the file-loading itself. I have now moved most of it out of LogFactory, but actually all logic about file-watching etc. should be controlled by XmlLoggingConfiguration (and not be visible in LogFactory).

**Comment by snakefoot** [comment]
Instead of `IsConfigAmend` then it could also be `IsNewConfiguration`

**Comment by snakefoot** [comment]
@304NotModified I'm happy with the PR now. Decided it is best to trigger the `ConfigurationLoading` after having flushed/closed the old-config, but just before initializing the new-config. Then the system should be somewhat "quiet".

**Comment by 304NotModified** [comment]
> Maybe mark ConfigurationReloaded as obsolete in NLog 5.0? (Since that event-handler only works for xml-config)

So for ApplyOnReload, we need to change it to ConfigurationChanged isn't? Too bad that will give a log of tests needed (shutdown etc)

**Comment by snakefoot** [comment]
> So for ApplyOnReload, we need to change it to ConfigurationChanged isn't? 

Yes change it to [ConfigurationLoading](https://github.com/NLog/NLog/pull/3954#issue-416215701)

**Comment by 304NotModified** [comment]
and what about LogManager? Do you think we should include this also there?

**Comment by 304NotModified** [comment]
> Yes change it to [ConfigurationLoading](https://github.com/NLog/NLog/pull/3954#issue-416215701)

No that's not possible? It should be changed after loading? (hmmm or not, not sure)

**Comment by 304NotModified** [comment]
> No that's not possible? It should be changed after loading? (hmmm or not, not sure)

And also not sure if it works with assigning (it should not apply then). But we could see after merge. Or maybe I should test it first...

**Comment by snakefoot** [comment]
The whole idea with LoadConfiguration-method is to afjust NLog before it is loaded. So the same should apply when enabling applyOnReload


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


Yes change it to ConfigurationLoading<https://github.com/NLog/NLog/pull/3954#issue-416215701>

No that's not possible? It should be changed after loading? (hmmm or not, not sure)

**Comment by 304NotModified** [comment]
I will test this with #3929 now

**Comment by 304NotModified** [comment]
Doesn't work, as this is now a "reload".

    logFactory.Configuration = logFactory.Configuration.Reload();

 And while that's true, then you can reset stuff. 

This is expected (and maybe a better case)

    logFactory.Configuration = new ... // don't expect applyonreload here.

**Comment by snakefoot** [comment]
Well to me there is no difference in loading a new configuration and reloading a new configuration. But I also think that applyOnReload should false by default, as users should opt-in to the side-effect.

**Comment by 304NotModified** [comment]
> Well to me there is no difference in loading a new configuration and reloading a new configuration. But I also think that applyOnReload should be false by default, as users should opt-in to the automagically side-effect.

Yes So I think we still need a reload event.

As this should not applyOnReload
```c#
logFactory.Configuration = something
```

As this should
```c#
logFactory.ReloadConfiguration()
```

**Comment by 304NotModified** [comment]
So I need an approval on https://github.com/NLog/NLog/pull/3952 ;)

**Comment by snakefoot** [comment]
> Yes So I think we still need a reload event.

I don't agree. But I have now made some requests for #3952

**Comment by 304NotModified** [comment]
> I don't agree. But I have now made some requests for #3952

don't agree with https://github.com/NLog/NLog/pull/3954#issuecomment-628266967, or need for a reload event?

**Comment by snakefoot** [comment]
I think that `ConfigurationLoading` will work just fine, and do the expected. But never too late to kill your darlings.

**Comment by 304NotModified** [comment]
> I think that `ConfigurationLoading` will work just fine, and do the expected. But never too late to kill your darlings.

I don't know which one you now mean  (in "don't agree with the functionality described in #3954 (comment), OR the need for a reload event?")

**Comment by snakefoot** [comment]
> I don't know which one you now mean (in "don't agree with the functionality described in #3954 (comment), OR the need for a reload event?")

That you are welcome to close this PR (without implementing ConfigurationLoading), and instead implement the same logic #3952 (With IsNewConfiguration and allowing one to provide LoggingConfiguration as parameter to ReloadConfiguration).

**Comment by snakefoot** [comment]
Closed as inactive for too long. See also #4250

**Pull request closed without merging**
