### PR TITLE
added switch to JsonLayout to suppress the extra spaces

### PR DESCRIPTION
**Pull request by tmusico**
the extra spaces can now be suppressed for the JsonLayout.  I found this modification to be useful when using a network target sending via UDP ... every little byte matters.

also added was a unit test and I tested the nlog file configuration (with the Nlog.test project) to ensure the configuration attribute was working correctly.

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks 

It would be nice if we create one (append)  method which add the optional spacing. Do you agree?

**Comment by tmusico** [comment]
That would work too. I was also thinking an extension method, that was the
way I first wrote it. But then when I looked through the rest of the nlog
source code I realized there wasn't any other extension methods that I
could see.

**Comment by 304NotModified** [comment]
I would like to merge this. But there is a conflict.  Can you fix this?

**Comment by 304NotModified** [comment]
We need also docs on the wiki. Can you add them (with an 4.1 note)

**Comment by 304NotModified** [comment]
Thanks! It has been merged!

**Pull request merged**
