### PR TITLE
Fix NLog.WindowsEventLog Package

### LINKED ISSUE #2828: Unable to log using EventLog target .NET Core 2.1
I'm trying to get my console application to log to the database, file, console and eventviewer. However everytime i had the eventviewer code it throws an exception. I added the NLog.WindowsEventLog nuget package but it still isnt working. The errors can be seen below and the full config image is attached:

2018-08-01 Error parsing layout all-event-properties will be ignored. Exception: LayoutRenderer cannot be found: 'all-event-properties' at NLog.Config.Factory

2018-08-01 Error Parsing configuration from C:\Users\user20\TestLogging\TestLogging\nlog.config failed. Exception: Exception when parsing C:\Users\user20\TestLogging\TestLogging\nlog.config. ---> Target cannot be found: 'EventLog' at NLog.Config.Factory

capture

### PR DESCRIPTION
**Pull request by 304NotModified**
Fixes #2828

### CODE REVIEW

**Comment by 304NotModified** [comment]
> By only defining NETSTANDARD2_0 and not NETSTANDARD, then it should be included.

Yes, also an option, but I think it's now more clear it also used in another package.

**Comment by snakefoot** [comment]
I just mentioned how it was working now, and curious how your change would change anything.

Since the NLog.WindowsEventLog-project only defines NETSTANDARD2_0 (and not NETSTANDARD)

**Comment by snakefoot** [comment]
But it is funny that NLog 4.5.6 is working but NLog 4.5.7 is not. Maybe NETSTANDARD has become a default define in MsBuild ?

**Comment by snakefoot** [comment]
@304NotModified The same problem also exist for "NLog.WindowsIdentity". https://www.nuget.org/packages/NLog.WindowsIdentity/4.5.6 is working (But ver. 4.5.7 does not)

**Comment by 304NotModified** [comment]
> Maybe NETSTANDARD has become a default define in MsBuild ?

sounds plausible 



> @304NotModified The same problem also exist for "NLog.WindowsIdentity". https://www.nuget.org/packages/NLog.WindowsIdentity/4.5.6 is working (But ver. 4.5.7 does not)
> 
> Please unlist the broken ver 4.5.7, and release a fixed ver 4.5.8 for that nuget-package also

thanks for checking, will do

**Pull request merged**
