### PR TITLE
InternalLogger: added LogMessageReceived event

### LINKED ISSUE #3350: Add internallogger event(s)
Easier to subscribe than  ` InternalLogger.LogWriter`

### PR DESCRIPTION
**Pull request by 304NotModified**
Fixes https://github.com/NLog/NLog/issues/2710, first steps for #3350 and https://github.com/NLog/NLog/issues/1193

@snakefoot please review, also the names. 

PS: I started with a delegate, but switched to EventHandler because of this (and also we use already in NLog (e.g. LogManager.ConfigurationChanged)

> For scenarios where the EventHandler and EventHandler<TEventArgs> delegates do not work, you can define a delegate. Scenarios that require you to define a delegate are very rare, such as when you must work with code that does not recognize generics. 

https://docs.microsoft.com/en-us/dotnet/standard/events/index?view=netframework-4.8

### CODE REVIEW

**Comment by 304NotModified** [comment]
again "No output has been received in the last 10m0s" in Travis

**Comment by 304NotModified** [comment]
@snakefoot please your opinion :)

**Comment by snakefoot** [comment]
I was thinking to extend with context info. So having Target-Type and Target-Info (Target ToString output) as info. Then remove the need to manual write it every time when logging but just provide "this" in as parameter.


But I have been waiting for the Dependency Injection adventure to complete, along with all other major changes so it happens just before NLog 5 is released, because it will make any merging from master to dev conflict almost by guarantee (will include rewrite of all internal logging statements)


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


@snakefoot<https://github.com/snakefoot> please your opinion :)

**Comment by snakefoot** [comment]
Instead of calling it ReceivedInternalLogEventArgs then I just prefer InternalLoggerEventArgs


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


@snakefoot<https://github.com/snakefoot> please your opinion :)

**Comment by snakefoot** [comment]
Please move this for NLog 5.0

**Comment by 304NotModified** [comment]
> Please move this for NLog 5.0

Because of 

> I was thinking to extend with context info. 

?

Can't we add that to NLog 5 afterwards? Doesn't sound like a breaking change

**Comment by snakefoot** [comment]
> > Please move this for NLog 5.0

>  Because of?

Well the issues this pull-request promise to resolve, do mention that it is important to have details of what target-type and target-name the event comes from. This is not included in this PR.

**Comment by 304NotModified** [comment]
true if fixes #2710, and are the first steps for #3350 and #1193

**Comment by 304NotModified** [comment]
> Instead of calling it `ReceivedLogEvent` and `ReceivedInternalLogEventArgs` then I prefer `OnLogEvent` and `InternalLoggerLogEventArgs`

- Renamed the ReceivedInternalLogEventArgs to InternalLoggerLogEventArgs
- I like also the On... name, but that's inconsistent with LogManager.ConfigurationChanged and LogManager.ConfigurationReloaded. We haven't anywhere a On... method in NLog currently. AFAIK MS is also inconsistent with On and not On ;). So I left it like this

**Comment by 304NotModified** [comment]
@snakefoot this is the latest for me for 4.7. If you think some things must be included for NLog 4.7, please let me know. Thanks!

**Comment by snakefoot** [comment]
Problem is that it is an InternalLogger event and not a Logevent. Find received-logevent very confusing


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


Instead of calling it ReceivedLogEvent and ReceivedInternalLogEventArgs then I prefer OnLogEvent and InternalLoggerLogEventArgs

  *   Renamed the ReceivedInternalLogEventArgs to InternalLoggerLogEventArgs
  *   I like also the On... name, but that's inconsistent with LogManager.ConfigurationChanged and LogManager.ConfigurationReloaded. We haven't anywhere a On... method in NLog currently. AFAIK MS is also inconsistent with On and not On ;). So I left it like this

**Comment by 304NotModified** [comment]
ReceivedInternalLogEvent then?

**Comment by 304NotModified** [comment]
but it's on the InternalLogger already?

**Comment by snakefoot** [comment]
I like `ReceivedInternalLogEvent` :)

**Comment by snakefoot** [comment]
Maybe call it `InternaLogger.RaiseEvent` or `InternaLogger.NotifyEvent` or `InternaLogger.NotifyEvent`

**Comment by 304NotModified** [comment]
Events should be in past tense?

**Comment by 304NotModified** [comment]
> Also think received is strange, since they are generated. Never seen "received" as event-notification, so it is actually the "received" part that I don't like.

https://docs.microsoft.com/en-us/dotnet/api/system.io.ports.serialport.datareceived

The internallogger received the generated event. But for sure LogEventRecieved is better than RecievedLogEvent

**Comment by 304NotModified** [comment]
EventWritten? (unfortunately written sounds like "written to file")

**Comment by 304NotModified** [comment]
related: https://stackoverflow.com/questions/724085/events-naming-convention-and-style

**Comment by 304NotModified** [comment]
I think the best candidates are LogEventReceived or LogMessageReceived. But im open for other suggestions

**Comment by snakefoot** [comment]
I agree if InternalLogger received its events from another machine through a network connection like the serial cable then the name received is good.


But I don't think NLog receives any events. It has generated / raised them by it self.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


I think the best candidates are LogEventReceived or LogMessageReceived. But im open for other suggestions

**Comment by snakefoot** [comment]
May call it LogWritten and ensure the event is raised after other destinations (Like LogWriter) have been notified.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


I think the best candidates are LogEventReceived or LogMessageReceived. But im open for other suggestions

**Comment by 304NotModified** [comment]
> Since the InternalLogger can write its messages to a lot of destinations (LogWriter + LogFile + Console + Trace). Then I don't think "Written" automatically means to file. See also: https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.eventlog.entrywritten

This is exactly why "written" is wrong here.

A target writes/calls to the internal logger. The internal logger writes to the console/file etc.

So these events would be written: ConsoleWritten, FileWritten. But that isn't the case here, as the event is trigger on receiving a log message and not after a write to console/file/db/eventlog whatever.

**Comment by snakefoot** [comment]
Well to me `LogMessageReceived` is completely wrong, because it sounds like it is triggered when NLog receives a LogMessage from the application. Anyway agree to disagree.

**Pull request merged**
