### PR TITLE
Allow configuring type of parameters for the database target (including fix for Oracle)

### PR DESCRIPTION
**Pull request by 304NotModified**
TODO:
- [ ] use the DB type configured in the config instead of typescanning
- [ ] scan for type at init, not at write
- [ ] implement for all DB types: 
  - [ ]  System.Data.EntityClient.EntityParameter
  - [ ] System.Data.Odbc.OdbcParameter
  - [ ] System.Data.OleDb.OleDbParameter
  - [ ] System.Data.OracleClient.OracleParameter
  - [ ] System.Data.SqlClient.SqlParameter
- [ ] parse DB type when parsing config (not on logging)
- [ ] check if parse type is needed
- [ ] create testcase for at least int, bit and oracletype
- [ ] create testcase with .mdf file.
- [ ] add integration tests .

Discuss:
- Maybe 2nd parameter to distinguish DBType vs **x**DbType (e.g. SqlDbType, OracleDbType)?

supersedes https://github.com/NLog/NLog/pull/1194

thanks to @sorvis

---

This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1435)

### CODE REVIEW

**Comment by 304NotModified** [comment]
@sorvis too bad I didn't have time to fix this :(

There reasons why this isn't merged yet:

- We should use the DB type that is already in the database target.
- We should scan for the parameter type at init, not at write. 
- I'm not sure if this works for e.g. `int` columns. We need unit tests for those.

Without those, it's to risky to merge this. 

Could you help me with this @sorvis? You can create a branch from this branch, or I can give you write permissions. Otherwise, I will try to work on this in the future, but some issues has more prio right now (.NET Core + structural logging + prio bugfixes). Let me know your thoughts! Cheers!

**Comment by SergeyChanaev** [comment]
Two things:
1. Please do not forget about PostgreSQL -> NpgsqlDbType
2. Is it duplicate of https://github.com/NLog/NLog/issues/522?

**Comment by 304NotModified** [comment]
> Please do not forget about PostgreSQL -> NpgsqlDbType

Thanks for the reminder.



> Is it duplicate of #522?

No as this one is a Pull Request (PR), unfortunately I didn't find time to finish it. Could you help us with this?

**Comment by SergeyChanaev** [comment]
Julian, sorry for late reply. I might try to do that, but can't give any time estimates.

**Comment by 304NotModified** [comment]
:+1: any help is welcome :)

I'm working on NLog 4.4.2 and 4.5 (structured logging)

**Comment by hubo0831** [comment]
My request use another method to resolve problem of Database Command Paremeter DbType and value convertion, use custom DbType property name. @304NotModified please pay attention to it.

**Comment by 304NotModified** [comment]
superseded by #2899 and expected to be released in NLog 4.6

**Pull request closed without merging**
