### PR TITLE
BucketSort - StringComparer.Ordinal should be faster than EqualityComparer.Default

### PR DESCRIPTION
**Pull request by snakefoot**

### CODE REVIEW

**Review by 304NotModified — APPROVED** [review]

**Comment by snakefoot** [comment]
Force push to restart Azure-Build, that was stuck in cancelled state. No changes made.

**Review by 304NotModified — APPROVED** [review]

**Comment by 304NotModified** [comment]
Thanks for the info :)

**Comment by snakefoot** [comment]
Starting to doubt if this is actually a performance improvement, after looking at the code for StringComparer.Ordinal.  It seems it is actually best when meeting many different long strings where ordinal-compare can shine.

But when meeting the same string again and again (ex. filetarget-filename) then `string.Equals` is faster as it performs  `Object.ReferenceEquals(this, value)` very early and it will usually return true (because of caching).

**Comment by snakefoot** [comment]
Created PR #4125 to rollback this one. Guess I should test instead of guessing.

**Comment by 304NotModified** [comment]
This has been reverted by removing the last commit, 28ce43fff546df2204540bf1ec81a72a97836e8a from dev

**Pull request merged**
