### PR TITLE
upgrade to C# 7.2

### PR DESCRIPTION
**Pull request by 304NotModified**
fails "MediumTrustWithExternalClass" test

works on: 7.0 and 7.1
fails on 7.2 and 7.3

most important exceptions:

```
System.Security.SecurityException
  HResult=0x8013150A
  Message=Request for the permission of type 'System.Security.Permissions.FileIOPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.
  Source=mscorlib
  StackTrace:
   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet)
   at System.Security.CodeAccessPermission.Demand()
   at System.AppDomainSetup.VerifyDir(String dir, Boolean normalize)
   at System.AppDomain.get_BaseDirectory()
   at NLog.Internal.Fakeables.AppDomainWrapper.LookupBaseDirectory(AppDomain appDomain) in D:\nlog\nlog\src\NLog\Internal\Fakeables\AppDomainWrapper.cs:line 100

System.Security.SecurityException
  HResult=0x8013150A
  Message=Request for the permission of type 'System.Security.Permissions.EnvironmentPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.
  Source=mscorlib
  StackTrace:
   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet)
   at System.Security.CodeAccessPermission.Demand()
   at System.Environment.GetEnvironmentVariable(String variable)
   at NLog.Internal.EnvironmentHelper.GetSafeEnvironmentVariable(String name) in D:\nlog\nlog\src\NLog\Internal\EnvironmentHelper.cs:line 83

System.Security.SecurityException
  HResult=0x8013150A
  Message=Request for the permission of type 'System.Security.Permissions.EnvironmentPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.
  Source=mscorlib
  StackTrace:
   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet)
   at System.Security.CodeAccessPermission.Demand()
   at System.Environment.GetEnvironmentVariable(String variable)
   at NLog.Internal.EnvironmentHelper.GetSafeEnvironmentVariable(String name) in D:\nlog\nlog\src\NLog\Internal\EnvironmentHelper.cs:line 83

System.Security.SecurityException
  HResult=0x8013150A
  Message=Request for the permission of type 'System.Security.Permissions.FileIOPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.
  Source=mscorlib
  StackTrace:
   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet)
   at System.Security.CodeAccessPermission.Demand()
   at System.AppDomainSetup.VerifyDir(String dir, Boolean normalize)
   at NLog.Internal.Fakeables.AppDomainWrapper.LookupConfigurationFile(AppDomain appDomain) in D:\nlog\nlog\src\NLog\Internal\Fakeables\AppDomainWrapper.cs:line 109


System.Security.SecurityException
  HResult=0x8013150A
  Message=Request for the permission of type 'System.Security.Permissions.FileIOPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.
  Source=mscorlib
  StackTrace:
   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet)
   at System.Security.CodeAccessPermission.Demand()
   at System.Reflection.RuntimeAssembly.VerifyCodeBaseDiscovery(String codeBase)
   at System.Reflection.RuntimeAssembly.get_CodeBase()
   at NLog.Internal.AssemblyHelpers.GetAssemblyFileLocation(Assembly assembly) in D:\nlog\nlog\src\NLog\Internal\AssemblyHelpers.cs:line 134


System.Security.SecurityException
  HResult=0x8013150A
  Message=Request for the permission of type 'System.Security.Permissions.FileIOPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.
  Source=mscorlib
  StackTrace:
   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet)
   at System.Security.CodeAccessPermission.Demand()
   at System.Reflection.RuntimeAssembly.VerifyCodeBaseDiscovery(String codeBase)
   at System.Reflection.RuntimeAssembly.get_CodeBase()
   at NLog.Internal.AssemblyHelpers.GetAssemblyFileLocation(Assembly assembly) in D:\nlog\nlog\src\NLog\Internal\AssemblyHelpers.cs:line 134



System.Reflection.ReflectionTypeLoadException
  HResult=0x80131602
  Message=Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
  Source=mscorlib
  StackTrace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at NLog.Internal.ReflectionHelpers.SafeGetTypes(Assembly assembly) in D:\nlog\nlog\src\NLog\Internal\ReflectionHelpers.cs:line 58


System.Security.SecurityException
  HResult=0x8013150A
  Message=Request failed.
  Source=NLog
  StackTrace:
   at NLog.Common.InternalLogger.LogAssemblyVersion(Assembly assembly) in D:\nlog\nlog\src\NLog\Common\InternalLogger.cs:line 492
   at NLog.LogFactory.LogConfigurationInitialized() in D:\nlog\nlog\src\NLog\LogFactory.cs:line 302


System.Security.VerificationException
  HResult=0x8013150D
  Message=Operation could destabilize the runtime.
  Source=NLog
  StackTrace:
   at NLog.Internal.AppendBuilderCreator.get_Builder() in D:\nlog\nlog\src\NLog\Internal\AppendBuilderCreator.cs:line 50


System.Security.VerificationException
  HResult=0x8013150D
  Message=Operation could destabilize the runtime.
  Source=NLog
  StackTrace:
   at NLog.Internal.AppendBuilderCreator.Dispose() in D:\nlog\nlog\src\NLog\Internal\AppendBuilderCreator.cs:line 68


System.Threading.ThreadAbortException
  HResult=0x80131530
  Message=Thread was being aborted.
  Source=NLog
  StackTrace:
   at NLog.Targets.Target.WriteAsyncLogEvents(IList`1 logEvents) in D:\nlog\nlog\src\NLog\Targets\Target.cs:line 393


```

### CODE REVIEW

**Comment by 304NotModified** [comment]
could be related: https://stackoverflow.com/questions/378895/operation-could-destabilize-the-runtime

**Comment by 304NotModified** [comment]
@snakefoot any idea, as you've wrote the unit test? 👼

**Comment by 304NotModified** [comment]
note: updating xunit / Microsoft.NET.Test.Sdk won't have any effect

test with

```
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">

```

**Comment by snakefoot** [comment]
> @304NotModified  any idea, as you've wrote the unit test?

Hehe I just grapped some random code on the internet and hammered on it until it could be used as unit-test for proving medium trust appdomains are supported by NLog. You can just grap some other random code on the internet that can prove the same :)

**Comment by snakefoot** [comment]
Maybe consider delaying C# 7.2 for NLog 5.0 and then revisit all internal methods/properties.

**Comment by 304NotModified** [comment]
> Maybe consider delaying C# 7.2 for NLog 5.0 and then revisit all internal methods/properties.

👍 thanks, will do that if I won't have a solution this week

**Comment by 304NotModified** [comment]
Maybe another time for this change (still unclear why this breaks the medium trust)

**Pull request closed without merging**
