### PR TITLE
AppDomainWrapper / IAppDomain moved to internal

### PR DESCRIPTION
**Pull request by 304NotModified**
Not sure if we should include this for NLog 4.x or 5

there are more `public` classes in "internal", e.g. for NLog.Extended

Also Not sure if this is used in external libs, e.g. NLog.Web

- [ ] update: IAppDomain is needed to be public, the wrapper doensn't

This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1691)

### CODE REVIEW

**Comment by 304NotModified** [comment]
not needed for 4.3/4.4 so 5.0 it is

**Comment by snakefoot** [comment]
Consider also to break the ProcessExit and DomainUnload-delegates, so they are perfect forwards to AppDomain.

**Comment by 304NotModified** [comment]
update: IAppDomain is needed to be public, the wrapper doensn't

**Comment by 304NotModified** [comment]
superseded by https://github.com/NLog/NLog/pull/3457

**Pull request closed without merging**
