### PR TITLE
Reducing memory allocations in ShortDateLayoutRenderer by caching the formatted date.

### PR DESCRIPTION
**Pull request by epignosisx**
This is a copy of the pull request #1064 but with a clean commit history.

### CODE REVIEW

**Comment by epignosisx** [comment]
Any idea why those unit tests are failing? They passed in my PC. They seem unrelated to the code I touched.

**Comment by 304NotModified** [comment]
I think the tests fails at a particular times (night), it's the archive method. I have restarted it

Any idea if we can rid of the `ref`s?

**Comment by epignosisx** [comment]
The other solution that comes to mind is creating a nested class:

    private class DateData
    {
        public DateTime Date { get; set; }
        public string FormattedDate { get; set; }
    }

and use it like this:

    private static DateData cachedLocalDate = new DateData();
    private static DateData cachedUtcDate  = new DateData();


    private static void AppendDate(StringBuilder builder, DateTime ts, DateData cachedDate)
    {
        ....
    }

**Comment by 304NotModified** [comment]
yes, that would be a great solution!

**Comment by epignosisx** [comment]
The mysterious unrelated failing unit tests strike again.

**Comment by 304NotModified** [comment]
Well, I never seen this error before!

**Comment by 304NotModified** [comment]
Well it worked :)

If you rename the names likes `ts`, `ie` `ei` to meaningful names (the code you touched), I will merge it :)

**Comment by epignosisx** [comment]
Done

**Comment by 304NotModified** [comment]
See gitter about you git/gibhub config. It's OK if you alter these commits and do a forced push

**Comment by 304NotModified** [comment]
Thanks! I has been merged! Nice improvement :)

**Pull request merged**
