### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by UgurAldanmaz**
Fixed typo.

### CODE REVIEW

**Comment by UgurAldanmaz** [comment]
I just updated the readme file which is not executable thing. Even so, appveyor and other continuous integration things checks my changing.

**Comment by 304NotModified** [comment]
Thanks!

Yeah, you van skip AppVeyor with `[skip ci]` in your comments.

**Comment by UgurAldanmaz** [comment]
I learned the magic thanks to you!

**Comment by 304NotModified** [comment]
:) that's part of the job :)

**Pull request merged**
