### PR TITLE
Added support for iOS, Android and WinPhone

### PR DESCRIPTION
**Pull request by stefandevo**
3 new projects added for supporting Xamarin iOS, Xamarin Android and WinPhone8.

### CODE REVIEW

**Comment by 304NotModified** [comment]
@Xharze Can you move the PR to another repo?

**Comment by Xharze** [comment]
@304NotModified Unfortunately this currently cannot be moved to a new repository, this is because a great deal of logic will need to be duplicated between platforms. But I'm working towards supporting individual repositories per platform

**Comment by 304NotModified** [comment]
@Xharze so we can't include this feature for 4.0?

**Comment by Odonno** [comment]
Could we have a preview version of NLog for Xamarin soon ?

**Comment by Xharze** [comment]
It is possible to include just not in a separate repository

**Comment by 304NotModified** [comment]
That would be a good idea

**Comment by 304NotModified** [comment]
To bad no in the 4.0 release due to AppVeyor limitations. We could use some help on this.

**Comment by brainchest** [comment]
Hi, any news on this? I'd be very interested in the Windows Phone 8.1 SL version

**Comment by 304NotModified** [comment]
Hey @brainchest 

Missed your question.  Well we like to work on it,  but need some experience from users who have experience with winphone / xamarin.

**Comment by 304NotModified** [comment]
We like to merge this PR, but we need some advise from experienced users of Xamarin / WinPhone 8. Do you have experience and some time to help? Let us know, so we can fix this PR, merge and release it!

**Comment by polipo** [comment]
Dear,
i need to use Nlog with xamarin Android, i can't found the working sources.
Can some one tell me the right repository ?
Thanks

**Comment by 304NotModified** [comment]
Thanks for this PR @stefandevo . I'm working on this in #1009

**Pull request closed without merging**
