### PR TITLE
CompoundLayout with layout from config variable

### LINKED ISSUE #4936: Use Layout Variables inside Compound Layouts?
In my NLog Config I have a variable to hold my JsonLayout:

```
<variable name="jsonLayoutv0.1">
    <layout type="JsonLayout">
      <attribute name="time" layout="${longdate}" />

    </layout>
  </variable>
```

I then want to place this layout inside a compoundLayout later on in my NLog config without having to re-write the whole jsonLayout again:
```
<sl:layout xsi:type="CompoundLayout">
    <layout xsi:type="SimpleLayout" text="@cee: " />
    <INSERT HERE/>
</sl:layout>
```

How can I go about re-using the variable inside a CompoundLayout?

### PR DESCRIPTION
**Pull request by snakefoot**
Trying to resolve #4936, so you can do this:

```xml
<nlog>
    <variable name='jsonLayoutv0.1'>
        <layout type='JsonLayout'>
          <attribute name='short_date' layout='${shortdate}' />
          <attribute name='message' layout='${message}' />
        </layout>
     </variable>
    <targets>
    <target name='compoundFile' type='File' fileName='log.txt'>
      <layout type='CompoundLayout'>
        <layout type='SimpleLayout' text='|Before| ' />
        <layout type='${jsonLayoutv0.1}' />
        <layout type='SimpleLayout' text=' |After|' />
      </layout>
    </target>
</nlog>
```

### CODE REVIEW

**Comment by 304NotModified** [comment]
I still don't understand the rationale for this syntax: `<layout type='${jsonLayoutv0.1}' />`


It now reads as:


```xml
<nlog>
    <targets>
    <target name='compoundFile' type='File' fileName='log.txt'>
      <layout type='CompoundLayout'>
        <layout type='SimpleLayout' text='|Before| ' />
        <layout type='<layout type='JsonLayout'>
          <attribute name='short_date' layout='${shortdate}' />
          <attribute name='message' layout='${message}' />
        </layout>' />
        <layout type='SimpleLayout' text=' |After|' />
      </layout>
    </target>
</nlog>
```

And now i'm confused!

**Comment by snakefoot** [comment]
Well not confusing to me. NLog config variable defines a type-of-layout, and you can reference this type using `<layout type="XXX" />` just you can reference the type using `layout="XXX"`

**Comment by 304NotModified** [comment]
> It now reads as

Do I need this wrong or is this example not confusing for you?

**Comment by snakefoot** [comment]
If your mind only sees config-variables as pure carbon-copy of raw-text, then you should probably never have changed NLog Config Variables to be of type `Layout`, but always kept them as pure `string`.

But to to me `<layout type="${TypeOfLayout}" />` and `layout="${TypeOfLayout}"` looks identical to me.

**Pull request merged**
