### PR TITLE
NLog - NETSTANDARD1_5

### PR DESCRIPTION
**Pull request by snakefoot**
Just checking if it can make a proper build

### CODE REVIEW

**Comment by 304NotModified** [comment]
looks good!

**Comment by 304NotModified** [comment]
Think we should merge it after resolving the conflict?

I'm doubting about the unit tests.  (enabling for netstandard1.5)

**Comment by snakefoot** [comment]
> I'm doubting about the unit tests. (enabling for netstandard1.5)

Allmost all tests are working after removing all those for features not available (ex. NLogTraceListener). Except the tests that checks current-class-logger for inner-classes where NetStandard1_5 uses "." as last delimiter (instead of "+")

**Comment by 304NotModified** [comment]
> But it will require some effort to force the NetCoreApp2 to load the NetStandard1_5-dll.

run it as NetCoreApp1?

**Comment by 304NotModified** [comment]
afaik this works: https://github.com/NLog/NLog.Web/blob/b5335fe1ad4f0df97e2af1fd761c5cdb2dfe1b76/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj#L3

**Comment by snakefoot** [comment]
> run it as NetCoreApp1?

Well then I have to fix the UnitTest-project to work under NetStandard1_5

**Comment by snakefoot** [comment]
@304NotModified after resolving the conflict?

Conflicts resolved.

**Comment by 304NotModified** [comment]
should the unit tests run in .net standard 1.5, as you have changed the testbase?

**Comment by snakefoot** [comment]
> should the unit tests run in .net standard 1.5, as you have changed the testbase?

I have just made some changes, so it was easier to make local hack of adding NETSTANDARD1_5 to unit-test-project for NetCoreApp2 and removing NetStandard2.0 from Nlog.dll

**Comment by 304NotModified** [comment]
OK thanks! Maybe later. I think we could run the tests on Travis in the future

**Comment by snakefoot** [comment]
@304NotModified Guess you could create an issue about the missing testing of the NetStandard1.5 assembly (Like #1186  and #1184)

**Pull request merged**
