### PR TITLE
Port 4.6.7 to dev

### PR DESCRIPTION
**Pull request by 304NotModified**

### CODE REVIEW

**Comment by 304NotModified** [comment]
@snakefoot please check. There were some not very easy conflicts

# Conflicts:
#	src/NLog/Config/ConfigSectionHandler.cs
#	src/NLog/Config/LoggingConfigurationParser.cs
#	tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs

**Comment by 304NotModified** [comment]
> [xUnit.net 00:00:44.94]     NLog.UnitTests.Filters.APITests.WhenMethodFilterApiTest [FAIL]

Not sure how this is broken

**Comment by snakefoot** [comment]
> @304NotModified please check. There were some not very easy conflicts

The merge looks sensible.

> Not sure how this is broken: WhenMethodFilterApiTest 

Yes that is very strange. Will try and take a look.

**Comment by snakefoot** [comment]
Unit Test `WhenMethodFilterApiTest` is failing because #3359 is in DEV-branch (and not in master-branch).

**Comment by 304NotModified** [comment]
Thanks!! : 💯

**Pull request merged**
