### PR TITLE
Adding OverflowAction options to BufferingTargetWrapper

### PR DESCRIPTION
**Pull request by mikegron**
I stumbled across this discussion: #1712 
It seemed the Overflow action was lost and only the trigger was implemented.
I added the option on the BufferingTargetWrapper to be "lossy", just like log4net's [BufferingAppender](https://logging.apache.org/log4net/release/sdk/html/T_log4net_Appender_BufferingAppenderSkeleton.htm). I used the same property name as the AsyncWrapper to keep it uniform and added a unit test.

Here is our use-case: 
- AutoFlushWrapper that flushes when it receives a LogLevel Error
- BufferingWrapper with OverflowAction = Discard
- File target

With this simple setup, nothing is logged unless an error occurs, and when it does you have a detailed log trace of the latest X (bufferSize) events before the error. Very handy for debugging purposes where you don't want to always log everything!

### CODE REVIEW

**Comment by mikegron** [comment]
For some reason this test failed in AppVeyor: 
`NLog.UnitTests.Targets.ConcurrentFileTargetTests.SimpleConcurrentTest`
Pretty sure it's not related to this pull request though.

**Comment by 304NotModified** [comment]
Thanks! It was an unstable test, works now :)

**Comment by 304NotModified** [comment]
Could you please add some docs to https://github.com/NLog/NLog/wiki/BufferingWrapper-target

Please add "introduced in NLog 4.5". Thanks!

**Comment by mikegron** [comment]
Done! Thanks 👍

**Comment by 304NotModified** [comment]
:+1:

**Comment by 304NotModified** [comment]
Hi, the master has changed a lot (we moved to one sln/csproj for netstandard). Could you please resolve the conflicts? It's correct that the csprojs are removed, so I think this is an easy one to fix.

Thanks!

**Comment by 304NotModified** [comment]
Close/reopen to trigger appveyor

**Comment by 304NotModified** [comment]
merged! Thanks!

**Comment by snakefoot** [comment]
New property `FlushOnConditionOnly` has been added to AutoFlushWrapper in NLog 4.6.6. See also #3513

It ensures that messages are NOT flushed when calling `NLog.LogManager.Flush()` or `NLog.LogManager.Shutdown()`

**Pull request merged**
