### PR TITLE
callsite-filename renderer

### PR DESCRIPTION
**Pull request by brunotag**
Implementing https://github.com/NLog/NLog/issues/2583

### CODE REVIEW

**Comment by brunotag** [comment]
not sure what to do about those two failing SimpleConcurrentTest

**Comment by 304NotModified** [comment]
Thanks! Will try to review soon!

**Comment by 304NotModified** [comment]
Thanks! Could please add some docs to the wiki?

**Comment by brunotag** [comment]
sure will do

**Pull request merged**
