### PR TITLE
MONO_4_0 support

### PR DESCRIPTION
**Pull request by ArsenShnurkov**
I added MONO_4_0 define for packaging with portage package manager

UPD: see also
http://stackoverflow.com/questions/33185770/older-version-of-net-not-installed-with-latest-mono

### CODE REVIEW

**Comment by ie-zero** [comment]
Excuse my ignorance but are there any conditional compilation code blocks which might be affected from this change?

**Comment by ArsenShnurkov** [comment]
Yes, I added 2 configurations for mono 2 and mono 4, and I tested building in both configurations (and also I corrected some conditional preprocessing directives)

**Comment by 304NotModified** [comment]
Thanks for this PR! 

To be consistent, we prefer:

- separate solutions and projects. 
- naming MONO2_0 instead of MONO_2_0

Can you tell me how to change the nuspec for this? As you can see,  mono isn't in nuspec yet.

**Comment by ArsenShnurkov** [comment]
1) You don't have mono-specific dlls, because your proj script doesn't contain line

    <NuGetDir>somedir</NuGetDir>

here:
https://github.com/NLog/NLog/blob/master/src/NLog.proj#L107-L108

the problem is that there should be no such thing as "mono specific", because they should be byte by byte the same as .net version dlls. You can install it into <NuGetDir>mono2</NuGetDir> and <NuGetDir>mono4</NuGetDir>. But why on the earth mono projects should use these libraries instead of libraries for their required frameworks (i.e. lib/net35, lib/net45) ?

And this is your problem, not mine. Because I don't use NLog.proj file at all. I have portage bash script which builds my package from my separate nuspec (I build my version of nupkg with lib/net45/NLib.dll inside)

2) you have a wrong name of project

https://github.com/NLog/NLog/blob/master/src/NLog/NLog.mono.csproj

but it should be NLog.mono2.csproj to be used in 

    <MSBuild Projects="NLog\NLog%(TargetFramework.ProjectFileSuffix).csproj" 
             Targets="Build" 
             Properties="$(StyleCopProperties);%(TargetFramework.Properties);BaseOutputDirectory=$(BaseOutputDirectory);BuildInfoFile=$(BuildInfoFile)" 
             ToolsVersion="%(TargetFramework.ToolsVersion)" 
             ContinueOnError="$(IgnoreBuildFailures)" 
             StopOnFirstFailure="false" />

https://github.com/NLog/NLog/blob/master/src/NLog.proj#L176

**Comment by 304NotModified** [comment]
Thanks for the comprehensive response!

1+2) Yes, the .proj isn't good for Mono, but that has probably a cause.
We are already using sometimes platform detection (https://github.com/NLog/NLog/blob/master/src/NLog/Internal/PlatformDetector.cs), but that's bad and cannot be used in PCL nor CoreCLR

3) You're right! Sorry for the mistake.

----

The key question is, if MONO uses the .Net dll's, then we can:

A) Make a separate nuget package for mono (has seen that before)
B) Ask people to build their own binaries (for mono)
C) Download the Mono binaries from somewhere else (not nuget)
D) Fix the code so it uses dynamic recognition of platform, instead of conditional compilation symbols eg`#if MONO_2_0`
E) Don't care and hope for the best (current approach, I'm afraid)

At least, the usage of conditional compilation symbols are questionable. The up-side, we can build it with mono and knows that it works (mostly).

But now I dunno what to do with `#if MONO_4_0`. With the current approach, if won't gain a lot? 

Also, it's not clear to mean what the benefit is besides the current MONO_2. What are the features what aren't supported inn MONO2?

**Comment by ArsenShnurkov** [comment]
Unfortunately I don't have xbuild on my linux yet, because of https://github.com/xunit/xunit/issues/548

So, I disabled build of tests in .sln file.
this lead to

  error: file not found: ./build/bin/Release/Mono 2.x/NLog.UnitTests.dll

and following

The command "mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe "./build/bin/Release/Mono 2.x/NLog.UnitTests.dll"" exited with 255.

Actually, I am working on issue https://github.com/gentoo/dotnet/issues/115
and NLog is just one of dependencies. So I see this project for the first time and need your help with this PR (because on my machnine everything works, and i don't have windows to build .proj and don't need tests).

Now I am going to reenable test projects in .sln files, and disable them locally with my portage patch

**Comment by ArsenShnurkov** [comment]
Mono.targets was broken (because it can't work on linux in principle)

1) this line gives an exception:

    <MonoDefaultClr>$(Registry:HKEY_LOCAL_MACHINE\SOFTWARE\Novell\Mono@DefaultCLR)</MonoDefaultClr>

https://github.com/NLog/NLog/blob/fb44621c71b1e159050ab95dcb365778745fc3be/src/Mono.targets#L4

the text of exception is

    /home/travis/build/NLog/NLog/tests/NLog.UnitTests/NLog.UnitTests.mono2.csproj: error : /home/travis/build/NLog/NLog/tests/NLog.UnitTests/NLog.UnitTests.mono2.csproj: Registry function
     3 Warning(s)
     1 Error(s)

and it is it's source:
https://github.com/mono/mono/blob/9a9e721cd85568cf4a5ae7ac22c7f12fea97be80/mcs/class/Microsoft.Build.Engine/Microsoft.Build.BuildEngine/Expression.cs#L345-L351

2) there is no .bat files on linux, they are .sh or without extension:

        <MonoCommandLine>"$(MonoInstallLocation)\bin\gmcs.bat"</MonoCommandLine>

https://github.com/NLog/NLog/blob/fb44621c71b1e159050ab95dcb365778745fc3be/src/Mono.targets#L39

Mono.targets was used in 
https://github.com/NLog/NLog/blob/0f3f34f62b899b2d41b1d2a6aae4836cd442c4af/tests/NLog.UnitTests/NLog.UnitTests.mono2.csproj#L158

This file was not tested in CI builds.

For now I have no opinion what to do with it...

**Comment by ArsenShnurkov** [comment]
NLog.UnitTests.LogFactoryTests.Auto_Reload_invalidxml_test [FAIL]
       System.Exception : failed to reload - 2
       Stack Trace:
         at NLog.UnitTests.LogFactoryTests.Auto_Reload_invalidxml_test () [0x00000] in <filename unknown>:0 
         at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
         at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0
    Tests complete: 491 of 703
    No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
    The build has been terminated

**Comment by ArsenShnurkov** [comment]
my local version of mono is exactly
Mono JIT compiler version 4.2.0 (Stable 4.2.0.179/a224653 Wed Sep 16 20:09:53 MSK 2015)

**Comment by 304NotModified** [comment]
@ArsenShnurkov I have no idea what to do with this PR. I can merge it (after resolve conflicts), but it's useless if we don't release it somewhere (nuget?)

So need you opinion on that. Also I was wondering, why can't we use Mono2 and that should also work on mono4?

**Comment by ArsenShnurkov** [comment]
"it's useless if we don't release it somewhere"

it is usefull in linux distributions, which builds software from sources (i.e. portage and paludis-based distributions, such as Gentoo)

"I was wondering, why can't we use Mono2 and that should also work on mono4"

Mono4 introduces breaking changes, and old programs will not compile anymore (binaries would run, but it's different story)

**Comment by 304NotModified** [comment]
OK, thanks for the answers. 

Can you check the conflicts?

**Comment by ArsenShnurkov** [comment]
It builds. It's the unit tests what fails.
    NLog.UnitTests.SourceCodeTests.VerifyProjectsInSync [FAIL]
in particular.

**Comment by 304NotModified** [comment]
Well it has a conflict now :(

image

Can you rebase?

You can fix VerifyProjectsInSync  with 

```
NLog\src>msbuild NLog.proj /t:SyncProjectItems

```

See https://github.com/NLog/NLog/blob/master/CONTRIBUTING.md

**Comment by 304NotModified** [comment]
PS: probably merging https://github.com/NLog/NLog/pull/1009 will also create conflicts. But I need some things to fix at https://github.com/NLog/NLog/pull/1009

**Comment by 304NotModified** [comment]
I like to merge this for 4.3 (first waiting for 4.2.1 release) . Do you need help on fixing the last things?

**Comment by ArsenShnurkov** [comment]
i have no enough physical resources now (i.e. money). may be later. sorry

**Comment by 304NotModified** [comment]
If you reopen this PR and add me as collaborator, I will fix these last things (iff you can answer some questions if i'm lost)

**Comment by 304NotModified** [comment]
We don't need this anymore with netstandard :)

**Pull request closed without merging**
