### PR TITLE
Improve warning in VariableLayoutRenderer

### PR DESCRIPTION
**Pull request by 304NotModified**

### CODE REVIEW

**Comment by 304NotModified** [comment]
@snakefoot. Ok with this?

**Comment by snakefoot** [comment]
Looks better. Would prefer not to have the warning at all.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


@snakefoot<https://github.com/snakefoot>. Ok with this?

**Comment by 304NotModified** [comment]
Agree on that!

**Comment by snakefoot** [comment]
The PR #4240 removes the need for any warning

**Pull request merged**
