### PR TITLE
AsyncTaskTarget_TestThrottleOnTaskDelay - More logging and increase treshold

### LINKED ISSUE #3277: Unstable test NLog.UnitTests.Targets.AsyncTaskTargetTest.AsyncTaskTarget_TestThrottleOnTaskDelay
See https://ci.appveyor.com/project/nlog/nlog/builds/23611460

### PR DESCRIPTION
**Pull request by snakefoot**
Trying to resolve #3277

### CODE REVIEW

**Comment by 304NotModified** [comment]
thanks! Would be great to get the build more stable. Restarting is now almost a daily task..

**Comment by 304NotModified** [comment]
would another option to call FlushAsync and use the AsyncContinuation.WaitOne?

**Comment by snakefoot** [comment]
The test ensures that the target performs correctly without doing explicit flushes.

**Comment by 304NotModified** [comment]
ok good one :)

**Pull request merged**
