### PR TITLE
Replaced netcoreapp2.1 with netcoreapp3.1 to fix obsolete test warnings

### PR DESCRIPTION
**Pull request by snakefoot**

### CODE REVIEW

**Comment by snakefoot** [comment]
Funny how xunit suddenly triggers warnings when updating to `netcoreapp3.1`. Guess it needs more time to cook.

**Comment by 304NotModified** [comment]
From the build log:

```
The given project `NLog` has no vulnerable packages given the current sources.
Project `NLog.UnitTests` has the following vulnerable packages
   [netcoreapp3.1]: 
   Transitive Package      Resolved   Severity   Advisory URL                                     
   > System.Net.Http       4.3.0      High       https://github.com/advisories/GHSA-7jgj-8wvc-jh57
   [net461]: No vulnerable packages for this framework.
The given project `SampleExtensions` has no vulnerable packages given the current sources.
The given project `NLogAutoLoadExtension` has no vulnerable packages given the current sources.
The given project `NLog.MSMQ` has no vulnerable packages given the current sources.
The given project `NLog.WindowsIdentity` has no vulnerable packages given the current sources.
The given project `NLog.Wcf` has no vulnerable packages given the current sources.
The given project `NLog.WindowsEventLog` has no vulnerable packages given the current sources.
The given project `PackageLoaderTestAssembly` has no vulnerable packages given the current sources.
The given project `ManuallyLoadedExtension` has no vulnerable packages given the current sources.
The given project `NLog.MSMQ.Tests` has no vulnerable packages given the current sources.
Project `NLog.Wcf.Tests` has the following vulnerable packages
   [netcoreapp3.1]: 
   Transitive Package                    Resolved   Severity   Advisory URL                                     
   > System.Net.Http                     4.3.0      High       https://github.com/advisories/GHSA-7jgj-8wvc-jh57
   > System.Text.RegularExpressions      4.3.0      Moderate   https://github.com/advisories/GHSA-cmhx-cq75-c4mj
   [net452]: No vulnerable packages for this framework.
   [net461]: No vulnerable packages for this framework.
Project `NLog.WindowsIdentity.Tests` has the following vulnerable packages
   [netcoreapp3.1]: 
   Transitive Package                    Resolved   Severity   Advisory URL                                     
   > System.Net.Http                     4.3.0      High       https://github.com/advisories/GHSA-7jgj-8wvc-jh57
   > System.Text.RegularExpressions      4.3.0      Moderate   https://github.com/advisories/GHSA-cmhx-cq75-c4mj
   [net452]: No vulnerable packages for this framework.
   [net461]: No vulnerable packages for this framework.
The given project `NLog.PerformanceCounter` has no vulnerable packages given the current sources.
Project `NLog.PerformanceCounter.Tests` has the following vulnerable packages
   [netcoreapp3.1]: 
   Transitive Package                    Resolved   Severity   Advisory URL                                     
   > System.Net.Http                     4.3.0      High       https://github.com/advisories/GHSA-7jgj-8wvc-jh57
   > System.Text.RegularExpressions      4.3.0      Moderate   https://github.com/advisories/GHSA-cmhx-cq75-c4mj
   [net452]: No vulnerable packages for this framework.
   [net461]: No vulnerable packages for this framework.
The given project `NLog.WindowsRegistry` has no vulnerable packages given the current sources.
Project `NLog.WindowsRegistry.Tests` has the following vulnerable packages
   [netcoreapp3.1]: 
   Transitive Package                    Resolved   Severity   Advisory URL                                     
   > System.Net.Http                     4.3.0      High       https://github.com/advisories/GHSA-7jgj-8wvc-jh57
   > System.Text.RegularExpressions      4.3.0      Moderate   https://github.com/advisories/GHSA-cmhx-cq75-c4mj
   [net452]: No vulnerable packages for this framework.
   [net461]: No vulnerable packages for this framework.
The given project `NLog.OutputDebugString` has no vulnerable packages given the current sources.
The given project `NLog.Database` has no vulnerable packages given the current sources.
Project `NLog.Database.Tests` has the following vulnerable packages
   [netcoreapp3.1]: 
   Transitive Package                    Resolved   Severity   Advisory URL                                     
   > System.Net.Http                     4.3.0      High       https://github.com/advisories/GHSA-7jgj-8wvc-jh57
   > System.Text.RegularExpressions      4.3.0      Moderate   https://github.com/advisories/GHSA-cmhx-cq75-c4mj
   [net462]: No vulnerable packages for this framework.
```

**Comment by 304NotModified** [comment]
I'm confused. When building NLog.Wcf.Tests for .NET Core 3.1 I get:

NLog.Wcf.Tests.deps.json

But I build NLog.Wcf.Tests for .NET Core 2.1 I *wont* get the NLog.Wcf.Tests.deps.json.


Anyway in NLog.Wcf.Tests.deps.json I see:

```json
      "NETStandard.Library/1.6.1": {
        "dependencies": {
          "Microsoft.NETCore.Platforms": "2.1.0",
           ....
          "System.Net.Http": "4.3.0",

```

So we need to manually bump System.Net.Http

**Comment by 304NotModified** [comment]
--> try here: https://github.com/NLog/NLog/pull/4946

**Comment by snakefoot** [comment]
> But I build NLog.Wcf.Tests for .NET Core 2.1 I wont get the NLog.Wcf.Tests.deps.json.

That explains why  .NET Core 2.1 doesn't produce the warnings, because it doesn't generate the output-file necessary to validate it.

Anyway I'm fine with leaving it as it, until xunit v2 is fixed, or xunit v3 is released.

**Pull request merged**
