### PR TITLE
DatabaseTarget - Enable OptimizeBufferReuse by default

### PR DESCRIPTION
**Pull request by snakefoot**
Waiting for NLog ver. 4.5

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1908)

### CODE REVIEW

**Comment by 304NotModified** [comment]
> NLog.UnitTests.Targets.Wrappers.BufferingTargetWrapperTests.BufferingTargetWrapperAsyncTest1 [FAIL]
   Assert.Equal() Failure
   Expected: 19
   Actual:   18
   Stack Trace:
     at NLog.UnitTests.Targets.Wrappers.BufferingTargetWrapperTests.BufferingTargetWrapperAsyncTest1 () [0x001e6] in <50fe24b3f1d14d7092cf9b8d5f6ecaaa>:0 
     at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
     at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0
1922 total, 1 failed, 21 skipped, took 50.686 seconds

Seems a fail from a recent change. Is that possible?

**Comment by 304NotModified** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/NLog/Targets/DatabaseTarget.cs, line 93 at r1](https://reviewable.io:443/reviews/nlog/nlog/1908#-KaOdXZ8iGp5X9BqmJHG:-KaOdXZ8iGp5X9BqmJHH:b-olgybg) ([raw file](https://github.com/nlog/nlog/blob/6befca702e35cd218d4e3ab47b3b574b3f21b79d/src/NLog/Targets/DatabaseTarget.cs#L93)):*
> ```Smalltalk
>             this.ConnectionStringsSettings = ConfigurationManager.ConnectionStrings;
>             this.CommandType = CommandType.Text;
>             this.OptimizeBufferReuse = GetType() == typeof(DatabaseTarget);
> ```

what's the use of this? Not enabling in subclasses? 

---

*[src/NLog/Targets/DatabaseTarget.cs, line 662 at r1](https://reviewable.io:443/reviews/nlog/nlog/1908#-KaOdkMQtiJFhvl176NM:-KaOdkMQtiJFhvl176NN:bbmaxfq) ([raw file](https://github.com/nlog/nlog/blob/6befca702e35cd218d4e3ab47b3b574b3f21b79d/src/NLog/Targets/DatabaseTarget.cs#L662)):*
> ```Smalltalk
>                     this.EnsureConnectionOpen(cs);
> 
>                     using (var command = this.activeConnection.CreateCommand())
> ```

behavior change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1908)*

**Comment by snakefoot** [comment]
> Seems a fail from a recent change. Is that possible?

Looks more like a bad unit test. There is no guarantee that the write-events will complete before the flush-event as MyAsyncTarget is using ThreadPool.QueueUserWorkItem.

So the the flushHit-event can be triggered before everything is written, thus causing the problem with expecting 19 but only 18 written. 

Maybe MyAsyncTarget should apply the newly created AsyncOperationCounter :). Like it has been done in AsyncTargetWrapperTests.cs

**Comment by snakefoot** [comment]
*[src/NLog/Targets/DatabaseTarget.cs, line 93 at r1](https://reviewable.io:443/reviews/nlog/nlog/1908#-KaOdXZ8iGp5X9BqmJHG:-KaOhMAH5-3WXGzzg5Um:b-yxu1tm) ([raw file](https://github.com/nlog/nlog/blob/6befca702e35cd218d4e3ab47b3b574b3f21b79d/src/NLog/Targets/DatabaseTarget.cs#L93)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

what's the use of this? Not enabling in subclasses? 
</blockquote></details>

Yes just like I have done in FileTarget.cs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1908)*

**Comment by snakefoot** [comment]
*[src/NLog/Targets/DatabaseTarget.cs, line 662 at r1](https://reviewable.io:443/reviews/nlog/nlog/1908#-KaOdkMQtiJFhvl176NM:-KaOhPvZ3aWvFH7eBai0:b-13vry9) ([raw file](https://github.com/nlog/nlog/blob/6befca702e35cd218d4e3ab47b3b574b3f21b79d/src/NLog/Targets/DatabaseTarget.cs#L662)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary><blockquote>

behavior change?
</blockquote></details>

I like to dispose stuff, when I'm done with it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1908)*

**Comment by snakefoot** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1908#-:-Kasv5VKmxxkbZlVtYYa:bnfp4nl)*

**Comment by 304NotModified** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1908)*

**Comment by snakefoot** [comment]
@304NotModified Updated documentation: https://github.com/NLog/NLog/wiki/Database-target

**Pull request merged**
