### PR TITLE
LogFactory - LoadConfiguration with better support for relative paths

### PR DESCRIPTION
**Pull request by snakefoot**
Also check Entry-Assembly-Path if different from AppDomain.BaseDirectory.

### CODE REVIEW

**Comment by 304NotModified** [comment]
Added some tests, still WIP

**Comment by 304NotModified** [comment]
sorry that I broke the unit test on travis. Need to fix that

**Comment by 304NotModified** [comment]
@snakefoot I think I fixed the tests. Could you please check the conflict? The conflict is a bit too hard to fix for me.

**Comment by 304NotModified** [comment]
@snakefoot could you help me with resolving the conflicts? AFAIK you wrote both changes ;)

In logfactory, unclear to me how to integrate both
image

**Comment by snakefoot** [comment]
> could you help me with resolving the conflicts? AFAIK you wrote both changes ;)

Well all the conflicts comes from you doing the dependency injection interface :)

**Comment by 304NotModified** [comment]
> Well all the conflicts comes from you doing the dependency injection interface :)

👼

**Pull request merged**
