### PR TITLE
Fix FileNotFoundException when loading extension DLLs. 

### LINKED ISSUE #2120: .NET Core: auto load fails
Problem seems to be tied to linux (Debian 8), Windows (2012R2) does not exhibit this behavior.

**Type** :

- Bug

**NLog version**:

- NLog 5.0.0-beta07
- NLog.Web.AspNetCore 4.4.0

**Platform**: 

- .NET Core 1.1

**Current NLog config**

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogFile="/home/wsnotif/logs/sci-internal-nlog.log" internalLogLevel="Debug">

  <extensions>
    <!--<add assembly="NLog.Web.AspNetCore"/>-->
    <add assembly="Notification.Template.Logging"/>
  </extensions>

  <!-- the targets to write to -->
  <targets>
	<target xsi:type="File" name="infofile" fileName="/home/wsnotif/logs/notif_template_sci.log"
            layout="${date:format=yyyy-MM-dd HH\:mm\:ss.fff} ${uppercase:${level}} : ${message} ${exception:format=tostring}"
            archiveFileName="/home/wsnotif/logs/archive/WSNotif_Main-${shortdate}.{####}.log"
            archiveAboveSize="209715200"
            archiveEvery="Day"
            archiveNumbering = "Sequence"
            maxArchiveFiles="2"
            concurrentWrites="false"
                    />
    <!-- write to the void aka just remove -->
    <target xsi:type="Null" name="blackhole" />
  </targets>

  <!-- rules to map from logger name to target -->
  <rules>
    <!--Skip Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" minlevel="Info" writeTo="blackhole" final="true" />

    <!--All logs, including from Microsoft-->
    <logger name="*" minlevel="Debug" writeTo="infofile" />
  </rules>
</nlog>
```

**What is the current result?**

internal logging :
```
2017-05-18 15:20:40.1439 Info Loading assembly: Notification.Template.Logging
2017-05-18 15:20:40.1978 Debug ScanAssembly('NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2017-05-18 15:20:40.3452 Debug Start auto loading, location: /home/wsnotif/sci-instance
2017-05-18 15:20:40.3482 Info Auto loading assembly file: /home/wsnotif/sci-instance/NLog.Web.AspNetCore.dll
2017-05-18 15:20:40.3482 Info Loading assembly file: /home/wsnotif/sci-instance/NLog.Web.AspNetCore.dll
2017-05-18 15:20:40.3482 Warn Auto loading assembly file: /home/wsnotif/sci-instance/NLog.Web.AspNetCore.dll failed! Skipping this file. Exception: System.IO.FileLoadException: Could not load file or assembly 'NLog.Web.AspNetCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at NLog.Config.ConfigurationItemFactory.BuildDefaultFactory()
2017-05-18 15:20:40.4597 Info Auto loading assembly file: /home/wsnotif/sci-instance/NLog.Extensions.Logging.dll
2017-05-18 15:20:40.4597 Info Loading assembly file: /home/wsnotif/sci-instance/NLog.Extensions.Logging.dll
2017-05-18 15:20:40.4597 Warn Auto loading assembly file: /home/wsnotif/sci-instance/NLog.Extensions.Logging.dll failed! Skipping this file. Exception: System.IO.FileLoadException: Could not load file or assembly 'NLog.Extensions.Logging, Version=1.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at NLog.Config.ConfigurationItemFactory.BuildDefaultFactory()
2017-05-18 15:20:40.4597 Debug Auto loading done
```

- What is the expected result?

No warning and `NLog.Extensions.Logging.dll` should be excluded from auto loading.

- Is there a version in which it did worked? 

Beta5 didn't display these warnings, but i didn't test thoroughly if it really worked.

### PR DESCRIPTION
**Pull request by snakefoot**
First try AssemblyLoadContext.GetAssemblyName. Fixes #2120 and #2143

### CODE REVIEW

**Comment by 304NotModified** [comment]
Are you sure this works? I think the issue is that nlog.web is trying to load nlog, and that crashes (wrong version, wrong evidence, dunno)

**Comment by snakefoot** [comment]
It worked for me, as I also got the exception in the simple test application I made for fun in:

https://github.com/graffen/NLog.Targets.Syslog/pull/94

The funny part is that even when getting the exception, then it still works. But with the modified code, then you don't get the exception, and it also works.

**Comment by 304NotModified** [comment]
could we also confirm #1091 ?

**Comment by snakefoot** [comment]
> could we also confirm #1091 ?

You are welcome to try it out. The code-change is very small, so just compile and test.

**Comment by 304NotModified** [comment]
> You are welcome to try it out. The code-change is very small, so just compile and test.

Will do that if beta8 is out, a bit less hassle.

**Pull request merged**
