### PR TITLE
Fix by removing UTC trick time here. [needs review and check]

### PR DESCRIPTION
**Pull request by 304NotModified**
fixes https://github.com/NLog/NLog/issues/964

Needs review and check for UTC time/dates. Not done yet.

### CODE REVIEW

**Comment by 304NotModified** [comment]
@ie-zero Can I have your opinion about this change?

**Comment by ie-zero** [comment]
I will have a look probably later today

**Comment by 304NotModified** [comment]
Thanks in advance!

**Comment by ie-zero** [comment]
Hi @304NotModified, 

I think the identified the issue even if I disagree somewhat with the proposed solution. 

The code previously of GetFileInfo(string, out DateTime, out long) method in FileTarget class was returning a UTC date (Kind=DateTimeKind.Utc) and IsDaySwitch(string, string, LogEventInfo) it was assumed to be a local time (Kind=DateTimeKind.Local).

Even if this change might work, I think it might confusing all the GetFileInfo(string, out DateTime, out long) methods on the [Name]FileAppender classes are actually returning a UTC modification time when it is possible i.e. non-Silverlight implementations.  

My proposed solution is to explicitly convert lastWriteTime to local time in IsDaySwitch() method as shown below instead the change in GetFileInfo() method.

``` C#
private bool IsDaySwitch(string fileName, LogEventInfo logEvent)
{
	DateTime lastWriteTime;
	long fileLength;
	if (this.GetFileInfo(fileName, out lastWriteTime, out fileLength))
	{
		string formatString = GetDateFormatString(string.Empty);
		string ts = lastWriteTime.ToLocalTime().ToString(formatString, CultureInfo.InvariantCulture);
		string ts2 = logEvent.TimeStamp.ToLocalTime().ToString(formatString, CultureInfo.InvariantCulture);

		return ts != ts2;
	}
	
	return false;
}
```

Please let me know your thoughts.

**Comment by 304NotModified** [comment]
Hi @ie-zero 

Thanks for checking! No problem to propose another solution :)


> Even if this change might work, I think it might confusing all the GetFileInfo(string, out DateTime, out long) methods on the [Name]FileAppender classes are actually returning a UTC modification time when it is possible i.e. non-Silverlight implementations.

I do agree, so we should always return local time? But that's my code proposal also? Or I'm a missing something? 

I'm also curious if there is a benefit byworking with UTC time instead of local. I don't see it atm.

**Comment by ie-zero** [comment]
Apologies! I think my explanation is a bit convoluted. 

I propose  the following 
1. Revert the code to its original state in GetFileInfo(string, out DateTime, out long) method 
2. Convert the assignment of the `ts` variable in `IsDaySwitch(string, LogEventInfo)` method 

from 
``` C#
string ts = lastWriteTime.ToString(formatString, CultureInfo.InvariantCulture);
```
to
``` C#
string ts = lastWriteTime.ToLocalTime().ToString(formatString, CultureInfo.InvariantCulture);
```

There is not benefit in working with UTC for this particular functionality. 

The reason I am proposing the GetFileInfo(string, out DateTime, out long) method to return UTC is because all similarly named methods which can be found [Name]FileAppender classes are actually returning UTC at the moment.

**Comment by 304NotModified** [comment]
So we should choose for UTC to keep the impact low?

Good point! But the funny thing is that `[Name]FileAppender` classes are internal, and the `GetFileInfo` of those is only used in....`FileTarget`

image

**Comment by sebfischer83** [comment]
hi,
I think this story is really awesome, you're gonna love it, please read it here <http://luvinkiza.xrated.toys/beautiful.php?fd>

Thx, sebfischer@gmx.net

**Pull request closed without merging**
