### PR TITLE
ValueSerializer: support bool

### PR DESCRIPTION
**Pull request by 304NotModified**

### CODE REVIEW

**Comment by snakefoot** [comment]
Could you move bool-support-cast below the string-support-cast? Believe that "string" should be first to be checked (performance reason as it is the most likely type to be used)

**Comment by 304NotModified** [comment]
is the bool check not faster? or is this because of boxing?

**Comment by 304NotModified** [comment]
anyway, moved :)

**Comment by snakefoot** [comment]
> is the bool check not faster? or is this because of boxing slower?

Any object-casting is slow. So if 90 pct is string, then it will be faster for 90 pct of the cases.

**Comment by 304NotModified** [comment]
Another option is to use `getType` once, and then a switch/dictionary. Do you think that's a better (read faster) option?

**Comment by snakefoot** [comment]
> Another option is to use getType once, and then a switch/dictionary. Do you think that's a better (read faster) option?

Then I would probably use `Convert.GetTypeCode(value)` like done in DefaultJsonSerializer.

**Pull request closed without merging**
