### PR TITLE
Feature/rename message template format method attribute to resharper like

### PR DESCRIPTION
**Pull request by imanushin**
**Important:** ignore this PR until #2974 will be merged.

Question: are you ok with attribute replacing? Please note, that old attribute was removed, however I put new in the each line.

After change:
image

Before change:
image

### CODE REVIEW

**Comment by 304NotModified** [comment]
> Question: are you ok with attribute replacing? Please note, that old attribute was removed, however I put new in the each line.

Do you mean `MessageTemplateFormatMethod("format")]` ->	        `[StringFormatMethod("format")]
`

unfortunately, that won't work well with the message templates.

**Comment by imanushin** [comment]
> unfortunately, that won't work well with the message templates.

Why? I can add attribute ```[StringFormatMethod("format")]``` for each method with ```[MessageTemplateFormatMethod("format")]```. The result will be the same with on my screenshots.

So questions:
1. Do we want to have pretty suggestions by ReSharper (as on screenshots)?
2. If yes: are you ok with attributes duplicating?
3. If "3"'s answer is "no" - do you have any suggestions, how to achieve this goal?

**Comment by 304NotModified** [comment]
> Why? I can add attribute `[StringFormatMethod("format")]` for each method with `[MessageTemplateFormatMethod("format")]`. The result will be the same with on my screenshots.

You get then "false positives" from Resharper?

**Comment by 304NotModified** [comment]
e.g. this:

image


when using ` [StringFormatMethod("message")]`

**Comment by imanushin** [comment]
@304NotModified , I see, I agree. Will reject

**Pull request closed without merging**
