### PR TITLE
Added ${currentDir}

### PR DESCRIPTION
**Pull request by UgurAldanmaz**
I've implemetend the CurrentDirLayoutRenderer which was requested in #2190. 

I cannot remember what we do for adding new files to the .csproj file. Cannot find any info at the contributing document. Please guide me if I've missed anything.

### CODE REVIEW

**Comment by 304NotModified** [comment]
> I cannot remember what we do for adding new files to the .csproj file. Cannot find any info at the contributing document. Please guide me if I've missed anything.

Since VS2017, there is no need to list all the files in the csproj :)
Also there is now 1 sln/csproj for all platforms.  So nothing to do here :)

Thx for contributing. I'm a bit busy these weeks, will try to review it soon!

**Comment by snakefoot** [comment]
@UgurAldanmaz Maybe it should be called "startupdir" instead of "currentdir" ?

**Comment by 304NotModified** [comment]
Where is the cache?

**Comment by snakefoot** [comment]
It is a member variable



Sent from my Samsung device


-------- Original message --------

**Comment by UgurAldanmaz** [comment]
> Since VS2017, there is no need to list all the files in the csproj :)
> Also there is now 1 sln/csproj for all platforms. So nothing to do here :)

Nice 👍 

> @UgurAldanmaz Maybe it should be called "startupdir" instead of "currentdir" ? (Since the layout renderer caches the currentdir as startupdir).

Yes, currentdir looks confusing. My suggestion is `appdir` as its documentation [says](https://msdn.microsoft.com/library/system.io.directory.getcurrentdirectory)

> Gets the current working directory of the application.

Thoughts?

**Comment by 304NotModified** [comment]
> It is a member variable

ow yes indeed. I think that's not needed. If someone likes to cache it, it should use `${currentDir:cache=true}`

@UgurAldanmaz  could you please remove the "cache"?

**Comment by UgurAldanmaz** [comment]
I've removed, tx!

**Comment by 304NotModified** [comment]
thx! Looks good! Some unit tests are a bit unstable, will restart Travis

**Comment by 304NotModified** [comment]
strange... `SimpleFileDeleteTest` fails every time on Travis? Restarted it multiple times, not an issue in other PRS

**Comment by 304NotModified** [comment]
merged! Thanks!

**Comment by 304NotModified** [comment]
Could you please create a wiki page? Thanks!

**Comment by UgurAldanmaz** [comment]
> Could you please create a wiki page? Thanks!

Of course, it is [here](https://github.com/NLog/NLog/wiki/CurrentDir-Layout-Renderer)

**Comment by 304NotModified** [comment]
thx @UgurAldanmaz !!

**Pull request merged**
