### PR TITLE
Set the service contract for LogReceiverTarget as one way

### PR DESCRIPTION
**Pull request by MartinTherriault**
Changed the service contract for the LogReceiverTarget to be one way. This will allow the messages to be multicast through a WCF routing service.

See issue #561 for more details.

### CODE REVIEW

**Comment by Xharze** [comment]
Thanks for the pull request. Will this change be breaking?

**Comment by MartinTherriault** [comment]
Yes you are right. I don't know what I was thinking. I will make some changes to allow the selection of the service contract through an optional property of the LogReceiverTarget, with the default value being the current two-way contract. This way it will be non breaking and will support the feature I need for multicast.

**Comment by Xharze** [comment]
Thanks for the pull request, it looks good.

**Comment by 304NotModified** [comment]
Is #106 related?

**Comment by MartinTherriault** [comment]
Yes #106 is about the same thing (IsOneWay property) in a different usage scenario (MSMQ). The changes I made should allow it to works with MSMQ when the new property of the target is set.

**Comment by 304NotModified** [comment]
Thanks @MartinTherriault

**Pull request merged**
