### PR TITLE
allow different separator for Exception.Data

### PR DESCRIPTION
**Pull request by FroggieFrog**
this should fix issue #1625

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1628)

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks for the PR but we need a fully backwards solution & unit tests. 

Fully backwards could be arranged by:
1. adding a new separator property
2. or adding a new boolean property 

I think 1 is the best, what do you think?

**Comment by 304NotModified** [comment]
@FroggieFrog your opinion please :)

**Comment by FroggieFrog** [comment]
I added a new property and tried to add good unit tests.
One test is failing, but I don't know how to fix it. Maybe you can fix this?

**Comment by 304NotModified** [comment]
OK I will check it!

**Comment by 304NotModified** [comment]
You should use `\n` for newline and not `${newline}`. You can only use `${}` renderers if the type is `Layout`. We could make the property `Layout`, but that isn't consistent with Separator property and changing that one in not backwards-compatible.

Also, I think the name `SeparatorData` should be changed, as it sounds as "data for separator".

**Comment by FroggieFrog** [comment]
I hope now everything is OK.

**Comment by 304NotModified** [comment]
\0/

**Comment by 304NotModified** [comment]
added to docs: https://github.com/NLog/NLog/wiki/Exception-layout-renderer

**Comment by 304NotModified** [comment]
NLog 4.3.9 is live! https://www.nuget.org/packages/NLog/4.3.9

**Pull request merged**
