### PR TITLE
Log4JXmlEventLayout code improvements

### PR DESCRIPTION
**Pull request by nikola02333**
ILog4JXmlEvent common interface for Log4JXmlEventLayout and Log4JXmlEventLayoutRenderer

### CODE REVIEW

**Comment by 304NotModified** [comment]
a yes, I was also thinking it's a good improvement, I was working in https://github.com/NLog/NLog/pull/2117

**Comment by nikola02333** [comment]
@304NotModified  Can you tell me why AppVeyor build failed , The Travis CI build failed  and how to fix it ?

**Comment by 304NotModified** [comment]
Dunno, but I have included your changes in https://github.com/NLog/NLog/pull/2117 and that one should working on the CI servers.

**Comment by 304NotModified** [comment]
Hi,

Thanks for this PR. While this PR is not merged, it helped us in finishing this task. (see https://github.com/NLog/NLog/pull/2117) So thanks!

**Pull request closed without merging**
