### PR TITLE
add final param to `AddRule` Methods

### PR DESCRIPTION
**Pull request by 893949088**
add final param by AddRule Method

### CODE REVIEW

**Comment by snakefoot** [comment]
This is a breaking change. You have to make new methods, instead of adding parameter to existing ones.

**Comment by 893949088** [comment]
@snakefoot I don‘t want to configure nlog by xml file.I want configure nlog by LoggingConfiguration.but the AddRule method don't has 'final' param. why this is a breaking change?

**Comment by snakefoot** [comment]
> why this is a breaking change?

Your code-change requires a complete recompile of all source-code using NLog, or else they will get a MIssingMethodException:

Ex. This method is suddenly gone:

`public void AddRuleForOneLevel(LogLevel level, Target target, string loggerNamePattern)`

Instead there is this method, but it has a different signature:

`public void AddRuleForOneLevel(LogLevel level, Target target, string loggerNamePattern, bool final = false)`

**Comment by 893949088** [comment]
@snakefoot  So, Should I open a new issue??

**Comment by snakefoot** [comment]
@893949088 You can just add more commits to the same PR. They will be squashed into a single commit before merge.

**Comment by 893949088** [comment]
@snakefoot But I don't have more change to commit.    ╯﹏╰ !!

**Comment by snakefoot** [comment]
@893949088 If you want in included within the next year, then you need to fix the breaking change. Else it will be postponed until like forever.

**Comment by 893949088** [comment]
@snakefoot  I'm very sad. why is the 'LoggingConfiguration' imperfect？

**Comment by snakefoot** [comment]
> why is the 'LoggingConfiguration' imperfect？

Because of the breaking change you have introduced, by changing the signature of the existing methods.

**Comment by 893949088** [comment]
@snakefoot How can I do it to  fix the breaking change？I haven't submit PR before.
^_^"

**Comment by snakefoot** [comment]
@893949088 The breaking change is that you have modified the signature of the existing methods. The very simple solution is not to modify the signature of the existing methods.

So just add the new methods without default parameters, and make the existing methods call the new method:

```C#
public void AddRuleForOneLevel(LogLevel level, Target target, string loggerNamePattern)
{
   // Existing method forwarding to new method
   AddRuleForOneLevel(level, target, loggerNamePattern, false);
}

public void AddRuleForOneLevel(LogLevel level, Target target, string loggerNamePattern, bool final)
{
   // Do the right thing
}
```

**Comment by 893949088** [comment]
@snakefoot  Thank you very much!!!

**Comment by 893949088** [comment]
〒_〒！〒_〒！〒_〒！

**Comment by snakefoot** [comment]
@893949088 Remember to remove the parameter default values for the new methods.

**Comment by 304NotModified** [comment]
looks good, thanks!

Will merge this when Travis gives green (restarted Travis, it was stuck)

**Pull request merged**
