### PR TITLE
added unit test: string with variable get expanded

### PR DESCRIPTION
**Pull request by 304NotModified**
Skipped as it's unclear if its a bug

### CODE REVIEW

**Comment by Xharze** [comment]
I believe this is a bug, shouldn't we try to fix in this pull request too?

**Comment by 304NotModified** [comment]
If it's a bug, yes. Although I could be handy to expand also strings? For configuring passwords globally etc.

**Comment by Xharze** [comment]
It could have use cases but I think it is a bit counter intuitive

**Comment by 304NotModified** [comment]
Agree. But I'm always reticent (not sure if this is the correct English word) with changing things non-backwards compatible.

**Comment by Xharze** [comment]
I'll merged the test for now, when we figure out what to do a new pull request can be added

**Comment by 304NotModified** [comment]
:+1:

**Comment by ArchonMegalon** [comment]
It seems to me that, there is a (new) bug originated in the change of the source Eventlog from the original Post: https://github.com/NLog/NLog/issues/669

I'm new to github, so - if this is not the place to say this please tell me so.

What I noticed: The EventLog-Target has as Source a Layout
https://github.com/nlog/nlog/wiki/EventLog-target

But: trying to set it like this failed:
```C#
logEvent.Properties["MySource"] = useSource;
logEvent.Properties["EventID"] = dicId.EventId;
```
```XML
   <target xsi:type="EventLog" name="ELNoFileName" machineName="."
            source="${event-properties:item=MySource}" log="Application"
            eventId="${event-properties:EventID}"
            layout="ELNoFileName (${event-properties:item=MySource}): ${message}"/>
```

It DOES set the EventID, it DOES set the source, but it seems to me it KEEPS the source the same for all logevents to the target after the first loggin-action.

Now - as you can see - it's pretty mystic for me. How to report such a bug or how to give you guys the possibility to re-create this problem?

Maybe it's also about the useSource?`Basically i fill it like this: 
```C#
 var eventLogSource = !string.IsNullOrEmpty(userMethod?.DeclaringType?.Assembly.GetName().Name)
                ? userMethod.DeclaringType.Assembly.GetName().Name
                : "Application Error";
```

**Comment by 304NotModified** [comment]
@ArchonMegalon is this the same issue as https://github.com/NLog/NLog/issues/1542?

**Comment by ArchonMegalon** [comment]
Hi! Yes! I was not able to find my own post again, so I opened a new issue. Sorry for that!

**Pull request merged**
