### PR TITLE
Implement IRawValue on ${whenEmpty}

### PR DESCRIPTION
**Pull request by 304NotModified**
fixes https://github.com/NLog/NLog/issues/3372

related: https://github.com/NLog/NLog/pull/3373 and https://github.com/NLog/NLog/issues/3139

### CODE REVIEW

**Comment by 304NotModified** [comment]
@snakefoot could you please help me getting this ready?

I doesn't work unfortunately, probably because `MutableUnsafe = true`. See this screenie when debugging (SimpleLayout.cs)

image

Any idea how to fix that? 

Also think this isn't the most efficient way, but dunno how to write a more efficient test.

```c#
   public bool TryGetRawValue(LogEventInfo logEvent, out object value)
        {
            var item = Inner.Render(logEvent);
            if (item.Length > 0)
                 ...

       }
```

**Comment by snakefoot** [comment]
Don't do this:

`var item = Inner.Render(logEvent);`

Instead check if the raw-value-returned is null or empty-string.

**Comment by snakefoot** [comment]
Created #3398

**Comment by 304NotModified** [comment]
Syoer

**Pull request closed without merging**
