### PR TITLE
Fix: Deadlock in NetworkTarget

### LINKED ISSUE #1058: Deadlock in NetworkTarget
This issue was initially found during testing of #902. I'm reposting it as a separate issue.

What we have noticed though is some deadlock condition happening both with previous and curent code. The setup is like following:

config:
```xml
      <target xsi:type="Network"
        onOverflow="Discard"
        newLine="true"
        layout="${msg4Json}"
        encoding="utf-8"
        connectionCacheSize="5"
        keepConnection="false"
        address="tcp://logstash.our_local_host_name.com:9002"
              name="network"
      />
```

test program
```c#
        static void Main(string[] args)
        {
            Logger logger = LogManager.GetCurrentClassLogger();
            for (int i = 0; i < 100000; ++i)
            {
                logger.Trace("log " + i);
            };
            Console.WriteLine("Done");
            Console.Read();
        }
```

Call stacks at the moment of deadlock for the 4.2.0:
```
Worker thread:
>	NLog.dll!NLog.Targets.NetworkTarget.Write.AnonymousMethod__a(System.Exception ex) + 0x76 bytes	
 	NLog.dll!NLog.Targets.NetworkTarget.ChunkedSend.AnonymousMethod__1a(System.Exception ex) + 0x74 bytes	
 	NLog.dll!NLog.Internal.NetworkSenders.TcpNetworkSender.ProcessNextQueuedItem() + 0x10c bytes	
 	NLog.dll!NLog.Internal.NetworkSenders.TcpNetworkSender.SocketOperationCompleted(object sender, System.Net.Sockets.SocketAsyncEventArgs e) + 0x1ad bytes	
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) + 0x285 bytes	
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) + 0x9 bytes	
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) + 0x57 bytes	
 	System.dll!System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(System.Net.Sockets.SocketError socketError, int bytesTransferred, System.Net.Sockets.SocketFlags flags) + 0xa6 bytes	
 	System.dll!System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* nativeOverlapped) + 0xa8 bytes	
 	mscorlib.dll!System.Threading._IOCompletionCallback.PerformIOCompletionCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* pOVERLAP) + 0x96 bytes	
 	[Native to Managed Transition]	

Main thread: 
> 	NLog.dll!NLog.Internal.NetworkSenders.TcpNetworkSender.ProcessNextQueuedItem() + 0x64 bytes	
	NLog.dll!NLog.Internal.NetworkSenders.TcpNetworkSender.DoSend(byte[] bytes, int offset, int length, NLog.Common.AsyncContinuation asyncContinuation) + 0x1f4 bytes	
 	NLog.dll!NLog.Internal.NetworkSenders.NetworkSender.Send(byte[] bytes, int offset, int length, NLog.Common.AsyncContinuation asyncContinuation) + 0x82 bytes	
 	NLog.dll!NLog.Targets.NetworkTarget.ChunkedSend.AnonymousMethod__1a(System.Exception ex) + 0x38c bytes	
 	NLog.dll!NLog.Targets.NetworkTarget.ChunkedSend(NLog.Internal.NetworkSenders.NetworkSender sender, byte[] buffer, NLog.Common.AsyncContinuation continuation) + 0x15b bytes	
 	NLog.dll!NLog.Targets.NetworkTarget.Write(NLog.Common.AsyncLogEventInfo logEvent) + 0x469 bytes	
 	NLog.dll!NLog.Targets.Target.WriteAsyncLogEvent(NLog.Common.AsyncLogEventInfo logEvent) + 0x1a4 bytes	
 	NLog.dll!NLog.LoggerImpl.WriteToTargetWithFilterChain(NLog.Internal.TargetWithFilterChain targetListHead, NLog.LogEventInfo logEvent, NLog.Common.AsyncContinuation onException) + 0x229 bytes	
 	NLog.dll!NLog.LoggerImpl.Write(System.Type loggerType, NLog.Internal.TargetWithFilterChain targets, NLog.LogEventInfo logEvent, NLog.LogFactory factory) + 0x23c bytes	
 	NLog.dll!NLog.Logger.WriteToTargets(NLog.LogLevel level, System.IFormatProvider formatProvider, string message) + 0xf9 bytes	
 	NLog.dll!NLog.Logger.Trace(string message) + 0x59 bytes	
 	NlogConsoleTest.exe!NlogConsoleTest.Program.Main(string[] args) Line 19 + 0x68 bytes	C#
```

call stacks at the moment of deadlock for the 4.2.1:
```
Worker thread:
 	mscorlib.dll!System.Threading.Monitor.Enter(object obj, ref bool lockTaken) + 0x17 bytes	
>	NLog.dll!NLog.Targets.NetworkTarget.Write.AnonymousMethod__a(System.Exception ex) Line 321 + 0x1a bytes	C#
 	NLog.dll!NLog.Targets.NetworkTarget.ChunkedSend.AnonymousMethod__19(System.Exception ex) Line 485 + 0x10 bytes	C#
 	NLog.dll!NLog.Internal.NetworkSenders.TcpNetworkSender.SocketOperationCompleted(object sender, System.Net.Sockets.SocketAsyncEventArgs e) Line 216 + 0x11 bytes	C#
 	System.dll!System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(System.Net.Sockets.SocketAsyncEventArgs e) + 0x15 bytes	
 	System.dll!System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(object ignored) + 0xf bytes	
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) + 0xa7 bytes	
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) + 0x16 bytes	
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) + 0x41 bytes	
 	System.dll!System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(System.Net.Sockets.SocketError socketError, int bytesTransferred, System.Net.Sockets.SocketFlags flags) + 0x77e bytes	
 	System.dll!System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* nativeOverlapped) + 0x37 bytes	
 	mscorlib.dll!System.Threading._IOCompletionCallback.PerformIOCompletionCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* pOVERLAP) + 0x6e bytes	
 	[Native to Managed Transition]	

Main thread:
 	mscorlib.dll!System.Threading.Monitor.Enter(object obj, ref bool lockTaken) + 0x17 bytes	
>	NLog.dll!NLog.Internal.NetworkSenders.TcpNetworkSender.ProcessNextQueuedItem() Line 227 + 0x11 bytes	C#
 	NLog.dll!NLog.Internal.NetworkSenders.TcpNetworkSender.DoSend(byte[] bytes, int offset, int length, NLog.Common.AsyncContinuation asyncContinuation) Line 172 + 0x8 bytes	C#
 	NLog.dll!NLog.Internal.NetworkSenders.NetworkSender.Send(byte[] bytes, int offset, int length, NLog.Common.AsyncContinuation asyncContinuation) Line 115 + 0x16 bytes	C#
 	NLog.dll!NLog.Targets.NetworkTarget.ChunkedSend.AnonymousMethod__19(System.Exception ex) Line 511 + 0x37 bytes	C#
 	NLog.dll!NLog.Targets.NetworkTarget.ChunkedSend(NLog.Internal.NetworkSenders.NetworkSender sender, byte[] buffer, NLog.Common.AsyncContinuation continuation) Line 514 + 0x10 bytes	C#
 	NLog.dll!NLog.Targets.NetworkTarget.Write(NLog.Common.AsyncLogEventInfo logEvent) Line 316 + 0x47 bytes	C#
 	NLog.dll!NLog.Targets.Target.WriteAsyncLogEvent(NLog.Common.AsyncLogEventInfo logEvent) Line 204 + 0x34 bytes	C#
 	NLog.dll!NLog.LoggerImpl.WriteToTargetWithFilterChain(NLog.Internal.TargetWithFilterChain targetListHead, NLog.LogEventInfo logEvent, NLog.Common.AsyncContinuation onException) Line 196 + 0x28 bytes	C#
 	NLog.dll!NLog.LoggerImpl.Write(System.Type loggerType, NLog.Internal.TargetWithFilterChain targets, NLog.LogEventInfo logEvent, NLog.LogFactory factory) Line 99 + 0xe bytes	C#
 	NLog.dll!NLog.Logger.WriteToTargets(NLog.LogLevel level, System.IFormatProvider formatProvider, string message) Line 542 + 0x41 bytes	C#
 	NLog.dll!NLog.Logger.Trace(string message) Line 183 + 0x13 bytes	C#
 	TEST.exe!TEST.Program.Main(string[] args) Line 18 + 0x46 bytes	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	mscorlib.dll!System.AppDomain.ExecuteAssembly(string assemblyFile, System.Security.Policy.Evidence assemblySecurity, string[] args) + 0x6b bytes	
 	Microsoft.VisualStudio.HostingProcess.Utilities.dll!Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly() + 0x27 bytes	
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart_Context(object state) + 0x6f bytes	
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) + 0xa7 bytes	
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) + 0x16 bytes	
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) + 0x41 bytes	
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart() + 0x44 bytes	
 	[Native to Managed Transition]	
```

### PR DESCRIPTION
**Pull request by kt1996**
Deadlock in NetworkTarget Issue. fixes #1058

### CODE REVIEW

**Comment by 304NotModified** [comment]
Changes without whitespace changes : https://github.com/NLog/NLog/pull/1110/files?w=1

Can you explain me why the declaration should be outside the `lock`? Then I can make sure we won't make the same mistake :)

**Comment by kt1996** [comment]
All line numbers with respect to
https://github.com/kt1996/NLog/blob/master/src/NLog/Targets/NetworkTarget.cs
https://github.com/kt1996/NLog/blob/master/src/NLog/Internal/NetworkSenders/TcpNetworkSender.cs

**Debugging Findings-**
Well actually on debugging I found out that the deadlock was caused by the main thread holding the lock to the `TCPNetworkSender.openNetworkSender` (NetworkTarget, Line 277) and waiting for lock on `TCPNetworkSender` instance (Multiple positions where `lock(this)`is present), whereas the worker thread had a lock on the `TCPNetworkSender` instance (TCPNetworkSender, Line 202) and was waiting for a lock on `TCPNetworkSender.openNetworkSender` (this was in the delegate passed on NetworkTargets, Line 318).

**Reason**
Note: Why this was happening was clear on going through the call stack and was the case when the toSend(Networktarget, Line 455) became zero and the sendNextChunk was invoked at a moment when the main thread was holding one lock and about to lock the other object too. Further description- 
**Detailed FlowThrough**
The main thread held the `TCPNetworkSender.openNetworkSender` lock and the worker thread had entered the `SocketOperationCompleted` method (thus acquiring the `TCPNetworkSender` Lock) with the `e.UserToken` not null, it proceeded with `asyncContinuation(this.pendingError)` (a few lines later) and invoked the delegate (the sendNextChunk one, NetworkTarget, Line 460) and this time proceeded to invoke the delegate provided via (NetworkTarget, Line 470) which next waited on the lock to` TCPNetworkSender.openNetworkSender`.  The main thread on the other hand waited for lock on `TCPNetworkSender` instance (TCPNetworkSender, Multiple positions where `lock(this)`is present, Like Line 227) and thus the deadlock situation arose.

**Lock Scope Changes**
I removed the declaration from the scope of lock as it was not needed, the only place the call might further on need to access openNetworkSenders was already protected by a call to lock (networkTargets, Line 318) in the delegate passed and now since the main thread was no longer unnecessarily holding the lock there was no issue of deadlock.

*The only thing wrong here was unnecessarily locking of an object by the main thread which caused the deadlock*

Hope I provided enough details, please ask again if u need any more info. Thanks!!

**Comment by 304NotModified** [comment]
Thanks for the info! 

I see now indeed that the scope of the `lock` has been changed.

**Comment by 304NotModified** [comment]
Thanks for this bugfix. I has been merged and will be released in 4.3 :)

**Pull request merged**
