### PR TITLE
WIP: DataTableTarget - Bulk-insert using DbDataAdapter and DataTable

### PR DESCRIPTION
**Pull request by snakefoot**
It is very similar to the existing DatabaseTarget in configuration. But with a different `xsi:type="DataTable"`  and a new parameter `UpdateBatchSize`.

```xml
<targets>
    <target name="db" type="AsyncWrapper" timeToSleepBetweenBatches="250" batchSize="200">
            <target name="wrapped_db" xsi:type="DataTable" updateBatchSize="200" keepConnection="True" prepareDbCommand="True">
                  <commandtext>INSERT INTO FooBar VALUES(@msg, @lvl)</commandtext>
                  <parameter name="@msg" layout="${message}" dbType="String" />
                  <parameter name="@lvl" layout="${level}"  dbType="String" />
            </target>
    </target>
</targets>
<rules>
   <logger name="*" minlevel="Debug" writeTo="db" />
</rules>
```

Pre-Release Nuget-package here: https://ci.appveyor.com/project/nlog/nlog/builds/22695687/artifacts (NLog.4.6.0.9175-PR3150.nupkg)

This should work better in cloud-enviroments when high network-latency to the database-instance.

For NetCore using Sql.Data.Client, then make sure to use ver. 4.7.0-preview:  https://www.nuget.org/packages/System.Data.SqlClient/4.7.0-preview.19073.11 (To fix bug https://github.com/dotnet/corefx/issues/29391)

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/3150)

### CODE REVIEW

**Comment by snakefoot** [comment]
@D9001 Just fixed some bugs. So you have to wait for the pending build to complete to test,.

**Comment by D9001** [comment]
> @D9001 Just fixed some bugs. So you have to wait for the pending build to complete to test,.

Sure, I'll test this out first thing tomorrow.

**Comment by snakefoot** [comment]
@D9001 Finally a proper build. Have updated the initial post with new link to the latest build.

**Comment by D9001** [comment]
Hey, the first sample runs of this worked **tremendously** better! I will schedule another full performance test next week and let you know how the results compared to our previous ones.

**Comment by D9001** [comment]
> Hey, the first sample runs of this worked **tremendously** better! I will schedule another full performance test next week and let you know how the results compared to our previous ones.

I can't tell what, if anything, has caused a breaking-change since I've started adding onto this to mimic my real table, but I'm getting this error now:

```
2019-03-01 18:54:35.6115 Error DataTableTarget(Name=database): Error when writing to database. Exception: System.ArgumentException: Specified parameter name 'Parameter1' is not valid.
   at System.Data.Common.DbDataAdapter.UpdatedRowStatusErrors(RowUpdatedEventArgs rowUpdatedEvent, BatchCommandInfo[] batchCommands, Int32 commandCount)
   at System.Data.Common.DbDataAdapter.UpdatedRowStatus(RowUpdatedEventArgs rowUpdatedEvent, BatchCommandInfo[] batchCommands, Int32 commandCount)
   at System.Data.Common.DbDataAdapter.Update(DataRow[] dataRows, DataTableMapping tableMapping)
   at System.Data.Common.DbDataAdapter.UpdateFromDataTable(DataTable dataTable, DataTableMapping tableMapping)
   at System.Data.Common.DbDataAdapter.Update(DataTable dataTable)
   at NLog.Targets.DataTableTarget.WriteEventsToDatabase(IList`1 logEvents, String connectionString, CommandType commandType, String commandText, IList`1 parameters)
   at NLog.Targets.DataTableTarget.Write(IList`1 logEvents)
```

It's still writing out the first time, but subsequent ones aren't working.

This is my configuration:

```xml
        <target xsi:type="AsyncWrapper"
            name="aDb"
            fullBatchSizeWriteLimit="100"
            timeToSleepBetweenBatches="10000"
            batchSize="200"
            overflowAction ="Grow">
      <target xsi:type="DataTable"
              name="database"
              connectionstring="..."
              keepConnection="True"
              prepareDbCommand="True"
              updateBatchSize="200">
        <commandText>
          INSERT INTO Analytics ([AltId],[ManagerId],[Registration],[Eng],[Time]) VALUES (@AltId,@ManagerId,@Registration,@Eng,@Time);
        </commandText>
        <parameter name="@AltId" layout="${event-properties:item=AltId}" dbType="SqlDbType.VarChar" size="50" />
        <parameter name="@Eng" layout="${event-properties:item=Eng}" dbType="SqlDbType.VarChar" size="50"/>
        <parameter name="@ManagerId" layout="${event-properties:item=ManagerId}" dbType="SqlDbType.Int" />
        <parameter name="@Registration"  layout="${event-properties:item=Registration}" dbType="SqlDbType.VarChar" size="500"/>
        <parameter name="@Time" layout="${date:universalTime=true}" dbType="SqlDbType.DateTime" />
      </target>
    </target>
```

**Comment by snakefoot** [comment]
@D9001 Strange where `Parameter1` comes from. Can you attach the full internal log-file?

**Comment by D9001** [comment]
@snakefoot  Here's the latest log: https://jpst.it/1Cnd5

**Comment by snakefoot** [comment]
@D9001 Sounds like you are hitting this "bug": https://github.com/dotnet/corefx/issues/29391

Could you try the 4.7.0-preview nuget-package: https://www.nuget.org/packages/System.Data.SqlClient/4.7.0-preview.19073.11

**Comment by snakefoot** [comment]
@304NotModified Should I make an effort in changing DataTableTarget to inherit from DatabaseTarget, so it can be included for NLog 4.6? Or should it be postponed for later?

**Comment by 304NotModified** [comment]
Any idea how much the performance gain is?

**Comment by snakefoot** [comment]
Well I guess it depends on database latency. High latency where single row takes 100 ms. Then single batch of 100 rows will take 200 ms (worst case) but 100 single row operations will take 10000<tel:10000> ms


Low latency where single row take 5 ms. Then  100 single row operations will take 500ms.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


Any idea how much the performance gain is?

**Comment by snakefoot** [comment]
Performed a small test against my LocalDb (Guess it is low-latency) of 100000 rows with 3 columns DateTime + Level + Message.

| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog 4.5.11 Database   |    21.022 |     4.756 |   0 |   0 |   4 |    4.593 |      208,8 |
| NLog 4.6 PR Database   |    21.733 |     4.601 |   0 |   0 |   3 |    2.281 |      175,3 |
| NLog 4.6 PR Database PrepareCmd  |  19.969 |     5.007 |   0 |   1 |   2 |    2.750 |       56,6 |
| NLog 4.6 PR DataTable   |    15.924 |     6.279 |   0 |   1 |   3 |      937 |      171,8 |
| NLog 4.6 PR DataTable PrepareCmd |  15.055 |     6.641 |   0 |   0 |   1 |      750 |      170,2 |

Looks like PrepareCmd doesn't do much. What really matters is reusing SqlCommand where possible. And one should probably also attempt to reuse the DataAdapter for DataTable.

**Comment by 304NotModified** [comment]
OK great results! great work!

>  Should I make an effort in changing DataTableTarget to inherit from DatabaseTarget, 

What about in the database target? As option? (we can still use internally subclasses and interfaces)

> so it can be included for NLog 4.6 with unit-tests etc.? 

I you have time for the docs for 4.6, then 4.6 is a go, otherwise 4.6.1 is also fine for me. Your choice 👼

**Comment by snakefoot** [comment]
> What about in the database target? As option? (we can still use internally subclasses and interfaces)

There will be some funny guessing logic whether DbProvider contains the ConnectionType or the ProviderFactoryType. The DataTable logic requires a working ProviderFactoryType. 

But I guess one could use UpdateBatchSize as parameter to decide whether to use DataTable, instead of single DbCommand.

**Comment by D9001** [comment]
> @D9001 Sounds like you are hitting this "bug" in NetCore: [dotnet/corefx#29391](https://github.com/dotnet/corefx/issues/29391)
> 
> Could you try the 4.7.0-preview nuget-package: https://www.nuget.org/packages/System.Data.SqlClient/4.7.0-preview.19073.11

I just tried it and this resolved my issue. The inserts still seem very fast compared to previous inserts. I won't be able to performance test my API again until later this week, but I'm hopeful with these results. I haven't dug into the code too much aside from skimming over the write methods when trying to debug the "Parameter1" issue, but I shouldn't be concerned that I see individual insert statements submitted with this approach, right? The response times between them are noticeably better, but I just want to make sure this isn't an indication that I am missing something else in my setup.

**Comment by 304NotModified** [comment]
@snakefoot this the latest merge before 4.6 rc2/RTM? Is that ok with you?

**Comment by snakefoot** [comment]
>  @D9001 but I shouldn't be concerned that I see individual insert statements submitted with this approach, right?

I have no control of how the SqlDataAdapter performs the bulk insert. But it looks like the SqlDataAdapter concats all provided row-parameters into one big sql-statement.

I'm guessing that `SqlBulkCopy` will perform better, as it supports streaming and can skip building up a huge payload in memory before executing. But it has to be dedicated NLog target with custom dependencies (outside the standard NLog-package).

The NLog database-target will probably also be moved into an isolated package to reduce the size and dependencies of the NLog-core.dll. I was just curious whether the batching logic could be used, since it would also allow batching against other DbProviders (MySql, etc.)

**Comment by snakefoot** [comment]
@304NotModified When does the window close for 4.6.0-rc2? When I have something working then you will probably have lots of comments. And I there is also the funny part of unit-testing this baby.

**Comment by snakefoot** [comment]
@304NotModified After consulting my energy-levels. Then I think I will just do #3131, and let this one be up-for-grabs for those wanting to contribute to the NLog-project.

**Comment by D9001** [comment]
@snakefoot It may just be the way that the profiler is choosing to display the insert statements that is making it appear this way. From the logs and what I can tell running the code, it is certainly inserting more than one at a time.

**Comment by snakefoot** [comment]
@D9001 Think the profiler is completely correct. It executes several individual insert-command-statements instead of just a single insert-command.

**Comment by 304NotModified** [comment]
Closing this due to inactivity

**Pull request closed without merging**
