### PR TITLE
Layout Wrappers should not crash when Inner-Layout is null

### PR DESCRIPTION
**Pull request by snakefoot**
Added null-check to handle #2844

### CODE REVIEW

**Comment by 304NotModified** [comment]
was `null` an issue in #2844?

**Comment by 304NotModified** [comment]
Thanks for the change, looks good!

**Comment by snakefoot** [comment]
Seems there is a test that depends on null working.

**Comment by snakefoot** [comment]
> @304NotModified  was null an issue in #2844?

```
Warn Exception in layout renderer. Exception: System.NullReferenceException: Object reference not set to an instance of an object.
```

But this PR doesn't resolve the actual issue of #2844

**Pull request merged**
