### PR TITLE
Log4JXmlEventLayout - Added support for configuration of Parameters

### PR DESCRIPTION
**Pull request by snakefoot**

### CODE REVIEW

**Comment by snakefoot** [comment]
@304NotModified Can also be included for NLog 4.6.4

**Comment by 304NotModified** [comment]
Ok! Could you please rebase it on master and change the PR's base afterwards? Thanks!

**Comment by snakefoot** [comment]
@304NotModified Changed base to master

**Comment by 304NotModified** [comment]
great work! thanks!

I will merge it first to an intermediate release branch (so I won't break the debug symbols of 4.6.3)

**Pull request merged**
