### PR TITLE
Port 4.6.8 to dev

### PR DESCRIPTION
**Pull request by 304NotModified**
merge commit!

### CODE REVIEW

**Comment by snakefoot** [comment]
Changes for `ConfigFileLocatorTests.cs` (Handle behavior change in loading `exe.nlog` first):

```xml
        [Fact]
        public void LoadConfigFile_NetCoreSingleFilePublish_IgnoreTempDirectory()
        {
            // Arrange
            var tmpDir = Path.GetTempPath();
            var appEnvMock = new AppEnvironmentMock(f => true, f => null)
            {
                AppDomainBaseDirectory = Path.Combine(tmpDir, "BaseDir"),
#if NETSTANDARD
                AppDomainConfigurationFile = string.Empty,                  // NetCore style
#else
                AppDomainConfigurationFile = Path.Combine(tmpDir, "TempProcessDir", "Process.exe.config"),
#endif
                CurrentProcessFilePath = Path.Combine(tmpDir, "ProcessDir", "Process.exe"),    // NetCore published exe
                EntryAssemblyLocation = Path.Combine(tmpDir, "TempProcessDir"),
                UserTempFilePath = Path.Combine(tmpDir, "TempProcessDir"),
                EntryAssemblyFileName = "Entry.dll"
            };

            var fileLoader = new LoggingConfigurationFileLoader(appEnvMock);

            // Act
            var result = fileLoader.GetDefaultCandidateConfigFilePaths().ToList();

            // Assert base-directory + process-directory + nlog-assembly-directory
#if NETSTANDARD
            Assert.Equal(Path.Combine(tmpDir, "ProcessDir", "Process.exe.nlog"), result.First(), StringComparer.OrdinalIgnoreCase);
#endif
            AssertResult(tmpDir, "TempProcessDir", "ProcessDir", "Process", result);
        }

        private static void AssertResult(string tmpDir, string appDir, string processDir, string appName, List<string> result)
        {
            if (NLog.Internal.PlatformDetector.IsWin32)
            {
#if NETSTANDARD
                Assert.Equal(5, result.Count);  // Case insensitive
#else
                Assert.Equal(4, result.Count);  // Case insensitive
#endif
            }
#if NETSTANDARD
            Assert.Contains(Path.Combine(tmpDir, processDir, appName + ".exe.nlog"), result, StringComparer.OrdinalIgnoreCase);
            Assert.Contains(Path.Combine(tmpDir, appDir, "Entry.dll.nlog"), result, StringComparer.OrdinalIgnoreCase);
#else
            Assert.Equal(Path.Combine(tmpDir, appDir, appName + ".exe.nlog"), result.First(), StringComparer.OrdinalIgnoreCase);
#endif
            Assert.Contains(Path.Combine(tmpDir, "BaseDir", "NLog.config"), result, StringComparer.OrdinalIgnoreCase);
            Assert.Contains(Path.Combine(tmpDir, appDir, "NLog.config"), result, StringComparer.OrdinalIgnoreCase);
            Assert.Contains("NLog.dll.nlog", result.Last(), StringComparison.OrdinalIgnoreCase);
        }
```

**Comment by 304NotModified** [comment]
Could you please push that to this branch? Afaik you have the correct rights for that.

**Comment by snakefoot** [comment]
Sorry working on DI right now

**Comment by 304NotModified** [comment]
Ok! 

Checked the rights. Now you have write access :)

**Pull request merged**
