### PR TITLE
Run logging code outside of transaction

### PR DESCRIPTION
**Pull request by Giorgi**
If the user tries to log to database inside transaction scope and rollbacks that transaction the logging will be rolled back to0. With this change we never create a transaction when writing to database.

### CODE REVIEW

**Comment by Giorgi** [comment]
@Xharze Was this included in the 4.0 release?

**Comment by 304NotModified** [comment]
yes :)

I has been merged and it has the milestone 4.0. 

It was not in the news post maybe, that because it was not labeled as "feature"

**Comment by 304NotModified** [comment]
I was not in the NLog team when this was merged. 

As far as I understand, `UseTransactions ` option has been removed?

**Comment by 304NotModified** [comment]
It would be great if you would update the wiki. https://github.com/NLog/NLog/wiki/Database-target

**Comment by Giorgi** [comment]
Yes, the option was removed because the logging code always runs outside of transaction to ensure that the log gets written to the database if you rollback the main transaction because of an error and want to log the error.

**Comment by 304NotModified** [comment]
It would be great if you would update the wiki. https://github.com/NLog/NLog/wiki/Database-target

**Comment by Giorgi** [comment]
Done.

**Comment by 304NotModified** [comment]
Thanks but the wiki is also for older versions. So just removing the option on the docs isn't maybe  the best idea. 

I think It needs be there and explained why it's removed in 4.0. 

Do you agree?

**Comment by Giorgi** [comment]
Done.

**Comment by 304NotModified** [comment]
your still editing?

**Comment by Giorgi** [comment]
No

**Comment by 304NotModified** [comment]
can you break down to smaller sentences ;) ?

**Comment by Giorgi** [comment]
Better now?

**Pull request merged**
