### PR TITLE
Changes at MDLC to support .Net 4.0 and .Net 4.5

### PR DESCRIPTION
**Pull request by BrutalCode**
Changed compiler #if directive to support .Net 4.0 and 4.5

### CODE REVIEW

**Comment by 304NotModified** [comment]
And the unit tests?

**Comment by BrutalCode** [comment]
I just changed the #if directive and compile it in 4.0. What kind of unit test can be written for this change? For references?

**Comment by 304NotModified** [comment]
There should be already unit tests for this. Those need also enabled for. Net 4

It should be in the test project and the class name is almost the same.

**Comment by BrutalCode** [comment]
You are right! Sorry for oversight. I changed and pushed it too.

**Comment by 304NotModified** [comment]
Yes, those where all of them (I used "find all references" in the .Net 4.5 solution, and I checked if there were more `#if` statement in 1 file )

**Comment by 304NotModified** [comment]
So good catch!  :+1:

**Pull request merged**
