### PR TITLE
LoggingRule.Final only suppresses matching levels. 

### PR DESCRIPTION
**Pull request by ilya-g**
Fix for #423

Added a test that reproduces the bug and passes after the change.

### CODE REVIEW

**Comment by snakefoot** [comment]
I have an application with different 3rd Party Dependencies. I have created some very specific logger-name-star-filters with final for these dependencies (Info-level and above), and then everything else (my stuff) goes to the catch-all-star-logger.

Does this change mean that I have specify these 3rd Party dependencies logger-filters for each log-level, so they don't get caught by my catch-all-star-loggger?.

Is there a setting so I can specify "FinalAll" and not just "FinalLevel" for my 3rd Party Dependency logger-filters?

**Comment by 304NotModified** [comment]
Hi @snakefoot , please open a new issue for this (reference to the PR would be nice) and please post an example config.

**Comment by snakefoot** [comment]
Will minLevel + Final for the 3rd Party Dependency loggers (Instead of just Level), make sure that nothing reaches my catch-all-start-logger?

**Comment by 304NotModified** [comment]
@snakefoot you can use `minlevel` or just remove the whole `level` attributes.

**Pull request merged**
