### PR TITLE
Updated NLog viewer target defaults

### PR DESCRIPTION
**Pull request by 304NotModified**
moved to defaults which works better out-of-the-box

fixes https://github.com/NLog/NLog/issues/2147

### CODE REVIEW

**Comment by snakefoot** [comment]
@304NotModified Updated documentation https://github.com/NLog/NLog/wiki/NLogViewer-target

**Comment by snakefoot** [comment]
@304NotModified Are you not missing `keepConnection="false"` ? `OnConnectionOverflow` has no effect when `keepConnection="true"` (current default)

**Comment by 304NotModified** [comment]
Think you're right, altough the defaults are now better when disabling keepConnection

**Comment by snakefoot** [comment]
Think a much better default for the NLogViewerTarget is to set the following:

`NewLine = true;`

The following config works without loosing any messages in Log4View, running at full speed:

`<target name="log4view" xsi:type="NLogViewer" address="tcp://127.0.0.1:878" NewLine="true" />`

Can see `keepConnection="false"` will cause lots of allocations, so it is a good idea not to enable it.

**Comment by 304NotModified** [comment]
That's also fine to me. Goal is to improve the default behavior of the target :)

**Comment by snakefoot** [comment]
@304NotModified Looks like it is just the Log4View-application that is very sensitive. Other applications (Ex. log2console) does not require NewLine=true to work.

**Comment by 304NotModified** [comment]
I think you're right. So what should be done, revert this change? Imo unlimited max connections is a bit tricky.

**Comment by snakefoot** [comment]
This change has no effect, besides adding a little confusion by adding settings that are not used.


Sent from my Samsung device


-------- Original message --------

**Pull request merged**
