### PR TITLE
Testing appveyor.yml with Ubuntu

### PR DESCRIPTION
**Pull request by snakefoot**
See also #4270

### CODE REVIEW

**Comment by snakefoot** [comment]
@304NotModified Well now it is possible to run Ubuntu-build on AppVeyor. It is faster than waiting for Travis, but still a single build takes 25 mins because one also is queued for Ubuntu-build on AppVeyor.

It also revealed that NLog is hit by this "bug" on the Linux-platform, that causes NLog Config Variables not to work on NetCore on Linux.

I think we should move to AppVeyor and drop Travis. Unless you have some secret desire for the more unstable Azure DevOps Pipeline or the untested Github-Actions?

**Comment by 304NotModified** [comment]
> I think we should move to AppVeyor and drop Travis. Unless you have some secret desire for the more unstable Azure DevOps Pipeline or the untested Github-Actions?

I prefer of course stability. Unfortunately the single agent on AppVeyor was for me a reason to try moving to Azure. Unfortunately this was never fully completed because of the stability and a lot of release scripts where build on AppVeyor. 

25min is long....I'm doubting if we should not try Azure for Linux, it's has more agents and work in parallel.

**Comment by 304NotModified** [comment]
> It also revealed that NLog is hit by this "bug" on the Linux-platform, that causes NLog Config Variables to no longer work on Net50-platform with Linux. dotnet/runtime#43736 (Will make a PR for the master-branch for this

Heavy change in .net 5! We don't need a separate build for .net 5, but only adding the stringComparison for every indexOf and contains?

**Comment by snakefoot** [comment]
> Heavy change in .net 5! We don't need a separate build for .net 5, but only adding the stringComparison for every indexOf and contains?

Yes think it is going to give a lot of headache all around. Seems it is only `IndexOf` that behaves different and requires Ordinal or OrdinalIgnoreCase

**Comment by snakefoot** [comment]
But since you agree to move away from Travis, then maybe this will be an okay alternative until someone comes around and fixes the Azure Pipeline?

For me having a 2 hour integration-build makes it a little hard to move forward. Hopefully when NLog 5.0 has been released, then all the "exotic" targets can be moved out of the NLog-core-repository and reduce build-times (and instability because of database-service-issues).

**Comment by 304NotModified** [comment]
2 hours? Travis takes 8min? Or do you mean with restart?

**Comment by snakefoot** [comment]
Takes 2 hours to complete a Travis build because of queue time. See also linked issue at the beginning


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


2 hours? Travis takes 8min? Or do you mean with restarts?

**Comment by 304NotModified** [comment]
Ow thanks, I missed something. 

Ok drop travis indeed. But I think it's wise if we could try Azure as 10 min queue is also not very nice. 

I'm not sure if you've the rights to change the Azure pipeline. In my experience the Linux build agents are more stable than the windows ones.

**Comment by snakefoot** [comment]
I think I have spent enough time on getting AppVeyor running, so I will leave it for someone else to play around with Azure Pipelines.

But I guess if you remove Travis, then the "conversion" must also happen on master-branch.

**Comment by snakefoot** [comment]
But if you can have 10 parallel jobs on Azure Pipelines then you could do this:
 - CodeCoverage NetCoreApp 2.0 + Net461 Windows - Debug
 - Test NetCoreApp 2.0 Windows - Release
 - Test NetCoreApp 2.0 Ubuntu - Release
 - Test NetFramework 3.5 - Release
 - Test NetFramework 4.5.2 Windows - Release
 - Test NetFramework 4.5.2 Ubuntu - Release
 - Test NetFramework 4.6.1 Windows - Release
 - Test NetFramework 4.6.1 Ubuntu - Release

**Comment by snakefoot** [comment]
@304NotModified So are you ready to disable Travis as pull-request requirement, after merging this pull-request?

**Comment by 304NotModified** [comment]
Yes Will do that!

**Comment by snakefoot** [comment]
Could consider to update the master-branch to drop Travis aswell, but lets see. Maybe NLog 5.0 will ready before another release from master is needed.

**Comment by snakefoot** [comment]
@304NotModified The PullRequest has now been merged, so you can remove Travis now.

**Comment by 304NotModified** [comment]
Done!

**Pull request merged**
