### PR TITLE
AutoFlushTargetWrapper - Added AsyncFlush property

### PR DESCRIPTION
**Pull request by snakefoot**
Allow the following setup to work out of the box:

```
  <target name="mailautoflush" xsi:type="AutoFlushWrapper" condition="level >= LogLevel.Error">
    <target name="mailbuffer" xsi:type="BufferingWrapper" bufferSize="1000000">
      <target name="mail" xsi:type="Mail" ... />
    </target>
  </target>
```

Before the BufferingWrapper would capture the LogEvent, so it wouldn't reach the final target, so the attached flush-operation was not executed. Disabling AsyncFlush will make AutoFlushWrapper work together with BufferingWrapper.

### CODE REVIEW

**Comment by 304NotModified** [comment]
Good catch!

**Comment by 304NotModified** [comment]
added to https://github.com/NLog/NLog/wiki/AutoFlushWrapper-target

**Comment by FixRM** [comment]
Hello! I'm experiencing same issue with Network target wrapped with AutoFlushWrapper and BufferingWrapper. Nothing is passed to final target. NLog 5.2.2 config:
```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
	  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xsi:schemaLocation="n NLog.xsd"
	  autoReload="true" 
	  internalLogToConsole="true" internalLogLevel="Info">
	<targets>
		<target name="Logstash" xsi:type="AutoFlushWrapper" condition="level >= LogLevel.Error" flushOnConditionOnly="true">
			<target xsi:type="BufferingWrapper" bufferSize="5" overflowAction="Discard">
				<!-- TCP protocol must be used and newLine is critical -->
				<target name="Network" xsi:type="Network" address="tcp://localhost:9045" newLine="true" />
					<layout xsi:type="JsonLayout" includeEventProperties="true" maxRecursionLimit="2" excludeEmptyProperties="true"/>
			</target>
		</target>
	</targets>
	<rules>
		<logger name="*" minlevel="Info" writeTo="Logstash" />
	</rules>
</nlog>
```
What am I doing wrong? Final target works well without wrappers.

**Comment by snakefoot** [comment]
@FixRM Please create new issue, instead of waking up old ones.

**Comment by FixRM** [comment]
Thanks, @snakefoot. Done: https://github.com/NLog/NLog/issues/5305

**Pull request merged**
