### PR TITLE
Handle Breaking change with string.IndexOf(string) in .NET 5

### PR DESCRIPTION
**Pull request by snakefoot**
LoggingConfiguration - Expand NLog Config Variables without issues on Net50

Changed from CurrentCultureIgnoreCase to OrdinalIgnoreCase to avoid issue described here: https://github.com/dotnet/runtime/issues/43736

Issue was identified with #4271

### CODE REVIEW

**Comment by snakefoot** [comment]
Tried to test myself on Net50-platform, and cannot reproduce the issue. So apparently it is not super urgent to fix on master.

**Comment by snakefoot** [comment]
Travis-Build Started Now

**Comment by snakefoot** [comment]
Travis-Build Started Now

**Comment by snakefoot** [comment]
AppVeyor and Azure Done

**Comment by snakefoot** [comment]
The travis-back-log is "only" 5000, when USA was awake then it was 10.000. Only 230 build-engines and each takes 5-10 mins.

**Comment by snakefoot** [comment]
Travis Build now running

**Comment by snakefoot** [comment]
Travis build broke at 09:13:53 GMT

**Review by 304NotModified — APPROVED** [review]
LGTM, not checked all possible other usages.

**Pull request merged**
