### PR TITLE
Refactor filetarget + target to reduce code complexity

### PR DESCRIPTION
**Pull request by snakefoot**

### CODE REVIEW

**Comment by 304NotModified** [comment]
Have you used a refactor tool for this? (So no need to review in depth)

**Comment by snakefoot** [comment]
FileTarget.cs and Target.cs changes was done by hand.

**Comment by 304NotModified** [comment]
thanks!

I think it would be nice if we could move out some methods out of the FileTarget in the future. It's really too large.

**Comment by snakefoot** [comment]
Yes the file archive logic would probably be a good candidate.

**Pull request merged**
