### PR TITLE
ObjectPathRendererWrapper - Refactoring to reduce code complexity

### PR DESCRIPTION
**Pull request by snakefoot**
Note merge to master

### CODE REVIEW

**Comment by 304NotModified** [comment]
? So we remove the optimization for simplelayout? (most of the cases).

**Comment by snakefoot** [comment]
> ? So we remove the optimization for simplelayout? (most of the cases).

Don't think skipping a virtual function-call is worth the additional code.

**Comment by snakefoot** [comment]
Also think there is a possible bug in Layout-Precalculate with ObjectPathRendererWrapper.

The ObjectPathRendererWrapper should not implement `IRawValue`-interface.

Lets say we have the following scenario:
- Inner-Layout references a complex-object (usually the reason for using `Object-path`).
- ObjectPathRendererWrapper lives in a SimpleLayout as a single _rawValueRenderer.
- SimpleLayout Precalculate asks its _rawValueRenderer whether it is "stable".
- ObjectPathRendererWrapper will perform lookup into the complex-object and returns a string-value.
- SimpleLayout Precalculate will say that a string-value is very stable and cannot change, so skips Precalculate.
- AsyncWrapper takes over and now wants to perform serialization.
- SimpleLayout has skipped the Precalculate, and instead ask its _rawValueRenderer to render.
- _rawValueRenderer lookup the complex-object, but it has been disposed, so when doing `Object-path`-lookup then it returns null (instead of original string-value).

**Comment by 304NotModified** [comment]
> SimpleLayout Precalculate asks its _rawValueRenderer whether it is "stable".

Maybe this is the issue, as that is a bit unexpected. This is an assumption and not defined behaviour. Proposal: replace this assumption with an attribute or and extra method/property on IRawValue

I think it would be nice if we could drop this (from SimpleLayout):

```
var success = _rawValueRenderer.TryGetRawValue(logEvent, out var value);
                    if (success && (Convert.GetTypeCode(value) != TypeCode.Object || value.GetType().IsValueType()))
                        return;

```

as we don't need the value at all. (only the type).

**Comment by snakefoot** [comment]
Yes new issue for that part is a good idea.

**Pull request merged**
