### PR TITLE
GetCurrentClassLogger based on Environment.StackTrace

### PR DESCRIPTION
**Pull request by snakefoot**
Tested with UWP, and it also works. Credits @stil

### CODE REVIEW

**Comment by snakefoot** [comment]
Guess #2140 should be merged to CoreCLR-branch (Together with rest of 4.4.10)

**Comment by 304NotModified** [comment]
FYI, i'm thinking to re-do the .NET standard implementation and then no netstandard 1 (but only netstandard 2). It's waiting on #2154

See also #2152

**Comment by snakefoot** [comment]
Looks like NetStandard 2 will make things very easy. Just have to wait 3 months time for it to be released.

**Comment by snakefoot** [comment]
@stil & @304NotModified Added your suggested solution.

**Comment by stil** [comment]
Thanks! It should also resolve #2162 
I'd hate it if we needed to wait next couple of months for upcoming .NET Standard 2.0.

However it seems it doesn't pass some tests.

**Comment by 304NotModified** [comment]
Yes you're right. Would be great to have this working!

**Comment by snakefoot** [comment]
Very strange the unit test in the CoreClr-branch was different from the main-branch. Now updated the CoreClr-branch.

**Comment by snakefoot** [comment]
@Stil Please try the NuGet-package and see if it works on your machine:

https://ci.appveyor.com/project/nlog/nlog/build/5.0.0-beta5394/artifacts

**Comment by stil** [comment]
@snakefoot I installed it into my projects and it seems to work. I haven't encountered any problems yet. I'll start using it and I hope @304NotModified finds time to review this PR and merge it. New beta release would also be nice.

**Comment by 304NotModified** [comment]
great work!

**Comment by arunprasathv** [comment]
I'm still facing this issue. Is there a fix ?

**Comment by 304NotModified** [comment]
Please create a new issue, thx!

**Pull request merged**
