### PR TITLE
Added LoggingConfiguration.Configure(..)

### PR DESCRIPTION
**Pull request by 304NotModified**
Fixes https://github.com/NLog/NLog/issues/1429

### CODE REVIEW

**Comment by snakefoot** [comment]
@304NotModified Created #3000 for you to see

**Comment by 304NotModified** [comment]
@snakefoot any idea why some unit tests are crashing?

- https://ci.appveyor.com/project/nlog/nlog/builds/20096301
- https://ci.appveyor.com/project/nlog/nlog/builds/20096295

both (different unit tests?) give " Required parameter 'FileName' on 'File Target[target3]"

**Comment by snakefoot** [comment]
Nope

**Comment by 304NotModified** [comment]
maybe another time for this.

**Pull request closed without merging**
