### PR TITLE
Webservicetarget special chars

### PR DESCRIPTION
**Pull request by chwebdude**
# 1724 Made it work. I'm not sure how to handle the chars over 255.

---

This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1728)

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks! 

Could you rebase this on master? As the changes I have made, aren't needed.

**Comment by chwebdude** [comment]
No problem for the code :)

But it's the first time I work with Git. I think I'm messing around a bit too much. Sorry. I tried with `git rebase -i master` and then drop the other commits and then sync, but it doesn't go in the master... I have honestly no idea (I'm working usually with TFVC) :confused:

**Comment by 304NotModified** [comment]
No problem, it can be hard if you not using git on daily basis

I seems that https://github.com/NLog/NLog/pull/1735 is also correcting your issue, isn't?

**Comment by chwebdude** [comment]
Yeah, I just tested #1735 out and it works also.

**Pull request closed without merging**
