### PR TITLE
JsonLayout - EscapeForwardSlash should be nullable

### LINKED ISSUE #3741: Fix EscapeForwardSlash on JsonLayout
The EscapeForwardSlash isn't proper implemented on JsonLayout.

Won't work:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true" internalLogToConsoleError="true">
    <targets>
        <target xsi:type="Console" name="console">
            <layout xsi:type="JsonLayout" includeMdlc="true" escapeForwardSlash="false">
                <attribute name="@timestamp" layout="${date:universalTime=true:format=o}" />
                <attribute name="level" layout="${level:upperCase=true}" />
                <attribute name="message" layout="${message}" />
                <attribute name="exception" layout="${onexception:|${exception:format=ToString}}" />
                <attribute name="logger_name" layout="${logger}" />
                <attribute name="thread_name" layout="${threadid}" />
            </layout>
        </target>
    </targets>

    <rules>
        <logger name="Microsoft.*" maxlevel="Info" final="true" />
        <logger name="*" minlevel="Debug" writeTo="console" />
    </rules>
</nlog>
```

Does work: It _does_ work if I add `escapeForwardSlash="false"` to each JsonAttribute individually though:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" autoReload="true" internalLogToConsoleError="true">
    <targets>
        <target xsi:type="Console" name="console">
            <layout xsi:type="JsonLayout" includeMdlc="true">
                <attribute name="@timestamp" layout="${date:universalTime=true:format=o}" escapeForwardSlash="false" />
                <attribute name="level" layout="${level:upperCase=true}" escapeForwardSlash="false" />
                <attribute name="message" layout="${message}" escapeForwardSlash="false" />
                <attribute name="exception" layout="${onexception:|${exception:format=ToString}}" escapeForwardSlash="false" />
                <attribute name="logger_name" layout="${logger}" escapeForwardSlash="false" />
                <attribute name="thread_name" layout="${threadid}" escapeForwardSlash="false" />
            </layout>
        </target>
    </targets>

    <rules>
        <logger name="Microsoft.*" maxlevel="Info" final="true" />
        <logger name="*" minlevel="Debug" writeTo="console" />
    </rules>
</nlog>
```

- Not sure if we could fix this easily, as EscapeForwardSlash on JsonEncodeLayoutRendererWrapper / JsonAttribute isn't nullable
- We need this for IncludeAllProperties / IncludeGdc etc
- Probable we also need to include JsonEncode / Encode  /  EscapeUnicode on layout level?

### PR DESCRIPTION
**Pull request by snakefoot**
Trying to resolve  #3741. But it will only apply to direct sub-attributes.

If a nested attribute embeds a JsonLayout using encode="false", then it will not inherit the configuration from the top-JsonLayout (There is no guaranteed of the order of initializing NLog Layouts)

### CODE REVIEW

**Comment by 304NotModified** [comment]
Great!

**Comment by 304NotModified** [comment]
Great work thank!

**Comment by chazt3n** [comment]
How is this done via API?

**Comment by snakefoot** [comment]
@chazt3n Think you have to explain what you want to do, since I cannot guess what you want. `EscapeForwardSlash` is property you can assign on JsonLayout and JsonAttribute:

https://nlog-project.org/documentation/v4.7.0/html/T_NLog_Layouts_JsonLayout.htm
https://nlog-project.org/documentation/v4.7.0/html/T_NLog_Layouts_JsonAttribute.htm

See also: https://stackoverflow.com/a/61033465/193178

**Comment by chazt3n** [comment]
@snakefoot my question was how would I set EscapeForwardSlash property via the fluent API. (i.e. code)

It is actually right on the JsonLayout object! Which is so super awesome. Thank you

**Comment by chazt3n** [comment]
I see now that it may be a recent addition to the API's? My brand new things have it and older things the same code doesn't compile. Could be just doing something stupid.

**Comment by snakefoot** [comment]
@chazt3n Do you have an error-message from the compiler? 

Remember to upgrade to the latest version of NLog in your older project to access the latest NLog-features.

**Comment by 304NotModified** [comment]
@chazt3n please open a new issue and provide more details (see explanation).

**Pull request merged**
