### PR TITLE
Async / buffering wrapper: Improve performance when blocking

### PR DESCRIPTION
**Pull request by snakefoot**
ConcurrentRequestQueue - Always see queue as empty after reached RequestLimit (and resolved it)

When reaching the RequestLimit, then producers perform asymmetric update of queue-count.

Instead of trying to coordinate which of the producers should signal start-timer, then all producers will signal start-timer since it is "exceptional" situation.

### CODE REVIEW

**Comment by 304NotModified** [comment]
Hi,

Is this a bug fix or an (performance)enhancement?

**Comment by snakefoot** [comment]
It is continuation from #3416 where I tried to fix the "bug" of failing to handle a RequestLimit of 2 with Blocking-mode.

**Comment by snakefoot** [comment]
It is a simplification of the previous commit. So instead of trying to be clever then it just takes a performance hit when blocking mode has been activated.


The simplication reduces the number of modifications of the _count variable, so less memory write barriers are needed when blocking mode is activated. Improves the concurrency of the producers as they are less chatty.


But now all producers will eagerly try to wake the timer-thread after blocking mode has been activated. This might kill any performance gain from improving producer concurrency.


But I like the simplicity of this change, and my simple performance tests still shows good performance


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


Hi,

Is this a bug fix or an (performance)enhancement?

**Comment by 304NotModified** [comment]
thanks! Merged!

**Pull request merged**
