### PR TITLE
Fix typo in comment

### PR DESCRIPTION
**Pull request by KurnakovMaksim**
Little fix in comment

### CODE REVIEW

**Comment by snakefoot** [comment]
Reluctant in fixing comment spelling errors in methods that have been marked obsolete :)

**Comment by snakefoot** [comment]
I'm surprised :) Since none of the NLog-maintainers have english as native tongue, so there should be lots of opportunities for improving sentences.

**Comment by snakefoot** [comment]
Maybe install this Visual Studio Extension, and in Visual Studio-menu "Tools" -> "Spellchecker" -> "Spellcheck current project" (Ensure NLog-project is marked **bold** as "Startup"-project ).

https://marketplace.visualstudio.com/items?itemName=EWoodruff.VisualStudioSpellCheckerVS2017andLater&ssr=false#qna

**Comment by KurnakovMaksim** [comment]
@snakefoot Thank you! This is a useful tool, I'll try to find something in the near future.

**Comment by snakefoot** [comment]
Alternative just search for "the the" and "with with" and fix those places in the source-code

**Comment by KurnakovMaksim** [comment]
I hope these fixes are enough :)

**Comment by snakefoot** [comment]
I asked for 3, and you gave me more.

**Comment by snakefoot** [comment]
Thank you for the contribution. I also tried the Spell Checker, and found some more obvious mistakes here #4968.

But I find the Spell Checker-extension extremely sluggish, and interferes with my code-navigation, so I have uninstalled it again.

**Pull request merged**
