### PR TITLE
MappedDiagnosticsLogicalContext - SetScoped with IReadOnlyList

### LINKED ISSUE #2948: MDLC Allow pushing a list of properties
Microsoft Extension Logging comes with BeginScope with 2-3 properties. See ActionLogScope  and HostingLogScope.

Instead of calling MappedDiagnosticsLogicalContext.SetScoped for each property, then it could be nice if one could deliver an `IList<KeyValuePair<string,object>>`

This would allow NLog to skip allocation of new Dictionary for every SetScoped-call (Along with skip allocation of Stack-collection in NLog.Extension.Logging)

### PR DESCRIPTION
**Pull request by snakefoot**
Resolves #2948 (And skips allocation of new dictionary when going to clear it by removing the last item).

### CODE REVIEW

**Comment by snakefoot** [comment]
Looks like the cloud has become broken again in the Travis-world. Maybe tomorrow the cloud is working again.

**Comment by 304NotModified** [comment]
Like the other PR, I just restart it on travis. It's indeed a bit unstable lately.

**Comment by snakefoot** [comment]
@304NotModified Seems SetLastWriteTime is not working that well on NetCore. Have now disable the test for NetCore on Travis.

**Comment by snakefoot** [comment]
Made a small performance test using a test-build with this PR:

| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| BeginScope with 2 Params |  5.000.000 |  12 |    2 |       2 |       1 |

| Test Name  | Msgs/sec  | CPU (ms) | Alloc (MB) |
|------------|-----------|----------|------------|
| This PR  |   360513 |   27,1 |     6.375,1 |
| Master    |    294867|   33,1 |   11.284,9 |
| Serilog 2.7.1 | 169176 | 55,7 |   19.731,3 |

**Pull request merged**
