### PR TITLE
Added new() contraint on LogFactory<T>

### PR DESCRIPTION
**Pull request by 304NotModified**
Fixes https://github.com/NLog/NLog/issues/962

### CODE REVIEW

**Comment by snakefoot** [comment]
Think #3990 and #3986 should be one PR. And the idea is to call the new-operator.

**Comment by 304NotModified** [comment]
superseded by https://github.com/NLog/NLog/pull/3990

**Comment by 304NotModified** [comment]
>  And the idea is to call the new-operator.

Do you mean we should make a new method internally that is generic? I don't think that will work well with _loggerCache etc. (not work well as in: lot of code duplication, and not really in improvement?)

**Comment by snakefoot** [comment]
Think one could send a factory-lambda into the internal GetLogger-method. But the whole new-exercise is fruitless if you are not calling the new-operator


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


And the idea is to call the new-operator.

Do you mean we should make a new method internally that is generic? I don't think that will work well with _loggerCache etc. (not work well as in: lot of code duplication, and not really in improvement?)

**Comment by 304NotModified** [comment]
> Think one could send a factory-lambda into the internal GetLogger-method. But the whole new-exercise is fruitless if you are not calling the new-operator

I think the new constraint with the Activtor is just fine. The benefit of new() is that it's clear how the instance is created (and that we need a public ctor, although not the case for our own Logger).

Is there a (performance?) benefit of using `new` compared to the activator?

**Pull request closed without merging**
