### PR TITLE
WIP Mono2+mono4

### PR DESCRIPTION
**Pull request by 304NotModified**
Split mono to mono2 and mono4, for https://github.com/NLog/NLog/issues/1644

todo:
- [x] build NLog for mono2
- [x] build NLog unit tests for mono2
- [x] fix mono.posix for mono2
- [ ] run both on Travis
- [ ] fix mono2 issues
- [ ] update docs
- [ ] remove mutex for Mono?

This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1682)

### CODE REVIEW

**Comment by snakefoot** [comment]
Could imagine that all tests in ConcurrentFileTargetTests are failing. Tried for fun to run the UnitTests using the Net35-Solution and adding NET3_5 to the list of systems not having #define SupportsMutex

**Comment by 304NotModified** [comment]
Yes I think we have to replace the mutex with something else/before

**Comment by snakefoot** [comment]
The standard low-tech global mutex solution is to create a filehandle with non-sharing read/write. The one being able to open the file handle has the "mutex"-file.

**Comment by 304NotModified** [comment]
local test results:

image

**Comment by 304NotModified** [comment]
squashed and rebased with master

**Comment by 304NotModified** [comment]
almost there. MONO2:

```
NLog.UnitTests.Targets.ConcurrentFileTargetTests.BufferedTimedFlushConcurrentTest(mode: "buffered_timed_flush") [FAIL]
   Assert.Equal() Failure
   Expected: 0
   Actual:   134
   Stack Trace:
     at NLog.UnitTests.Targets.ConcurrentFileTargetTests.DoConcurrentTest (Int32 numProcesses, Int32 numLogs, System.String mode) [0x00000] in <filename unknown>:0 
     at NLog.UnitTests.Targets.ConcurrentFileTargetTests.BufferedTimedFlushConcurrentTest (System.String mode) [0x00000] in <filename unknown>:0 
     at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
     at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0

NLog.UnitTests.Targets.ConcurrentFileTargetTests.BufferedConcurrentTest(mode: "buffered") [FAIL]
   Assert.Equal() Failure
   Expected: 0
   Actual:   134
   Stack Trace:
     at NLog.UnitTests.Targets.ConcurrentFileTargetTests.DoConcurrentTest (Int32 numProcesses, Int32 numLogs, System.String mode) [0x00000] in <filename unknown>:0 
     at NLog.UnitTests.Targets.ConcurrentFileTargetTests.BufferedConcurrentTest (System.String mode) [0x00000] in <filename unknown>:0 
     at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
     at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0
```

@snakefoot could help me with these two tests? :)

and multiple settimespan from string tests

```
NLog.UnitTests.Config.XmlConfigTests.SetTimeSpanFromXmlTest(interval: "1:0:0:0", seconds: 86400) [FAIL]
   Assert.NotNull() Failure
NLog.UnitTests.Config.XmlConfigTests.SetTimeSpanFromXmlTest(interval: "0:0:1:1", seconds: 61) [FAIL]
   Assert.NotNull() Failure
NLog.UnitTests.Config.XmlConfigTests.SetTimeSpanFromXmlTest(interval: "000:0000:000:001", seconds: 1) [FAIL]
   Assert.NotNull() Failure

...
```

**Comment by snakefoot** [comment]
@304NotModified Don't have a Mono environment running. So I have to use old school debugging (write internal-log to assert statement) when debugging tests for Travis/Mono. Not something I'm really fond of, so I will skip the offer :)

**Comment by 304NotModified** [comment]
any clues for me then? It the last 2 issues!

**Comment by snakefoot** [comment]
> any clues for me then? It the last 2 issues!

Never run a Mono-application, but I'm guessing there is some issue with parsing the timespan-strings, that causes an exception when loading the NLog-configuration.

**Comment by 304NotModified** [comment]
yes the timespan parses has been fixed 

it's the BufferedConcurrentTest and BufferedTimedFlushConcurrentTest which I don't get

**Comment by snakefoot** [comment]
> it's the BufferedConcurrentTest and BufferedTimedFlushConcurrentTest which I don't get

Well I guess you can activate the debug-code, I have left from last time I was diagnosing multiprocess-logging, so the spawned processes writes the exception to a process-specific internal log-file And when the unit-test gets a non-zero exit-code, then it loads the matching internal-log-file and displays the contents of the log-file using an assert(internal-log-content, string.Empty)

**Comment by 304NotModified** [comment]
thx! see the testcode!

**Comment by 304NotModified** [comment]
MONO2 (not mono4)

```
2017-03-04 23:36:50.7392 Trace Closing '/tmp/ffebf815-5fdf-48f5-b798-d9a6d15492fb/test_5_1000_none_mutex.txt'
2017-03-04 23:36:50.7406 Trace Closing '/tmp/ffebf815-5fdf-48f5-b798-d9a6d15492fb/test_5_1000_none_mutex.txt'
2017-03-04 23:36:50.7419 Trace Closing Layout Renderer: ${literal}
2017-03-04 23:36:50.7437 Trace Closing '${message}'
2017-03-04 23:36:50.7441 Trace Closing Layout Renderer: ${message}
2017-03-04 23:36:50.7441 Debug Finished closing logging configuration.
2017-03-04 23:36:50.7458 Trace Continuation invoked: 
2017-03-04 23:36:50.7480 Trace Parallel task completed. 0 items remaining
2017-03-04 23:36:50.7465 Error Logger failed to shut down properly. Exception: System.NullReferenceException: Object reference not set to an instance of an object
  at NLog.LogFactory.OnStopLogging (System.Object sender, System.EventArgs args) [0x00000] in <filename unknown>:0 
2017-03-04 23:36:50.7564 Debug Closing logging configuration...
2017-03-04 23:36:50.7608 Trace Closing File Target[(unnamed)]
Stacktrace:


Native stacktrace:

	/usr/bin/mono() [0x4b73d8]
	/usr/bin/mono() [0x50f13b]
	/usr/bin/mono() [0x423d22]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x10330) [0x7ffbedddc330]
	/usr/bin/mono() [0x5e30c7]
	/usr/bin/mono() [0x5e338d]
	/usr/bin/mono() [0x5d88cd]
	/usr/bin/mono() [0x5da3da]
	/usr/bin/mono() [0x5db034]
	/usr/bin/mono() [0x5de4f8]
	/usr/bin/mono(mono_gc_collect+0x28) [0x5ded98]
	/usr/bin/mono(mono_domain_finalize+0x5c) [0x5abc1c]
	/usr/bin/mono() [0x41b82b]
	/usr/bin/mono(mono_main+0x1159) [0x48caf9]
	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7ffbeda28f45]
	/usr/bin/mono() [0x419c1a]

Debug info from gdb:

2017-03-04 23:36:50.7726 Debug FileAppender Closing Invalidate - /tmp/ffebf815-5fdf-48f5-b798-d9a6d15492fb/test_5_1000_none_mutex.txt

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
```

**Comment by snakefoot** [comment]
@304NotModified Maybe MONO2 should not react to DomainUnload and ProcessExit?

**Comment by 304NotModified** [comment]
superseded by vs2017

**Pull request closed without merging**
