### PR TITLE
TryGetRawValue instead of GetRawValue

### PR DESCRIPTION
**Pull request by 304NotModified**
part of #3140

### CODE REVIEW

**Comment by 304NotModified** [comment]
@snakefoot merge or no merge for this one. What do you think?

**Comment by snakefoot** [comment]
Well if you want the WhenEmpty to work, then you need something like this.

I guess I would change SimpleLayout, so when one rawvalue-lookup fails then it will stop trying to use the rawvalue-lookup-interface (set it to null).

**Comment by 304NotModified** [comment]
> Well if you want the WhenEmpty to work, then you need something like this.

Yes, I like that. (in the future)



> I guess I would change SimpleLayout, so when one rawvalue-lookup fails then it will stop trying to use the rawvalue-lookup-interface (set it to null).

Could you elaborate on that (or PR?) Thanks!

**Comment by snakefoot** [comment]
> Could you elaborate on that (or PR?) Thanks!

You can just look at how `_stringValueRenderer` is assigned null. Same could be done for `_rawValueRenderer` when it fails (returns false).

**Comment by 304NotModified** [comment]
well, next time (e.g. with the ${when}, ) it could return true. See #3140

**Comment by snakefoot** [comment]
That will only happen if the Layout suddenly contains a different layoutrenderer. Funky wonky logic is not good.

**Comment by 304NotModified** [comment]
no it doesn't? one part of the ${when} has a irawvalue-layout and the other a non-irawvalue layout. e.g. the example in the PR: `${when:${db-null}:when=logger=='logger':else=better}`

**Comment by snakefoot** [comment]
Should only work when both layouts supports rawvalue


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


no it doesn't? one part of the ${when} has a irawvalue-layout and the other a non-irawvalue layout. e.g. the example in the PR: ${when:${db-null}:when=logger=='logger':else=better}

**Comment by snakefoot** [comment]
It is going to be strange logic with overhead, because you will be executing the when-clause multiple times if the resulting layout doesn't support rawvalue.

But as long you make sure that the rawvalue-probe-logic (casting and double-checking when-condition) only happens when having explicitly specified PropertyType / ParameterType / DbType different from string-type. Then can you add whatever you need. Hopefully this extra raw-code-path will have minimal impact on future code-maintenance.

**Pull request merged**
