### PR TITLE
Also check current working directory for nlog.config (DNX compatible)

### LINKED ISSUE #1342: Config file not found when running via .NET Core
We have a DNX application that we run through Visual Studio or via the command line as in 

```
dnx.exe --project "[path to my project.json]" run
```

There is an _NLog.config_ file in the project's folder, but NLog does not find it. This is because NLog is looking in the `BaseDirectory` of the current app domain, and under this environment that directory is the directory of DNX (where dnx.exe resides). In this scenario the correct directory is given by `Directory.GetCurrentDirectory()`.

**Type**:
- Bug

**NLog version**: 4.2.3 (current build also)

**Platform**: DNX 1.0.0-RC1-Final

### PR DESCRIPTION
**Pull request by 304NotModified**
Also check current working directory for nlog.config (DNX compatible)
But don't try twice the same file.

supersedes #1343

fixes #1342

### CODE REVIEW

**Comment by bhaeussermann** [comment]
Thanks! I will pull this to double-check if it works for me tomorrow before I merge it.

**Comment by 304NotModified** [comment]
I think @phenixdotnet is right and this change isn't good :(

**Comment by bhaeussermann** [comment]
> I think @phenixdotnet is right and this change isn't good :(

That is a valid point, and unfortunately I don't know of another way to get to the right folder path.

For now, we are loading the config "manually" by constructing the `XmlLoggingConfiguration` object with the correct path and assigning it to `LogManager.Configuration`. I suppose "tricky" cases like these are to be handled this way until we can find a way for NLog to find the correct path automatically.

**Comment by 304NotModified** [comment]
> For now, we are loading the config "manually" by constructing the XmlLoggingConfiguration object with the correct path and assigning it to LogManager.Configuration

Well, that is also not a good solution, see https://github.com/NLog/NLog.Extensions.Logging/issues/24

**Comment by bhaeussermann** [comment]
@304NotModified Thanks! I'll look into that.

**Comment by phenixdotnet** [comment]
@304NotModified No ideas here, this thing drive me crazy. Same call (IE ```PlatformServices.Default.Application.ApplicationBasePath```) give you 2 differents behaviors based on app context

I hope it will be fixed in rc2.

**Comment by 304NotModified** [comment]
Anyway this isn't an improvement

**Pull request closed without merging**
