### PR TITLE
${event-properties} - Added culture and format properties

### LINKED ISSUE #870: Add format property for event-properties layout renderer
See #868

Example:

```xml
<parameter name="@CreationDate" layout="${event-propertiest:item=creationDate:format=dd-MM-yy}" />
```

### PR DESCRIPTION
**Pull request by 304NotModified**
Examples:

`"${event-properties:prop1:format=yyyy-M-dd}";`

`"${event-properties:aaa:culture=nl-NL}`

closes #870

### CODE REVIEW

**Comment by BrutalCode** [comment]
@304NotModified Hey! I read your codes in this commit and I read another related issues. I got the idea.
Is it enough that explain _Culture_ and _Format_ parameters in the *Parameters* section?
And correct the *Configuration Syntax*, giving an example also.

Related wiki page:
https://github.com/NLog/NLog/wiki/EventProperties-Layout-Renderer

Is that right?

**Comment by 304NotModified** [comment]
Yes that's correct. An example is nice-to-have.

**Comment by 304NotModified** [comment]
And please add: "introduced in NLog 6.1"

**Comment by BrutalCode** [comment]
I made changes at wiki page.
https://github.com/NLog/NLog/wiki/EventProperties-Layout-Renderer

**Pull request merged**
