### PR TITLE
FileTarget: set writing BOM initial to true for UTF-16 and UTF-32

### PR DESCRIPTION
**Pull request by 304NotModified**
Fixes https://github.com/NLog/NLog/issues/2533

### CODE REVIEW

**Comment by 304NotModified** [comment]
Waiting for https://github.com/NLog/NLog/pull/3978

**Comment by snakefoot** [comment]
Funny how `Encoding`-property is not a RequiredParameter.

**Comment by snakefoot** [comment]
Maybe some comments about the abbreviations (le = little endian, be - big endian).

| Codepage | Encoding | Description |
| ----- | ---- | --- |
| 1200 | utf-16 | Unicode UTF-16, little endian byte order (BMP of ISO 10646); available only to managed applications |
| 1201 | unicodeFFFE | Unicode UTF-16, big endian byte order; available only to managed applications |
| 12000 | utf-32 | Unicode UTF-32, little endian byte order; available only to managed applications |
| 12001 | utf-32BE | Unicode UTF-32, big endian byte order; available only to managed applications |

https://docs.microsoft.com/en-us/windows/win32/intl/code-page-identifiers

**Comment by 304NotModified** [comment]
> Funny how `Encoding`-property is not a RequiredParameter.

Because it has a default?

**Comment by 304NotModified** [comment]
> Maybe some comments about the abbreviations (le = little endian, be - big endian).
> 
> Codepage	Encoding	Description
> 1200	utf-16	Unicode UTF-16, little endian byte order (BMP of ISO 10646); available only to managed applications
> 1201	unicodeFFFE	Unicode UTF-16, big endian byte order; available only to managed applications
> 12000	utf-32	Unicode UTF-32, little endian byte order; available only to managed applications
> 12001	utf-32BE	Unicode UTF-32, big endian byte order; available only to managed applications
> https://docs.microsoft.com/en-us/windows/win32/intl/code-page-identifiers

Maybe nice in the wiki. But in source sounds a bit out of scope? Without BE/LE the BOM construct wasn't really needed ;)

**Comment by snakefoot** [comment]
> Because it has a default?

Still required

**Comment by snakefoot** [comment]
Updated wiki https://github.com/NLog/NLog/wiki/File-target about writeBom being enabled automatically when using UTF16 + UTF32

**Pull request merged**
