### PR TITLE
new SHFB config [wip]

### PR DESCRIPTION
**Pull request by 304NotModified**
- Created new SHFB config for NLog 4
- Removed old en unused:
 - tools
 - configs
 - scripts

SHFB.exe is no longer in this repos. I could not get it working without installing it locally, hence the .exe in the repos is unused.

### CODE REVIEW

**Comment by 304NotModified** [comment]
The SHFB is working, but not with the mbuild target. Maybe we should fix that before merge of this one?

**Comment by Xharze** [comment]
What is the problem when running with MSBuild?

**Comment by 304NotModified** [comment]
This config is separated developed, without any msbuild  / script integration. 

I cannot integrate in the MSbuild targets, as it's fully undocumented.

**Comment by Xharze** [comment]
Could you create a script file or similar generating the documentation? Then this can be called from MSBuild

**Comment by 304NotModified** [comment]
Yes I will. I will let you know when it's done

**Comment by 304NotModified** [comment]
I will re-open this in the future

**Pull request closed without merging**
