### PR TITLE
 Added TypesInInternalNamespaceShouldBeInternalTest

### PR DESCRIPTION
**Pull request by 304NotModified**
Currently the issues: "NLog.Internal.Xamarin.PreserveAttribute" + "NLog.Internal.Fakeables.IAppDomain"

move the namepaces for those?

proposal:

-  "NLog.Internal.Xamarin.PreserveAttribute" -> "NLog.Xamarin.PreserveAttribute" 
- "NLog.Internal.Fakeables.IAppDomain" ->  "NLog.IAppDomain"

### CODE REVIEW

**Comment by 304NotModified** [comment]
@snakefoot you mentioned somewhere you like to have this test, isn't?

**Comment by snakefoot** [comment]
> you mentioned somewhere you like to have this test, isn't?

Yes I prefer types in NLog.Internal-namespace are not leaked by accident.

**Comment by snakefoot** [comment]
> Currently the issues: "NLog.Internal.Xamarin.PreserveAttribute" + "NLog.Internal.Fakeables.IAppDomain"

I think there should be an opt-out-list for accepted types. Where `PreserveAttribute` is one of them. But I think `IAppDomain` should not be public.

Funny that it doesn't see `public static class XmlHelper`.

**Comment by 304NotModified** [comment]
> I think there should be an opt-out-list for accepted types. Where `PreserveAttribute` is one of them

But why should we have it in the internal namespace then?

**Comment by 304NotModified** [comment]
> Funny that it doesn't see `public static class XmlHelper`.

Well detecting if it's internal is a bit hard, but look into this

**Comment by snakefoot** [comment]
> But why should we have it in the internal namespace then?

Similar to how Microsoft handles its API. Public classes in the Internal-namespace are subject to change and not guaranteed to be completely stable.

Ex. PreserveAttribute is not intended for others to use, but just a class used for tooling, so NLog-assembly works better on the Xamarin-platform. Internal for NLog alone, and should not be used by others. But have to be public or else the Xamarin-tooling will get sad.

**Comment by 304NotModified** [comment]
fixed, now we have these:


- NLog.Internal.IConfigurationManager 
- NLog.Internal.IUsesStackTrace 
- NLog.Internal.ConfigurationManager 
- NLog.Internal.StreamHelpers 
- NLog.Internal.StringHelpers 
- NLog.Internal.XmlHelper 
- NLog.Internal.Fakeables.IAppDomain

**Comment by 304NotModified** [comment]
IUsesStackTrace should be public?

**Comment by snakefoot** [comment]
I think they should be made internal with NLog 5.0, and skipping the step with marking them "obsolete" first.

**Comment by 304NotModified** [comment]
yes there where a bit marked already by the namepace :)

**Comment by 304NotModified** [comment]
IAppDomain is hard to be internal, as LogFactory has CurrentAppDomain

**Comment by snakefoot** [comment]
But it would make sense to move `IUsesStackTrace` into NLog.Layout-namespace.

**Comment by snakefoot** [comment]
> IAppDomain is hard to be internal, as LogFactory has CurrentAppDomain

But why does LogFactory exposure CurrentAppDomain ?

**Comment by 304NotModified** [comment]
> But why does LogFactory expose CurrentAppDomain ? Some kind of special use-case ?

I really don't know. Doubting if we should obsolete it. Just make it internal sounds breaking. Maybe google (duckduckgo / github search) if someone uses it

**Comment by 304NotModified** [comment]
only forks, https://github.com/search?l=C%23&p=2&q=Factory.CurrentAppDomain&type=Code

but of course a bit sloppy search

**Comment by snakefoot** [comment]
Also did a sloppy search for CurrentAppDomain + LogFactory and then CurrentAppDomain + LogManager.

Neither revealed any source-code outside the NLog-repository. But some callstacks where both where included.

Doesn't look like anyone is using CurrentAppDomain for anything exciting.

**Comment by 304NotModified** [comment]
I think we should handle

**Comment by 304NotModified** [comment]
superseded by https://github.com/NLog/NLog/pull/4331

**Pull request closed without merging**
