### PR TITLE
JsonLayout

### PR DESCRIPTION
**Pull request by vladikk**
A new layout that renders log events as structured JSON documents.
The implementation and setup are similar to the CsvLayout:

``` XML
<target name="jsonFile" xsi:type="File" fileName="${logFileNamePrefix}.json">
      <layout xsi:type="JsonLayout">
              <attribute name="time" layout="${longdate}" />
              <attribute name="level" layout="${level:upperCase=true}"/>
              <attribute name="message" layout="${message}" />
              <attribute name="callsite" layout="${callsite:includeSourcePath=true}" />
              <attribute name="stacktrace" layout="${stacktrace:topFrames=10}" />
              <attribute name="exception" layout="${exception:format=ToString}"/>
       </layout>
</target>
```

### CODE REVIEW

**Comment by grbinho** [comment]
Hi.
First of all I think this is a great addition to the library.

I'm trying to use it, but i have a problem with nested objects. If you want to add something like a property bag to event-context that is already serialized Json, this layout will escape it. 

Were nested objects a consideration for this feature or just plain key value pairs?

Ivan

**Comment by grbinho** [comment]
Hi,

First of all, I think this is a great addition to NLog. 

I have a question about nested JSON objects.

Is this intended only of key value pairs? Can we nest our own JSON? Something like a property bag that we serialize and add to event-context. 

As far as i can see all attributes are not json-encoded. That means that attributes that are already valid JSON will get escaped where that is not needed or am i missing something?
It would be beneficial if encoding is a property on the attribute.

Best,
Ivan

**Comment by 304NotModified** [comment]
Hi,

We do you mean with 
> As far as i can see all attributes are not json-encoded.

So far I know, everything is encoded with the `JsonEncodeLayoutRendererWrapper`.

I think other objects besides key-value pairs would be nice. Please create a new issue for this feature request if you like. An (config) example would be nice.

**Comment by grbinho** [comment]
Sorry, tipo :)

I have forked the project and implemented a small change.

I have added encode attribute on JsonAttribute so that user can control if output should be encoded. Setting this to false will enable user to add arbitrary JSON into context.

I'm still missing some tests, but can eventually create a pull request if you find it interesting.

**Comment by 304NotModified** [comment]
I find it interesting :+1: 

PR is welcome, but I does need some unit tests (and examples for the documentation)

**Comment by grbinho** [comment]
Ok. Great, I will try to get that done as soon as possible.

**Pull request merged**
