### PR TITLE
FallbackGroupTarget - Fixed spelling of WINDOWS_PHONE define + improvement GarbageCollection2Test() unit test on Travis

### PR DESCRIPTION
**Pull request by snakefoot**

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks!

**Comment by 304NotModified** [comment]
Travis seems to be broken

> 0.50sE: Unable to locate package dotnet-sdk-2.0.0
E: Couldn't find any package by glob 'dotnet-sdk-2.0.0'
E: Couldn't find any package by regex 'dotnet-sdk-2.0.0'
The command "sudo apt-get install -qq dotnet-sdk-2.0.0" failed and exited with 100 during .

**Comment by 304NotModified** [comment]
Fix?
https://www.queryxchange.com/q/27_55757025/travis-e-unable-to-locate-package-dotnet-sdk-2-0-0/

**Comment by snakefoot** [comment]
Trusty is Ubuntu 14.04
Xenial is Ubuntu 16.04

Major version is the release year. Guess there is nothing wrong with upgrading Travis to year 2016.

**Comment by 304NotModified** [comment]
Indeed! #3325

**Pull request merged**
