### PR TITLE
FileTarget - Added extra archive check is needed, after closing stale file handles

### PR DESCRIPTION
**Pull request by snakefoot**
As shown by #1513, then it is possible for two (or more) processes to detect that a file should be archived.

There is no protection against the case that one process is faster than the others, and performs the archive and creates the new file with its new entry. The next process will then archive the newly created file, and create its own new file.

To protect against this, then a bonus archive-is-needed-check is done after having taken the archive-mutex (And closed stale file handles). This will ensure the next process doesn't succeed in performing the archive operation (will see the archive operation has been done).

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1771)

### CODE REVIEW

**Comment by snakefoot** [comment]
Little curious about the disconnect between FileTarget.CleanupInitializedFiles() and FileTarget.fileAppenderCache.CloseAppenders().

I guess the File-Footer-Logic is not intended to be used with ConcurrentWrites.

**Comment by 304NotModified** [comment]
> Little curious about the disconnect between FileTarget.CleanupInitializedFiles() and FileTarget.fileAppenderCache.CloseAppenders().

Think that's wrong.

> I guess the File-Footer-Logic is not intended to be used with ConcurrentWrites.

Guess it's forgotten ;)

**Comment by snakefoot** [comment]
Have now changed the call from CloseAppenders() to just invalidating a single filename (And also cleanup the InitializedFiles-map)

**Comment by 304NotModified** [comment]
👍 looks good!

**Comment by 304NotModified** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1771)*

**Comment by snakefoot** [comment]
After looking at the code a little more. Then it seems that the whole mutex-thing (along with the new extra bonus check) should be moved closer down to FileTarget.ArchiveFile.

The archive-mutex only helps while writing to the log-file, but doesn't protect against races at opening/closing the FileTarget. This seems to be an issue independent of using keepFileOpen or not. But there is a lot bonus-archive logic (Ex. rolling log-files), that also might need protection of the archive-mutex. 

But I think the possible multi-process archive-issues at startup/shutdown are for another PR. And not sure I will be making it :)

**Comment by 304NotModified** [comment]
> But I think the possible multi-process archive-issues at startup/shutdown are for another PR. And not sure I will be making it :

Agree on that. Maybe we should create a github issue

Thanks again!

**Comment by 304NotModified** [comment]
Does this PR fixes https://github.com/NLog/NLog/pull/1771?

**Comment by 304NotModified** [comment]
Thanks!

**Pull request merged**
