### PR TITLE
Introduced NLog.AppConfig for .NET 45 + .NET Standard 2.0

### PR DESCRIPTION
**Pull request by snakefoot**
Allow access to appsettings in app.config (or web.config) without using NLog.Extended (That depends on Msmq).

Also added support for NetStandard2.0 (See https://www.nuget.org/packages/System.Configuration.ConfigurationManager/4.4.0)

Decided not to make a file-link into NLog.Extended, because it enforced caching. Instead one have to manually use `${appsetting:cached=true:name=MySetting}`.

### CODE REVIEW

**Comment by snakefoot** [comment]
Will create another nuget-package NLog.Extension.Configuration for reading appsettings.json.

**Comment by snakefoot** [comment]
Created https://github.com/NLog/NLog.Extensions.Logging/pull/245 for Net Core AppSettings.json

**Comment by 304NotModified** [comment]
Why not call it NLog.AppSettings?

This also works for web.config

**Comment by snakefoot** [comment]
> AppConfig is a bit confusing as this also works for web.config

I hope people who knows about WebConfig, also knows about AppConfig. And that they cover the same logic.

But yes I chose the name AppConfig to make it very different from appsettings.json.

**Comment by 304NotModified** [comment]
> I guess this nuget-package should also include the logic to load NLog-LoggingConfiguration from AppConfig. Though right now it collides a little with NLog own attempt to load from AppConfig.

good one. I don't think we should hold this PR? I think this should be NLog 5.0?

**Comment by snakefoot** [comment]
> I don't think we should hold this PR? I think this should be NLog 5.0?

No we can start the nuget-package without having this feature. If NLog 5.0 is the "minor" breaking release, and NLog 6.0 is the "major" breaking release. Then I guess auto-loading NLog-Configuration from App.Config should be in NLog 6.0

**Comment by snakefoot** [comment]
> For appsettings.json etc. in ASP.NET core, use ${configsetting:name-MySetting} in https://www.nuget.org/packages/NLog.Extensions.Logging

Should probably be:

> For appsettings.json etc. in ASP.NET core, use ${configsetting:name-MySetting} from https://www.nuget.org/packages/NLog.Extensions.Configuration

**Comment by snakefoot** [comment]
And there came the push :)

**Comment by 304NotModified** [comment]
thanks :)

**Comment by snakefoot** [comment]
Created https://github.com/NLog/NLog.Extensions.Logging/pull/248 to include details about `${configsetting}` in https://www.nuget.org/packages/NLog.Extensions.Configuration

**Comment by 304NotModified** [comment]
SimpleConcurrentTest is really unstable lately. :(

**Comment by snakefoot** [comment]
Been trying to implement a working solution with automatic loading of nlog-config from app.config, and it has not been a success.

Since the app-config loading only happens for NetFramework, and the NetFramework is entering maintance-mode. Then I don't think that having this dependency for NetFramework will be a big problem.

**Comment by snakefoot** [comment]
Closing this issue in favor of #3053

**Pull request closed without merging**
