### PR TITLE
Logger should not crash when platform cannot capture StackTrace

### PR DESCRIPTION
**Pull request by snakefoot**
Minor refactoring and adding of exception-handler. See also https://github.com/KoalaBear84/OpenDirectoryDownloader/issues/19

Note merge to master (And NLog 4.7)

### CODE REVIEW

**Comment by 304NotModified** [comment]
close/reopen to trigger CI (Travis and AppVeyor)

**Comment by 304NotModified** [comment]
PS Resharper highlighted me this small mistake (9f24196)

**Comment by 304NotModified** [comment]
> src\NLog\LoggerImpl.cs(106,49): Error CS1503: Argument 1: cannot convert from 'int' to 'System.Exception'

I don't get this error?

**Comment by snakefoot** [comment]
> PS Resharper highlighted me this small mistake (9f24196)

Thanks for fixing the mistake, and for the merge. Have updated the PR with changelog.

**Pull request merged**
