### PR TITLE
Fix: LogFactoryTests remove Windows specific values

### PR DESCRIPTION
**Pull request by ie-zero**
Fixed some of the tests in LogFactoryTests class which they were using Windows specific temporary directory location i.e. C:\temp. Now the temp directories are created through managed code.

### CODE REVIEW

**Comment by ie-zero** [comment]
Following the comment from @ArsenShnurkov at #958 "MONO_4_0 support" I removed the Windows specific hardcode values.

It appears though the mono built still breaks.

**Comment by ArsenShnurkov** [comment]
* Assertion at mini-exceptions.c:856, condition `unwind_options == MONO_UNWIND_NONE' not met

i think that your mono version is not current (because line number is different)
https://github.com/mono/mono/blob/8cfef6d19071ed2215b13b4ded3b916752364c2d/mono/mini/mini-exceptions.c#L843

But it need to be researched even for most recent version of mono

**Comment by ArsenShnurkov** [comment]
see https://github.com/mono/mono/pull/1649

Should work on mono >= mono-4.2.0.179

**Comment by ie-zero** [comment]
I will have a look. Thank you @ArsenShnurkov

**Comment by 304NotModified** [comment]
Thanks! 

Would be nice if those tests were working with mono. 

I dunno which mono version we use at travis. I think 2

**Comment by ArsenShnurkov** [comment]
travis uses
Mono JIT compiler version 4.0.4 (Stable 4.0.4.1/5ab4c0d Tue Aug 25 23:11:51 UTC 2015)

you can see that in the build log

**Comment by 304NotModified** [comment]
> Mono JIT compiler version 4.0.4 (Stable 4.0.4.1/5ab4c0d Tue Aug 25 23:11:51 UTC 2015)

**Comment by 304NotModified** [comment]
Haha I'm too late :beer:

**Comment by ArsenShnurkov** [comment]
By default build service uses latest version of mono from Xamarin Repositories:
https://github.com/travis-ci/travis-ci/issues/4727#issuecomment-136500307

The docs don't say where Xamarin Repositories reside:
http://docs.travis-ci.com/user/languages/csharp/#Choosing-Mono-version-to-test-against

**Comment by ArsenShnurkov** [comment]
Addition of 

    mono:
      - weekly

to travis.yml may help

**Comment by 304NotModified** [comment]
Hey @ArsenShnurkov ,

I think it is preferred to have  NLog  working in Mono 4.0+ and not Mono 4.2+ ? Can we test in code which Mono version we're working with?

**Comment by 304NotModified** [comment]
PS to test, it's OK to change .appveyor.yml

**Comment by 304NotModified** [comment]
Is aa nice improvement, so merge :)

**Comment by ArsenShnurkov** [comment]
I don't understood, what was changed to make it passing the tests. May I ask you to write down (document) the details?

**Comment by 304NotModified** [comment]
it do not pass mono-4.0.4 yet - it skips those tests in Mono. But that's another issue.

**Comment by 304NotModified** [comment]
See https://github.com/NLog/NLog/pull/1006, but still not working :(

**Comment by ArsenShnurkov** [comment]
in 1006 there is no unwind error, there are another texts:

<pre>Starting: NLog.UnitTests.dll
   NLog.UnitTests.Targets.FileTargetTests.MaxArchiveFilesWithDate_removesToManyFiles [SKIP]
      TODO not working, needs to be fixed
   NLog.UnitTests.Targets.FileTargetTests.ArchiveAboveSizeWithArchiveNumberingModeDate_maxfiles_o [SKIP]
      this is not supported, because we cannot create multiple archive files with  ArchiveNumberingMode.Date (for one day)
   NLog.UnitTests.Targets.WebServiceTargetTests.WebserviceTest_restapi_httpget [SKIP]
      Not working - ProtocolViolationException - skip for fix later
   NLog.UnitTests.LogReceiverService.LogReceiverServiceTests.RealTestLogReciever_one_way_binary [SKIP]
      unit test should listen to non-http for this
   NLog.UnitTests.LogReceiverService.LogReceiverServiceTests.RealTestLogReciever_two_way_binary [SKIP]
      unit test should listen to non-http for this
   NLog.UnitTests.Contexts.MappedDiagnosticsLogicalContextTests.given_multiple_threads_running_asynchronously_when_setting_and_getting_values_should_return_thread_specific_values [FAIL]
      Assert.Equal() Failure\r\nPosition: First difference is at position 12\r\nExpected: ValueForTask3\r\nActual:   ValueForTask2
      Stack Trace:
         tests\NLog.UnitTests\Contexts\MappedDiagnosticsLogicalContextTests.cs(207,0): at NLog.UnitTests.Contexts.MappedDiagnosticsLogicalContextTests.given_multiple_threads_running_asynchronously_when_setting_and_getting_values_should_return_thread_specific_values()
   NLog.UnitTests.Config.VariableTests.VariablesTest_string_expanding [SKIP]
</pre>

does this mean that mono version bump helped? Or you bumped mono AND commented out the tests, so we don't know does bump help or not?

**Pull request merged**
