### PR TITLE
Internal logger Improved layout - Part 1

### PR DESCRIPTION
**Pull request by FrancisChung**
# Description

Improving the InternalLogger for better readabilty and functionality.
The intention is to gradually introduce the fixes and improvements over several PRs, to make the reviews more manageable.

## Fixes # (issue)
2506, 3673
https://github.com/NLog/NLog/issues/2506
https://github.com/NLog/NLog/issues/3673

## Type of change

(from #2506 )

- level in caps, or between [ and ] (easier to filter in text editor)
- fixed with for Level? (padded)
- field separator between message, level etc? eg. |

The proposed fix is to include full Namespace names (e.g [NLog.Config.LoggingConfiguration] ) for Trace|Debug entries and just Class names for Info Level and above entries (e.g. [LoggingConfiguration]) 

## Before Change (Sample Output)

```
2024-03-05 15:26:43.1408 Debug Message Template Auto Format enabled
2024-03-05 15:26:43.1844 Trace FindReachableObject<NLog.Internal.IRenderable>:
2024-03-05 15:26:43.1844 Trace Scanning LongDateLayoutRenderer 'Layout Renderer: ${longdate}'
2024-03-05 15:26:43.1844 Trace FindReachableObject<NLog.Internal.IRenderable>:
2024-03-05 15:26:43.1844 Trace Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2024-03-05 15:26:43.1844 Trace FindReachableObject<NLog.Internal.IRenderable>:
2024-03-05 15:26:43.1844 Trace Scanning LoggerNameLayoutRenderer 'Layout Renderer: ${loggername}'
2024-03-05 15:26:43.1844 Trace FindReachableObject<NLog.Internal.IRenderable>:
2024-03-05 15:26:43.1844 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2024-03-05 15:26:43.1844 Debug Adding target NLog.Targets.ColoredConsoleTarget(Name=console)
2024-03-05 15:26:43.1844 Info Registered target NLog.Targets.ColoredConsoleTarget(Name=console)
2024-03-05 15:26:43.1844 Trace ParseRulesElement
2024-03-05 15:26:43.1968 Info NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 5.0.0.0. Product version: 1.0.0+65406dce4979e0d75d8c5a55110dc48b1bfbd74a. GlobalAssemblyCache: False
2024-03-05 15:26:43.1968 Debug --- NLog configuration dump ---

```

## After Change  (Sample Output)

```
2024-03-14 17:59:21.1759 [DEBUG ] [NLog.Config.ServiceRepositoryExtensions] Message Template Auto Format enabled
2024-03-14 17:59:22.0413 [DEBUG ] [NLog.Config.LoggingConfiguration] Adding target NLog.Targets.ColoredConsoleTarget(Name=console)
2024-03-14 17:59:22.8458 [INFO  ] [LoggingConfiguration] Registered target NLog.Targets.ColoredConsoleTarget(Name=console)
2024-03-14 17:59:23.2343 [INFO  ] NLog, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c. File version: 5.0.0.0. Product version: 1.0.0+381621aff0d412a8d366ca902c07c1db29c8d513. GlobalAssemblyCache: False
2024-03-14 17:59:23.6781 [DEBUG ] --- NLog configuration dump ---
2024-03-14 17:59:24.1182 [DEBUG ] [NLog.Config.LoggingConfiguration] Targets:
2024-03-14 17:59:24.5730 [DEBUG ] [NLog.Targets.ColoredConsoleTarget] [NLog.Config.LoggingConfiguration] ColoredConsoleTarget(Name=console)
2024-03-14 17:59:25.2727 [DEBUG ] [NLog.Config.LoggingConfiguration] Rules:
2024-03-14 17:59:25.7057 [DEBUG ] --- End of NLog configuration dump ---
```

# How Has This Been Tested?

A new class InternalLoggerLayoutTests (Nlog.UnitTests.Common) has been created with the following tests

- TestLInternalLoggerLevelFieldFormattingInCapitalsAndBrackets() 
- TestInternalLoggerClassFieldShouldBeFullNameSpaceForTraceAndDebug()
- TestInternalLoggerClassFieldShouldBeJustClassNamesForInfoAndAbove

# Waiting For
- #5443

### CODE REVIEW

**Comment by snakefoot** [comment]
Have now merged all pul-requersts for NLog v5.3 into dev-branch. So if you rebase your pull-request, then it should only reflect your own changes.

Notice that you have picked up a task for NLog v6, so it will probably not be merged in near future.

**Comment by FrancisChung** [comment]
> Notice that you have picked up a task for NLog v6, so it will probably not be merged in near future.

Out of interest, which one was that? I'd be happy to be wait til this to be merged and carry-on with the further improvements

**Comment by snakefoot** [comment]
> Out of interest, which one was that? I'd be happy to be wait til this to be merged and carry-on with the further improvements

Believe #2506 has milestone 6.0. But #3673 about improving the log-messages (readable english) is open for business.

**Comment by snakefoot** [comment]
Closing due to inactivity. Wellcome to reopen when having resolved merge-conflicts.

**Pull request closed without merging**
