### PR TITLE
Misc. fixes for .NET Core

### PR DESCRIPTION
**Pull request by jasonwilliams200OK**
- Removed a wapper project for System.Linq
- Update, format and renamed Global.json to global.json
- Fix Travis script to build and test for Linux and macOS targeting release and debug configurations
- Merged current master, resolved conflicts and applied fixes for netcore
- Update project.jsons with updated versions of packages and consistent indentation of 2 spaces
- Minor fixes

/cc @304NotModified, there are still some failing tests, but Travis build NLog, NLog.UnitTests and SampleExtensions  projects successfully on Linux and macOS: https://travis-ci.org/jasonwilliams200OK/NLog/builds/152123995

### CODE REVIEW

**Comment by 304NotModified** [comment]
\0/ great work! Thanks! Will review it!

**Comment by 304NotModified** [comment]
looks good to me :)

**Comment by 304NotModified** [comment]
> Removed a wapper project for System.Linq

Could you elaborate on that?

**Comment by jasonwilliams200OK** [comment]
Sorry it is `System.Xml.Linq`, this guy https://github.com/NLog/NLog/tree/91f1d5c/wrap/System.Xml.Linq

We have a substitute package https://www.nuget.org/packages/System.Xml.XDocument/, which covers most of the surface area of System.Xml.Linq (at least what the code was using). In case the transitive/indirect reference is required, nuget will handle it. Seems like build is happy without it. `wrap` was a legacy DNX concept anyway and CLI has never advertised that its support (and secretly discouraging it) :sunglasses:

**Comment by jasonwilliams200OK** [comment]
A potential goal (, IMO,) should be to clear the wrap directory completely. :)

**Comment by jasonwilliams200OK** [comment]
Also, moved DNXCore50SampleApp to DotnetCore50Sample... since DNX-anything is obsolete.

**Comment by 304NotModified** [comment]
> Sorry it is System.Xml.Linq, this guy https://github.com/NLog/NLog/tree/91f1d5c/wrap/System.Xml.Linq
> 
> We have a substitute package https://www.nuget.org/packages/System.Xml.XDocument/, which covers most of the surface area of System.Xml.Linq (at least what the code was using). In case the transitive/indirect reference is required, nuget will handle it. Seems like build is happy without it. wrap was a legacy DNX concept anyway and CLI has never advertised that its support (and secretly discouraging it)

That would be great.

> A potential goal (, IMO,) should be to clear the wrap directory completely. :)

Well all those Silverlight stuff isn't really used. Dunno if it even works. :|

**Comment by jasonwilliams200OK** [comment]
Removed the wrap directory. :blush:

**Comment by 304NotModified** [comment]
thanks!

**Pull request merged**
