### PR TITLE
Support for Replacing Windows Line Endings under Unix

### LINKED ISSUE #3937: `replace-newlines` Not Replacing Windows New Lines on Unix
**NLog version**: `1.6.8`

**Platform**: .Net 3.5 / .Net 4.5 / .NET Core 2 / .NET Core 3

**Current NLog config**

```csharp
var fileTarget = new FileTarget
{
    FileName = targetPath,
    Encoding = Encoding.UTF8,
    ArchiveAboveSize = 104_857_600, // 100mb
    ArchiveFileName = archivePath,
    KeepFileOpen = true,
    ConcurrentWrites = false,
    OpenFileCacheTimeout = 30,
    EnableFileDelete = true,
    MaxArchiveFiles = 10,
    WriteBom = false,
    Layout = "${longdate} \t"
             + "${level:uppercase=true} \t"
             + "${processid}:${threadid} \t"
             + "${logger} \t"
             + @"${replace-newlines:replacement=\\r\\n:${message}}${onexception:inner= Exception\:${exception:format=ToString}}"
};
```

- What is the current result?

Given the following message logged under Linux (using Windows line endings, per spec):

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <me...
```

The following is logged:
```
<!DOCTYPE html>
\r\n<html lang="en">
\r\n<head>
\r\n    <meta charset="utf-8" />
\r\n    <me...
```

image

It appears the `\r` character is never replaced.

- What is the expected result?

The replace-newlines wrapper should replace all line endings.

- Are there any workarounds? Regex, the solution to all.
- Is there a version in which it did work? Unknown
- Can you help us by writing an unit test? Yep, could also make a pr, but since this behavior depends on Environment.NewLine, I'm unsure how we want to make that test.

### PR DESCRIPTION
**Pull request by Silvenga**
Resolves #3937.

### CODE REVIEW

**Comment by snakefoot** [comment]
@Silvenga If you rebase to master-branch then it can be included in NLog 4.7.1

**Comment by Silvenga** [comment]
@snakefoot rebased onto master. Hopefully, the checks will unbreak, they didn't seem to pick up the change of pr target correctly.

**Comment by snakefoot** [comment]
Closing and reopening to tickle the build-servers

**Comment by 304NotModified** [comment]
You could also mention me. The azure devops is easy to restart :)

**Comment by 304NotModified** [comment]
Thanks!

**Pull request merged**
