### PR TITLE
EventLogTarget - Enable OptimizeBufferReuse by default

### PR DESCRIPTION
**Pull request by snakefoot**
Waiting for NLog ver. 4.5

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1910)

### CODE REVIEW

**Comment by snakefoot** [comment]
Was thinking to implement a method like this to fix the merge-conflicts that will soon arrive with doing int / short conversions

```
        protected T RenderLogEventConvert<T>(Layout layout, LogEventInfo logEvent, T defaultValue = default(T), IFormatProvider formatProvider = null)
        {
            string renderedValue = RenderLogEvent(layout, logEvent);

            try
            {
                T parsedValue = (T)Convert.ChangeType(renderedValue, typeof(T), formatProvider ?? System.Globalization.CultureInfo.InvariantCulture);
                return parsedValue;
            }
            catch (Exception ex)
            {
                InternalLogger.Warn(ex, "{0}: parsing of value {1} failed, returning default: {2}", Name, renderedValue, defaultValue);
                return defaultValue;
            }
        }
```

**Comment by 304NotModified** [comment]
> But maybe the issue about allocations is not that important for these properties. Certainly don't hope someone writes 1 million EventLog-messages per sec :)

I hope also :)

**Comment by 304NotModified** [comment]
could you please check the merge conflict? Thanks!

**Comment by snakefoot** [comment]
@304NotModified Have resolved the merge conflicts.

**Comment by 304NotModified** [comment]
Thanks!

**Comment by snakefoot** [comment]
@304NotModified Updated documentation https://github.com/NLog/NLog/wiki/Eventlog-target

**Pull request merged**
