### PR TITLE
OutputDebugStringTarget - Support Xamarin iOS and Android

### LINKED ISSUE #2799: Qestion: OutputDebugString for Xamarin.Android and iOS
Hello.

Is there a reason, why the target `OutputDebugString` is not included in the Android / iOS version of NLog?

I use the current version 4.5.6 and use it in my Xamarin.Forms applications. The `Debug.Write` as a underlying implementation of `OutputDebugString` works on all platforms (UWP, Android, iOS) I use.

### PR DESCRIPTION
**Pull request by snakefoot**
Resolves #2799

### CODE REVIEW

**Comment by 304NotModified** [comment]
note: checked failed unit test

**Comment by snakefoot** [comment]
@304NotModified Force push resolved the failing build

**Comment by 304NotModified** [comment]
Thank you!

**Comment by snakefoot** [comment]
Updated wiki: https://github.com/NLog/NLog/wiki/OutputDebugString-target and https://github.com/NLog/NLog/wiki/platform-support

**Comment by 304NotModified** [comment]
thanks!

**Pull request merged**
