### PR TITLE
Add layout support for FinalMinLevel 

### LINKED ISSUE #5172: `finalMinLevel` not compatible with environment variables
I want to configure something similar to the default `appsettings.json` in NLog. I'm using `finalMinLevel` do this, but it seems incompatible with environment variables.

**NLog version**: 5.1.0

**Platform**: .NET6

**Current NLog config**

```xml
  <rules>
    <!-- Only show Microsoft logs from 'Warn' level or higher because it spams too much on 'Info',
         except for Microsoft.Hosting.Lifetime which doesn't spam and has useful information.
         This is the ASP.NET default configuration. -->
    <logger name="Microsoft.*" finalMinLevel="${environment:HOST_LOG_LEVEL}" />
    <logger name="Microsoft.Hosting.Lifetime" finalMinLevel="${environment:APP_LOG_LEVEL}" />
    <logger name="*" minlevel="${environment:APP_LOG_LEVEL}" maxLevel="Warn" writeTo="stdout" />
    <logger name="*" minlevel="Error" writeTo="stderr" />
  </rules>
```

**What is the current result?**

Nothing gets logged. When I configure NLog to throw errors, I get the following exception:

> Unhandled exception. System.TypeInitializationException: The type initializer for 'MyCompany.Configuration.ConfigurationBuilderExtensions' threw an exception.
 ---> NLog.NLogConfigurationException: Exception when loading configuration MyProject/bin/Debug/net6/NLog.config
 ---> System.ArgumentException: Unknown log level: ${environment:HOST_LOG_LEVEL} (Parameter 'levelName')
   at NLog.LogLevel.FromString(String levelName)
   at NLog.Config.LoggingConfigurationParser.LogLevelFromString(String text)
   at NLog.Config.LoggingConfigurationParser.ParseRuleElement(ValidatedConfigurationElement loggerElement)
   at NLog.Config.LoggingConfigurationParser.ParseRulesElement(ValidatedConfigurationElement rulesElement, IList`1 rulesCollection)
   at NLog.Config.LoggingConfigurationParser.LoadConfig(ILoggingConfigurationElement nlogConfig, String basePath)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(ILoggingConfigurationElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   at NLog.Config.XmlLoggingConfiguration..ctor(XmlReader reader, String fileName, LogFactory logFactory)
   at NLog.Config.LoggingConfigurationFileLoader.LoadXmlLoggingConfiguration(XmlReader xmlReader, String configFile, LogFactory logFactory)
   at NLog.Config.LoggingConfigurationFileLoader.LoadXmlLoggingConfigurationFile(LogFactory logFactory, String configFile)
   at NLog.Config.LoggingConfigurationFileLoader.TryLoadLoggingConfiguration(LogFactory logFactory, String configFile, LoggingConfiguration& config)
   at NLog.Config.LoggingConfigurationFileLoader.TryLoadFromFilePaths(LogFactory logFactory, String filename)
   at NLog.Config.LoggingConfigurationFileLoader.Load(LogFactory logFactory, String filename)
   at NLog.Config.LoggingConfigurationWatchableFileLoader.Load(LogFactory logFactory, String filename)
   at NLog.LogFactory.get_Configuration()
   at NLog.LogFactory.GetLoggerThreadSafe(String name, Type loggerType)
   at NLog.LogFactory.GetLogger(String name)
   at NLog.LogManager.GetLogger(String name)

**What is the expected result?**

Log levels are retrieved from the environmental variables and NLog logs as the logs as expected.

**Are there any workarounds?**

It is not exactly the same, but close enough, and this seems to work just fine:

```xml
  <rules>
    <!-- Only show Microsoft logs from 'Warn' level or higher because it spams too much on 'Info',
         except for Microsoft.Hosting.Lifetime which doesn't spam and has useful information.
         This is the ASP.NET default configuration. -->
    <logger name="Microsoft.Hosting.Lifetime" minLevel="${environment:APP_LOG_LEVEL}" maxLevel="Warn" writeTo="stdout" final="true" />
    <logger name="Microsoft.Hosting.Lifetime" minLevel="Error" writeTo="stderr" final="true" />
    <logger name="Microsoft.Hosting.Lifetime" maxLevel="${environment:APP_LOG_LEVEL}" final="true" />
    <logger name="Microsoft.*" minLevel="${environment:HOST_LOG_LEVEL}" maxLevel="Warn" writeTo="stdout" final="true" />
    <logger name="Microsoft.*" minLevel="Error" writeTo="stderr" final="true" />
    <logger name="Microsoft.*" maxLevel="${environment:HOST_LOG_LEVEL}" final="true" />
    <logger name="*" minlevel="${environment:APP_LOG_LEVEL}" maxLevel="Warn" writeTo="stdout" />
    <logger name="*" minlevel="Error" writeTo="stderr" />
  </rules>
```

**Is there a version in which it did work?**

I have not tested multiple versions.

### PR DESCRIPTION
**Pull request by Aaronmsv**
I tried to keep refactorings to a minimum and stay consistent with the rest of the code. Let me know if more changes are required.

### CODE REVIEW

**Comment by snakefoot** [comment]
Thank you for the unit-tests, that is a great step. Think they should also support that one updates the NLog-Config-Variable and it takes effect when calling `logFactory.ReconfigureExistingLoggers()`

**Comment by Aaronmsv** [comment]
Okay, so just to be clear: I add a new property to `ILoggingRuleLevelFilter`, update its implementations to handle this, and pass `finalMinLevel` to `EnableLoggingForLevels`, `EnableLoggingForLevelLayout` and `EnableLoggingForLevelsLayout`?

In my first try, I implemented a new `ILoggingRuleLevelFilter` and set it during parsing of `finalMinLevel`, but it just got cleared after `EnableLevelsForRule` was called. I think it misunderstood it then.

**Comment by snakefoot** [comment]
Maybe it is better to create a new method that takes inspiration from how Minlevel + MaxLevel from Layout is handled (without touching the existing logic for Minlevel + Max Level)

I trust what feels natural for you will be a good first direction.


Sent from my Galaxy



-------- Original message --------
From: Aaron Mousavi ***@***.***>
Date: 21/03/2023 09:54 (GMT+01:00)
To: NLog/NLog ***@***.***>
Cc: Rolf Kristensen ***@***.***>, Comment ***@***.***>
Subject: Re: [NLog/NLog] Add layout support for FinalLevelMin (PR #5174)


Okay, so just to be clear: I add a new property to ILoggingRuleLevelFilter, update its implementations to handle this, and pass finalMinLevel to EnableLoggingForLevels, EnableLoggingForLevelLayout and EnableLoggingForLevelsLayout?

In my first try, I implemented a new ILoggingRuleLevelFilter and set it during parsing of finalMinLevel, but it just got cleared after EnableLevelsForRule was called. I think it misunderstood it then.

**Comment by snakefoot** [comment]
I think one should use `DynamicRangeLevelFilter` whenever one the conditions are true:
- MaxLevel comes from dynamic NLog Layout
- MinLevel comes from dynamic NLog Layout
- FinalMinLevel comes from dynamic NLog Layout

So I would merge `FinalMinLogLevelLayoutFilter` into `DynamicRangeLevelFilter`.

> Shouldn't the following log be ignored, since it is below Error from finalMinLevel?

Lets say you have an application that depends on a special sub-component, and you want to have a dedicated log-target for that sub-component, but at the same time you would like all errors to flow to the catch-all log-target (but not info/warn):
```xml
<logger name='RequestLogger' minLevel='Debug' finalMinLevel='Error' writeTo='requestTarget' />
<logger name='*' minLevel='Info' writeTo='catchAllTarget' />
```

**Comment by snakefoot** [comment]
Sorry about the many small commits to your pull-request-branch. But it looks like the pull-request is making `FinalMinLevel` work with NLog Layout.

Will squash the commits, and starting working on getting NLog v5.1.3 released.

**Comment by Aaronmsv** [comment]
Sorry for the late reply, last days were busy. Thanks @snakefoot!

**Pull request merged**
