### PR TITLE
LayoutRenderer Initialize should swallow exceptions when configured

### PR DESCRIPTION
**Pull request by snakefoot**
Breaking change, should be moved to NLog ver. 5.0

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/2069)

### CODE REVIEW

**Comment by c0shea** [comment]
Isn't this a breaking change considering `NLogConfigurationException` is not derived from the existing `ArgumentException` and an exception is now being thrown where one was never thrown before?

**Comment by snakefoot** [comment]
> Isn't this a breaking change 

Certainly is. Just me being lazy. Have now updated the description.

**Comment by 304NotModified** [comment]
Wrong button? ;)

**Comment by snakefoot** [comment]
More or less. Just had so many stale branches, that the pending ones was mixed together :)

**Pull request merged**
