### PR TITLE
WindowsMultiProcessFileAppender - FileSystemRights.AppendData

### PR DESCRIPTION
**Pull request by snakefoot**
Merged #1474 with master, and changed from native windows file handle to managed FileStream-object

Using FileSystemRights.AppendData (FILE_APPEND_DATA / O_APPEND) allows multiple processes to write to the same local file without needing a global mutex object. This improves file-write performance with a factor 2.

There are different rumors on the Internet whether FILE_APPEND_DATA works correctly when the number of bytes written in a single operation is larger than 1KByte or 4KByte. The file-size increase that allocates the needed room in the file is atomic. But writing the bytes to the allocated room is probably done in sector size depending on version of operating system. This means if having very aggressive tail application that performs direct file reads, then it can momentarily read the allocated room without data has actually been written.

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1756)

### CODE REVIEW

**Comment by snakefoot** [comment]
I have tested the updated solution with the test-project from #1474 made by @AndreGleichner, and it completes and performs successful verification.

**Comment by 304NotModified** [comment]
> There are different rumors on the Internet whether FILE_APPEND_DAT

So it's untrue? Or unsure?

**Comment by 304NotModified** [comment]
Thanks for the changes! Will try to review it soon and release in into 4.4 (rc)

**Comment by snakefoot** [comment]
Have discovered that the unit test time has increased. Most likely because of the added combinations in FileTargetTests.cs  (Linq-booleanValues).

Not sure if this is a good direction, as every new parameter will double the time.

**Comment by 304NotModified** [comment]
Good to know. It was ~11min and now ~19. 

In my experience 11 was already to long. When working on several items, I have to wait for hours. 

Everything is tested with net35+net40+net45. Maybe we should test some tests only with net45

**Comment by snakefoot** [comment]
Added a filter so it only exercises the major FileAppenders. 

Travis Test Count = 1734 (Before=2190), but still an increase from current master=1554
AppVeyor Test Count = 1875 (Before=2355), but still an increase from current master=1677

**Comment by 304NotModified** [comment]
Will try to test this next week

**Comment by 304NotModified** [comment]
Reviewed 1 of 20 files at r1, 23 of 24 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/NLog/Internal/FileCharacteristicsHelper.cs, line 68 at r2](https://reviewable.io:443/reviews/nlog/nlog/1756#-KXIHmXPvc-kSlznkjIt:-KXIHmXPvc-kSlznkjIu:b7nzdq8) ([raw file](https://github.com/nlog/nlog/blob/80e40da421e5cd43a20f25afef968827d5934f6c/src/NLog/Internal/FileCharacteristicsHelper.cs#L68)):*
> ```Smalltalk
>         /// <param name="fileStream">The file stream.</param>
>         /// <returns>The file characteristics, if the file information was retrieved successfully, otherwise null.</returns>
>         public abstract FileCharacteristics GetFileCharacteristics(string fileName, FileStream fileStream);
> ```

Is this not infecting performance?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1756)*

**Comment by 304NotModified** [comment]
Need docs for

  ForceManaged = forceManaged,
                    ForceMutexConcurrentWrites = forceMutexConcurrentWrites

**Comment by snakefoot** [comment]
*[src/NLog/Internal/FileCharacteristicsHelper.cs, line 68 at r2](https://reviewable.io:443/reviews/nlog/nlog/1756#-KXIHmXPvc-kSlznkjIt:-KXIJj8GF0MM-oKWsZpU:b-lwufxd) ([raw file](https://github.com/nlog/nlog/blob/80e40da421e5cd43a20f25afef968827d5934f6c/src/NLog/Internal/FileCharacteristicsHelper.cs#L68)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary>
> Is this not infecting performance?
</details>
Changing the parameter from IntPtr to FileStream-reference ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1756)*

**Comment by 304NotModified** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/NLog/Internal/FileCharacteristicsHelper.cs, line 68 at r2](https://reviewable.io:443/reviews/nlog/nlog/1756#-KXIHmXPvc-kSlznkjIt:-KXIN1CuIpqv6N8Cclmw:b-t0zdn3) ([raw file](https://github.com/nlog/nlog/blob/80e40da421e5cd43a20f25afef968827d5934f6c/src/NLog/Internal/FileCharacteristicsHelper.cs#L68)):*
<details><summary><i>Previously, snakefoot (Rolf Kristensen) wrote…</i></summary>
> Changing the parameter from IntPtr to FileStream-reference ?
</details>
Well using FileStream insteaf of IntPtr

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1756)*

**Comment by snakefoot** [comment]
*[src/NLog/Internal/FileCharacteristicsHelper.cs, line 68 at r2](https://reviewable.io:443/reviews/nlog/nlog/1756#-KXIHmXPvc-kSlznkjIt:-KXINEJSfNTcYYp0oW1E:b-37q2ip) ([raw file](https://github.com/nlog/nlog/blob/80e40da421e5cd43a20f25afef968827d5934f6c/src/NLog/Internal/FileCharacteristicsHelper.cs#L68)):*
<details><summary><i>Previously, 304NotModified (Julian Verdurmen) wrote…</i></summary>
> Well using FileStream insteaf of IntPtr
</details>
I'm only using the FileStream-parameter to carry the IntPtr (If needed). If using Win32FileCharacteristicsHelper then it will use fileStream.SafeFileHandle.DangerousGetHandle()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1756)*

**Comment by 304NotModified** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/NLog/Internal/FileCharacteristicsHelper.cs, line 68 at r2](https://reviewable.io:443/reviews/nlog/nlog/1756#-KXIHmXPvc-kSlznkjIt:-KXIP254n6eKV0UHjBEv:b-c52rt6) ([raw file](https://github.com/nlog/nlog/blob/80e40da421e5cd43a20f25afef968827d5934f6c/src/NLog/Internal/FileCharacteristicsHelper.cs#L68)):*
<details><summary><i>Previously, snakefoot (Rolf Kristensen) wrote…</i></summary>
> I'm only using the FileStream-parameter to carry the IntPtr (If needed). If using Win32FileCharacteristicsHelper then it will use fileStream.SafeFileHandle.DangerousGetHandle()
</details>
OK thanks! :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1756)*

**Comment by 304NotModified** [comment]
from tests give me ~10% performance gain, also with 1 thread.

tested with 

```
NLogPerformance\bin\Release\NLogPerformance.exe 3000000 1  8  1 false >> performance-log.log
NLogPerformance\bin\Release\NLogPerformance.exe 3000000 1  16 1 false >> performance-log.log
NLogPerformance\bin\Release\NLogPerformance.exe 3000000 1  32 1 false >> performance-log.log
NLogPerformance\bin\Release\NLogPerformance.exe 3000000 2  16 1 false >> performance-log.log
NLogPerformance\bin\Release\NLogPerformance.exe 3000000 4  16 1 false >> performance-log.log
NLogPerformance\bin\Release\NLogPerformance.exe 3000000 8  16 1 false >> performance-log.log
NLogPerformance\bin\Release\NLogPerformance.exe 3000000 16 16 1 false >> performance-log.log
NLogPerformance\bin\Release\NLogPerformance.exe 3000000 60 16 1 false >> performance-log.log
```

**Comment by 304NotModified** [comment]
Will be in news post

**Pull request merged**
