### PR TITLE
Remove redundant qualifiers

### PR DESCRIPTION
**Pull request by c0shea**
I inadvertently did a force push, which closed #2336 and I couldn't seem to get it back. This PR is a redo now that #2327 has been merged.

To continue on our previous discussion, I'll create a new PR for expression-bodied members once this one is merged to avoid more conflicts.

I personally love to use var for everything. I know some people hate it because they want to see the types explicitly spelled out, but to me that's too verbose. If I want to know the type, I can just hover over the variable ;) That said, I could go either way depending on your thoughts. I think it would make the most sense for complex expressions, e.g. LINQ and other nested generic types, but it would be fine to keep using `string test = "123"` instead of making that a var.

### CODE REVIEW

**Comment by c0shea** [comment]
@304NotModified Not sure why Travis is failing the build with `The command "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF" failed and exited with 2 during .` after I resolved the latest conflicts. Thoughts?

**Comment by 304NotModified** [comment]
> @304NotModified Not sure why Travis is failing the build with The command "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF" failed and exited with 2 during . after I resolved the latest conflicts. Thoughts?

Travis is buggy. Will retry (a few times).

**Comment by 304NotModified** [comment]
worked after 1 retry :)

Double check, you used R# for this isn't?

**Comment by c0shea** [comment]
Yes, I used ReSharper for this. So nice to do it in s couple clicks for the solution.

**Comment by 304NotModified** [comment]
thanks!!

**Comment by snakefoot** [comment]
Must admit I kind of liked the NLog-prefix for the NLog-namespace specifications. But the removal of explicit `this` is great.

**Pull request merged**
