### PR TITLE
RoundRobinGroupTarget - Replaced lock with Interlocked for performance

### PR DESCRIPTION
**Pull request by snakefoot**
Makes it possible to create a highly concurrent file-target.

```xml
<target type="RoundRobinGroup" name="superfast">
    <target type="AsyncWrapper" timeToSleepBetweenBatches="0">
          <target type="file" keepFileOpen="false" fileName="single.log" />
    </target>
    <target type="AsyncWrapper" timeToSleepBetweenBatches="0">
          <target type="file" keepFileOpen="false" fileName="single.log" />
    </target>
    <target type="AsyncWrapper" timeToSleepBetweenBatches="0">
          <target type="file" keepFileOpen="false" fileName="single.log" />
    </target>
    <target type="AsyncWrapper" timeToSleepBetweenBatches="0">
          <target type="file" keepFileOpen="false" fileName="single.log" />
    </target>
    <target type="AsyncWrapper" timeToSleepBetweenBatches="0">
          <target type="file" keepFileOpen="false" fileName="single.log" />
    </target>
    <target type="AsyncWrapper" timeToSleepBetweenBatches="0">
          <target type="file" keepFileOpen="false" fileName="single.log" />
    </target>
</target>
```

Allowing multiple threads to write to the same file without being hit by lock congestion in PrecalculateVolatileLayouts. See also #2627

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks!

@snakefoot I'm thinking to automatic release Dev packages on nuget (for every master commit?)
What do you think? I think it will boost creating releases and people could faster test it. Like the serilog Dev releases.

**Comment by snakefoot** [comment]
@304NotModified Well if release cycle is going to be once every year, then it is a good idea. If the release cycle is once a month, then I think people can wait. Those too impatient can make private builds. Cannot predict the amount of support it will give, or the eagerness for using pre-release-build by users. NLog 4.5-rc was not that popular, and probably only used by those needing NetCore.

**Comment by 304NotModified** [comment]
> @304NotModified Well if release cycle is going to be once every year, then it is a good idea. If the release cycle is once a month, then I think people can wait.

true. Any way, it was hoping for more feedback between releases, it would make it easier to release fast. (fix, test in dev package, confirmation, release)

**Comment by snakefoot** [comment]
> true. Any way, it was hoping for more feedback between releases, it would make it easier to release fast

After all the work with implementing structured logging and all the provided release-candidates, then I find the feedback-loop a little weak for the NLog-project. Uncertain if more dev-releases will improve on this.

**Comment by 304NotModified** [comment]
> After all the work with implementing structured logging and all the provided release-candidates, then I find the feedback-loop a little weak for the NLog-project. Uncertain if more dev-releases will improve on this.

Agree on that. I only expect feedback of the ones that reports the error unfortunately. 

Anyway, made make the internal nuget packages (AppVeyor) more visible would be nice

**Pull request merged**
