### PR TITLE
FileTarget - Calculate correct archive date, when using Monthly archive

### PR DESCRIPTION
**Pull request by snakefoot**
@304NotModified Please include this for NLog 4.5.4

### CODE REVIEW

**Comment by snakefoot** [comment]
Will try and make a unit-test.

**Comment by 304NotModified** [comment]
> @304NotModified Please include this for NLog 4.5.4

OK 👍

**Comment by 304NotModified** [comment]
> Will try and make a unit-test.

Thanks in advance! 

This is a bug fix, isn't?

**Comment by 304NotModified** [comment]
PS: we should really try to move into mockable tests for the filetarget, although i'm not sure if that would influence performance (interface calls instead of instances)

**Comment by snakefoot** [comment]
> This is a bug fix, isn't?

Yes bug introduced with NLog 4.5.3

**Comment by 304NotModified** [comment]
appreciate the transparency :)

**Comment by snakefoot** [comment]
@304NotModified Created a unit-test, though it cannot be used on Travis, because Linux file-birth-time is required.

**Comment by snakefoot** [comment]
Fixed merge conflict

**Comment by 304NotModified** [comment]
merged :)

**Pull request merged**
