### PR TITLE
System.UriFormatException on load (Mono)

### LINKED ISSUE #1965: System.UriFormatException on load (Mono)
**Type** (choose one): Bug

**NLog version**: Latest NuGet, 5.0.0-beta05

**Platform**: Mono 4.6.2

**Current NLog config**: None, this is crash during target registering.

In case of a BUG:

- What is the current result?
Unhandled exception being thrown when registering a custom target.

- What is the expected result?
Properly registering target with no exception.

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
I didn't as it's an error on client machine. I'm working on getting internal log from affected machine and will provide later on.

- Please post full exception details (message, stacktrace, inner exceptions)
```
Exception: UnhandledExceptionHandler() One or more errors occurred.
StackTrace:
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00014] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00052] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Threading.Tasks.Task.Wait () [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
  at ArchiSteamFarm.Program.Main (System.String[] args) [0x0000d] in <8e2c5bf04c21476991605cd1e2f2f8aa>:0 Exception: UnhandledExceptionHandler() Invalid URI: The hostname could not be parsed.
StackTrace:
  at System.Uri.CreateThis (System.String uri, System.Boolean dontEscape, System.UriKind uriKind) [0x00090] in <5071a6e4a4564e19a2eda0f53e42f9bd>:0 
  at System.Uri..ctor (System.String uriString) [0x00017] in <5071a6e4a4564e19a2eda0f53e42f9bd>:0 
  at NLog.Config.ConfigurationItemFactory.BuildDefaultFactory () [0x00033] in <294b42a9e7eb4ed898baa93ed17d3c81>:0 
  at NLog.Config.ConfigurationItemFactory.get_Default () [0x00007] in <294b42a9e7eb4ed898baa93ed17d3c81>:0 
  at NLog.Targets.Target.Register (System.String name, System.Type targetType) [0x00000] in <294b42a9e7eb4ed898baa93ed17d3c81>:0 
  at NLog.Targets.Target.Register[T] (System.String name) [0x0000b] in <294b42a9e7eb4ed898baa93ed17d3c81>:0 
  at ArchiSteamFarm.Program+<Init>d__29.MoveNext () [0x00031] in <8e2c5bf04c21476991605cd1e2f2f8aa>:0 
```

- Are there any work arrounds?
Apart from trying/catching in my own code, I don't think so. This looks like internal NLog issue.

- Is there a version in which it did worked?
This doesn't look like regression to me, so I don't know, but I hit this issue also **[a while ago](https://github.com/JustArchi/ArchiSteamFarm/issues/292)**, without reporting it back then. Perhaps it was here for the entire time. This looks like exactly the same issue to me.

- Can you help us by writing an unit test?
I don't think so, I don't know what is the culprit of this bug yet.

Extra info:

This looks like Mono-only issue that is happening with some specific environment I'm not able to reproduce, I got a report from one of my users where I make use of NLog. This crash comes as soon as I hit ```Target.Register<SteamTarget>("Steam")```. It's nice to note that my code in general works fine for all users, including me as a developer, but there is some affected machine on which this line hits the exception instead of passing through. I made sure that there are no calls to NLog prior to reaching that line, which you can see from the stacktrace, as target registering triggers NLog ```BuildDefaultFactory()```.

In case it'd be wanted to check how ```SteamTarget``` is defined, source code for that part is available **[here](https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/SteamTarget.cs)**.

I'll try to update my issue with internal log once I get it. I'd provide it right away, but I'm unable to reproduce this bug and I have to rely on communication with the client of affected machine.

### PR DESCRIPTION
**Pull request by JustArchi**
Fixes #1965

This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1966)

### CODE REVIEW

**Comment by JustArchi** [comment]
I'm pretty sure that Travis failure is a mere coincidence of broken Mono, as the build got stalled. Please re-run it if needed.

**Comment by 304NotModified** [comment]
Retied travis but still an issue?

**Comment by 304NotModified** [comment]
Mmmmm should indeed not trigger these issues. Will retry again

**Comment by 304NotModified** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1966)*

**Comment by 304NotModified** [comment]
Unfortunately this needs to be ported to NLog 5 (coreCLR branch which is behind - still merging 4.4.2 into it) see https://github.com/NLog/NLog/pull/1944

**Comment by JustArchi** [comment]
I sent a PR for CoreCLR in #1967 - thanks a lot for merging the bugfix!

**Pull request merged**
