### PR TITLE
Make Set methods of MDC and MDLC return IDisposable

### PR DESCRIPTION
**Pull request by MikeFH**
Attempt at implementing #2526

### CODE REVIEW

**Comment by 304NotModified** [comment]
Cool! But unfortunately this is a breaking change. 

So proposal to add a new method, `Scope` or something like that?

**Comment by MikeFH** [comment]
Got it.
I guess you can close this PR, I'll open a new one with another solution. I don't know when though, so if someone wants to look at it, it's cool.

**Comment by snakefoot** [comment]
You could also call the method `Push` or `PushProperty`:

https://github.com/serilog/serilog/blob/3cd376c8c75ed49ab307c50cd80beaa06cbaecb7/src/Serilog/Context/LogContext.cs#L77

**Comment by 304NotModified** [comment]
> guess you can close this PR, I'll open a new one with another solution

Just push new commits on your branch, we can squash them later.

**Comment by MikeFH** [comment]
I added a new method. It is called `Push` as suggested, but maybe it is a bit misleading since it might imply that the user works works on a stack (like in serilog) and that's not what we have here.

**Comment by 304NotModified** [comment]
What do you think about `SetScoped`?

**Comment by MikeFH** [comment]
`SetScoped` it is. 
I can still rename it if someone comes up with a better idea.

**Comment by 304NotModified** [comment]
> Build seems to be ok on my appveyor and travis accounts.

Tests are sometime a bit unstable :(

Will restart the CI

**Comment by 304NotModified** [comment]
Looks great! merged!

Thanks!

**Pull request merged**
