### PR TITLE
NLog InternalLogger Setup: added AddLogSubscription and RemoveLogSubscription

### PR DESCRIPTION
**Pull request by snakefoot**
Fluent API for LogMessageReceived

```c#
                LogManager.Setup().SetupInternalLogger(s =>
                {
                    s.AddLogSubscription(eventHandler);
                });
```

### CODE REVIEW

**Comment by 304NotModified** [comment]
I think it should have the term "internal" in the name, otherwise I would think this will be triggered when I log a message to a logger.

So  AddInternalLogSubscription and RemoveInternalLogSubscription?

**Comment by snakefoot** [comment]
But we are already in the Setup-method called `SetupInternalLogger`. Just like LogToFile doesn't say InternalLogToFile.

**Comment by 304NotModified** [comment]
Ow yes indeed, missed that!

**Comment by snakefoot** [comment]
Updated wiki-page: https://github.com/NLog/NLog/wiki/Fluent-Configuration-API

**Pull request merged**
