### PR TITLE
Added unit test to validate the [DefaultValue] attribute values + update DefaultAttributes

### LINKED ISSUE #652: Need unit test: test [DefaultValue] is really the default
There were, (and maybe are), multiple issues with the `[DefaultValue]` attribute. Some think this will set the default value, but it doesn't.

This will lead to bugs like #555 and #650.

We need a unit test for this. It probably use "reflection" and should be located in `SourceCodeTests`

### PR DESCRIPTION
**Pull request by 304NotModified**
Added unit test to validate the `[DefaultValue]` attribute values because of the recurring bugs.

Closes #652

Note: the unit tests are failing for 3 properties. We have to fix those 3. (also I would like to see the error message in AppVeyor.

message:
----

Additional information: 3 errors: 

 -------- 

- NLog.Targets.DatabaseTarget.KeepConnection has a wrong value for [DefaultValueAttribute] compared to the default ctor. DefaultValueAttribute says = 'True' and ctor tells = 'False'

- NLog.Targets.DatabaseTarget.CommandType has a wrong value for [DefaultValueAttribute] compared to the default ctor. DefaultValueAttribute says = 'Text' and ctor tells = '0'

- NLog.Targets.MailTarget.Body has a wrong value for [DefaultValueAttribute] compared to the default ctor. DefaultValueAttribute says = '${message}' and ctor tells = ''${message}${newline}''

### CODE REVIEW

**Comment by 304NotModified** [comment]
- `NLog.Targets.DatabaseTarget.KeepConnection `: wiki says `true` but the default ctor says `false`. I think the ` [DefaultValueAttribute] ` and wiki are wrong?
- `NLog.Targets.DatabaseTarget.CommandType` is fixed in #650

**Comment by Xharze** [comment]
I would say that we should change it to match the wiki. This is what everyone thinks it should be anyway

**Comment by 304NotModified** [comment]
Yes, but It's unclear for the mailtarget. Dunno what currently the default is.

**Comment by 304NotModified** [comment]
I think we should match the documentation on the code. Otherwise we get unneeded backwards comp problems. I think this is no problem because:

- If the user sets the property, there is no problem.
- If the user use the defaults, I would have noticed that the documentation is wrong, or he doesn't care ;)

@Xharze What doe you think?

@Xharze How can be a property required and also have a default value?

**Comment by 304NotModified** [comment]
SO proposal: change [defaultAttributes] and wiki to:

- `MailTarget.Body` and `MailTarget.Layout` to `${message}${newline}`
- `DatabaseTarget.KeepConnection` to `false`

**Comment by Xharze** [comment]
If it is unclear I think it should be changed to match the code as you suggest

**Comment by 304NotModified** [comment]
wikipages also updated!

**Comment by 304NotModified** [comment]
This code is nowadays in tools\CheckSourceCode

**Pull request merged**
