### PR TITLE
DI support (total) (WIP)

### PR DESCRIPTION
**Pull request by 304NotModified**
https://github.com/NLog/NLog/issues/3675

### CODE REVIEW

**Comment by snakefoot** [comment]
Think that the internal ServiceRepository in NLog should NEVER be used to register random user-types / interface-types. 

It should still be possible to override existing NLog-interface-implementations, so they become registered in the internal ServiceRepository. Ex. override the IJsonConverter without providing their custom dependency container.

If needing to register random types then one must register an external IServiceResolver that is used as primary lookup, and then fallback to internal ServiceRepository and then Activator.CreateInstance.

People using Dependency Injection already knows about Microsoft IServiceProvider and Autofac Container (or whatever favorite pet they have). They should just know that their DI-container becomes king when hooked together with NLog.

**Comment by 304NotModified** [comment]
@snakefoot I will try to merge this after #3815

**Comment by 304NotModified** [comment]
Those conflicts in MethodFactory and ConfigurationItemFactory are pretty hard

**Comment by snakefoot** [comment]
Think we need to reduce the flexibility of the dependency injection system, so users can only do this:
- Register singleton object where providing the actual object-instance
- Register object-type where NLog will be responsible for calling the constructor.

Thus removing the ability to register a custom factory-function or external dependency-injection-container.

Suddenly remembered this case where deadlock occurred because NLog suddenly made use of Microsoft ServiceProvider while logging:

https://github.com/NLog/NLog/issues/2064#issuecomment-296813153

Think we should put a lot of effort in preventing deadlocks (external dependency injection taking locks in wrong order) and stackoverflows (external dependency injection system creating objects that causes logging).

**Comment by 304NotModified** [comment]
superseded by #3831

**Pull request closed without merging**
