### PR TITLE
FileTarget - Skip checking file-length on every file write, when using ArchiveEvery

### PR DESCRIPTION
**Pull request by snakefoot**
Fixes performance regression introduced with #3691 when only using `ArchiveEvery` without specifying `ArchiveAboveSize`. The performance hit most is for this setup:

- KeepFileOpen=true and ConcurrentWrites=true

The performance hit comes from doing a probe of file-length for every write to file-stream. The probe was introduced to ensure the file was still valid (not archived by other process). But since the archive-operation is already performing double-check (One with filestream open, Second with filestream closed). Then there is no need to perform triple check.

Also removed  InternalLogger noise when using file-appender without mutex-support. Ex. KeepFileOpen=true and ConcurrentWrites=false.

### CODE REVIEW

**Comment by snakefoot** [comment]
Made a performance test with this (Removed `ArchiveAboveSize="100000000000"` only using `ArchiveEvery="Year" `):

`<target name="SyncFilePerfArchive" type="File" fileName="C:\Temp\Log\NLogPerformanceArchivePerf.txt" autoFlush="false" keepFileOpen="true" concurrentWrites="true" layout="${message}" MaxArchiveFiles="1000" ArchiveEvery="Year" ArchiveNumbering="Date" />`

| Test Name        | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog 4.6.8|    20.424 |   244.798 |   0 |   0 |  44 |   20.484 |    1.453,9 |
| NLog 4.7 |    29.861 |   167.441 |   0 |   0 |  44 |   29.843 |    1.453,9 |
| PR |    30.546 |   163.685 |   1 |   3 |  43 |   30.546 |    1.453,9 |

And when using `concurrentWrites="false"` where I thought the PR would help:

| Test Name        | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog 4.6.8 |     5.816 |   859.568 |   0 |   0 |  45 |    5.859 |    1.453,9 |
| NLog 4.7|     5.845 |   855.369 |   0 |   1 |  44 |    5.906 |    1.453,9 |
| PR |     5.861 |   853.070 |   0 |   0 |  46 |    5.906 |    1.453,9 |

Think more investigation is needed :)

**Comment by snakefoot** [comment]
Ohh well happy to confirm that NLog 4.7 is still good. 

The drop in performance when using `concurrentWrites="true"` is the sacrifice for synchronizing file-handles between multiple processes.

**Comment by 304NotModified** [comment]
> Ohh well happy to confirm that NLog 4.7 is still good.

How could you conclude that? 

29.861 / 20.424 = 146%?

**Comment by snakefoot** [comment]
My worry was about KeepFileOpen=true and ConcurrentWrites=false.


That performance has been hurt for KeepFileOpen=true and ConcurrentWrites=false for net471 (not NetCore) because of extra stream validation is not that bad.


Curious how KeepFileOpen=false and ConcurrentWrites=true is performing. When just using ArchiveEvery.


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


Ohh well happy to confirm that NLog 4.7 is still good.

How could you conclude that?

29.861 / 20.424 = 146%?

**Comment by snakefoot** [comment]
But I guess one could consider removing this section completely from FileTarget.cs:

```c#
            var fileLength = _fileAppenderCache.GetFileLength(fileName);   // Verifies file-handle by checking FileStream.Length
            if (!fileLength.HasValue)
            {
                InternalLogger.Debug("FileTarget(Name={0}): Cannot get length of file {1} with creation date {2}.", Name, fileName, creationTimeSource.Value);
                _initializedFiles.Remove(fileName);
                return null;
            }
```

Since the FileTarget.cs already include double verification of archive operation. First happens when with open filestream, and second happens after having closed filestream.

Lets try and remove it.

**Comment by snakefoot** [comment]
Looks like the code wasn't needed, and the existing double-check is already working well.

**Comment by snakefoot** [comment]
| Test Name        | Messages   | Size | Args | Threads |
|------------------|------------|------|------|---------|
| PerfArchiveLogger |  2.000.000 |  128 |    0 |       1 |


| Test Name        | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog 4.6.8 |     8.870 |   225.464 |   0 |   0 |  16 |    8.906 |      581,6 |
| NLog 4.7 |    12.746 |   156.901 |   0 |   0 |  15 |   12.750 |      581,6 |
| NLog 4.7.1|     8.887 |   225.043 |   0 |   1 |  16 |    8.828 |      581,6 |

`<target name="SyncFilePerfArchive" type="File" fileName="C:\Temp\Log\NLogPerformanceArchivePerf.txt" autoFlush="false" keepFileOpen="true" concurrentWrites="true" layout="${message}" MaxArchiveFiles="1000" ArchiveEvery="Year" ArchiveNumbering="Date" />`

**Comment by snakefoot** [comment]
| Test Name        | Messages   | Size | Args | Threads |
|------------------|------------|------|------|---------|
| PerfArchiveLogger |     10.000 |  128 |    0 |       1 |


| Test Name        | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------------|-----------|-----------|-----|-----|-----|----------|------------|
| NLog 4.6.8 |     38.611 |       258 |   0 |   0 |   1 |    3.937 |       49,0 |
| NLog 4.7 |    38.298 |       261 |   0 |   0 |   1 |    4.000 |       50,7 |
| PR |     37.913 |       263 |   0 |   0 |   1 |    3.968 |       49,0 |

`<target name="SyncFilePerfArchive" type="File" fileName="C:\Temp\Log\NLogPerformanceArchivePerf.txt" autoFlush="false" keepFileOpen="false" concurrentWrites="true" layout="${message}" MaxArchiveFiles="1000" ArchiveEvery="Year" ArchiveNumbering="Date" />`

**Pull request merged**
