### PR TITLE
Replaced question.md issue-template with contact_links (fix bom)

### PR DESCRIPTION
**Pull request by snakefoot**
Followup to #4912

### CODE REVIEW

**Comment by 304NotModified** [comment]
We could only test it after merge? Or maybe at a fork?

I see the indents on https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser, so not sure if this would fix things

**Comment by snakefoot** [comment]
Yes testing it now. there is some BOM-issue

**Comment by snakefoot** [comment]
now it works

**Comment by 304NotModified** [comment]
Yes indeed! Nice!

**Pull request merged**
