### PR TITLE
Replace NewLines Layout Renderer Wrapper

### PR DESCRIPTION
**Pull request by flower189**
Added a layout renderer wrapper to replace newline characters with spaces as per issue https://github.com/NLog/NLog/issues/86

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks!

It seems that to unused `using` are used? 

What's the benefit of the config property?

**Comment by flower189** [comment]
I thought I had removed the unused `using`s and that property. It is redundant, I added it before I realised initially.

**Comment by 304NotModified** [comment]
OK. You need to copy the file header of another file to it to fix the failing unit test.

**Comment by 304NotModified** [comment]
I looks nice! short and clean :+1: 

Maybe we could also make it configurable how to replace the newline? Because I was expecting "" (no chars), but a space is also an option. I propose to add the property: `public string replacement`. The default for space is then fine.

What do you think?

**Comment by flower189** [comment]
I like the idea. I was thinking it needed an option to control the separation character/string. I figured having no separator would make it hard to read.

**Comment by 304NotModified** [comment]
hint: the `[DefaultValue]` is only a marker and won't set the value. (it's a common mistake and therefor I have created an unit test for it.)

**Comment by 304NotModified** [comment]
You can ignore the failing unit test. That one is failing really sometimes (so there is really something wrong but not in this code)

**Comment by flower189** [comment]
Sorry, I really should have checked how the other properties had been implemented.

**Comment by 304NotModified** [comment]
No problem.  It's just a matter of style.

**Comment by 304NotModified** [comment]
We will include this in 4.1 :) 

One last thing: can you document this on the wiki? (new page) 

Maybe also reference from https://github.com/NLog/NLog/wiki/Replace-Layout-Renderer

**Comment by flower189** [comment]
Added a documentation page to the wiki here: https://github.com/NLog/NLog/wiki/Replace-NewLines-Layout-Renderer

**Comment by 304NotModified** [comment]
OK thanks,

I added also your examples and a 4.1 notice.

But I missed something. How does the test `ReplaceNewLineOneLineTest` work? And can't we replace with empty string now? It seems that `ReplaceNewLineOneLineTest` is wrong.

**Comment by flower189** [comment]
The ReplaceNewLineOneLineTest was added for a check that it wasn't applying when it wasn't meant to.

The default could be replaced with an empty string. My preference is to have a space to help keep it a little bit more readable by default.

**Comment by 304NotModified** [comment]
The default of space is good.

But replace with a empty value is a corner case. We need an unit test for that. Can you add this unit test?

**Comment by 304NotModified** [comment]
Thanks! It has been merged :)

**Pull request merged**
