### PR TITLE
Prevent Thread.Abort tryout1: ManualResetEvent instead of Thread.Abort

### PR DESCRIPTION
**Pull request by 304NotModified**
code by @jonreis, see https://github.com/NLog/NLog/issues/1415

### CODE REVIEW

**Comment by 304NotModified** [comment]
updated.. @jonreis you co-author in the commit :)

**Comment by jonreis** [comment]
Hey Julian, did you check out my pull request #1415?

**Comment by 304NotModified** [comment]
not yet, just saw it. How is that one related to this PR?

**Comment by jonreis** [comment]
Thanks Julian. I pretty new to PRs, so I may not have done it correctly.

It is a replacement for this request, however, it does not spin up a thread so I think it is better, but it needs review.

**Comment by 304NotModified** [comment]
Indeed, no threads are indeed better. Why do we need the dispose in the test?

**Comment by 304NotModified** [comment]
Anyway, Thanks for the code proposals!

**Comment by jonreis** [comment]
I assumed it was because the roll has not happened yet, so the target still has an opened file. But, wasn't sure about this.

**Comment by 304NotModified** [comment]
Oops we now discuss in the wrong pr. Bit confusing.

**Comment by 304NotModified** [comment]
superseded by https://github.com/NLog/NLog/pull/1444

**Pull request closed without merging**
