### PR TITLE
DLL to Docs - in csproj SDK

### PR DESCRIPTION
**Pull request by 304NotModified**
I don't like old csproj files :P

This also works the wildcards are nice :)

See also: https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#generatepathproperty

Also I think we need a rebuild instead of build - otherwise nice stuff is missing

### CODE REVIEW

**Comment by 304NotModified** [comment]
PS: noticed this for the first time: https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#restoring-and-building-with-one-msbuild-command

**Review by snakefoot — APPROVED** [review]
If BuildDoc.cmd also works with the new project format, then fine with me.

**Comment by 304NotModified** [comment]
Yes it works. I already updated the wiki (with that script) for nlog.mailkit v5

**Comment by snakefoot** [comment]
Guess one could move the doc-project out of the src-folder and into the tools-folder.

Since it no longer depends on the NLog-src, but only the relevant nuget-packages.

**Comment by 304NotModified** [comment]
good idea :)

**Comment by snakefoot** [comment]
Created #4942

**Pull request merged**
