### PR TITLE
Fix immutability of LogLevel properties

### PR DESCRIPTION
**Pull request by ie-zero**
It fixes the immutability of the static properties AllLevels and AllLoggingLevels for LogLevel class.

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1854)

### CODE REVIEW

**Comment by snakefoot** [comment]
Why use the yield-state-machine for a get-property, when you can just use IList<T>.AsReadOnly() ?

**Comment by ie-zero** [comment]
In the previous implementation the following unit tests should be failing but instead they were passing 

``` C#
[Fact]
public void LogLevel_SetAllLevels()
{
	((ICollection<LogLevel>) LogLevel.AllLevels).Add(LogLevel.Fatal);
	Assert.Equal(
		new List<LogLevel>() { 
			LogLevel.Trace, LogLevel.Debug, LogLevel.Info, 
			LogLevel.Warn, LogLevel.Error, LogLevel.Fatal, LogLevel.Off 
		},
		LogLevel.AllLevels);
}
```

``` C#
[Fact]
public void LogLevel_SetAllLoggingLevels()
{
	((ICollection<LogLevel>)LogLevel.AllLoggingLevels).Add(LogLevel.Fatal);
	Assert.Equal(
		new List<LogLevel>() { 
			LogLevel.Trace, LogLevel.Debug, LogLevel.Info, 
			LogLevel.Warn, LogLevel.Error, LogLevel.Fatal 
		},
		LogLevel.AllLoggingLevels);
}
```

**Comment by snakefoot** [comment]
Well old code didn't call AsReadOnly() on the static-allocated List.

**Comment by ie-zero** [comment]
I have no strong preference. If the preference is IList.AsReadOnly()  I can happily change to that. I simply noticed that the immutability was compromised.

**Comment by snakefoot** [comment]
Then it is only done once, instead of getting a new ienumerable allocated every time.

**Comment by 304NotModified** [comment]
I prefer AsReadOnly :)

**Comment by ie-zero** [comment]
To be perfectly honest, I cannot see how those two static properties fit on this object as they refer to a 'collection' rather than an individual object. We can  consider separating the ```LogLevel``` from the ```LogLevelCollection``` in the next major version.

**Comment by ie-zero** [comment]
Fair enough. I will change the code to AsReadOnly than :)

**Comment by ie-zero** [comment]
I will resubmit this PR as you proposed.

**Pull request closed without merging**
