### PR TITLE
added condition to AutoFlushWrappper

### LINKED ISSUE #1712: Add flushCondition and overflow options to the  BufferingWrapper
As discussed at #1710, add flushCondition and overflow options to the  BufferingWrapper

Example: 

``` xml
<targets>
  <target xsi:type="BufferingWrapper"
          name="ErrorFlushingBuffer"
          slidingTimeout="False"
          bufferSize="100"
          flushTimeout="-1"  <!-- Disabled timed flushes so flush only occurs when flushCondition is met -->
          overflow="discard"> <!-- discard if buffer is full. Default: flush-->
          flushCondition="level>LogLevel.Info">  <!-- Flush the buffer when a Warn, Error, or Fatal message is logged-->

          <target xsi:type="wrappedTargetType" ...target properties... />
  </target>
</targets>
```

### PR DESCRIPTION
**Pull request by nazim9214**
fixes #1712 

Added condition property to AutoFlushTargetWrapper, to allow autoflush on special conditions.

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1817)

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks! 👍 👍

**Comment by 304NotModified** [comment]
@nazim9214 Do you have time to add this to the wiki? If so, then we could include it for NLog 4.4. Please also add an example :)

Please add "introduced in NLog 4.4" .

I have still [some documentation for NLog 4.4](https://github.com/NLog/NLog/issues/1783) to do, so working on that first

**Comment by nazim9214** [comment]
@304NotModified yes, i will change the wiki

**Comment by nazim9214** [comment]
Changed wiki: https://github.com/NLog/NLog/wiki/AutoFlushWrapper-target/_compare/2426c0be762eab38c35889c80497f1d9dbb7be2f...0b3505d8d457af555d6c1278f8096863061bdc6a

Can you review changes, please?

**Comment by 304NotModified** [comment]
looks great, I have enabled syntax highlighting :)

**Comment by 304NotModified** [comment]
Thanks!

**Comment by snakefoot** [comment]
New property `FlushOnConditionOnly` has been added to AutoFlushWrapper in NLog 4.6.6 . See also #3513

It ensures that messages are NOT flushed when calling `NLog.LogManager.Flush()` or `NLog.LogManager.Shutdown()`

**Pull request merged**
