### PR TITLE
Enabled more NLog features for NETSTANDARD1_3

### PR DESCRIPTION
**Pull request by snakefoot**
Enabled the following features for NETSTANDARD1_3:

- Enabled auto-retry when using FileTarget.KeepFileOpen = false
- Enabled file-watcher when using FileTarget.KeepFileOpen = true
- Fixed FileTarget.EnableFileDelete so it works with FileTarget.KeepFileOpen = true
- BaseDirLayoutRenderer (basedir) can now also use ProcessDir-property
- ProcessIdLayoutRenderer (processid) has been enabled
- ProcessInfoLayoutRenderer (processinfo) has been enabled
- ProcessNameLayoutRenderer (processname) has been enabled
- TraceTarget (trace) has been enabled
- NLogViewerTarget (NLogViewer) has been enabled
- ChainsawTarget (Chainsaw) has been enabled

Also enabled a lot of unit tests.

Attempted to rename NETSTANDARD1_0 to NETSTANDARD
Attempted to rename NETSTANDARD_1plus to NETSTANDARD1_3

Added reference to System.Diagnostics.Process": "4.1.0" in project.json

### CODE REVIEW

**Comment by 304NotModified** [comment]
Great!

Unfortunately appveyor isn't reporting the unit tests correctly to github. There are always 10 failed tests, but we always see the in gitgub green badge. Dunno what's the problem.

**Comment by snakefoot** [comment]
I'm guess the exit code from the test-runner is not handled properly. 

I converted the project.json to VS2017-projects so I could run the tests myself, and they worked on my machine. But with the many new tests, then I guess more tests will now be failing, if the dotnet-test is more sensitive.

**Comment by 304NotModified** [comment]
If the vs2017 format is working, please send a PR. 

Ps. Tried vs2017 format on appveyor weeks ago, but could not get it working. See https://github.com/NLog/NLog.Web/pull/114

**Comment by snakefoot** [comment]
> If the vs2017 format is working, please send a PR

Not sure I have a perfect conversion. I find the multi-target-frameworks very confusing, as the normal build within the IDE doesn't show what specific target-framework is having issues.

Also I received errors regarding duplicate AssemblyTitle, where I just set GenerateAssemblyInfo=false. It didn't react to GenerateAssemblyTitleAttribute=false. Not sure what the correct solution is there.

**Comment by 304NotModified** [comment]
Unfortanly more unit tests are failing (now 17 instead of 10), including `NLog.UnitTests.LayoutRenderers.MdlcLayoutRendererTests.given_item_exists_when_rendering_item_and_message_should_render_item_and_message`

Could you look at that?

**Comment by snakefoot** [comment]
> Could you look at that?

Think it is parallel execution that xUnit2 performs by default for different test-classes. This doesn't work well with the NLog-singleton-pattern. Have now changed the classes to inherit from NlogTestBase that disables parallel execution for xUnit2.

**Comment by 304NotModified** [comment]
great! Will try to fix the build and fix/disable the last tests so appveyor gives a correct green

**Pull request merged**
