### PR TITLE
JSON serialize: support for DynamicObject + Improve JSON tests

### LINKED ISSUE #2901: Feature request: Support for logging properties of dynamic objects when using JsonLayout.
Feature request: Support for logging properties of dynamic objects when using JsonLayout. or other structured logging targets.
Below sample code serialize an empty object. This feature should serialize it as  

` "dObj": { "Id": "Hallo" }`

Sample code:
```c#
        class MyDynamicClass : DynamicObject
        {
            private string id = "";
            public override bool TryGetMember(GetMemberBinder binder,
                                  out object result)
            {
                result = id;
                return true;
            }

            public override bool TrySetMember(SetMemberBinder binder, object value)
            {
                id = value.ToString();
                return true;
            }
            public override IEnumerable<string> GetDynamicMemberNames()
            {
                return new List<string>() { "Id" };
            }
        }

      public void LogTest()
        {
                var log = LogManager.GetCurrentClassLogger();
                dynamic dObj = new MyDynamicClass();
                dObj.Id = "Hallo";                    
                log.Debug().Message("Write Hi").Property("dObj", dObj).Write();
        }
```

Configuration snippet:
```xml
<nlog>
<targets>
    <target xsi:type="AsyncWrapper" name="asyncJsonFile" overflowAction="Block">
      <target xsi:type="File" fileName="logfile.json">
        <layout xsi:type="JsonLayout" includeAllProperties="true"  maxRecursionLimit="20"  >
          <attribute name="time" layout="${longdate}" />
          <attribute name="level" layout="${level}" />
          <attribute name="loggername" layout="${logger}"/>
          <attribute name="message" layout="${message}" />
        </layout>
      </target>
    </target>
</targets>
  <rules>
       <logger name="*" minlevel="Trace" writeTo="asyncJsonFile" />
  </rules>
</nlog>

```

### PR DESCRIPTION
**Pull request by 304NotModified**
fixes #2901

Splitted DefaultJsonSerializerTests into: 3 classes

1. DefaultJsonSerializerTestsBase
2. DefaultJsonSerializerTests
3. DefaultJsonSerializerLegacyTests

todo:

- [x] move code
- [x] fix test -> jsonayout

### CODE REVIEW

**Comment by snakefoot** [comment]
You have modified the old source-path. You need to put the code into `SerializeTypeCodeValue`.

Maybe change `GetProps(value)` to return an array of Func-delegates that can return KeyValuePair from index. Thus hiding the PropertyInfo[]-array and LateBoundMethod[]-array.

Then for dynamic-object then you can provide a different Func-delegate.

**Comment by 304NotModified** [comment]
> You have modified the old source-path.

mmm any idea why my unit test succeeds? Do I need to add another unit test?

**Comment by snakefoot** [comment]
> mmm any idea why my unit test succeeds? Do I need to add another unit test?

Maybe unit-test the JsonLayout instead.

**Comment by 304NotModified** [comment]
OK Thanks!



> Maybe change GetProps(value) to return an array of Func-delegates that can return KeyValuePair from index. Thus hiding the PropertyInfo[]-array and LateBoundMethod[]-array. Then for dynamic-object then you can provide a different Func-delegate. But this needs some performance testing.

It's unclear what needs to be changed here, but I leave it as "maybe" ;)

**Comment by NLog-SonarQube** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [DefaultJsonSerializer.cs#L71](https://github.com/NLog/NLog/blob/d988b8f41eb0db7339279c1396789c73ca286757/src/NLog/Targets/DefaultJsonSerializer.cs#L71): Initialize all 'static fields' inline and remove the 'static constructor'. [rule](https://sonarcloud.io/coding_rules#rule_key=csharpsquid%3AS3963)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by 304NotModified** [comment]
```
  Processing API file 'C:\projects\nlog\src\nlog\bin\Release\net45\API\NLog.api'
EXEC : error : System.NotSupportedException: Unknown API type 'NLog.IDatabaseValueConverter'. [C:\projects\nlog\src\NLog.proj]
     at MakeNLogXSD.XsdFileGenerator.GetXsdType(String apiTypeName, Boolean attribute) in C:\projects\nlog\tools\MakeNLogXSD\XsdFileGenerator.cs:line 367
     at MakeNLogXSD.XsdFileGenerator.GetPropertyElement(XElement propertyElement) in C:\projects\nlog\tools\MakeNLogXSD\XsdFileGenerator.cs:line 268
     at MakeNLogXSD.XsdFileGenerator.GetPropertyElements(XElement type) in C:\projects\nlog\tools\MakeNLogXSD\XsdFileGenerator.cs:line 249
     at MakeNLogXSD.XsdFileGenerator.ProcessApiFile(String apiFile) in C:\projects\nlog\tools\MakeNLogXSD\XsdFileGenerator.cs:line 106
     at MakeNLogXSD.Program.Main(String[] args) in C:\projects\nlog\tools\MakeNLogXSD\Program.cs:line 98
C:\projects\nlog\src\NLog.proj(498,5): error MSB3073: The command ""C:\projects\nlog\src\..\build\bin\tools\MakeNLogXSD.exe" -api API\NLog.api -out NLog.netfx45.xsd -xmlns http://www.nlog-project.org/schemas/NLog.netfx45.xsd" exited with code 1.
Command exited with code 1
```

**Pull request merged**
