### PR TITLE
added SwallowAsync(Task)

### PR DESCRIPTION
**Pull request by breyed**
implements #765

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks, also for fixing the docs of another method. We will merge this with 4.1

**Comment by breyed** [comment]
I just noticed a typo in the documentation. I fixed it on the branch for the original pull request. Is there any need for another pull request.

**Comment by 304NotModified** [comment]
Yes, a new PR is needed, because it was already merged. Not sure if you can create a new PR from the current branch - otherwise creating a new one is 2 clicks (+ typing name)

**Comment by breyed** [comment]
Thanks. It turns out that the tweak I was considering had become irrelevant anyway due to other changes (I had been looking at the latest released code). Instead, several documentation enhancements were possible, which I put in PR #940.

**Pull request merged**
