### PR TITLE
Make forked pull requests to master indicate failure

### PR DESCRIPTION
**Pull request by nathan-schubkegel**
This is a continuation of #1062 

Right now, forked pull requests silently don't test iOS/Android stuff.

If NLog was my project, I'd want to know clearly in github when builds/unit tests weren't performed for a pull request. And I'd want the requester to know too. And it should not prevent any other steps from running.

This seems like a reasonable way to achieve that.

### CODE REVIEW

**Comment by nathan-schubkegel** [comment]
Hey! Did I misunderstand when 'build_with_xamarin' is undefined? (this PR is from a forked repository... but the AppVeyor build log clearly shows it performed the iOS/Android build steps... and also the perl script I added did not run)

When is 'build_with_xamarin' undefined? (ever?)

Sorry for the lack of understanding here.

**Comment by nathan-schubkegel** [comment]
I think I see how I misunderstood.

'build_with_xamarin' is undefined in a pull request to a forked repo (like mine at https://github.com/nathan-schubkegel/NLog ) where the AppVeyor service has been added but not configured with a 'build_with_xamarin' variable. Correct?

I still like these changes because they help avoid silent lack of build/test for someone out there... but I'll need to update the message and provide a way to explicitly ignore.

Also I'm still fine rejecting this change if [the core NLog maintainers] just don't care.

**Comment by 304NotModified** [comment]
Hey!

Forgot te respond on this, sorry about that.

For the Xamarin build, you need a license. We (NLog) have a OSS license for that, but we can distribute that one of course. 

Xamarin is now built on:

- All NLog branches,
- PR's to NLog.

But not on forks, as the Xamarin license is not there. With the `build_with_xamarin` variable we make sure that the build won't fail in your fork (but can fail in the PR because something was broken with Xamarin). 

So if you have a valid Xamarin license, you can set them in AppVeyor and set the `build_with_xamarin` environment variable. If you don't have one, well, then we can only check it at NLog PR / branches.

**Comment by 304NotModified** [comment]
Please let me know I you think this PR is still applicable.

**Comment by nathan-schubkegel** [comment]
Thanks for confirming all that!

I think this PR is applicable, but I need someone to weigh the advantage/disadvantage and confirm it's a good idea.

Advantage: Forked repo owners won't be mislead into thinking everything builds OK in AppVeyor when really iOS/Android silently weren't built. Earlier mistake detection.

Disadvantage: it will probably annoy folks the first time.

If you understand this and still don't have a preference, then merge it. =)

**Comment by 304NotModified** [comment]
But with this change, the build always fails in the fork?

**Comment by nathan-schubkegel** [comment]
With this change, the build fails in the fork until the forked repo owner defines either ```build_with_xamarin``` or ```build_without_xamarin```. It forces awareness at the cost of a first-time build nag.

**Comment by 304NotModified** [comment]
OK, thanks for the info! 

> It forces awareness at the cost of a first-time build nag.

Yes, that's a good thing, but the bad thing is that people will have issues (initial) when forking this repo. We really don't want that, because it will could confuse people and also (IMO) will make the barrier to contribute lower. It should be easy to contribute to NLog, even when you don't have much knowledge about AppVeyor / build servers.

The worst case what now can happen is that someone makes a change, submit a PR, and then AppVeyor complains that Xamarin is broken. I think it's better then breaking builds in forks.

**Comment by nathan-schubkegel** [comment]
Sounds great, thanks!

**Pull request closed without merging**
