### PR TITLE
FlushTriggerWrapper is implemented

### LINKED ISSUE #1712: Add flushCondition and overflow options to the  BufferingWrapper
As discussed at #1710, add flushCondition and overflow options to the  BufferingWrapper

Example: 

``` xml
<targets>
  <target xsi:type="BufferingWrapper"
          name="ErrorFlushingBuffer"
          slidingTimeout="False"
          bufferSize="100"
          flushTimeout="-1"  <!-- Disabled timed flushes so flush only occurs when flushCondition is met -->
          overflow="discard"> <!-- discard if buffer is full. Default: flush-->
          flushCondition="level>LogLevel.Info">  <!-- Flush the buffer when a Warn, Error, or Fatal message is logged-->

          <target xsi:type="wrappedTargetType" ...target properties... />
  </target>
</targets>
```

### PR DESCRIPTION
**Pull request by nazim9214**
I needed a way to automatically flushing to a File target(autoflush=false, keepOpen=true, concurrentWrites=false), only for special LogLevels(>=Warn). 
After some research i have found this [idea](https://github.com/NLog/NLog/issues/1712) of FlushTriggerWrapper and implemented this wrapper.

fixes #1712

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1807)

### CODE REVIEW

**Comment by nazim9214** [comment]
I'm not sure, but we could add Condition property (not required) to AutoFlushTargetWrapper. Or it's better to be separate wrapper?

**Comment by 304NotModified** [comment]
Cool ! Looks good!


> I'm not sure, but we could add Condition property (not required) to AutoFlushTargetWrapper. Or it's better to be separate wrapper?

I think that's even a better option! What do you think @snakefoot ?

**Comment by snakefoot** [comment]
As long the flush-triger-logic is not located on the BufferingTargetWrapper, then I'm good :)

But yes adding a condition-filter on the AutoFlushTargetWrapper would also work.

**Comment by 304NotModified** [comment]
>Would also work

not better?

**Comment by 304NotModified** [comment]
Ps. Rebuild for codecov.

**Comment by snakefoot** [comment]
It will probably be better for the NLog users to have just one wrapper, that is dedicated to flushing.

**Comment by nazim9214** [comment]
Ok, i'll move code to AutoFlushTargetWrapper this weekend

**Comment by 304NotModified** [comment]
👍 

please open a new PR then, thanks!

**Pull request closed without merging**
