### PR TITLE
Fix 'System.ReadOnlySpan`1[System.Char]' cannot be converted to type 'System.String'. 

### PR DESCRIPTION
**Pull request by 304NotModified**
#2599 for NLog 4.4

Thanks @snakefoot !

### CODE REVIEW

**Comment by snakefoot** [comment]
Think it is better to just use the `TryImplicitConversion` implementation from #2598

**Comment by 304NotModified** [comment]
I did a new branch and rebase on 4.4.12

**Comment by 304NotModified** [comment]
> Think it is better to just use the TryImplicitConversion implementation from my comment in #2598 (The single commit doesn't cover all changes made in NLog 4.5)


OK done

**Comment by snakefoot** [comment]
Looks like the SimpleFileDeleteTest is also broken in NLog 4.4.12 (FileWatcher not working in Travis)

**Comment by 304NotModified** [comment]
> Looks like the SimpleFileDeleteTest is also broken in NLog 4.4.13 (FileWatcher not working in Travis)

unstable I guess, the PR build succeeds. re-queued on Travis

**Comment by snakefoot** [comment]
Consider adding the following:

```C#
#if !MONO
        [Theory]
#else
        [Theory(Skip="Not supported on MONO on Travis, because of FileSystemWatcher not working")]
#endif
        [PropertyData("SimpleFileTest_TestParameters")]
        public void SimpleFileDeleteTest(bool concurrentWrites, bool keepFileOpen, bool networkWrites, bool forceManaged, bool forceMutexConcurrentWrites, bool optimizeBufferReuse)
```

**Comment by 304NotModified** [comment]
I will if the next 2 builds also fails. The build on Travis is a lot faster compared to Travis

**Comment by 304NotModified** [comment]
green :)

**Comment by 304NotModified** [comment]
@snakefoot I think the tag 4.4.12 is wrong :| double checked it, but think #2245  should be included? 

(I made v4.4.13 branch from the v4.4.12 tag). What do you think?

**Comment by 304NotModified** [comment]
OK thanks, I think now also. #2245 is confusing, but it's merged after the release date.

**Comment by snakefoot** [comment]
Well the v4.4.12-tag is missing an update to the CHANGELOG.md (v4.4.12)

**Comment by 304NotModified** [comment]
With bug fix releases, I tend to release first, then update docs.

**Comment by snakefoot** [comment]
But I think noise comes from you waited 5 days before merging the fix from the 4.4.12-branch back to the master-branch.

**Comment by 304NotModified** [comment]
published:

image

**Comment by Taloth** [comment]
For Sonarr I actually simply upgraded to 4.5 RC6, which already contained a fix for TryImplicitConversion as part of the netstandard 1.5 support. (Since it's [excluding all System namespace casts](https://github.com/NLog/NLog/commit/6c50c4eef22563b3fda97cebbedb410e1b0d803e#diff-2b8001b497489e626bb92e742342472fR203) _and_ [checks the return type](https://github.com/NLog/NLog/commit/6c50c4eef22563b3fda97cebbedb410e1b0d803e#diff-2b8001b497489e626bb92e742342472fR212)) added by @snakefoot no less.

Please note that those fixes are not yet present for latest 5.0 beta release (that affects Jackett since they were running that version)

Btw. As always, tnx for the rapid response, appreciate it.

**Comment by Taloth** [comment]
ah, I'll let the Jackett team know, tnx.

**Pull request merged**
