### PR TITLE
Issue 941: Add annotations for customer string formatting messages

### PR DESCRIPTION
**Pull request by wrangellboy**
fixes 941, add annotations per resharper guidelines.
https://www.jetbrains.com/resharper/help/Code_Analysis__String_Formatting_Methods.html

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks!

I thinks we also should include those attributes in https://github.com/NLog/NLog/blob/master/src/NLog/Logger.tt ? (for logger1.cs)

**Comment by wrangellboy** [comment]
Should be there now...

**Comment by 304NotModified** [comment]
Looks good. I think that are all the cases. 

If you fix the indenting in the `logger.tt` (and so `logger1.cs`), I will merge it :)

**Comment by wrangellboy** [comment]
Ok, I think I have it all sorted now.  Sorry about that.

**Comment by 304NotModified** [comment]
Thanks! It has been merged :)

**Pull request merged**
