### PR TITLE
Log4JXmlEventLayout - Added IncludeCallSite + IncludeSourceInfo

### LINKED ISSUE #3387: MappedDiagnosticsLogicalContext issues with ASP.NET Core 2.2 InProcess hosting
Hi,

Until recently, we were using NLog with our ASP.NET Core app without issue. We have configured log4jxmlevent using the MappedDiagnosticsLogicalContext. This has always worked for us.

Recently we switched to ASP.NET Core InProcess hosting and suddenly our log4jxmlevent layout renderer is no longer including data that we had initially set on the MappedDiagnosticsLogicalContext, because MappedDiagnosticsLogicalContext for some reason now gets cleared. The same goes for MappedDiagnosticsLogicalContext. More specifically, when we set them and log at startup it’s fine, but once the app is up and running and requests come in on different threads both these dictionaries get cleared.

The only one that doesn’t get cleared is GlobalDiagnosticsContext, however to my knowledge the log4jxmlevent does not attempt to GetNames() from here at any point.

Has anyone got any idea how to solve this problem please as I’ve been banging my head against this for a few days now and cannot find a satisfactory solution?

Thanks.

### PR DESCRIPTION
**Pull request by snakefoot**
Missing a nail to resolve #3387

One could probably rebase to NLog:master

### CODE REVIEW

**Comment by SkinnySackboy** [comment]
Thanks for this.

**Comment by 304NotModified** [comment]
> One could probably rebase to NLog:master

I think that's better indeed. NLog 5 take some weeks at least

**Comment by snakefoot** [comment]
>  think that's better indeed. NLog 5 take some weeks at least

Rebased to master

**Comment by 304NotModified** [comment]
@snakefoot could you please help me with the docs?

Working on a release now

**Comment by snakefoot** [comment]
Have updated the wiki: https://github.com/NLog/NLog/wiki/Log4JXmlEventLayout

**Comment by 304NotModified** [comment]
thanks!

**Comment by 304NotModified** [comment]
FYI, delaying 4.6.5 for https://github.com/NLog/NLog/issues/3472 😞

**Comment by 304NotModified** [comment]
@SkinnySackboy  NLog 4.6.5 has been released!  https://www.nuget.org/packages/NLog/4.6.5 :)

**Pull request merged**
