### PR TITLE
FileTarget: Archiving not working properly with AsyncWrapper

### LINKED ISSUE #1182: Archiving logs by hour is sporadically working
We are currently using Common.Logging with NLog 4.2.3 in a Windows .NET 4.5.2 service for diagnostic logging.

One of the targets we have set up can receive a reasonable throughput of logs so we have set it up to archive hourly rather than daily like the rest of our logs.

In the three or so days that we've been soak testing the service it appears that this hourly archive sometimes works every hour, other times it can take up to 23 hours to archive (resulting in a single file 23 times bigger than we expected, rather than 23 separate files).

I see there was a bug fix in NLog 4.2.0 where daily archiving would not always work so I'm wondering if this is related or if anyone else has experienced this.

Here is a sanitised sample of our configuration showing how it has been set up for this service:

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" internalLogToConsole="true">

   <variable name="LogFormat" value="${date:format=yyyy-MM-dd},${date:format=HH\:mm\:ss.fff},${counter},${processid},${threadid},${processtime},${level:uppercase=true},&quot;${processname}&quot;,&quot;${callsite:includeSourcePath=false:methodName=false}&quot;,&quot;${callsite:className=false:includeSourcePath=false:methodName=true}&quot;,&quot;${message}${onexception:inner= ${exception:format=tostring}}&quot;" />

   <variable name="FileNameFormat" value="Current.tlg" />

   <variable name="BaseLogDirectory" value="${whenEmpty:whenEmpty=${basedir}/Logs:inner=${registry:value=Folder:key=HKEY_LOCAL_MACHINE/PathToSettingStore:defaultValue=}}/TheService/" />

   <targets>
      <target name="Messaging" xsi:type="AsyncWrapper" queueLimit="5000" overflowAction="Block">
         <target xsi:type="File" layout="${LogFormat}" fileName="${BaseLogDirectory}/Messaging/${FileNameFormat}" keepFileOpen="true" archiveEvery="Hour" archiveNumbering="Date" archiveFileName="${BaseLogDirectory}/Messaging/{#}h.tlg" archiveDateFormat="yyyyMMdd-HH" maxArchiveFiles="336" />
      </target>         
   </targets>

   <rules>
      <logger name="MyMessagingLibrary.*" minlevel="Debug" writeTo="Messaging" final="true" />
   </rules>
</nlog>
```

### PR DESCRIPTION
**Pull request by bhaeussermann**
Augments `FileTargetTests` to run all tests through a wrapper target and fixes all bugs that these tests reveal. 

This should fix #1182, but is to be confirmed.

### CODE REVIEW

**Comment by bhaeussermann** [comment]
It seems AppVeyor froze :-/

**Comment by 304NotModified** [comment]
> It seems AppVeyor froze :-/

I just works? I think it was busy after I restarted everything (because of the Xamarin license stuff)

**Comment by 304NotModified** [comment]
Thanks! But can you revert the move of `FlushCurrentFileWrites`? This reviewing a bit easier, also, this will otherwise makes it difficult to port it to the CoreCLR branch

**Comment by 304NotModified** [comment]
Thanks @bhaeussermann !

**Pull request merged**
