### PR TITLE
App domain layout renderer

### LINKED ISSUE #485: Add layout renderer for app domain name
Example:
```c#
using NLog;
using NLog.Config;
using NLog.LayoutRenderers;
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Text;
namespace NLog
{
	/// <summary>
	///  Used to render the application domain name.
	///  </summary>
	[ThreadAgnostic, LayoutRenderer("appdomain")]
	public class AppDomainLayoutRenderer : LayoutRenderer
	{
		private string _Format;
		private const string shortFormat = "{0:00}";
		private const string longFormat = "{0:0000}:{1}";
		[DefaultParameter]
		public string Format
		{
			get
			{
				return this._Format;
			}
			set
			{
				this._Format = value;
			}
		}
		public AppDomainLayoutRenderer()
		{
			Format = "Long";
		}
		protected override void Append(StringBuilder builder, LogEventInfo logEvent)
		{
			string formattingString;
			if (Format.Equals("Short", StringComparison.OrdinalIgnoreCase))
			{
				formattingString = shortFormat;
			}
			else if (!Format.Equals("Long", StringComparison.OrdinalIgnoreCase))
			{
				formattingString = longFormat;
			}
			else
			{
				throw new ArgumentException("Invalid format");
			}
			builder.Append(string.Format(formattingString, AppDomain.CurrentDomain.Id, AppDomain.CurrentDomain.FriendlyName));
		}
	}
}
```

### PR DESCRIPTION
**Pull request by 304NotModified**
Influenced by and closes #485. Unit tests are also included. 

`IAppDomain` and `AppDomainWrapper` are extented with the `Id` property.

Examples:

`${appdomain}`, `"${appdomain:format=short}` or `${appdomain:format=long}`. 

Note: Custom formating is not working due to #427.See unit test `AppDomainCustomFormatTest`.

### CODE REVIEW

**Comment by 304NotModified** [comment]
I will check the AppVeyor warnings

**Comment by 304NotModified** [comment]
@Xharze what tool do you use to sync the project files?

**Comment by Xharze** [comment]
The Msbuild project file, src/nlog.proj contains a target called something
syncprojectitems, which does exactly this.

**Comment by 304NotModified** [comment]
Nice! It will try this tomorrow. 

 Also I think we also should document how to submit a feature/question/ bug-report to smoothing this process

**Comment by 304NotModified** [comment]
"NLog\src>msbuild NLog.proj /t:SyncProjectItems" dos the trick

**Comment by 304NotModified** [comment]
AppVeyor flips. I created a new PR

**Pull request closed without merging**
