### PR TITLE
Release 4.6.1

### PR DESCRIPTION
**Pull request by 304NotModified**

### CODE REVIEW

**Comment by snakefoot** [comment]
Can this line be fixed in ChangeLog.md:

> - [#3060](https://github.com/NLog/NLog/pull/3060)](https://github.com/NLog/NLog/pull/[#3060](https://github.com/NLog/NLog/pull/3060)) TargetWithContext - Support for PropertyType using IRawValue-interface (@snakefoot)

To become:


> - [#3060](https://github.com/NLog/NLog/pull/3060) TargetWithContext - Support for PropertyType using IRawValue-interface (@snakefoot)

**Comment by 304NotModified** [comment]
done!

**Comment by snakefoot** [comment]
Maybe also remove these lines from the NLog 4.6 ChangeLog-message:

> Full changelog: https://github.com/NLog/NLog/blob/master/CHANGELOG.md
> 
> Supported can be found on https://nlog-project.org/config/

**Comment by 304NotModified** [comment]
also done :)

**Comment by 304NotModified** [comment]
I try to get this thing build today 😄 😉

**Comment by snakefoot** [comment]
Will stop throwing more obstacles in front of you then :)

**Comment by 304NotModified** [comment]
👼 

Thanks for all the help! 👍 🥇

**Comment by 304NotModified** [comment]
just 2 commits ;)

image

**Comment by snakefoot** [comment]
Seems I have been a busy bee with improving NetCore support :). Have been a good learning experience to navigate in a non-breaking solution-world. Usually it is break often and run swiftly away from the trouble :)

**Comment by 304NotModified** [comment]
Unfortunately I'm more busy with maintaining besides coding in NLog :(  The long build times also won't help.

**Comment by snakefoot** [comment]
Yes I can see the wish for improving the file-mocking. Especially for config-file-loading-tests.

**Pull request merged**
