### PR TITLE
Various XSD improvements (NLog.Schema package)

### PR DESCRIPTION
**Pull request by 304NotModified**
fixes https://github.com/NLog/NLog/issues/3377

- [x] fix LoggerName

related https://github.com/NLog/NLog/issues/2394 and https://github.com/NLog/NLog/pull/2891

### CODE REVIEW

**Comment by snakefoot** [comment]
@304NotModified Think you should also fix this method to recognize `RULENAME`:

```c#
        private LoggingRule ParseRuleElement(ILoggingConfigurationElement loggerElement)
        {
            IEnumerable<LogLevel> enableLevels = null;
            int minLevel = 0;
            int maxLevel = LogLevel.MaxLevel.Ordinal;

            string ruleName = null;
            string namePattern = null;
            bool enabled = true;
            bool final = false;
            string writeTargets = null;
            foreach (var childProperty in loggerElement.Values)
            {
                switch (childProperty.Key?.Trim().ToUpperInvariant())
                {
                    case "NAME":
                        if (loggerElement.MatchesName("logger"))
                            namePattern = childProperty.Value; // Legacy Style
                        else
                            ruleName = childProperty.Value;
                        break;
                    case "RULENAME":
                        ruleName = childProperty.Value; // Legacy Style
                        break;
```

**Comment by 304NotModified** [comment]
> @304NotModified Think you should also fix this method to recognize `RULENAME`:

This isn't used for the XML, isn't?

**Comment by 304NotModified** [comment]
I think we have to update the XSD for NLog 5 and recommend the new approach IMO

**Comment by snakefoot** [comment]
> This isn't an issue in the XML now isn't?

Nope but it would make sense that `rulename` is recognized by the parser, when adding it to the xml-doc :)

**Comment by 304NotModified** [comment]
ow this is a mistake then. I'm confused why the names aren't in sync...

**Comment by snakefoot** [comment]
Created #3411

**Pull request merged**
