### PR TITLE
Drop NLog.Extended, Introduce NLog.MSMQ

### PR DESCRIPTION
**Pull request by 304NotModified**
fixes https://github.com/NLog/NLog/issues/3365

### CODE REVIEW

**Comment by 304NotModified** [comment]
@snakefoot could you please review this one? Thanks!

**Comment by snakefoot** [comment]
Have this line in appveyor.yml been fixed (Contains "NLog.Extended")

`- OpenCover\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"\"C:\projects\nlog\tests\NLog.UnitTests\bin\debug\net452\NLog.UnitTests.dll\" -appveyor -noshadow"  -returntargetcode -filter:"+[NLog]* +[NLog.Extended]* -[NLog]JetBrains.Annotations.*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:coverage.xml`

**Comment by snakefoot** [comment]
@304NotModified It looks good. And very happy about this change :)

**Comment by 304NotModified** [comment]
> Have this line in appveyor.yml been fixed (Contains "NLog.Extended")

Thanks, have done a search all files :)

> And very happy about this change :)

Me too :)

**Comment by snakefoot** [comment]
Updated wiki https://github.com/NLog/NLog/wiki/MSMQ-target with new nuget-package

**Pull request merged**
