### PR TITLE
Added AddCallSiteHiddenClassType to hide single class type from callsite

### PR DESCRIPTION
**Pull request by wadebaird**
- [x] Waiting for NLog v5.3 (And implementation as `LogManager.Setup()`-extension-method.

Refactored the SkipAssembly method into a ShouldSkip method to take both Hidden assemblies and types into account. Refactored LookupAssemblyFromStackFrame method into a LookupAssembly method that takes a MethodBase for better performance, as both places that call it use the MethodBase that is retrieved at the top of the method.

Added a HiddenTypeTest that tests the functionality.

### CODE REVIEW

**Comment by snakefoot** [comment]
Thank you for the pull-request. I propose to move the `AddHiddenAssembly` away from NLog.LogManager. But instead redirect to these Setup-extension-methods:
```c#
NLog.LogManager.Setup().SetupLogFactory(setup => setup.AddCallSiteHiddenAssembly(hideAssembly));
NLog.LogManager.Setup().SetupLogFactory(setup => setup.AddCallSiteHiddenClassType(hideClassType));
```
If you could resolve the current merge-conflicts, and apply the suggested changes from #5484 then it can be merged for NLog v5.3.

Alternative then I can merge #5484, and manually merge this pull-request after manuall fixing merge-conflicts.

**Comment by wadebaird** [comment]
Thank you! Sorry I didn't get to your request above. Thank you so much for supporting the community!

**Comment by snakefoot** [comment]
[NLog v5.3.1](https://www.nuget.org/packages/NLog) has been released, that allows you to hide specific class-type, instead of the entire assembly.

Thanks again for the contribution.

**Comment by wadebaird** [comment]
Thank you for your hard work!

**Pull request merged**
