### PR TITLE
Updated SandCastle project to use packagereferences + added Readme

### PR DESCRIPTION
**Pull request by snakefoot**
- Updated NLog.shfbproj to download its own nuget-packages
- Introduced dll_to_doc.csproj to download selected NLog-extensions (merged into the official docs)
- Updated BuildDoc.cmd to perform release-build and download nlog-extensions before building docs-files (Must be run from a Visual Studio Developer Command Prompt)

### CODE REVIEW

**Review by 304NotModified — COMMENTED** [review]
I like to review this, but I really don't know how to run this anymore 😆

**Comment by snakefoot** [comment]
You just open a Developer Command Prompt from Visual Studio and run `src/Docs/BuildDoc.cmd`

**Comment by snakefoot** [comment]
Now `BuildDoc.cmd` will also download additional-nuget-packages for the dll_to_doc-folder, so they will be included in documentation.

**Comment by 304NotModified** [comment]
I get this error at the end:

```
"D:\nlog\NLog\src\Docs\NLog.shfbproj" (default target) (1) ->
(CoreBuildHelp target) ->
  SHFB : error BE0020: Unknown substitution tag ID: 'SHFBFolder' [D:\nlog\NLog\src\Docs\NLog.shfbproj]

    27 Warning(s)
    1 Error(s)

Time Elapsed 00:00:11.54
The system cannot find the path specified.
        0 file(s) copied.
``

**Comment by 304NotModified** [comment]
related: https://github.com/EWSoftware/SHFB/issues/878

**Comment by 304NotModified** [comment]
Works great, 

one downside is that the official .dlls of the nuget packages aren't used. 

For example:

https://nlog-project.org/documentation/v4.7.0/html/T_NLog_GlobalDiagnosticsContext.htm vs
https://nlog-project.org/documentation/v5.0.0/html/T_NLog_GlobalDiagnosticsContext.htm

`Assembly:  NLog (in NLog.dll) Version: 4.7.0+4d138800820311d0b60b6437f1dd2ed1d571d47d` vs
`Assembly:  NLog (in NLog.dll) Version: 1.0.0+ed2cffe863ee8885497515fc543fa0a1c6bb4224`

notice the 1.0.0

But it's not breaking or something like that.

**Review by 304NotModified — APPROVED** [review]

**Comment by snakefoot** [comment]
I can remove the build local dll with just adding more nuget-packages to the new  dll_to_doc-project

**Comment by 304NotModified** [comment]
Would be a nice improvement:)

**Comment by snakefoot** [comment]
Created #4934

**Pull request merged**
