### PR TITLE
LogEventInfo.MessageFormatter - External Structured Logging Formatter

### PR DESCRIPTION
**Pull request by snakefoot**
Add support for external Message Formatter. This will allow integration with external logger formatters like Microsoft.Extensions.Logging. See also https://github.com/NLog/NLog.Extensions.Logging/pull/125

### CODE REVIEW

**Comment by snakefoot** [comment]
Can make extra PRs for CoreCLR and release-4.4.12. This will allow jump-start of structured-logging support for NLog.Extensions.Logging.

Will then update #2208 to work through the official LogEventInfo.MessageFormatter, so structured logging support is also added for the internal NLog-MesageFormatter.

**Comment by snakefoot** [comment]
@304NotModified Removed some premature optimization regarding FormatProvider (Too many side-effects in attempt to save 8 byte)

**Comment by 304NotModified** [comment]
:+1:

**Comment by 304NotModified** [comment]
Thanks! Merged!

**Comment by snakefoot** [comment]
Updated some documentation:

https://github.com/nlog/nlog/wiki/Message-Layout-Renderer

**Comment by 304NotModified** [comment]
Thanks!

**Pull request merged**
