### PR TITLE
FileTarget: Add WriteFooterOnArchivingOnly parameter.

### LINKED ISSUE #1602: Footer is written more than once
**Type**:
Bug

**NLog version**: (e.g. 4.3.7)

**Platform**: .Net 4.0

**Current NLog config** (xml or C#, if relevant)
```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <extensions>
    <add assembly="NLog.Xml"/>
  </extensions>
<target name="myXml" xsi:type="File" fileName="${basedir}/LOG/${logger}_${date:format=yyyyMMdd}.xml"
            maxArchiveFiles ="30"  archiveEvery="Day"
            archiveNumbering="Date" archiveDateFormat="yyyyMMdd"
            archiveFileName="${basedir}/LOG/${logger}_{#}.xml"
            ArchiveOldFileOnStartup="true"
            concurrentWrites="true"
            createDirs="true"
            autoFlush="true"
            header="&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;Log.xsl&quot;?&gt;${newline}&lt;Log date=&quot;${shortdate}&quot;&gt;"
            footer="&lt;/Log&gt;"
            >
      <layout xsi:type="XmlLayout">
        <property name="Date" layout="${longdate}"/>
      </layout>
    </target>
  </targets>
```

In case of a BUG:

- What is the current result? Footer is written after every time the application exits with the result that its present more than once and not only at the end of the file
- What is the expected result? one footer at the end of the file
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? NO
- Please post full exception details (message, stacktrace, inner exceptions) N.A.
- Are there any work arrounds? not found
- Is there a version in which it did worked?  checked only version 4.3.7
- Can you help us by writing an unit test?

this is one example of the LOG output:
```xml
<?xml-stylesheet type="text/xsl" href="Log.xsl"?>
<Log date="2016-08-23">
<LogEvent>
  <SequenceID>9</SequenceID>
  <TimeStamp>2016-08-23T14:53:09.3215244+02:00</TimeStamp>
  <Level>Debug</Level>
  <LoggerName>TEST</LoggerName>
  <Message>DEBUG 23\08\2016 14:53:09.3059</Message>
  <Properties>
    <Property>
      <Name>Date</Name>
      <Value>2016-08-23 14:53:09.3215</Value>
    </Property>
  </Properties>
</LogEvent>
<LogEvent>
  <SequenceID>11</SequenceID>
  <TimeStamp>2016-08-23T14:53:10.4291244+02:00</TimeStamp>
  <Level>Info</Level>
  <LoggerName>TEST</LoggerName>
  <Message>INFO 23\08\2016 14:53:10.4291</Message>
  <Properties>
    <Property>
      <Name>Date</Name>
      <Value>2016-08-23 14:53:10.4291</Value>
    </Property>
  </Properties>
</LogEvent>
<LogEvent>
  <SequenceID>12</SequenceID>
  <TimeStamp>2016-08-23T14:53:11.1935244+02:00</TimeStamp>
  <Level>Warn</Level>
  <LoggerName>TEST</LoggerName>
  <Message>WARNING 23\08\2016 14:53:11.1935</Message>
  <Properties>
    <Property>
      <Name>Date</Name>
      <Value>2016-08-23 14:53:11.1935</Value>
    </Property>
  </Properties>
</LogEvent>
<LogEvent>
  <SequenceID>13</SequenceID>
  <TimeStamp>2016-08-23T14:53:12.6599244+02:00</TimeStamp>
  <Level>Error</Level>
  <LoggerName>TEST</LoggerName>
  <Message>ERROR 23\08\2016 14:53:12.6599</Message>
  <Properties>
    <Property>
      <Name>Date</Name>
      <Value>2016-08-23 14:53:12.6599</Value>
    </Property>
  </Properties>
</LogEvent>
<LogEvent>
  <SequenceID>14</SequenceID>
  <TimeStamp>2016-08-23T14:53:13.7207244+02:00</TimeStamp>
  <Level>Error</Level>
  <LoggerName>TEST</LoggerName>
  <Message>ERROR EXCEPTION 23\08\2016 14:53:13.7207</Message>
  <Error>
    <TypeName>System.DivideByZeroException</TypeName>
    <MethodName>Main</MethodName>
    <ModuleName>TestNlogXml</ModuleName>
    <ModuleVersion>1.0.0.0</ModuleVersion>
    <Message>Tentativo di divisione per zero.</Message>
    <Source>TestNlogXml</Source>
    <StackTrace>   in TestNlogXml.Program.Main(String[] args) in C:\Users\Username\Documents\Visual Studio 2015\Projects\TestNlogXml\TestNlogXml\Program.cs:riga 52</StackTrace>
    <ExceptionText>System.DivideByZeroException: Tentativo di divisione per zero.
   in TestNlogXml.Program.Main(String[] args) in C:\Users\Username\Documents\Visual Studio 2015\Projects\TestNlogXml\TestNlogXml\Program.cs:riga 52</ExceptionText>
  </Error>
  <Properties>
    <Property>
      <Name>Date</Name>
      <Value>2016-08-23 14:53:13.7207</Value>
    </Property>
  </Properties>
</LogEvent>
<LogEvent>
  <SequenceID>15</SequenceID>
  <TimeStamp>2016-08-23T14:53:14.5007244+02:00</TimeStamp>
  <Level>Fatal</Level>
  <LoggerName>TEST</LoggerName>
  <Message>FATAL 23\08\2016 14:53:14.5007</Message>
  <Properties>
    <Property>
      <Name>Date</Name>
      <Value>2016-08-23 14:53:14.5007</Value>
    </Property>
  </Properties>
</LogEvent>
</Log>
</Log>
<LogEvent>
  <SequenceID>17</SequenceID>
  <TimeStamp>2016-08-23T14:53:15.5771244+02:00</TimeStamp>
  <Level>Debug</Level>
  <LoggerName>TEST</LoggerName>
  <Message>DEBUG 23\08\2016 14:53:15.5771</Message>
  <Properties>
    <Property>
      <Name>Date</Name>
      <Value>2016-08-23 14:53:15.5771</Value>
    </Property>
  </Properties>
</LogEvent>
<LogEvent>
  <SequenceID>19</SequenceID>
  <TimeStamp>2016-08-23T14:53:16.6379244+02:00</TimeStamp>
  <Level>Info</Level>
  <LoggerName>TEST</LoggerName>
  <Message>INFO 23\08\2016 14:53:16.6379</Message>
  <Properties>
    <Property>
      <Name>Date</Name>
      <Value>2016-08-23 14:53:16.6379</Value>
    </Property>
  </Properties>
</LogEvent>
<LogEvent>
  <SequenceID>20</SequenceID>
  <TimeStamp>2016-08-23T14:53:17.6207244+02:00</TimeStamp>
  <Level>Warn</Level>
  <LoggerName>TEST</LoggerName>
  <Message>WARNING 23\08\2016 14:53:17.6207</Message>
  <Properties>
    <Property>
      <Name>Date</Name>
      <Value>2016-08-23 14:53:17.6207</Value>
    </Property>
  </Properties>
</LogEvent>
<LogEvent>
  <SequenceID>21</SequenceID>
  <TimeStamp>2016-08-23T14:53:18.1667244+02:00</TimeStamp>
  <Level>Error</Level>
  <LoggerName>TEST</LoggerName>
  <Message>ERROR 23\08\2016 14:53:18.1667</Message>
  <Properties>
    <Property>
      <Name>Date</Name>
      <Value>2016-08-23 14:53:18.1667</Value>
    </Property>
  </Properties>
</LogEvent>
<LogEvent>
  <SequenceID>22</SequenceID>
  <TimeStamp>2016-08-23T14:53:19.6643244+02:00</TimeStamp>
  <Level>Error</Level>
  <LoggerName>TEST</LoggerName>
  <Message>ERROR EXCEPTION 23\08\2016 14:53:19.6643</Message>
  <Error>
    <TypeName>System.DivideByZeroException</TypeName>
    <MethodName>Main</MethodName>
    <ModuleName>TestNlogXml</ModuleName>
    <ModuleVersion>1.0.0.0</ModuleVersion>
    <Message>Tentativo di divisione per zero.</Message>
    <Source>TestNlogXml</Source>
    <StackTrace>   in TestNlogXml.Program.Main(String[] args) in C:\Users\Username\Documents\Visual Studio 2015\Projects\TestNlogXml\TestNlogXml\Program.cs:riga 52</StackTrace>
    <ExceptionText>System.DivideByZeroException: Tentativo di divisione per zero.
   in TestNlogXml.Program.Main(String[] args) in C:\Users\Username\Documents\Visual Studio 2015\Projects\TestNlogXml\TestNlogXml\Program.cs:riga 52</ExceptionText>
  </Error>
  <Properties>
    <Property>
      <Name>Date</Name>
      <Value>2016-08-23 14:53:19.6643</Value>
    </Property>
  </Properties>
</LogEvent>
<LogEvent>
  <SequenceID>23</SequenceID>
  <TimeStamp>2016-08-23T14:53:21.1619244+02:00</TimeStamp>
  <Level>Fatal</Level>
  <LoggerName>TEST</LoggerName>
  <Message>FATAL 23\08\2016 14:53:21.1619</Message>
  <Properties>
    <Property>
      <Name>Date</Name>
      <Value>2016-08-23 14:53:21.1619</Value>
    </Property>
  </Properties>
</LogEvent>
</Log>
```

### PR DESCRIPTION
**Pull request by bhaeussermann**
Fix #1602

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1641)

### CODE REVIEW

**Comment by 304NotModified** [comment]
Cool! Thanks !

Not sure about the property name though. What about "onlyFooterOnArchives" ?

**Comment by bhaeussermann** [comment]
> Not sure about the property name though. What about "onlyFooterOnArchives" ?

Well, normally the footer is written in the following three cases:

1. The target is closed,
2. The file is archived,
3. We are starting to write to a different file name (without explicit archiving).

If the option claimed to write the footer upon archiving only, that would suggest that the footer would not be written for case (3) above either, which is probably not what we want.

**Comment by 304NotModified** [comment]
> If the option claimed to write the footer upon archiving only, that would suggest that the footer would not be written for case (3) above either, which is probably not what we want.

Well I was think we would like that, because we never known if we would write the file again.





> Well, normally the footer is written in the following three cases:
> 
> 1. The target is closed,
> 2. The file is archived,
> 3. We are starting to write to a different file name (without explicit archiving).

With `WriteFooterOnTargetClose =false` I'm not sure if a footer would be written in case 3.

**Comment by bhaeussermann** [comment]
> Well I was think we would like that, because we never known if we would write the file again.

Makes sense. I changed the property to `WriteFooterOnArchivingOnly`.

**Comment by 304NotModified** [comment]
:+1:

**Comment by 304NotModified** [comment]
oops merge conflict. Could you fix this? 

(PS if you create a branch on the NLog repos, I could also easily fix the merge conflict.)

**Comment by 304NotModified** [comment]
Could you add this to the wiki? Will release it in 4.3.9.

Thanks!

**Pull request merged**
