### PR TITLE
NetworkTarget - Respect MaxQueueSize in case of http(s)

### PR DESCRIPTION
**Pull request by snakefoot**
Minor fix to #3546

### CODE REVIEW

**Comment by snakefoot** [comment]
Updated wiki: https://github.com/NLog/NLog/wiki/Network-target

**Comment by 304NotModified** [comment]
Thanks! Sounds more like a bug fix?

**Comment by snakefoot** [comment]
Enhancement / bugfix - potato / potato :)

**Comment by 304NotModified** [comment]
It was documented as `Only used for TCP (not http/https/udp)`, so not a bug fix :)

**Comment by 304NotModified** [comment]
Thanks! Merged!

**Pull request merged**
