### PR TITLE
Eventlog audit events

### LINKED ISSUE #289: EventLog target to support SuccessAudit and FailureAudit events
Currently EventLog target translates `logEvent.Level` into `EventLogEntryType.Error`,`.Warning` or `.Information`. 

It will be good to have new entryType configuration parameter that will allow to specify `SuccessAudit` and `FailureAudit` events
 (reference http://msdn.microsoft.com/en-us/library/system.diagnostics.eventlogentrytype(v=vs.110).aspx)

### PR DESCRIPTION
**Pull request by 304NotModified**
added optional property `EntryType` (layoutable), closes #289

With this property we can log to all various levels: `Error`, `FailureAudit`, `Information`, `SuccessAudit` & `Warning`. [MSDN EventLogEntryType  ](https://msdn.microsoft.com/en-us/library/system.diagnostics.eventlogentrytype(v=vs.110).aspx)

If not set, then uses the backwards compatible behavior: 

- LogLevel.Trace => EventLogEntryType.Information
- LogLevel.Debug => EventLogEntryType.Information
- LogLevel.Info => EventLogEntryType.Information
- LogLevel.Warn => EventLogEntryType.Warning
- LogLevel.Error => EventLogEntryType.Error
- LogLevel.Fatal => EventLogEntryType.Error

Doc: 

```xml
<targets>
  <target xsi:type="EventLog"
          name="String"
          layout="Layout"
          machineName="String"
          source="String"
          category="Layout"
          eventId="Layout"
          entryType="Layout" <!-- new -->
          log="String" />
</targets>
```

Including unit tests, also unit tests for backwards compatible behavior

### CODE REVIEW

**Comment by 304NotModified** [comment]
I will fix the build error. Maybe I should edit the .net 3.5 project first, as I used .Net 4 stuff (`Enum.TryParse`)

**Comment by 304NotModified** [comment]
@Xharze How do I handle this? I would like to use `Enum.TryParse` in .Net 4+ (performance thing)

**Comment by Xharze** [comment]
@304NotModified So this makes it possible to use a fixed entry type? Would that make sense? I mean effectively ignoring the log level?

**Comment by 304NotModified** [comment]
Well it's layoutable, so we can use conditions.

**Comment by Xharze** [comment]
Of course didn't think about that

**Pull request merged**
