### PR TITLE
Extracted DatabaseTarget into NLog.Database with help from ValueTypeLayoutInfo

### LINKED ISSUE #2676: Move DatabaseTarget to NLog.DatabaseTarget package
Remove the following dependencies from NLog-core:

```
<Reference Include="System.Data" />
<Reference Include="System.Transactions" />
```

And add support for Silverlight, Android + iOS.

Probably for NLog 5.0

### PR DESCRIPTION
**Pull request by snakefoot**
Resolves #2676 and ensures NLog is not generating security vulnerability warnings #4051

ValueTypeLayoutInfo has also been included in:
- TargetWithContext
- MethodCallTarget

ValueTypeLayoutInfo is special as it uses `Layout<T>` to handle type-conversion, while ensuring layout-precalculate always happens on `Layout<T>`-instance (and not the SimpleLayout assigned from config). This makes performance optimizations in `Layout<T>` available from `NLog.config`.

Guess later PR can update JsonLayout and XmlLayout to also use ValueTypeLayoutInfo

### CODE REVIEW

**Comment by snakefoot** [comment]
New `DefaultValue` option has also been added, and available for TargetWithContext + MethodCallTarget + WebServiceTarget

**Comment by snakefoot** [comment]
Guess I have to make some extra bonus tests of the `ValueTypeLayoutInfo`, since most of the type-conversion-tests comes from the DatabaseTarget-Tests.

When NLog.Database is moved to its own repository (or maybe just own solution-file), then they will no longer be part of default-build.

**Comment by snakefoot** [comment]
@304NotModified Do you have objections against introducing `ValueTypeLayoutInfo` as a configuration-file-friendly type-conversion-helper?

**Comment by snakefoot** [comment]
@304NotModified After this has been merged. Do you have more items before NLog 5.0 RC1 ?

**Comment by 304NotModified** [comment]
Dunno, it's an alpha or beta first? I guess we need to trim the 5.0 milestone for RC1?

**Comment by snakefoot** [comment]
> Dunno, it's an alpha or beta first?

Well [beta](https://www.nuget.org/packages/NLog/5.0.0-beta11) is already taken, so I think RC is the way forward.

**Comment by 304NotModified** [comment]
RC should be feature complete imo

**Comment by snakefoot** [comment]
> RC should be feature complete imo

What features are missing ?

**Comment by 304NotModified** [comment]
A lot is this list? https://github.com/NLog/NLog/milestone/61

So that's what I mean before, maybe trim the milestone

**Comment by snakefoot** [comment]
> So that's what I mean before, maybe trim the milestone

Maybe each of us should move our own issue to the next milestone, unless we plan to create a pull-requests within the near future?

**Comment by snakefoot** [comment]
Maybe also create a NLog 5.1 milestone, so issue that might not introduce breaking changes can be moved to. Ex. #4335

**Comment by snakefoot** [comment]
Rebase and force-push to re-align with #4436

**Comment by snakefoot** [comment]
Approving and merging since tired of merge-conflicts caused by sql-nuget-package-updates.

**Comment by snakefoot** [comment]
Looks like Microsoft introduced a bug with Visual Studio 2019 ver. 16.10:

https://github.com/dotnet/msbuild/issues/6493

And it seems AppVeyor have just updated to the broken version, that causes the issue with `Unable to load DLL 'SQLite.Interop.dll'`. Guess one have to wait for AppVeyor to update their Visual Studio Images again.

**Comment by snakefoot** [comment]
Updated wiki: https://github.com/NLog/NLog/wiki/Database-target (About new nuget-package)

**Pull request merged**
