### PR TITLE
Updated T4 with changes from #1719 and #1814

### PR DESCRIPTION
**Pull request by c0shea**
Changes introduced in #1719, which [added a new overload](https://github.com/NLog/NLog/commit/0b79e8b1019b6b4a4a3f1f059a8cb642b34d5760#diff-1f6be57be51c734382d9b0a49268badc), and #1814, which [improved obsolete warnings](https://github.com/NLog/NLog/commit/f064b6c0276c6330d6463d3bdc9f4c20f3c77f5f#diff-1f6be57be51c734382d9b0a49268badc), both edited the Logger1.cs directly. This PR updates Logger.tt, such that if it's run and Logger1 is regenerated the class will contain the latest changes.

### CODE REVIEW

**Comment by 304NotModified** [comment]
Food catch! Thanks!

We should rename logger1.cs  to something like logger-generated.cs

**Comment by c0shea** [comment]
Great idea! I added another commit to rename Logger1.cs to Logger-generated.cs and update the project files.

**Comment by 304NotModified** [comment]
Thanks!

Could you please do also a replace in `ProjectFileInfo.xml`, `NLog.SourceCodeTests.exe.config` and `NLog.SourceCodeTests/App.config` ?  See https://github.com/NLog/NLog/search?p=1&q=logger1.cs&type=&utf8=%E2%9C%93

Thanks in advance!

**Comment by c0shea** [comment]
Sure, I updated those 3 additional files.

**Comment by 304NotModified** [comment]
thanks!

**Pull request merged**
