### PR TITLE
AsyncTargetWrapper - TimeToSleepBetweenBatches changed default to 1ms

### PR DESCRIPTION
**Pull request by snakefoot**
Means lazy trigger on request. Will work very well together with #2650

### CODE REVIEW

**Comment by 304NotModified** [comment]
What's the impact? Do you think it has low risk (NLog 4.6), or maybe some higher (then NLog 5)

**Comment by snakefoot** [comment]
It works very well with FileTarget. And it works very well with minimizing Timer-events, when system idle.

I guess if some network-based-targets uses the AsyncWrapper to throttle requests, then they will affected. But for that case they should already have configured TimeToSleepBetweenBatches manually to 150 or 200 ms (Because every 50 ms is aggressive).

**Comment by 304NotModified** [comment]
> I guess if some network-based-targets uses the AsyncWrapper to throttle requests, then they will affected. But for that case they should already have configured TimeToSleepBetweenBatches manually to 150 or 200 ms (Because every 50 ms is aggressive).

mmm doubting about this. 

Will think about this

Thanks!

**Comment by snakefoot** [comment]
Change TimeToSleepBetweenBatches = 1 to also be on activity. But a little more lazy than TimeToSleepBetweenBatches = 0. To improve batching for "slow" targets.

| Logger Name      | Messages   | Size | Args | Threads | Loggers |
|------------------|------------|------|------|---------|---------|
| PerfLogger       | 10.000.000 |  128 |    0 |       1 |       1 |

| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| 0ms   |     9.320 | 1.072.874 |   0 |   7 |  14 |   12 |    1.137,0 |

| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| 1ms   |    24.551 |   407.304 |   0 |   7 |  14 |   45 |    1.137,0 |

| Test Name  | Time (ms) | Msgs/sec  | GC2 | GC1 | GC0 | CPU (ms) | Alloc (MB) |
|------------|-----------|-----------|-----|-----|-----|----------|------------|
| 50ms    |   250.083 |    39.986 |   0 |   7 |  14 |      609 |    1.139,1 |

**Pull request merged**
