### PR TITLE
Introduced NLog.Wcf and Nlog.WindowsIdentity for .NET standard

### LINKED ISSUE #2400: Move WCF targets into seperate package for NetStandard2.0
Instead of having extra dependencies for NetStandard2.0, then it could be nice if there was a dedicated WCF-nuget-package (Just like MailKit)

### PR DESCRIPTION
**Pull request by snakefoot**
NLog without extra dependencies for NetStandard2.0. Resolves #2400

### CODE REVIEW

**Comment by 304NotModified** [comment]
guess this should wait on the next major version ('cause of semver)

**Comment by snakefoot** [comment]
Not sure I understand. There is no semver for NetStandard.

**Comment by 304NotModified** [comment]
the same comment as -> https://github.com/NLog/NLog/issues/2400

Semver for NLog.

**Comment by snakefoot** [comment]
Hard to have breaking changes when never made an official release yet.

**Comment by 304NotModified** [comment]
sure only on officials releases. But it breaks stuff compared to 4.4.x isn't?

**Comment by snakefoot** [comment]
There is no breaking change. The WCF stuffs is part of the Nlog.dll for NetFramework as always. It is just NetStandard2.0 that needs extra help.

**Comment by 304NotModified** [comment]
oops sorry, missed that this was .net standard only

**Comment by 304NotModified** [comment]
@snakefoot    release of beta8 after this one?

**Comment by snakefoot** [comment]
> release of beta8 after this one?

Yes think that is a good idea. No more changes in the pipeline for me.

**Comment by 304NotModified** [comment]
👍

**Comment by snakefoot** [comment]
Updated documentation:

https://github.com/NLog/NLog/wiki/Platform-Support

**Comment by 304NotModified** [comment]
thx!

**Comment by 304NotModified** [comment]
FYI beta8 is live, including 

https://www.nuget.org/packages/NLog.WindowsIdentity

and https://www.nuget.org/packages/NLog.wcf

:)

**Comment by snakefoot** [comment]
@304NotModified Looks great! Happy about the empty dependency-list for NetStandard2.0. Expects that NLog 5.0 (or maybe it should be 6.0) will focus on extracting even more targets/layout-renderers into separate nuget-packages.

Is something needed from this list to create a release-candidate: https://github.com/NLog/NLog/milestone/27 ?

**Comment by 304NotModified** [comment]
> Is something needed from this list to create a release-candidate: https://github.com/NLog/NLog/milestone/27 ?

yes, https://github.com/NLog/NLog/issues/2355 and #2321

**Pull request merged**
