### PR TITLE
Add flush logic based on level

### PR DESCRIPTION
**Pull request by imanushin**
**Imporant:** please check branch name. Is it correct?

Changes:
* Add two new properties into the BufferingTargetWrapper.
* Add tests for these properties

If this change is ok to merge I will do the same for ```AsyncWrapper```

Questions:
* How it is better to update help? Can I just click on ```Edit``` and copy documentation from the ```BufferingTargetWrapper``` (with examples)?

### CODE REVIEW

**Comment by snakefoot** [comment]
Why not just do this:

```
var bufferingTargetWrapper = new BufferingTargetWrapper(testTarget, 100);
var autoFlushOnLevelWrapper = new AutoFlushTargetWrapper(bufferingTargetWrapper);
autoFlushOnLevelWrapper.Condition = "level > LogLevel.Info";
```

**Comment by imanushin** [comment]
@snakefoot , primary feature: have ability of blocking ```Flush``` for fatal level. As I said in comments this is really imporart of case when your applications have ```Environment.FailFast``` calls after Fatal error write.

However thank you about ```AutoFlushTargetWrapper``` it is reasonable for several other scenarios.

**Comment by snakefoot** [comment]
Also mentioned the AutoFlushTargetWrapper as answer to your original question: https://github.com/NLog/NLog/issues/3145#issuecomment-468375179

**Comment by imanushin** [comment]
@snakefoot, you are right about mention [AutoFlushTargetWrapper](https://github.com/NLog/NLog/issues/3145#issuecomment-468375179).

So can we have blocking flush? Of course I can move my code to ```AutoFlushTargetWrapper``` (if it is more logical place).

**Comment by 304NotModified** [comment]
> Of course I can move my code to `AutoFlushTargetWrapper` (if it is more logical place).

That sounds as a good decision.

**Comment by 304NotModified** [comment]
> > Of course I can move my code to `AutoFlushTargetWrapper` (if it is more logical place).
> 
> That sounds as a good decision.

Please do and please create a new PR then, thanks!

**Pull request closed without merging**
