### PR TITLE
Merge NLog 4.7.7 to dev

### PR DESCRIPTION
**Pull request by snakefoot**

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks!

**Comment by 304NotModified** [comment]
Yes indeed, ideally master should be for bugfixes only.

**Comment by snakefoot** [comment]
@304NotModified Think I pressed the wrong button on merge. Became a squash instead of merge. Should we "uncommit" and re-merge ?

**Comment by 304NotModified** [comment]
And please remove with force push. Then a new pr or a push from local.

**Comment by snakefoot** [comment]
> The "merge when passing" wasn't triggering?

No because the build-servers required "restart".

**Comment by snakefoot** [comment]
> Yes please remove with force push. 

Not sure I can force push agains the dev-branch. Says "Cannot force-push to this protected branch"

**Comment by 304NotModified** [comment]
Ow yes force push is only for admin I guess, will do that

**Comment by 304NotModified** [comment]
The squased commit (4dbc737b61e3a8fb97adc551c43719342fcb4d91) has been removed from dev and I'm busy with a new PR

**Pull request merged**
