### PR TITLE
LocalIpAddressLayoutRenderer - Higher priority when valid gateway

### PR DESCRIPTION
**Pull request by snakefoot**
Looks like the real-ip will have a default-gateway:

https://stackoverflow.com/questions/8089685/c-sharp-finding-my-machines-local-ip-address-and-not-the-vms

While the VMware Network Adapter will have none or just 0.0.0.0

### CODE REVIEW

**Comment by snakefoot** [comment]
@jol5 Please check if the pre-release-build is able to resolved the expected `${local-ip}`:

https://ci.appveyor.com/project/nlog/nlog/builds/29958203/artifacts

**Comment by 304NotModified** [comment]
Polite bump @jol5

**Comment by snakefoot** [comment]
@304NotModified Don't think jol5 doesn't have English as first language and not in the mood for playing with local nuget-package stores, so it will be an uphill challenge to get any confirmation.

You just have to take my word (or rather stackoverflows word) for that the solution will be working for VM-Ware-Nodes.

**Comment by 304NotModified** [comment]
Ok merged!

**Pull request merged**
