### PR TITLE
FileTarget - Introduced OpenFileFlushTimeout to help when AutoFlush = false

### PR DESCRIPTION
**Pull request by snakefoot**
Faster and fewer side-effects than `OpenFileCacheTimeout=1`

### CODE REVIEW

**Comment by 304NotModified** [comment]
nice improvements!

NLog 4.5.7 or 4.6?

**Comment by snakefoot** [comment]
I think Nlog ver. 4.5.7
________________________________

**Comment by snakefoot** [comment]
Created  #2804 with some minor improvements to File-Last-Modified-Timestamp handling, when `AutoFlush = false`.

**Comment by snakefoot** [comment]
Updated wiki: https://github.com/NLog/NLog/wiki/File-target

**Pull request merged**
