### PR TITLE
FileTarget - MONO should also check SupportsSharableMutex

### PR DESCRIPTION
**Pull request by snakefoot**
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1859)

### CODE REVIEW

**Comment by snakefoot** [comment]
Interesting. Seems there is a bug in MutexMultiProcessFileAppender when running on MONO. Or a bug in the tester?

Can see that we favor the UnixMultiProcessFileAppender on MONO, with fallback to MutexMultiProcessFileAppender on Win32.

Guess the PR should be changed from checking ForceMutexConcurrentWrites to SupportsSharableMutex.

**Comment by 304NotModified** [comment]
looks good, so in Mono4 we now support MutexMultiProcessFileAppender

**Comment by snakefoot** [comment]
> looks good, so in Mono4 we now support MutexMultiProcessFileAppender

More like in MONO4 on Windows then we support MutexMultiProcessFileAppender

**Comment by 304NotModified** [comment]
Thanks, looks good!

**Pull request merged**
