### PR TITLE
Avoid (Internal)Logger-boxing and params-array-allocation on Exception

### PR DESCRIPTION
**Pull request by snakefoot**
No need to box value-types when trying to avoid params-array-allocation.

No need to create empty params-array when reporting Exception to Logger.

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1719)

### CODE REVIEW

**Comment by 304NotModified** [comment]
LOL maybe we should consider to implement `ILogger` or merge both code bases

**Comment by snakefoot** [comment]
Yes could have saved me one PR :). But now I learned the trick with using generics to optimize the params-array.

**Comment by 304NotModified** [comment]
But isn't it this case better to implement ILogger? Although we need singleton instead of static. Dunno if backwards comp.

**Comment by snakefoot** [comment]
Since the InternalLogger is a static class, then it will be difficult for it to implement the ILogger-interface.

It could have a static property that implements ILogger, but the InternalLogger would still have to forward its method to this property.

**Comment by 304NotModified** [comment]
Could you add the related unit tests?

**Comment by 304NotModified** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1719)*

**Comment by 304NotModified** [comment]
Reviewed 1 of 2 files at r2.
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1719)*

**Comment by snakefoot** [comment]
Have updated the UnitTests to cover the new interface-methods.

**Comment by 304NotModified** [comment]
Thanks! Why are some unit tests changed?

**Comment by snakefoot** [comment]
For some reason when the last parameter was "null" (without type), then the compiler chose the interface-method taking params-array.

I also added the ${exception} to layout in the other tests to show that the Exception was actually included.

**Comment by 304NotModified** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1719)*

**Comment by 304NotModified** [comment]
Thanks!

**Pull request merged**
