### PR TITLE
MdlcLayoutRenderer - AsyncLocal for NET4_6 and NETSTANDARD1_3

### LINKED ISSUE #1729: MDLC support for .NET Core
Feature Inquiry/Request

NLog version: 4.4.0 - *

Platform: .Net Core

According to the Platform Support page, it seems that there is not yet planned support of MDLC for .Net Core yet, is this correct? And if so, do we know when can we expect the support to be available? 

Ask because we currently rely on MDLC to track things like correlation IDs and stuff, to keep them "logic context safe" and the render layout is really convenient to output them. 

Thanks.

### PR DESCRIPTION
**Pull request by snakefoot**
Also allow NET3_5 and MONO to use CallContext.LogicalGetData (But not Silverlight and WindowsPhone8)

Fixes  #1729

### CODE REVIEW

**Comment by 304NotModified** [comment]
Is this needed?

Netstandard and net46 are (only) in the coreclr branch. Currently (in master)net46 uses the net45 binary

**Comment by snakefoot** [comment]
> Is this needed?

Maybe just use it for inspiration when doing the next merge to the CoreClr-branch.

**Comment by snakefoot** [comment]
Now changed the PR to point against coreclr-branch. Had to disable the MdlcLayoutRendererTests as the use of constructor doesn't seem to work properly. Also strange one cannot see the test output for the Travis-build.

**Comment by snakefoot** [comment]
@304NotModified Now squashed the PR, so it is a merge of a single change. Discovered that the MdlcLayoutRendererTests was also failing before (#2030), so I have left it untouched.

**Comment by 304NotModified** [comment]
Thanks! Will try to look at it soon.

**Comment by 304NotModified** [comment]
great! Thanks! Now we could also fix https://github.com/NLog/NLog.Extensions.Logging/issues/10 

\0/

**Pull request merged**
